### ISSUE TITLE
Support des formats d'image AVIF

### ISSUE THREAD

**Issue by Zoldiru** [YesWiki/yeswiki#1005]
Bonjour,

Est-ce qu'un support du format d'image AVIF est envisagé pour la prochaine version ?

**Comment by mrflos** [comment]
Bonjour, je n'avais pas vu cette issue, désolé pour le looooong temps de réponse...  
On peut paramétrer le wiki pour permettre l'upload de fichiers avif, par contre, à ma connaissance les bibliothèques de redimensionnement et conversion d'image comme GD et Avif, n'ont que récemment supporté ce format, il faudrait donc peut etre implémenter un support partiel pour l'instant (permettre l'upload et l'affichage sans redimensionnement si pas supporté). Je vais étudié la faisabilité de cela.
