### ISSUE TITLE
Attach ajouter un paramètre max_image_filesize

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#1006]
New feature / Nouvelle fonctionnalité

**Description**
Proposition de permettre de fixer une taille max pour les images uploadées via attach
permettrai de limiter l'espace disque utilisé sur des wikis avec beaucoup de contributeurs qui partagent des images

**Comment by J9rem** [comment]
@MelanieMichel c'est déjà le cas avec le paramètre `"max_file_size"` qu'on peut configurer dans le fichier `wakka.config.php` par exemple `"max_file_size" => 2*1024*1024,` pour restreindre à 2Mo.

**On pourrait alors faire apparaître ce paramètre dans la page `GererConfig`.**
Êtes-vous d'accord @furax37 ou @gatienbataille pour cet ajout ?

@MelanieMichel tu peux dores et déjà vérifier que le paramètre mis à la main dans `wakka.config.php` est déjà pris en compte.

_On pourrait aussi ajouter de l'aide au niveau de cette page https://yeswiki.net/?AttacH une fois la modification apportée dans GererConfig_

**Comment by mrflos** [comment]
c'est une bonne idée de rendre accessible le max_file_size dans la gestion de la configuration, mais par contre d'avoir un tuning pour les images serait important, car on peut avoir envie d'attacher un pdf de 20mo ou une video mp4, mais tout de meme vouloir restreindre les images

**Comment by MelanieMichel** [comment]
@J9rem merci pour l'info, en effet le paramètre fonctionne et il y a bien un message en cas de dépassement de la taille max.

Je rejoins @mrflos sur l'idée de différencier les images et éventuellement de donner la possibilité d'un redimensionnement coté serveur comme on le fait via les templates ? avec du coup un paramètre "reduce_uploaded_images"

**Comment by J9rem** [comment]
Est-ce que ma première proposition facile à faire de rendre disponible `max_file_size` dans la gestion de la configuration telle quelle est validée par @mrflos et @MelanieMichel  ?

Et on garde la présente issue ouverte en attendant de trouver quelqu'un pour développer le truc plus lourd avec la gestion fine selon les types de fichiers.

Ca n'est pas très clair dans vos réponses qui sont plutôt du genre `oui mais ...`
Je suis binaire soit c'est `oui`, soit c'est `non` avec des idées d'améliorations requises au préalable

**Comment by MelanieMichel** [comment]
rendre disponible max_file_size dans la gestion de la configuration répond à la demande initiale

j'ajouterai à la documentation de attach lorsque l'option sera disponible via page configuration

J'ai ouvert une [nouvelle issue à propos de la question du redimensionnement ](https://github.com/YesWiki/yeswiki/issues/1007) qui était un rebond ;)

**Comment by gatienbataille** [comment]
oui ok pour moi pour max_file dans config

**Comment by J9rem** [comment]
merci @MelanieMichel et @mrflos pour votre clarification ici (et par message privé).
Je rajoute donc l'option `max_file_size` dans gérer config et on conserve la présente PR pour la deuxième partie concernant la mise en place plus tardive de pouvoir choisir une taille différente en fonction du type de fichier.

**Comment by seballot** [comment]
Je ferme je pense que ce que tu as Jerem répond déjà à la plus grande partie du besoin !
