### ISSUE TITLE
Redimensionner les images coté serveur

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#1007]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
De grandes images (largeur >1900px) sont gourmandes en espace disque et ne sont (à priori) pas utiles sur un wiki.
L'idée est d'offrir la possibilité d'un redimensionnement coté serveur   avec un paramètre "reduce_uploaded_images"  , on ne garderait que le fichier redimensionné dans le dossier  files.

Ce paramètre pourrait être disponible au niveau de attach ou au niveau du fichier de conf ? à voir

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/24/redimensionner-les-images-cote-serveur
