### ISSUE TITLE
Les mots clés (TAGS) en bas de page ne s'affichent plus

### ISSUE THREAD

**Issue by Zheelnat** [YesWiki/yeswiki#1009]
Comme discuté sur le Framateam, Nous n'avons plus de tags en bas de page et ça nuit pas mal à la navigation.

**Comment by J9rem** [comment]
Merci pour ce retour @Zheelnat .
J'ai besoin de précisions pour comprendre d'où vient le souci.
Avec quelle version les `tags` ne s'affichent plus en bas de page ?
Avec quelle version les `tags` s'affichaient ?

**Comment by J9rem** [comment]
Trouvé, effectivement la fusion de cette [PR](https://github.com/YesWiki/yeswiki/pull/919) a supprimé l'affichage

**Comment by J9rem** [comment]
@mrflos effectivement les travaux sur les commentaires ont fait disparaître l'affichage des tags en bas des pages.

J'ai créé une [branche avec un commit](https://github.com/YesWiki/yeswiki/compare/doryphore-dev...retrieve-tags-at-bottom) pour montrer comment nous pourrions réactiver leur affichage.

@mrflos est-ce que c'était volontaire de les faire disparaître ? Serais-tu d'accord pour leur retour ?

**Comment by mrflos** [comment]
@J9rem non, ce n'était pas intentionnel, j'ai du couper un truc en rapport avec les commentaires un peu vite ou autre erreur, désolé...  
Merci pour le fix, et avec du refacto en plus, cool!  
Juste l'affichage dans le handler /show devrait être géré dans le tools tags (d'ailleurs tout le reste est géré dans tags).

On pourra voir dans ectoplasme si ca ne serait pas mieux de rapatrier l'extension tags dans le coeur, mais en attentant, il me semble plus propre que ce soit géré dans l'extension. Qu'en penses tu? Si t'as pas le temps je pourrais regarder vite fait ce WE.

**Comment by J9rem** [comment]
OK je fais un `ShowHandler__.php` en 5 sec dans `tags` et je fusionne direct dans `doryphore-dev`
