### ISSUE TITLE
Include action preview in documentation

### ISSUE THREAD

**Issue by seballot** [YesWiki/yeswiki#1012]
Yop,
juste une petite issue pour tester un readme driven development concernant le `docsify-component` :)

# Readme

### Include yeswiki code in the doc
To include inline piece of code, juste use markdown delimiter <code>`</code>

`'{{yeswikicode}}'`

To include bigger piece of code (multiline), use markdown delimiter <code>```</code> 

```
'''
=====Title=====
{{someaction}}
'''
```

### Preview some yeswiki code
To include a preview of some yeswiki code in the documentation, use following syntax
`<preview>{{ yeswikicode }}</preview>`

You can go with multiple lines
```
<preview>
=====Title=====
{{someaction}}
</preview>
```

### Include yeswiki code + preview
If you want both the code and the preview to be displayed (code first, preview bellow), use following syntax
```
<preview show-code>
=====Title=====
{{someaction}}
</preview>
```

_____

@mose c'est un truc comme ça qui est attendu?
@J9rem t'en penses quoi? j'ai fait cette issue car je trouve la syntaxe actuelle `<yw-code action-name="toto">` pas très pratique. Pour info pour utiliser le preview tel que je décrit avec vue, faut utiliser les slot  d'une manière particulière, comme [décrit ici](https://stackoverflow.com/a/63427192/9272573)

**Comment by J9rem** [comment]
@seballot bonne idée de trouver une syntaxe plus jolie.
en effet, j'avais surtout créé la branche pour faire la preuve de concept mais je ne m'étais pas permis de faire de PR ou d'issue car pas le temps ni l'envie de rentrer dans les discussions pour définir la bonne syntaxe.

Si ça te motive @seballot , je te laisse la main sur la branche pour adapter.

NB : j'ai l'impression qu'un README driven c'est plus quelque chose où un fichier README.md est créé et restera, là on est plus sur de l'explication standard de PR, ou une issue en mode spec.

NB 2 : Je ne suis pas habitué au README driven, donc je reformule à ma manière pour montrer ce que j'ai compris, sûrement avec des erreurs et en prenant le risque de vous voir réagir dynamiquement pour me corriger et m'apprendre ainsi quelque chose

**Comment by seballot** [comment]
ça marche je peux prendre le relais sur ta branche !

**Comment by seballot** [comment]
pas con l'idée de créer le readme pour de vrai plutot que de mettre du texte dans un commentaire github ! comme ça on garde l'historique des modifs faites sur ce readme. Merci !

**Comment by J9rem** [comment]
et j'y réfléchis, c'est un peu ce que j'ai fait dans la branche `docsify-components` en créant la doc associée : 

 - https://github.com/YesWiki/yeswiki/blob/docsify-components/docs/fr/dev.md#ins%C3%A9rer-une-action-yeswiki-dans-la-documentation
 - https://github.com/YesWiki/yeswiki/blob/docsify-components/docs/en/dev.md#insert-a-yeswiki-action-in-documentation

a priori, pour intégrer ce que tu proposes, li faudrait modifier ces fichiers puis implémenter ce qu'il faut.

**Comment by seballot** [comment]
yes !

**Comment by seballot** [comment]
Je ferme puisqu'on bosse sur un nouveau Readme : https://md.yeswiki.net/e9kPN6HHQUyrxKXC46OLHg?both#
