### ISSUE TITLE
Userstable action add send mail when creating new user 

### ISSUE THREAD

**Issue by AudreyAuriault** [YesWiki/yeswiki#1016]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Sorry guys, mais j'ai pas le niveau pour écrire ça en english...
Dans la 4.3, qu'on est en train de tester (14/09/22), il y a une fonctionnalité qui permet de créer un nouvel utilisateur par un admin.
Dans la version actuelle, le nouvel utilisateur ne reçoit pas de mail de confirmation d'inscription (donc c'est l'admin qui doit trouver un moyen de prévenir ce nouveau bienheureuse)
**Proposition : créer une case à cocher proposant "envoyer un mail au nouvel utilisateur pour lui permettre de générer son nouveau mot de passe"**
Ça vous irait ?
Bises bises
Audrey la Garcess

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
**Doryphore test future 4.3**

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/23/quand-un-admin-cree-un-utilisateur-envoyer-un-email-dinvitation
