### ISSUE TITLE
Card template broken

### ISSUE THREAD

**Issue by seballot** [YesWiki/yeswiki#1021]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug

**Description**
En utilisant les blocs en mode "vertical" avec des images dedans, les blocs ne sont pas bien resizé, si y'a trop de colonnes ils dépassent sur la droite

**Additionnal informations / Informations complémentaires**
`{{bazarliste id="7" template="card" displayfields="visual=imagebf_image,title=bf_titre" nbcol="4" style="vertical" }}`

Rendu avec le bug (ça dépasse du cadre de la fenetre sur la droite)
![image](https://user-images.githubusercontent.com/17404254/191837958-8242d3a1-0d98-42c0-b262-ab21c3925c71.png)

Rendu attendu : les images se resizent pour respecter le nombre de colonnes indiquées
![image](https://user-images.githubusercontent.com/17404254/191837855-91517a03-767d-4fe2-9ebc-c96cf3dd929e.png)

@J9rem je te l'assigne car il semble que le bug provienne de tes changements sur ce template. A mon dernier commit b62e03c0cbf6faed8d5823911893b4c901ece943 sur `card.twig` le comportement était ok. Je pense que le problème vient de ce commit a45e224ba3f8f2baa6af27604261dc31720978b6, en mode `vertical` il ne faut pas utiliser d'objet `img` mais bien garder l'image en `background-image` pour que le redimensionnement puisse se faire dans le template grid

Est ce que tu es ok pour regarder?

Merci,
Sebastian

**Comment by J9rem** [comment]
@seballot merci pour ce point de vigilance.
A l'époque, j'avais privilégié la possibilité de générer dynamiquement les images manquantes en utilisant `<img />` mais j'ai une petit idée pour le faire avec `background`, ... je vais faire un commit de fix

**Comment by seballot** [comment]
Merci pour le fix, je confirme ça re fonctionne !
