### ISSUE TITLE
Création de page plus intuitive

### ISSUE THREAD

**Issue by seballot** [YesWiki/yeswiki#1023]
## Problème

En faisant la doc, on a rediscuté de la création de page dans YesWiki. Et malgré que ça soit une fonctionnalité de base, on a toujours pas d'interface super intuitive pour le faire. Bien sur quand on a compris qu'il suffit de créer un lien pour créer une page ça va, mais quand on débarque on ne peut pas deviner ça

## Piste 1 : amélioration de l'interface pour créer des liens

J'ai tenté de simplifier/améliorer le bouton "lien" dans l'éditeur de page, qui est une des manière classique de créer une page

#### Avant

![image](https://user-images.githubusercontent.com/17404254/192614076-c5280a5c-0278-46b7-9ebe-4c7fe8338e87.png)

#### Après

![image](https://user-images.githubusercontent.com/17404254/192614144-f8b55c9a-7a0c-4173-aa91-110c9becf03c.png)

Il y a aussi une validation si on entre un nom de page incorrect

![image](https://user-images.githubusercontent.com/17404254/192614369-952b1e22-8d5f-497d-918a-5415f4a384bc.png)

## Piste 2 : un bouton pour créer une page?

Perso je verrai bien un bouton dans la roue crantée "créer une page" -> petit popup qui demande juste le nom de la page et on est redirigé vers l'édition de celle ci

Ou alors on met une nouvelle icon genre "page+" dans la barre d'édition d'une page? mais du coup ça créera aussi un lien ou alors ça ouvre la nouvelle page...?

Vous en pensez quoi?

## Piste 3 : la syntaxe {{button}}

Le bouton lien crée maintenant par default des liens en utilisant l'action `{{button}}` plutot que l'ancien `[[Lien nom du lien]]`. Ca me semble cohérent de faire ça, par contre je verrai deux petites améliorations

### Retour du crayon

Avec button, il n'y a plus le petit crayon si la page n'existe pas. ça serait bien de le remettre non?

### Amélioration de la syntaxe

Perso je trouve que `{{button nobtn="1"}}` c'est quand meme super chelou comme concept xD
Je propose cette nouvelle syntaxe
```
{{button as="link" to="MaPage" text="click me"}}
au lieu de
{{button nobtn="1" link="MaPage" text="click me"}}
```

On pourrait aussi créer une nouvelle action raccourci `{{link to="MaPage" text="click me"}}`, qui serait juste une alias de `{{button as="link"}}`.

**Comment by gatienbataille** [comment]
Hello
Piste 1 : popup plus ergonomique mais pas sûr que ça résolve le souci évoqué par Audrey
Piste 2 : j'hésite... le gros souci quand tu crées une page "en mode débutant" sur yeswiki c'est que tu piges difficilement que la pape porte un nomwiki et qu'elle peut être appelée via un mot en français (voir plusieurs différents)... donc si on crée la page par ce petit bouton dans la roue crantée, la personne pourra bien remplir cette nouvelle page mais je prédis que les questions qui viendront après c'est (une fois sauvé et retourné sur une autre page du wiki), comment je retourne la page que je viens de créer ? et donc en gros il faudra expliquer qu'en passant par tableau de bord on voit toutes les pages du wiki, y compris les pages orphelines... selon moi chipo 

reflexion : je crois qu'il faut garder l'idée de créer une page avec directement le lien vers cette page mais que en effet le faire en passant par le chainon n'est pas intuitif et qu'un bouton en plus (créer une page) qui mènerait vers le popup du chainon déjà configuré aiderait peut-être... 
bref je sais pas trop mais créer des pages orphelines je pense que ça va générer bcq de questions...

**Comment by furax37** [comment]
Pour moi, le petit crayon n'est pas utile en syntaxe button et je propose ici ma remarque mattermost : Proposition audacieuse, supprimer la syntaxe [[ManouvellePage Ma nouvelle page]] pour passer à une syntaxe bouton. Cette proposition me fend le cœur mais pour les usagers qui kiffent grave le petit crayon dans la marge, ils faut user de pédagogie alambiquée pour leur faire comprendre qu'il fonctionne partout sauf sur les [[ ]]]. qu'en pensez-vous ?

**Comment by furax37** [comment]
Et j'aime bien la piste 1 que je trouve efficace 
Quant à la piste 2, le risque c'est de créer des pages et que les moldus ne les retrouvent jamais

**Comment by seballot** [comment]
Coucou !

Merci pour vos retours :)

Donc on garde l'amélioration de la popup du chainon
On ne rajoute pas de bouton de création de page depuis la roue crantée

@furax37 et que penses tu d'un nouveau bouton "page+" à côté du chainon, qui va ouvrir un peu la meme popup mais plus orientée création de page?

Et concernant la piste 3 : faire évoluer le  `nobtn="1"` ? 

@furax37 pour info c'est déjà le nouveau comportement par default de créer un lien avec {{button}}. Quand tu dis supprimer la syntaxe [[ ]] c'est juste d'enlever cette possibilité dans la popup? Si c'est ça je suis d'accord. si c'est pour remplacer tout les [[ ]] par des {{button}} dans les wiki existants, c'est plus audacieux lol !

**Comment by furax37** [comment]
Page+ pas d'objection

piste 3 ok

@furax37 pour info c'est déjà le nouveau comportement par default de créer un lien avec {{button}}.
=> j'ai vraiment décroché ces derniers temps...
 Quand tu dis supprimer la syntaxe [[ ]] c'est juste d'enlever cette possibilité dans la popup? 
=> oui, c'est simplement cela
Si c'est ça je suis d'accord. si c'est pour remplacer tout les [[ ]] par des {{button}} dans les wiki existants, c'est plus audacieux lol !

**Comment by mrflos** [comment]
Pas d'objections sur l'ajout d'une icone page+ et de retravailler les modales pour créer des liens.  
Mais je suis toujours chagriné par l'idée de remplacer les liens par des actions button, c'est pas la même chose d'un point de vue composant web, ca alourdit la pages avec des syntaxe actions (surtout si l'action c'est `{{button nobtn="1" link="" class=""}}` c'est pas glorieux ), ce sera moins facile de faire la transformation en liens markdown.  
Je proposais à un moment de faire apparaître le pinceau et les popups sur les liens écrits en syntaxe wiki ou md (en gros, le pinceau d'édition pour autre chose que des actions).  
Car en l'état, cette proposition pousserait plus à abandonner la syntaxe markdown, pour avoir une syntaxe avec les actions pour tout, si on veut etre cohérent, si on fait les liens là, il faudra aussi remplacer la syntaxe des titres  `===titre===` ou `### titre` par `{{title level="3"}}titre{{end elem="titre"}}`, idem pour les tableau et autre syntaxes.

**Comment by seballot** [comment]
Faire un crayon sur des liens [[ ]] oui c'est possible. Mais du coup si on rajoute une option genre "ouvrir dans un nouvel onglet", on passe en `{{button}}` ? ou alors on  bricole une syntaxe genre `[[MapPage Click me @new-window]]` ? j'imagine que c'est pas un cas super courant donc on peut peut être passer en boutton pour pas trop s'embeter?

**Comment by mrflos** [comment]
En fait ya le support partiel de markdown sur la version de dev, je ne suis pas sur que ce soit du markdown pur mais dans la doc, il y a une syntaxe de lien avec des id et class, que l'on pourrait utiliser pour ce cas là.  
Je suis favorable à toute modification qui ramenerait vers du markdown plutot que l'utilisation des actions, qui n'est standard que dans yeswiki.

**Comment by seballot** [comment]
mais [[ ]] c'est une syntaxe wiki pas une syntaxe markdown, du coup je suis pas sur de comprendre, tu veux que ça utilise plutot la syntaxe markdown maintenant `[Click me](MaPage)` ?

**Comment by mrflos** [comment]
Ca m'irait mieux que des actions boutons, mais ce n'est que mon avis.
si les liens [[ ]] sont transformés en liens markdown apres édition pinceau, et que ces meme liens markdown sont aussi accessibles par pinceaux, ca me parait une belle avancée pour arriver à markdown.

Après fait au plus simple selon ton temps dispo, juste les pinceaux sur les [[]] seraient bien, si en plus ca transformer en MD c'est pour ma part, top.

**Comment by acheype** [comment]
Pareil que flo, je serais d'avis à préparer le terrain pour le passage à la syntaxe markdown dans les pages. Je suis pas sûr que ça vaille le coup de passer juste les liens sans le reste, et ça pourrait à mon sens perturber d'avoir une syntaxe mi-yeswiki mi-markdown.
sachant que ça ne sera pas du 100% markdown, j'imagine plus un markdown étendu avec du mardown-extra pour prendre en compte ces cas notamment :
`[Example](https://www.example.com){target=_blank}` pour l'ouverture dans un nouvel onglet
`[link](url){#id .class}` pour mettre une classe à n'importe quelle balise
et surtout on ne sera pas pure markdown avec nos actions un peu partout.
Bref si on peut mettre en place le pinceau sur d'autres trucs que les actions, ça pourra être bien utile !

**Comment by seballot** [comment]
Résolu par #1024

**Comment by seballot** [comment]
Résolu par #1027
