### ISSUE TITLE
Bazar field image 8 files in cache folder

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#1025]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lorsqu'un formulaire bazar contient un champ de type image, celle ci est sauvegardée 8 fois dans le dossier cache avec différentes dimensions ... Cela semble un peu redondant, stocker un format vignette dans le cache pour optimiser l'affichage pourquoi pas, mais 8 formats aux dimensions proches, cela sature les espaces disques rapidement.
![image](https://user-images.githubusercontent.com/37141192/194254153-eca48dc7-7471-4f0b-bc87-c755b9d05803.png)

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki 4.2.4

**Comment by mrflos** [comment]
Hello @MelanieMichel ces fichiers sont générés par les templates bazar que tu utilises : si l'image est petite dans l'affichage liste, il est plus gros dans le trombi, différent dans la page de visu de la fiche..  
Bref, si tu veux moins de fichiers, il faudrait harmoniser les tailles définies dans les differents templates.

**Comment by MelanieMichel** [comment]
ok c'est vrai qu'entre les redimensionnement dans le formulaire, dans le template liste et dans le template fiche ca fait du monde potentiellement. Je ferme l'issue et je reprendrai des tests sur une install fraiche pour vérifier
