### ISSUE TITLE
Action login param userpage 

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#1028]
Bug / Bogue

**Description**
Le paramètre userpage de l'action login ne renvoie pas vers la page demandée - l'utilisateur reste sur la même page.
{{login template="modal.tpl.html" nobtn="0" userpage="?MesFiches" }}

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki 4.2.4.

- url to see the problem or an example / url pour voir le probleme ou un exemple
- screenshot / capture d’écran
- logs

**Comment by mrflos** [comment]
Je hackes cette issue pour aussi voir si ya une issue plus générique sur le fait de ne pas avoir à mettre page="?Nompage" mais juste page="NomPage".  
J'ai l'impression que de vérifier que la syntaxe sans ? de partout corrigerait cela (et c'est peut etre une piste pour cette issue d'essayer sans ?)

**Comment by MelanieMichel** [comment]
En fait le problème est corrigé dans le 4.3 sauf que le nom du paramètre a changé : loggedinurl="MesFiches"
pour la confusion avec les ? c'était pas le pb ici mais j'ouvre une autre issue parce que c'est vrai que ca perturbe pas mal les utilisateurs

**Comment by J9rem** [comment]
@MelanieMichel est-ce que la présente a encore besoin de rester ouverte vu que le souci sera corrigé dans la `4.3` ?
En effet, en regardant le code, ça fait plusieurs années que le paramètre `userpage` ne fonctionne pas (depuis `cercopitheque`) pour un nom de page mais qu'il fonctionne si on met `user`.
pour éviter les confusions possibles, avec @VeveQNV nous avons ajouté un nouveau paramètre `loggedinurl`
