### ISSUE TITLE
Paramètre redirecturl need ? before PageName

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#1029]
Bug / Bogue

**Description**
Dans action {{bazar}} le paramètre redirecturl="MaPage" ne fonctionne que si on ajoute un ? : redirecturl="?MaPage"
Un utilisateur qui passe par le composant "Afficher un formulaire de création de fiche" entre directement le nom de page sans le ? 

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki  4.2.4 et testing 4.3
- url to see the problem or an example / url pour voir le probleme ou un exemple
- screenshot / capture d’écran
- logs

**Comment by J9rem** [comment]
@MelanieMichel la PR a automatiquement été close par l'ajout du correctif mais tu peux vérifier que ça fonctionne en installation une version `doryphore-dev` (ex https://testing.yeswiki.net/)
