### ISSUE TITLE
Ajouter le choix de preset dans action {{gererthemes}}

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#1033]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
L'action {{gererthemes}} disponible dans gestion du site permet de choisir le theme, le squelette, le style pour une selection de pages mais pas de possibilité de choisir le preset . 
Pour le moment si on veut appliquer un preset à un groupe de pages, il faut modifier le preset sur chacune des pages via le bouton theme en mode édition.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki 4.2.4
- url to see the problem or an example / url pour voir le probleme ou un exemple https://testing.yeswiki.net/?GererThemes
- screenshot / capture d’écran
- logs

**Comment by J9rem** [comment]
@mrflos : pour te prévenir, je vais me charger de résoudre cette issus avant le 10/02. @MelanieMichel est OK pour me financer sur ce point (et en plus ça e sera pas long)
