### ISSUE TITLE
Login : pouvoir voir son mot de passe quand on le tape

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#1034]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Il serait utile de pouvoir avoir une vue des caractères tapés lors de la saisie du mot de passe (au clic sur un icone à droite par exemple) comme cela se fait habituellement dans ce type d'interface.

_Demande remontée par utilisatrice rencontrée dans le cadre d'animacoop_

**Comment by mrflos** [comment]
Une piste de résolution : https://www.csestack.org/hide-show-password-eye-icon-html-javascript/

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/22/login-pouvoir-voir-son-mot-de-passe-quand-on-le-tape
