### ISSUE TITLE
Problème d'affichage de fiches liées

### ISSUE THREAD

**Issue by TimotheeINRAE** [YesWiki/yeswiki#1037]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lors de l'affichage des données d'un formulaire, la liste des fiches liées aux fiches du formulaire ne s'affiche pas lorsque le paramètre **dynamic="true"** est présent dans bazarliste (en revanche elles s'affichent bien lorsqu'on les ouvre depuis _Base de données_).

{{bazarliste id="46" template="liste_accordeon" filtersresultnb="false" dynamic="true" groups="listeListeBlocDeCompetences" }}

Lorsque l'on supprime dynamic="true", les fiches liées apparaissent.

{{bazarliste id="46" template="liste_accordeon" filtersresultnb="false" groups="listeListeBlocDeCompetences" }}

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki doryphore : 4.2.4
- url to see the problem or an example / url pour voir le probleme ou un exemple : https://www.cerealocales.org/?ExpertisesListe
- screenshot / capture d’écran
Avec dynamic="true" : ![screen_avecfichesliees](https://user-images.githubusercontent.com/117929237/201648443-a667c50c-9612-4f11-b3b1-7496c51c4fb7.png)
Sans dynamic="true" : ![screen_sansfichesliees](https://user-images.githubusercontent.com/117929237/201648450-706dbf36-f3d8-4f75-8de4-f042888105ba.png)

- logs

**Comment by mrflos** [comment]
@seballot ou @J9rem , sauriez vous si les champs fiches liées sont effectivement incompatibles avec l'affichage dynamique ?

**Comment by J9rem** [comment]
@mrflos effectivement, mes tests rapides m'avaient amené la conclusion que `{{bazarliste dynamic="true"}}` ne fonctionne pas lors de son usage dans les champs `listefiches` (alias de `listefichesliees`).

En l'état, ça ne devrait pas fonctionner.
Mais si on regardait le système de chargement des `bazarliste` (https://github.com/YesWiki/yeswiki/blob/fe8a0a73a45be71e2d2670bfc681ceb38d080a5d/tools/bazar/presentation/javascripts/bazar-list-dynamic.js#L10), nous pourrions peut-être passer par un service javascript qu'on appelle on moment de l'évènement `DOMContentLoaded` comme actuellement, mas que nous pourrions aussi appeler sur un autre évènement à définir genre `entryDynamicallyLoaded`, qu'il faudrait générer une fois la fiche chargée en dynamique par le `bazarliste` de tête

**Comment by mrflos** [comment]
Ok merci pour la confirmation @J9rem , et donc @TimotheeINRAE cela veut dire qu'en l'état, il n'est pas possible d'utiliser les rendus dynamiques avec des fiches contenant des fiches liées.  
On laisse l'issue ouverte afin de trouver une solution technique pour que cela soit possible dans le futur.

**Comment by TimotheeINRAE** [comment]
Bonjour à tous, merci pour les réponses !
