### ISSUE TITLE
pb d'accents

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#104]
http://site-coop.net/accueilpedacivam/wakka.php?wiki=CartoAccueil

j'ai un pb d'accents dans les fiches bazar

**Comment by gekette** [comment]
j'ai aussi des problèmes d'accent...pourtant je viens d'installer la toute dernière version (du jour)
donc après que tu aies fermé le bug ...

par exemple 
http://les.couches.lavables.free.fr/wakka.php?wiki=BazaR&vue=listes&action=modif_liste&idliste=ListeElacmentsPersonnalisables
cette liste a pris un drôle de nom parce que j'avais un accent dans son titre

**Comment by MichelCauzid** [comment]
Avec quel caractère accentué de façon à ce que j'essaie de le reproduire 
chez moi.
Cordialement
Michel

**Comment by gekette** [comment]
Alors je n'ai pas fini mes vérifications, avec Flo, on a pensé que
peut-être ce ne sont que les fiches qui datent d'avant la mise à jour qui
ont des mauvais accents. Je ne crois aps avoir le temps de tester
aujourd'hui. J'essaye dès que possible
