### ISSUE TITLE
Validation d'un formulaire en tapant "entrée" dans un champ "code postal"

### ISSUE THREAD

**Issue by FleurianeH** [YesWiki/yeswiki#1048]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Ce n'est pas complètement un bug mais le comportement normal de validation d'un formulaire en utilisant la touche "entrée" peut poser problème pour le champ "code postal" car ce champ propose de l'autocomplétion. La plupart des utilisateurices utilisent la touche "entrée" pour valider une autocomplétion, ce qui valide en fait le formulaire, même s'il restait des champs (non-obligatoires) à compléter.

**Informations complémentaires**
- version of YesWiki / version de YesWiki 4.3.1

**Comment by J9rem** [comment]
merci @FleurianeH pour ce retour mais je n'arrive pas à reproduire le souci.
En effet, je suis surpris que ceci survienne (le code a priori ne devrait pas avoir le comportement annoncé).

Donc je suppose qu'il y a dans le cas précis un usage moins attendu par les dév. Pourrais-tu me transmettre le lien vers un tel formulaire ? (en message privé si tu préfères) Je pourrai regarder le javascript du site en question pour comprendre ce qui se passe.

**Comment by FleurianeH** [comment]
merci @J9rem pour tes tests. Je t'envoie le wiki en question et les codes d'accès en mp, c'est un formulaire qui n'est ouvert qu'à certain.e.s utilisateur.rices.

**Comment by J9rem** [comment]
@FleurianeH je suis en train de faire les tests sur le site en question (fourni en MP), j'ai essayé avec Firefox. pas de soucis.

Avec quel navigateur le souci apparaît-il ?

**Comment by FleurianeH** [comment]
:/ Moi aussi, j'utilise Firefox et quand j'entre un code postal dans le formulaire et que j'appuie sur "entrée", ça valide le formulaire. ça ne le fait pas quand je clique sur l'autocomplétion proposée. Mais parfois avec le temps de latence, on clique sur "entrée" avant que l'autocomplétion apparaisse.

**Comment by J9rem** [comment]
est-ce que le champ titre est complété dans ton cas avant l'appui sur entrée ?
Quels sont les champs obligatoires non complétés qui n'ont pas empêché l'enregistrement ?
(l'origine du souci est un peu précise donc il me faut le maximum d'info pour la détecter, même si la conséquence semble très facile à voir).

Aurais-tu une capture d'écran du formulaire avant l'appuie sur entrée ? (par MP si tu préfères) et aussi le lien vers la fiche créée, pour que je puisse la voir avec un /raw, ... ça me donnera des indices :mag:

**Comment by FleurianeH** [comment]
Tu peux voir les fiches "Test" créées avec le profil passé en mp. Sur ce formulaire, le champ "code postal" arrive à la fin, tous les champs obligatoires ont été complétés en amont, dont le champ titre, ce qui rend la validation facile. J'imagine que dans d'autres cas de figure, il reste des champs obligatoires dans le formulaire donc la validation ne peut pas se faire.
Capture d'écran avant d'appuyer sur entrée : 
![image](https://user-images.githubusercontent.com/97882886/216012875-1aa97308-c9ed-49e6-97d0-c38198de9712.png)

**Comment by J9rem** [comment]
OK, j'ai mieux compris le souci.
Il faudrait attraper l'évènement "touche entrée" sur les champs texte pour qu'il ne valide pas le formulaire.

**Comment by J9rem** [comment]
a priori, @FleurianeH le correctif sera déployé dans `doryphore 4.4`, 

sachant qu'il sera souhaitable de faire des tests préalables avec `doryphore-test` sur chaque champ bazar en mode saisie de fiche en appuyant sur `Enter` quand le champ a le focus (ping @mrflos @MelanieMichel  pour les tests)

**Comment by FleurianeH** [comment]
Top ! Merci @J9rem. A dispo pour faire des tests sur la branche doryphore-test quand ce sera le bon moment.
