### ISSUE TITLE
Une image par défaut dans les formulaires bazar ?

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#1051]
Demande récurrentes : pourrait-il y avoir une image par défaut dans les agenda, dans les trombinoscopes ?...

Idée, dans les éléments paramétrables des champs image lors de la fabrication d'un formulaire, ajouter un champ optionnel url de l'image par défaut. 
Si pas d'image uploadée lors de la création de fiche, c'est celle là qui s'affiche

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/20/une-image-par-defaut-dans-les-formulaires-bazar
