### ISSUE TITLE
Ajouter le paramètre `preview_before_save` dans la page `GererConfig`

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#1052]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Ajouter le paramètre `preview_before_save` dans la page `GererConfig`

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki `doryphore-dev` après 26 janvier 2023

@mrflos peux-tu / veux-tu le faire ?

**Comment by mrflos** [comment]
oui, je veux/peux bien mais ca ne sera pas dans mes priorités avant la release de la prochaine version.

**Comment by J9rem** [comment]
oh pas d'urgence (l'issue qui parlait du rétablissement de la prévisualisation datait de 2014, et le commentaire de Laurent de 2021) donc nous ne sommes pas , vraiment pas dans l'urgence

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/32/ajouter-le-parametre-preview_before_save-dans-la-page-gererconfig

**Comment by J9rem** [comment]
Il n'y a peut-être pas besoin d'en faire une action pour une priorité pour ce point : je vais faire une PR en 5 minutes, qui va résoudre l'issue.

**Comment by J9rem** [comment]
En fait, nous pourrions même supprimer https://priorites.yeswiki.net/posts/32/ajouter-le-parametre-preview_before_save-dans-la-page-gererconfig car ce commit https://github.com/YesWiki/yeswiki/commit/d87ab723132dd9c4889441ea5c91ae8e8f537038 a déjà implémenté l'option

**Comment by seballot** [comment]
Top merci !
