### ISSUE TITLE
attach : sur png fond transparent si size small ou medium le fond devient blanc

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#1056]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
lorsqu'on insère une image avec action attach, le redimensionnement en small/ medium/large ne respecte pas le fond transparent du png
Il est nécessaire d'insérer une image avec les dimensions exactes et de choisir size=original

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki doryphore 4.3.1

**Comment by J9rem** [comment]
En fait, c'est lié à la bibliothèque utilisée pour redimensionner les images : pour les png, lors du redimensionnement, il faut choisir une couleur de fond.
Il a été choisi pour le cas général, de choisir la couleur blanche par défaut (et éviter le fond noir) : https://github.com/YesWiki/yeswiki/blob/72a8fb7b95b535ecdb1a5f9d2eacbabc3498b9ba/tools/attach/libs/attach.lib.php#L1136-L1142 (`#FFFFFF`)

C'est lié aux échanges https://github.com/YesWiki/yeswiki/issues/641 et https://github.com/YesWiki/yeswiki/pull/948

Donc c'est pas vraiment un bug mais un comportement désiré pour éviter les soucis de fond noir.
Nous pourrions nous concerter pour définir un paramètre de plus dans `wakka.config.php` pour pouvoir choisir une couleur de fond pour les png, mais bon, .... il nous faudrait pour ceci un ou une faciliateurice pour arriver à la bonne décision et un ou une développeureuse disponible, ...

**Comment by MelanieMichel** [comment]
question naive : avez-vous tenté le transparent : #fff0 à tout hasard ?

**Comment by J9rem** [comment]
La librairie doit recevoir une couleur qui fonctionne à la fois pour `jpeg` et `png`.
Après, si on un dev prêt à creuser la question , ...

**Comment by mrflos** [comment]
@MelanieMichel selon la [doc](https://stefangabos.github.io/Zebra_Image/Zebra_Image/Zebra_Image.html#methodresize), mettre -1 à la place du code couleur de l'image, permettrait de préserver la transparence et de mettre du blanc pour les formats non transparents.
Pourrais tu tester en mettant `-1` à la place de `'#FFFFFF'` à la ligne 1142 citée par @J9rem  et tester si ca marche ?
