### ISSUE TITLE
Markdown default support

### ISSUE THREAD

**Issue by Gredin67** [YesWiki/yeswiki#1061]
New feature / Nouvelle fonctionnalité

**Description**
- Support Markdown Syntax by default
  - e.g. without having to add `""<div class="markdown"> votre markdown ici </div>""`
- A graphical editor for the Markdown syntax when chosen by default

Already available in [BookStack ](https://github.com/BookStackApp/BookStack)

**Comment by mrflos** [comment]
It's already partially implemented in next 4.4 release cf. https://testing.yeswiki.net/?Markdown , you can do titles, links and text formatting in md syntax
But the full implementation of markdown in the editor and conversion of actual syntax will only happen in next main release YesWiki "Ectoplasme" 5.0

**Comment by Gredin67** [comment]
Which syntax flavor is planned ? Only the basics or also some advanced one like [GitHub Flavoured Markdown](https://github.github.com/gfm/) ? Support for multiline table cells would be nice.

**Comment by Gredin67** [comment]
When is the next release approximately planned?

**Comment by J9rem** [comment]
@Gredin67 you can use the new revision `doryphore 4.4`. Does this revision allow you to use markdown syntax as you need ?

**Comment by seballot** [comment]
closing in favor of https://priorites.yeswiki.net/posts/19/support-complet-du-markdown-dans-lediteur
