### ISSUE TITLE
Raccourci pour espace insécable (no-break space)

### ISSUE THREAD

**Issue by Hoppicker** [YesWiki/yeswiki#1063]
New feature / Nouvelle fonctionnalité
# Créer un raccourci clavier pour obtenir un espace insécable

En mode édition, un espace insécable peut être copié-collé dans le texte (il apparait alors sous forme d'une plage rose avec un point rouge au centre), mais ne peut pas être écrit à l'aide d'une touche ou d'une combinaison de touches.
La combinaison de touches Ctrl + Maj + Espace, utilisée dans LibreOffice, serait l'option préférable.
Un espace insécable (code décimal 160, hexadécimal U + A0) est utilisé :
- devant les signes de ponctuation  ! ? : ; 
- devant ou derrière – (tiret long), « et » (guillemets typographiques)
- entre le nombre et l'unité 
- et en tant que séparateur de milliers

afin d'éviter un passage à la ligne inopportun

**Comment by mrflos** [comment]
Pour mémoire, les raccourcis clavier de aceditor https://defkey.com/ace-editor-shortcuts
Pas d'espace insécable par défaut, mais si c'est facile d'ajouter des raccourcis claviers à aceditor, ca serait bien d'avoir cette option!

**Comment by J9rem** [comment]
@mrflos il est possible d'ajouter des évènements dans ce fichier pour créer un autre raccourcis : [aceditor-key-bindings.js](https://github.com/YesWiki/yeswiki/blob/doryphore-dev/tools/aceditor/presentation/javascripts/aceditor-key-bindings.js).
J'espère que ça peut aider.

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/31/editor-ajouter-un-raccourci-pour-espace-insecable-no-break-space
