### ISSUE TITLE
[extension-ipblock] : pas de blocage des ips selon les cas

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#1064]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
malgré la configuration d'adresses IP bloquées dans l'extension `ipblock` : il n'y a pas de blocage lors de la modification de fiches ou de pages 

_Problème initialement soulevé par @EdmondAgate : https://framateam.org/yeswiki/pl/9cmny3jwp3fsbp4grtjqcmdyna_
_Ce souci concerne bien l'extension `ipblock`, mais vu que la page des issues de cette extension est moins suivie : https://github.com/YesWiki/yeswiki-extension-ipblock/issues et vu que les améliorations à faire sont très liées au coeur, j'ai décidé de la déposer ici. J'espère que ça convient_

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki `doryphore 4.3.1`
- version `ipblock` `1.0.1`

**Comment by J9rem** [comment]
Effectivement @EdmondAgate, il semble possible de ne pas passer par le test de `ipblock` dans les cas suivants :
 - _lors de l'édition d'une page via le handler `/edit`, l'enregistrement est déclenché par `$_POST['submit']=='Sauver'` (voir [code](https://github.com/YesWiki/yeswiki/blob/8e659061d63c91a54da5aceb581b01f6edd73d3a/handlers/page/edit.php#L58))_
 - dans l'extension `ipblock`, lors de l'usage du handler `/edit`, ( voir [code](https://github.com/YesWiki/yeswiki-extension-ipblock/blob/02ab7315d967e663473529e6941dff65e3537aaf/handlers/page/__edit.php#L19)), si `$_POST['submit']=='Sauver'`, alors il y a test pour l'ip
 - lors de la modification d'une page via `/editiframe`, comme le handler `/edit` est utilisé, le test est lui aussi réalisé
 - le problème concerne les fiches :
   - il n'y a aucun test dans l'extension `ipblock`, pour tester l'adresse IP avant la création d'une fiche via l'action `{{bazar}}`
   - lors de la modification d'une fiche via le handler `/edit` (voir [code](https://github.com/YesWiki/yeswiki/blob/doryphore-dev/tools/bazar/handlers/__EditHandler.php)), il n'y a pas de test de `$_POST['submit']=='Sauver'`, donc l'extension `ipblock` peut être contournée
   - lors de la modification d'une fiche via `/editiframe`, (voir [code](https://github.com/YesWiki/yeswiki/blob/8e659061d63c91a54da5aceb581b01f6edd73d3a/handlers/EditIframeHandler.php#L28)) il n'y a même pas de test `$_POST['submit']=='Sauver'`, donc l'extension `ipblock` peut être contournée
   - dans le champ [`ImageField`](https://github.com/YesWiki/yeswiki/blob/8e659061d63c91a54da5aceb581b01f6edd73d3a/tools/bazar/fields/ImageField.php#L57), lors de la suppression d'une image, si l'usager a le droit de supprimer l'image (mode connecté), alors il n'y a pas de test pour l'adresse IP.
   
 Bref, je laisse ici une trace de mon analyse pour que la ou le dev. qui voudrait améliorer `ipblock` sache quels tests rajouter.

**Comment by mrflos** [comment]
@J9rem je déplace l'issue dans https://github.com/YesWiki/yeswiki-extension-ipblock/issues/1 car elle concerne cette extension, et qu'il est possible de faire des tests dans l'extension pour gérer le cas des fiches bazar
