### ISSUE TITLE
basculer de l'onglet "Code wiki" à l'onglet "Constructeur graphique" sans sortir de l'édition du formulaire en cours

### ISSUE THREAD

**Issue by ghost** [YesWiki/yeswiki#1078]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lors de l'édition d'un formulaire, lorsque l'on fait une modification dans le Constructeur Graphique, on peut aller sur l'onglet "Code Wiki" et la modification est prise en compte sans autre message.
Par contre, en cas de modification dans l'onglet "Code Wiki", lors d'un retour sur l'onglet "Constructeur Graphique", un message d'alerte nous informe "En affichant le constructeur graphique, vous perdrez vos modifications faites dans le code ici-même. Continuer sans sauvegarder les changements ? (Cliquez sur le bouton "Valider" en bas de page pour conserver vos modifications !)"
Cela implique qu'il faut alors cliquer sur "Valider" pour enregistrer les modifications. Puis cela renvoie sur la page de gestion des formulaires puis il faut retrouver son formulaire, cliquer sur "éditer" pour revenir sur l'onglet "Constructeur Graphique".

Le comportement attendu serait que l'on puisse basculer de l'onglet "Constructeur graphique" et "Code wiki" et [vice-versa](https://www.youtube.com/watch?v=ZTeqM5gciH8) sans sortir de l'édition du formulaire en cours

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : 4.2 / 4.3 / 4.4
[- url to see the problem or an example / url pour voir le probleme ou un exemple](https://testing.yeswiki.net/?BazaR&vue=formulaire&action=modif&idformulaire=2)

**Comment by J9rem** [comment]
Merci @JeremyCDP pour ce retour.
En fait, à un moment, nous avons mis en place l'aller-retour avec mise à jour automatique mais ceci a posé de TRES GROS SOUCIS. 
En effet, lorsque des personnalisations du code du formulaire sont intégrées par des personnes aguerries, celle-ci peuvent disparaître sans prévenir lors de la génération automatique du formulaire via le constructeur graphique.

Ainsi, pour permettre les personnalisations avancés (qui ne seraient pas encore implémentées dans le constructeur graphique ou qui n'ont pas été validée pour leur intégration dans le constructeur graphique), la mise à jour de l'affichage via constructeur graphique n'est pas plus automatique.

Un message d'alerte permet d'expliquer ceci.

Je suis tout à fait d'accord que le comportement n'est pas fluide. Mais comme il s'adresse à des usagers très avancés, je trouve personnellement que c'est mieux de conserver la stabilité à cette endroit.

**Comment by seballot** [comment]
> Je suis tout à fait d'accord que le comportement n'est pas fluide. Mais comme il s'adresse à des usagers très avancés, je trouve personnellement que c'est mieux de conserver la stabilité à cette endroit.

d'accord avec jerem, je ferme l'issue
