### ISSUE TITLE
Ecran blanc apres caracteres spéciaux

### ISSUE THREAD

**Issue by MichelCauzid** [YesWiki/yeswiki#108]
Que le monde des apostrophes est complexe !
quand je tape le caractère «  ' » (en dessous du 4 sur mon clavier) il me semble que j'utilise le caractère 0027 '
Lorsque je tape parcequ'on (c'est pas très joli.... mais c’est ce que j'ai tapé ce matin)
Le correcteur orthographique me propose
parce qu’on (c'est pas plus joli... mais peut être orthographiquement exact)
et lui il utilise, me semble-t-il, le caractère 2019 …. beaucoup plus esthétique lorsqu'on regarde au microscope.... ! Mais qui plante tout.

**Comment by mrflos** [comment]
bonjour, merci pour ce retour, on dirait le meme bug que #105 j'ai fait une correction a l'instant, pourrais tu tester?

**Comment by MichelCauzid** [comment]
ça marche avec tous les caractères accessibles depuis mon clavier
ça marche avec d'autres caractères comme ... 2026
et surtout lorsque le caractère n'est pas reconnu ça renvoie un point 
d’interrogation... mais ça ne plante pas!

Je continue à tester plus en profondeur.

Merci
Michel

**Comment by mrflos** [comment]
ok Michel merci de tes tests!
Dans l'idéal je veux bien une liste des caractères non reconnus pour trouver une éventuelle solution!

Cordialement

**Comment by MichelCauzid** [comment]
Bonsoir
La question c'est jusqu’où veut-on aller?
J'ai créer 4 fichiers de tableaux des caractères Unicode

```
Table des caractères Unicode "Latin de base" d’après Wikipedia
Table des caractères Unicode "Supplément Latin-1" d’après Wikipedia
Table des caractères Unicode "Latin étendu A" d’après Wikipedia
Table des caractères Unicode "Latin étendu B" d’après Wikipedia
```

J'ai copier ces fichiers dans des pages YesWiki 
Le résultat doit être accessible ici ..... http://www.notes.cauzid.eu/wakka.php?wiki=EssaiSystematiquePages 
- Il n'y a eu aucun écran blanc au moment de la sauvegarde
- Les deux premières tables sont complètes
- Quelques caractères seulement sur les deux dernières tables, les caractères non reconnus sont modifiés en ? au moment ou l'on sauve.
