### ISSUE TITLE
Bug sur utilisation des onglets dans les formulaires

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#1081]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Dans les formulaires bazar le champ tabs ne gère pas correctement l'absence d'onglets pour la fiche - ce qui est la valeur par défaut actuellement
A l'enregistrement de la fiche, un onglet est ouvert même si le paramètre "pour la fiche" est vide : 
`<div role="tabpanel" class="yeswiki-tab with-padding tab-pane active" id="">`
absence de </div>  l'affichage explose

Version 4.4.0
Page de test : https://pratic-coop.fr/doryphore/?TestOngletSaisie

**Comment by J9rem** [comment]
merci pour le retour @MelanieMichel , c'est corrigé avec https://github.com/YesWiki/yeswiki/commit/6273aca6c72512eb9090987d468b8df71263ad29
