### ISSUE TITLE
Titre en double pour les modales ouvertes par BazarListe

### ISSUE THREAD

**Issue by acheype** [YesWiki/yeswiki#1087]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Depuis la mode du "dynamic" dans bazar, on a maintenant des iframes qui sont ouvertes dans les modales de présentation de la fiche sélectionnée. Or on se retrouve systématiquement avec le titre en double (celui de la modale + celui de la fiche) comme ci-dessous :
![2023-07-06 08-12 - Capture d'écran](https://github.com/YesWiki/yeswiki/assets/8435038/7761b04e-82ba-4821-b729-15c1268a9b98)
Auparavant les fiches n'étaient pas en iframe et le js s'occupait de virer le titre dans le contenu de la fiche.
Perso, je règle souvent cela en css en enlevant le titre de la modale et en modifiant les marges : 
![2023-07-06 08-15 - Capture d'écran](https://github.com/YesWiki/yeswiki/assets/8435038/6989cd0c-53d1-4de7-98f5-a284eac5d2d7)

**Proposition**
Ce serait plus ergonomique de régler cela directement dans le cœur. Soit il y'a cette solution, soit on peut appeler l'iframe systématiquement avec le paramètre d'url pour supprimer le champ bf_titre. Cette dernière façon ressemble à ce qui se fait avant avec l'intégration des fiches non iframe dans les modales, elle permet d'avoir le titre bien aligné avec la croix et avec un CSS adapté pour le titre de la modale, c'est certainement une meilleure solution.

**Additionnal informations / Informations complémentaires**
- Doryphore 4 & doryphore-dev

**Comment by acheype** [comment]
Finalement la solution 1 me paraît plus approprié si l'on prend en compte la possibilité qu'on puisse afficher des fiches liées dans la même modale, cf cette PR où j'explique cela : https://github.com/YesWiki/yeswiki/pull/1089

en plus, il me semble finalement que le paramètre `exclude_fields`  (ou un truc du genre) fonctionne qu'avec l'API et le soucis d'alignement n'est qu'un soucis CSS (en absolute, ça doit pouvoir se régler).

**Comment by acheype** [comment]
@seballot Vu que ça touche à la fois à margot et à l'affichage dynamique, est-ce que tu pourrais y jeter un œil à la rentrée ?

Vu qu'on peut ensuite changer de fiche au sein de cette même modale, je propose de partir sur la solution 1 (cf screenshot juste au dessus). Je peux partager mon code CSS si besoin, c'est jusque que pour l'instant, mon code cache le titre pour toutes les modales. 
Pour le cas notamment d'un site extérieur qu'on voudrait afficher dans une modale, on peut avoir besoin de ce titre. J'imagine que ça pourrait être paramétrable dans le formbuilder lorsqu'on décide qu'un lien s'ouvre dans une modale. Concrètement, ça pourrait se traduire par une classe CSS qui permettrait de dire qu'on veut un titre (ou l'inverse) pour la modale.

**Comment by seballot** [comment]
ok j'essaie de regarder ce week end !
