### ISSUE TITLE
Boutons de mise en forme qui ne fonctionnent plus

### ISSUE THREAD

**Issue by SiM** [YesWiki/yeswiki#1097]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lorsque j'édite une page, aucun bouton de mise en forme n'a d'effet. Aucun message d'erreur à signaler.
Si je tape le code directement cela fonctionne.
J'ai l'impression que c'est arrivé depuis la dernière mise à jour. Cela me fait ça sur les deux Yeswiki installés sur le même serveur.

Je remarque que ma barre de boutons d'édition est un peu "bizarre" (deux fois le bouton "Envoyer un fichier" par exemple cf. capture)

![yeswiki](https://github.com/YesWiki/yeswiki/assets/71776/ade4af35-ebf8-40a2-a501-253d79358e10)

Autrel indice : dans la page `?GererThemes`, j'ai ce message d'erreur :

> Une erreur inattendue s'est produite. Veuillez contacter l'administrateur du site et lui communiquer l'erreur suivante :
> Call to undefined function recup_meta() in /var/www/yeswiki__4/tools/templates/actions/gererthemes.php on line 47

Pas d'autres messages d'erreur à signaler ailleurs à priori.

Merci d'avance !

**Additionnal informations / Informations complémentaires**
- version de YesWiki : doryphore 4.4.1
- thème : Margot
- installé via YunoHost (11.2.4)

**Comment by mrflos** [comment]
Bonjour @SiM , merci du retour!  
Je pense que la mise a jour ne s'est pas bien passee , car le fichier tools/templates/actions/gererthemes.php ne devrait pas exister, il s'appelle maintenant GererThemesAction.php (cf. https://github.com/YesWiki/yeswiki/tree/doryphore/tools/templates/actions).

Peut etre passer par la roue crantee > gestion du site > MAJ et extensions et reinstaller la version 4.4.1 par la?

**Comment by mrflos** [comment]
Le bug concerne la version Yunohost de yeswiki, et une correction est en cours cf. https://github.com/YunoHost-Apps/yeswiki_ynh/pull/68

**Comment by mrflos** [comment]
corrigé par https://github.com/YunoHost-Apps/yeswiki_ynh/pull/72
