### ISSUE TITLE
interpréter les éléments de mise en forme dans un tableau ou un affichage cards

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#1102]
Quand j'affiche des contenus de fiches bazar dans un tableau ou dans un affichage de type cards, les éléments de mise en forme ne sont pas interprétés ce qui permet de voir les codes wiki. 
une piste pour remédier à ça ?

![image](https://github.com/YesWiki/yeswiki/assets/1269848/f6737f57-f078-4afa-8422-17c0d3365a52)

![image](https://github.com/YesWiki/yeswiki/assets/1269848/55a8427a-3ce9-412e-bb45-a7b038ba4fba)

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/18/interpreter-les-elements-de-mise-en-forme-dans-un-tableau-ou-un-affichage-cards
