### ISSUE TITLE
Prévenir avant de sortir du mode édition

### ISSUE THREAD

**Issue by matcho** [YesWiki/yeswiki#111]
Quand on est en mode édition et que par mégarde on change d'URL (précédent, clic sur un marque-page etc.), il serait méga cool trop bien d'avoir un petit message "êtes-vous sûr de vouloir quitter cette page?". Moi j'dis ça j'dis rien.

**Comment by mrflos** [comment]
bonjour cher ours qui aime les enfants, cette extension existe : https://github.com/mrflos/yeswiki-external-extensions/tree/master/alerte 
Elle n'a pas été intégrée au coeur de yeswiki car meme ceux qui nous l'avait demandé ont fini par être dérangés par le fait contraire: on ne les laissait pas partir tranquillement du mode édition sans raison. Mais n'hésites pas à l'essayer!
