### ISSUE TITLE
Les actions YesWiki en mode edition ne sont plus reconnues quand dans une liste a puce

### ISSUE THREAD

**Issue by mrflos** [YesWiki/yeswiki#1115]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
```
 - liste a puce 
 - liste a puce 2
 - liste {{button class="btn btn-primary" link="TotO" text="Toto"}}
 - liste a puce 3
```
:arrow_up: l'edition de l'action button ne marche pas

------

```
 - liste a puce 
 - liste a puce 2
 - liste 
 - liste a puce 3
{{button class="btn btn-primary" link="TotO" text="Toto"}}
```
:arrow_up: l'edition de l'action button ne marche pas

------
```
 - liste a puce 
 - liste a puce 2
 - liste 
 - liste a puce 3

{{button class="btn btn-primary" link="TotO" text="Toto"}}
```
:arrow_up: l'edition de l'action button marche enfin mais les cas précédents devraient aussi marcher

------
ping @seballot si t'as une piste (vers quel fichier regarder) pour changer ce comportement? Merci!!!

**Comment by seballot** [comment]
Yes tu peux regarder ici : https://github.com/YesWiki/yeswiki/blob/87b68ca7aeec92d512df78dceffc48dc4c7a758a/tools/aceditor/presentation/javascripts/aceditor.js#L97

voir quelle est la valeur de cursor.groupType

et groupType est définit ici : https://github.com/YesWiki/yeswiki/blob/87b68ca7aeec92d512df78dceffc48dc4c7a758a/tools/aceditor/presentation/javascripts/ace-wrapper.js#L94
Mais là c'est un peu plus touchy, je me souviens plus vraiment comment ça marche mais je vois que y'a quelques commentaires !

Si tu galères dis moi je regarderai

Zoubs

**Comment by seballot** [comment]
ah en fait je viens de me souvenir, toute cette logique repose en fait sur la colorization syntaxique. Donc en fait ce qu'il faut fixer c'est plutot cette enchevetrement de regexp pour correctement détecter une action à l'intérieur d'une liste à puce

https://github.com/YesWiki/yeswiki/blob/87b68ca7aeec92d512df78dceffc48dc4c7a758a/tools/aceditor/presentation/javascripts/mode-yeswiki.js#L16

ça serait intéressant de tester ce code avant introduction du support markdown, voir si ce bug est là depuis toujours ou si quelque chose a été cassé recemment

Zoubs !
