### ISSUE TITLE
Composant bazar conditionschecking incompatible avec checkboxfiche

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#1132]
**Description**
Pour un formulaire bazar conditionschecking permet de définir des conditions d'affichage d'une partie du formulaire : par exemple si je coche "autre" alors un nouveau champ texte est afficher pour préciser

conditionschecking fonctionne correctement lorsque la condition est basée sur
- une liste d'éléments
- une liste de fiches bazar
- des checkbox d'éléments
mais cela ne fonctionne pas lorsque la condition est basée sur des checkbox de fiche bazar

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki 4.4.2.

**Comment by J9rem** [comment]
Salut @MelanieMichel ,
est-ce que tu pourrais donner des détails ?
Par exemple ?
 - code du formulaire concerné
 - nom du champ qui plante dans ce formulaire
 - comportement attendu pour ce champ
 - comportement obtenu
 
 Ainsi, je pourrai refaire les tests en local et ainsi comprendre ce qui ne va pas. Alors que en l'état, .... ça n'est pas suffisant pour retrouver le cas qui plante.

**Comment by MelanieMichel** [comment]
Merci pour ton retour Jeremy
Voici le code d'un formulaire dans lequel la condition fonctionne (si une fiche de la liste est sélectionnée alors on affiche le champ texte nb de personnes)
texte***bf_titre***Titre de la fiche*** *** *** *** ***text***1*** *** *** * *** * *** *** *** ***
listefiche***2***Liste déroulante*** *** *** ***bf_event*** ***0*** *** *** * *** * *** *** *** ***
conditionschecking***bf_event is not empty*** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
texte***bf_nombre***Nombre de personnes*** *** *** *** ***number***0*** *** *** * *** * *** *** *** ***
labelhtml***</div>*** *** ***

Si tu remplaces listefiche par checkboxfiche, la condition ne fonctionne pas : le champ texte n'apparait pas lorsqu'une case est cochée

Si c'est pas suffisant, tu peux en contacter en direct

**Comment by J9rem** [comment]
Merci @MelanieMichel c'est beaucoup plus facile de reproduire le bug avec toutes ces informations.
D'ailleurs, j'ai proposé une PR de correction que tu pourras valider si ça corrige le bug.
