### ISSUE TITLE
Impossible d'associer un utilisateur avec un espace à la fin de son nom à un groupe

### ISSUE THREAD

**Issue by sylvainlehmann** [YesWiki/yeswiki#1148]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lors de la création d'un utilisateur, il n'y a pas de vérification si ce dernier a un espace à la fin.
Seulement lors de l'ajout d'un utilisateur à un groupe le script supprime cet espace dans le champ permettant d'indiquer l'utilisateur correspondant, donc l'utilsateur n'est jamais associé au groupe.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : 4.4.4

**Comment by mrflos** [comment]
La demande serait de supprimer les espaces a la fin (et au début) d'un compte utilisateurise ou alors de permettre l'insertion dans les groupes de user avec des espaces qui traînent? 
;)

**Comment by sylvainlehmann** [comment]
@mrflos je sais pas trop. A ton avis quel serait la meilleure solution ? A mon avis l'ajout d'une contrainte serait plus pérenne mais il y a un enjeu de migration de données (pour pas casser les wikis existant).
L'autre solution évite de gérer une migration de données supplémentaire mais comme le nom d'utilisateur sert de clé à plein d'endroit dans la base j'ai peur qu'il y ait d'autres effets de bord pas détectés.

Je peux regarder en vitesse pour faire un fix rapide une fois la solution technique validée

**Comment by mrflos** [comment]
Je pense qu'il vaut mieux supprimer l'espace, on pourra aussi faire un trim au moment du test du login et de l'authentification, voire une requete dans la base de donnees pour appliquer ce trim, mais je ne pense pas qu'il y ait des wikis avec des usager.es en espace a la fin qui existent.

**Comment by mrflos** [comment]
@sylvainlehmann j'ai corrigé sur la branche de dev, mais pour l'extension loginsso, je me demande s'il faudrait pas utiliser la méthode UserController->create plutot que celle du UserManager, je pense qu'il y a d'autres tests de fait (mais peut etre c'est bloquant si le provider d'auth est plus permissif que le controlleur Yeswiki).
En tout cas j'ai aussi renforcé la méthode UserManager->create pour etre tranquille.
