### ISSUE TITLE
template card : l'ID d'une fiche s'affiche au lieu de son titre pour le champ 'title'

### ISSUE THREAD

**Issue by acheype** [YesWiki/yeswiki#1179]
**Description**
Lorsqu'on a un champ de formulaire qui est une listefiche (ou checkboxfiche, etc.) et qu'on choisit dans l'affichage du template card que ce champ s'affiche au niveau du titre de la fiche, ce n'est pas le titre de l'affiche qui est affichée mais son ID.

Ca fonctionne parfaitement avec tous les autres emplacements du template (`subtitle`, `text`, `footer`, `floating`), il doit donc y avoir un traitement particulier quand c'est `title`.

Dans le screenshot ci-dessous, j'ai mis pour chaque emplacement de la fiche le même champ. On voit bien que le soucis se produit uniquement avec `title`.

**Additionnal informations / Informations complémentaires**
![2024-06-29 12-10 - Capture d'écran](https://github.com/YesWiki/yeswiki/assets/8435038/62eeae15-71ee-4eee-ae42-032ab2d60cbd)

**Comment by acheype** [comment]
@seballot Est-ce que tu pourrais y jeter un oeil stp ? Ca doit pas être grand chose à mon avis.

**Comment by seballot** [comment]
yes je regarderai !

**Comment by acheype** [comment]
salut @seballot,
je me permet une petite relance étant donné que c'est la rentrée. Est-ce que tu pourrais jeter un coup d’œil à ce bug stp ? :pray:

**Comment by acheype** [comment]
J'aimerais bien le corriger seul, mais j'arrive pas avec cette partie full vue. Si jamais @seballot ou quelqu'un d'autre pouvait y jeter un oeil, je suis sûr que c'est vraiment pas grand chose étant donné que cela se produit uniquement pour le champ `title`.

**Comment by mrflos** [comment]
Hello ce problème mériterait d’être traité plus globalement, car il s'agit de formater des contenus pour les listes bazar dynamiques, mais on a le soucis pour les dates, pour les images, pour les liens, etc,..
En gros il prend la valeur brute des champs pas la valeur calculée.

En tout cas la bonne nouvelle, j'ai eu a faire du sur mesure pour regler un truc dans le genre, et c'est du php et pas du vuejs: cf. https://github.com/YesWiki/yeswiki/blob/feat/entry-with-extra-data/tools/bazar/controllers/ApiController.php#L314 (par ici j'ai fait un truc pour formater le wiki des champs textelong pour les descriptions si elles sont utilisées pour le champ subtitle des templates dynamiques).
Tu devrais pouvoir t'en inspirer et tester sur un pseudo code du genre
```
si champ=title and title==id_fiche alors va chercher le vrai titre
```

*Et juste pour éviter le burnout des mainteneurs, peut etre ne pas tagguer Sebastian pour chaque souci concernant vuejs, c'est un choix assumé collectivement, même si c'est galère, en tout cas l'effort de maintenance ne doit pas reposer sur lui seul.*

**Comment by mrflos** [comment]
`

**Comment by acheype** [comment]
Hello,
Merci pour la piste mais ça aurait vraiment fait trop bidouille de modifier le champ étant donné que c'est la seule propriété card qui ne remplace pas le tag par le bf_titre. Exemple ci-dessous où toutes les propriétes card affichent le même champ : 
![2024-09-30 02-41 - Capture d'écran](https://github.com/user-attachments/assets/5d7f61cb-e93c-492a-8961-fbee7aac2d13)

En regardant de plus près la partie twig, j'ai vu que la façon dont était traité le champ title différait, c'était un span simple qui affichait la valeur, au lien d'un appel à un composant view. J'ai passé le title avec le composant view et ça semble bien fonctionner. Le seul truc qui change c'est que ça rajoute un div dans le code html.
J'ai fait une PR avec cette correction très simple : https://github.com/YesWiki/yeswiki/pull/1210

Une fois validé de votre côté pour s'assurer qu'il n'y ait pas d'effet de bord, je pourrai clore le ticket.

**Comment by acheype** [comment]
branche mergée
