### ISSUE TITLE
Nouveau nom des champs EnumField : pas de maintien du nom après modification du formulaire

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#1198]
**Description**
Avec `doryphore-dev`, lorsqu'on modifie un formulaire créé avec `doryphore 4.4.4` qui contient un champ `EnumField`, on perd l'affichage des données des fiches pour ce champ.

**Additionnal informations / Informations complémentaires**
- version de YesWiki `doryphore-dev-2024-08-02-58`

**Comment reproduire le bug**:
 - Téléchargement de l'archive de `doryphore 4.4.4` depuis https://yeswiki.net/?PageCreer (SHA256: `d60b4361d9449e4f91498125138ee56f60200b5a063e6741c157772f88281de7`)
 - Installation du yeswiki
 - Connexion en tant qu'administrateur
 - Configuration des paramètres pour ne pas faire de sauvegarde automatique avant chaque mise à jour
 - Mise à jour du thème `margot` et réinstallation de yesWiki en `doryphore 4.4.4`
 - Création d'une liste `Choix`
   - a: Alpha
   - b: Beta
   - c: Gamma
 - Création d'un formulaire avec ce template
   ```
   texte***bf_titre***Titre de la fiche*** *** *** *** ***text***1*** *** *** * *** * *** *** *** ***
   checkbox***ListeChoix***Choix*** *** *** ***bf_choix*** ***1*** *** *** * *** * *** *** *** ***
   ```
 - Création de quelques fiches
 - Dans la page `GererMisesAJour`, remplacement de `{{update}}` par `{{update version="doryphore-dev"}}`
 - Mise à jour de YesWiki vers cette nouvelle version (`doryphore-dev-2024-08-02-58`)
 - Affichage des fiches précédemment créées : OK
 - Modification du formulaire pour ajouter un champ texte simple. Voici le nouveau template
   ```
   texte***bf_titre***Titre de la fiche*** *** *** *** ***text***1*** *** *** * *** * *** *** *** ***
   checkbox***ListeChoix***Choix*** *** *** ***checkboxlistechoixbf_choix*** ***1*** *** *** * *** * *** *** *** ***
   texte***bf_text***Texte court*** *** *** *** ***text***0*** *** *** * *** * *** *** *** ***
   ```
   - **on constate que le nom du champ type `CheckboxField` est passé en minuscule** (`checkboxListeChoixbf_choix` => `checkboxlistechoixbf_choix`)
 - Le contenu des fiches précédemment créées n'affiche plus les champs de type `checkbox`
 
**Origine plausible du bug**:
 - le script du fichier [`tools/bazar/presentation/javascripts/form-edit-template/form-edit-template.js`](https://github.com/YesWiki/yeswiki/blob/56f728b21bd7c19aeff2c415f5b7f267b9cbcf5e/tools/bazar/presentation/javascripts/form-edit-template/form-edit-template.js#L213) force en minuscule le nom des champs lors de l'édition graphique d'un formulaire
 - ceci modifie le nom du champ 
 - il y a alors rupture de la liaison des données entre le formulaire et les fiches
 
**Proposition de correctif**:
 - serait-il possible de retirer la ligne 213 du fichier [`tools/bazar/presentation/javascripts/form-edit-template/form-edit-template.js`](https://github.com/YesWiki/yeswiki/blob/56f728b21bd7c19aeff2c415f5b7f267b9cbcf5e/tools/bazar/presentation/javascripts/form-edit-template/form-edit-template.js#L213) (`.toLowerCase()`) ?
 - Je ne fais pas de PR car je ne sais pas si la proposition est en accord avec la philosophie des évolutions en cours de YesWiki. 
 
 Qu'en pensez-vous @seballot @mrflos ?

**Comment by mrflos** [comment]
Merci pour le retour sur ce sérieux dysfonctionnement @J9rem 
Si c'est bien cela le problème, j'imagine que de permettre les majuscules serait le plus facile a faire, car faire une migration qui met tous les index des fiches en minuscule serait extrêmement couteux pour des wikis avec des milliers de fiches.

Qu'en penses tu @seballot ?

**Comment by seballot** [comment]
Yes bien vu Jerem, merci !

Je suis aussi d'accord pour retirer ce toLowercase, c'est safe
