### ISSUE TITLE
Pb d'affichage des pdf sur certains navigateurs

### ISSUE THREAD

**Issue by acheype** [YesWiki/yeswiki#1207]
Depuis la mise à jour de pdf.js avec la version en mjs, j'ai remarqué que les affichages de pdf ne se font plus dans de nombreux navigateurs.

Suivant le paramétrage du serveur, le .mjs n'était pas une extension autorisée. Le patch de @J9rem a corrigé cela : https://github.com/YesWiki/yeswiki/pull/1184 

Mais maintenant, certains navigateurs qui ne sont pas tout à fait à jour ne semblent pas reconnaître certaines syntaxes utilisées.

Je suis arrivé à reproduire cela sur 2 versions de navigateur que j'ai.

Sur firefox 112.0.1 : 
![2024-09-27 01-02 - Capture d'écran](https://github.com/user-attachments/assets/f003a039-0f83-4357-a305-8d39d379f220)

Sur chromium 83.0.4103.116 : 
![2024-09-27 01-03 - Capture d'écran](https://github.com/user-attachments/assets/c8eb3a29-6584-4b3f-9315-350fcac1f80a)

S'il n'y a pas de solution pour intégrer cette nouvelle version tout en garantissant le maximum de compatibilité, je me demande s'il ne serait pas plus judicieux de remettre l'ancienne version de pdf.js. Car à la base, l'intégration des pdf dans yeswiki a été prévu s'assurer que tout le monde pouvait les lire,  y compris ceux qui n'ont pas de lecteur intégré à leur navigateur.

**Comment by mrflos** [comment]
Elles sont bizarres tes erreurs @acheype , ca pourrait pas être lié a des extensions antipubs/ antijs?
En tout cas, la situation est merdique, car rester sur une vieille version me parait pas une bonne option, les pdf étant connus comme pouvant ne pas être surs et donc livrer des librairies vieilles c'est pas génial.

Après c'est l'introduction des modules mjs qui fait chier car cela nécessite des changements sur les vieux serveurs web ne reconnaissant pas cette extension, et on n'a pas toujours la main...

A mon avis, malgré le fait que seuls 50% des navigateurs ont un lecteur pdf intégré https://caniuse.com/pdf-viewer , on se rend compte que c'est google chrome pour mobile qui ne marche pas, et je me demande si un comportement ou l'iframe du pdf est affiché pour les navigateurs le supportant et sinon on met un bouton de téléchargement, ne serait pas la meilleure solution.

En tout cas YesWiki serait plus facile a maintenir et pèserait bien moins lourd.

**Comment by acheype** [comment]
Non c'était bien lié à du code js qui ne fonctionne pas sur les vieux navigateurs.
Sur le github de Pdf.js, ils spécifient qu'ils ont deux versions et la version legacy prend en compte les anciens navigateurs.
J'ai donc remplacé la version New Browser avec celle-ci : la Legacy et ai mis la toute dernière.
Voici la PR : https://github.com/YesWiki/yeswiki/pull/1211

J'ai remarqué qu'il y avait des fichiers ajoutés en plus pour yeswiki (ça me paraît pas super clean mais je les ai remis) : le .htaccess et le pdf-viewer.php. J'espère que j'en ai pas oublié d'autres.

En tout cas, ça fonctionne bien maintenant sur mon vieux firefox, mais j'ai toujours les mêmes erreurs sur mon Chromium. Mais c'est pas grave, c'est certainement une très vieille version.

Pour la solution pdf intégré au navigateur, merci d'avoir regardé. C'est sûr que c'est pas encore la panacée vu que les navigateurs sur mobile ne semblent pas encore l'intégrer. À checker et voir comment cela évolue...

**Comment by acheype** [comment]
branche mergée
