### ISSUE TITLE
L'édition de page échoue silencieusement lorsque use_hashcash est activé

### ISSUE THREAD

**Issue by Sekiltoyai** [YesWiki/yeswiki#1208]
**Description**

Lors de l'édition d'une page (e.g. ?PageMenuHaut/edit), cliquer sur "Sauver" ramène sur le formulaire d'édition, sans afficher d'erreur. En rechargeant la page, on constate que les modifications n'ont pas été prises en compte.

Le comportement est présent lorsque use_hashcash est à true dans la configuration. Lorsque use_hashcash est à false, la modification des pages est fonctionnelle.

En traçant les modifications sur la variable $_POST['submit'] au cours de l'exécution, on constate qu'elle est vidée dans tools/security/handlers/page/__edit.php:26

**Additionnal informations / Informations complémentaires**

- version 4.4.4, fraichement installée
- Authentifié en tant que user appartenant au groupe admins
- Utilisant le thème par défaut (margot)
- La page a les droits de lecture et écriture à "Tout le monde".

**Comment by mrflos** [comment]
Ca parait étrange car use hash_cash est a true par défaut sur des milliers de yeswiki en production, qui arrivent bien a sauver leur page...
Après ça se peut qu'il y ait un soucis avec hashcash et qu’après la page ne soit pas sauvée, mais en théorie il devrait y avoir une erreur.
Javascript est bien activé sur le navigateur? Ya pas d'extension qui empecherait l'execution de javascript pour les pages du wiki (genre bloqueur de pub)?
En allant en mode édition, ya bien un appel ajax de https://<mon url de yeswiki>/tools/security/wp-hashcash-getkey.php qui réussi?

edit: peut être aussi vérifier les parametres de `base_url` et  `redirect_mode` dans le fichier `wakka.config.php` (la base_url devrait avoir le ? et redirect a false par défaut)

**Comment by Sekiltoyai** [comment]
> Javascript est bien activé sur le navigateur? Ya pas d'extension qui empecherait l'execution de javascript pour les pages du wiki (genre bloqueur de pub)?

Oui, et boucliers désactivés (sur Brave). Testé aussi sur Safari.

> En allant en mode édition, ya bien un appel ajax de https:///tools/security/wp-hashcash-getkey.php qui réussi?

Alors, effectivement dans la console réseau, je vois qu'il me télécharge le code PHP au lieu de l'interpréter, donc le problème est là. Je vais corriger ça.

Il n'y a pas une configuration de référence pour nginx ?

**Comment by Sekiltoyai** [comment]
Problème corrigé après correction de la configuration nginx. Je pense qu'il serait utile d'ajouter une configuration de référence dans la documentation.
