### ISSUE TITLE
trouver des solutions techniques pour etre moins dépendant de bootstrap

### ISSUE THREAD

**Issue by mrflos** [YesWiki/yeswiki#121]

**Comment by Cyrille37** [comment]
Salut
Ce ticket est vieux et probablement obsolète. N'est-il pas à fermer ?
Cheers.

**Comment by Cyrille37** [comment]
Seuls les thèmes (éléments html et js) devraient être dépendants d'un framework de présentation. Suffit de ne plus avoir de html dans le code (coeur et plugins) de YesWiki ;-)
