### ISSUE TITLE
modifier sa fiche bazar par lien envoyé par mail

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#130]
dans le bon coin, il y a une astuce que je trouve bien vue. Pour modifier une fiche, on t'envoie un lien par mail et quand tu cliques dessus, tu peux modifier la fiche...
Aucun mot de passe nécessaire. c'est dans certains cas un bon compromis.

**Comment by mrflos** [comment]
je clos cette issue, apparemment il n'y a pas eu de gain d’intérêt de cette proposition passé 6 ans!
