### ISSUE TITLE
Decalages dans la barre de menu avec theme bootstrap par defaut

### ISSUE THREAD

**Issue by daviddelon** [YesWiki/yeswiki#131]
Par  défaut, problème de décalage dans l'affichage de la zone recherche, flux rss avec theme bootstrap.
![pb_template_yeswiki](https://cloud.githubusercontent.com/assets/592862/3230922/a647c7cc-f0a7-11e3-9076-84705216282f.jpg)

**Comment by mrflos** [comment]
on a changé la PageRapideHaut pour éviter ce décalage.
