### ISSUE TITLE
Problème affichage indicateur de sous menu

### ISSUE THREAD

**Issue by daviddelon** [YesWiki/yeswiki#134]
Avec certains thèmes, l'affichage de l'indicateur de sous menu apparaît en double.
http://site-coop.net/mbc/wakka.php?wiki=PagePrincipale .
![doubletriangle](https://cloud.githubusercontent.com/assets/592862/3370043/ea88e3de-fb89-11e3-9b61-840ef23dfad0.jpg)

**Comment by mrflos** [comment]
Ce bug n'est pas présent dans la distribution cercopitheque, il apparait quand un ancien theme est utilisé, avec à l'intérieur cette partie javascript, qui est obsolète (il suffit donc de l'enlever) :

```
// on ajoute en jquery les classes css du bootstrap
/*menuhaut.find("> div > ul").each(function() { // menu du haut
    var $this = $(this);
    $this.addClass('nav').append($('<div>').addClass('clear').html());
    $this.find('>li:has(ul)').each(function() {
        $(this).addClass('dropdown').find('a:first').addClass('dropdown-toggle').attr({'href':'#', 'data-toggle':'dropdown'}).append('<b class="caret"></b>').next('ul:first').addClass('dropdown-menu')});
}); 

menuhaut.find("ul ul li:has(ul)").each(function() { // menu du haut
    var $this = $(this);
    $this.addClass('dropdown-submenu')
    $this.find('a:first').next('ul:first').addClass('dropdown-menu');
}); */
```

**Comment by daviddelon** [comment]
Procédure à ajouter dans la documentation de migration de bachi. à cerco, donc.
