### ISSUE TITLE
Retablir la previsualisation

### ISSUE THREAD

**Issue by daviddelon** [YesWiki/yeswiki#137]
Depuis la suppression de la prévisualisation, certain Wiki très actifs voient leur bases de données gonfler exagérément, visiblement suite à de nombreuses sauvegardes d'un successives d'une même page, chose qui aurait pu être évité si la prévisualisation était présente. Cela pose beaucoup de problème pour les wiki disposant d'un faible espace de stockage pour leur base de donnée.

**Comment by Cyrille37** [comment]
:+1:   C'est une fonction de base d'un "wiki". Presque tous les outils la propose, c'est bien qu'elle est utile ;-)
Au delà de l'espace de stockage, la pré-visualisation donne du sens aux versions.

**Comment by Almaric78** [comment]
Bonjour, comment est il possible de rétablir cette fonctionnalité essentielle ? Merci

**Comment by mrflos** [comment]
Dans la version ancienne de yeswiki qui supportait la prévisualisation, il y avait un soucis d'ux, qui faisait revenir en mode affichage de la page sans indication flagrante qu'on était en mode prévisualisation, et pas mal de gens perdaient leur contribution, car ils ne réalisaient pas que c'etait pas sauvegardé.  
Ma proposition, si cette fonctionnalité vous semble essentielle, serait de plutôt faire un bouton "Prévisualisation" dans  l'éditeur qui ouvre une fenêtre modale pour voir le contenu formaté, histoire que l'on comprenne où on est.

**Comment by furax37** [comment]
Excellente proposition => Ma proposition, serait de plutôt faire un bouton "Prévisualisation" dans l'éditeur qui ouvre une fenêtre modale pour voir le contenu formaté, histoire que l'on comprenne où on est.

**Comment by J9rem** [comment]
Résolution  avec ce commit https://github.com/YesWiki/yeswiki/commit/2260a9d9f65c0e83894cf9d5ca81bdd7943d1053 merci @seballot 

Par contre, l'option doit être activée à la main dans `wakka.config.php`.

Je clos cette issue, mais je serais pour ajouter le paramètre `preview_before_save` dans la page de gestion des config. => issue https://github.com/YesWiki/yeswiki/issues/1052
