### ISSUE TITLE
Migrer un Wiki Bachibouzouk vers Cercopitheque : pb avec les thèmes

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#141]
Mettre à jour un wiki vers Cercopithèque nécessite une modification du thème pour que le wiki soit toujours utilisable. Est il possible de conserver une compatibilité avec les thèmes déjà existant ?

**Comment by mrflos** [comment]
hello, ce n'est pas le cas normalement, les themes n'ont pas changés, le seul bug connu est la présence d'un deuxieme triangle pour les menus déroulants du haut. pourrais tu préciser où tu as rencontré le problème?

**Comment by mrflos** [comment]
un petit "up" avant fermeture!

**Comment by fbredow** [comment]
Ayant migré tout mes thèmes depuis je n'ai malheureusement plus d'exemple. J'avais notamment ce bug du triangle (non solutionné d'ailleurs). Des problème d'images débordant des zones et aussi eu des soucis avec l'encodage (peut être lié au fait que bazar était désactivé) si ma mémoire est bonne mais ça remonte loin.

**Comment by mrflos** [comment]
ok j'ai clos, mais l'issue documenter la migration reste ouverte!
