### ISSUE TITLE
pb accents dans action facette

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#145]
http://site-coop.net/accueilpedacivam/wakka.php?wiki=CherCherunoutilFacette

comme son nom l'indique

**Comment by mrflos** [comment]
@furax37 apparemment c'est corrigé sur le site, cela est réparé avec la dernière version?

**Comment by mrflos** [comment]
apparement n'est plus d'actualité

**Comment by daviddelon** [comment]
C'est réglé dans cercopitheque
