### ISSUE TITLE
Certain caractères utf8 ne sont pas pris en cpmpte.

### ISSUE THREAD

**Issue by daviddelon** [YesWiki/yeswiki#157]
Certains caractères utf8 ne sont pas sauvegardé correctement par yeswiki, par exemple č est remplacé par un ? .

**Comment by mrflos** [comment]
ca ne va pas être possible de gérer cela sans toucher à l'encodage des données par défaut de yeswiki dans MySQL (qui est en ISO-8859-1).
A moins de changer une liste de caractères non ISO-8859-1 en entités html avant de les sauvegarder dans la base de données?
