### ISSUE TITLE
categorienature ne fonctionne plus

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#162]
dans wikimesclat, tentative d'utilisation de categorienature... toutes les fiches sont affichées sans dicernement, pas de message d'erreur

**Comment by mrflos** [comment]
je pense qu'on va documenter pour proposer de passer au parametre id="12,2,3" a valeurs séparées par des virgules, ce qui offre les memes fonctionnalités mais plus de souplesse.

**Comment by mrflos** [comment]
Du coup, c'est documenté ?

**Comment by gatienbataille** [comment]
je vais regarder. 
Cela dit si cette fonction est non utilisée, ne pourrait-on pas la "cacher" dans la partie création de formulaire ? elle soulève souvent des questions avec pour seule réponse : "ce n'est plus utilisé".

**Comment by mrflos** [comment]
oui, je vais virer ce champ et virer aussi celui des classes css, less is more

**Comment by gatienbataille** [comment]
j'ai fait un ajout dans la doc https://yeswiki.net/?FormulaireSoimeme

**Comment by gatienbataille** [comment]
et dans la même idée (car c'est une remarque qui revient tout le temps) les boutons bleus dans le /revisions qui permettaient de comparer deux versions de pages yeswiki. ça perturbe bcq les users ces boutons... alors qu'ils ne servent plus...

**Comment by mrflos** [comment]
normalement ils servent a choisir les 2 versions et afficher les differences entre les 2

**Comment by mrflos** [comment]
le champs est supprimé
