### ISSUE TITLE
Icones blancs

### ISSUE THREAD

**Issue by MichelCauzid** [YesWiki/yeswiki#164]
Dans la version Cerco du 16 janvier 15 les icones en blanc n'apparaissent plus, ils apparaissaient normalement dans la version du 22 octobre 14 par exemple 
- {{button link="PageOutils" class="pull-right btn-small" icon="wrench icon-white" title="Pourquoi cette page"  nobtn="1" }}

**Comment by mrflos** [comment]
corrige par le passage a bootstrap 3, aujourd'hui, a tester!
