### ISSUE TITLE
L'activation de bazar fait perdre la compatibilité W3C

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#168]
Line 77, Column 76: Element link is missing required attribute property.
<link rel="stylesheet" href="tools/bazar/libs/vendor/leaflet/leaflet.css" />

 Line 81, Column 92: Element link is missing required attribute property.
…="stylesheet" href="tools/bazar/libs/vendor/leaflet/label/leaflet.label.css" />

Avec en commentaire : Encore un css/js de plus ?????

**Comment by mrflos** [comment]
c'est ici : https://github.com/mrflos/yeswiki/blob/cercopitheque/tools/bazar/actions/bazarcarto.php#L482
Que faut il pour le rendre valide?

Pour l'abondance de js/css, je suis d'accord que cela vaudrait le cout de tout concatener et minimiser en un fichier css et un js pour de meilleures performances.

A meme en feature pour une version prochaine?

**Comment by fbredow** [comment]
Concaténer les js et les css n'est qu'une réponse partielle au problème. A mon sens, l'utilisation de css/js devrait dépendre du thème utilisé et non de l'utilisation d'un plugin.

Exemple : l'utilisation obligatoire de bootstrap avec bazar. Comment allons nous faire lorsqu'un nouveau framework CSS apparaîtra ? nous l’empilerons par dessus l'existant pour pouvoir l'utiliser ? 

Si je prend la page d’accueil de yeswiki.net : 
- 10 css pour 214,49ko
- 7 js pour 174,94ko  Donc un qui vient de chez google (merci pour la vie privée au passage... il devrait être possible de choisir d'utiliser ou pas un CDN) 

Cela donne 17 connexions et 400ko pour la mise en forme uniquement... C'est plus lourd que les données (images+html : 200,45ko et 5 connexions). 

Effectivement ils ne sont chargé qu'a la première page, mais sur une connexion 2g ou 3g ça prend du temps sans parler des connexions que nous avons à la campagne.

Pour finir il me semble indispensable de séparer contenu et mise en forme et là tout est mélangé. (bazar qui fait de la mise en forme, usage de bootstrap qui vient modifier le contenu en ajoutant des classes/balises spécifiques pour la mise en forme, javascript changeant la mise en forme qu'il faut outrepasser à grand renfort de !important dans le CSS...) On en arrive a devoir faire des choses complexes et sales pour réaliser des choses normalement simples.

**Comment by mrflos** [comment]
Ca fait beaucoup de points à discuter, surtout qu'ils ne sont pas en lien avec le sujet "L'activation de bazar fait perdre la compatibilité W3C"..

Je veux bien qu'on discute des choix techniques, mais pour les versions futures, il serait bien de sortir la version cercopitheque avec ses qualités (compabilité nouvelles versions de php, internationalisation) et défauts (dépendance à bootstrap, ..)

A l'origine, j'ai fait le choix (et trop individuellement) de mettre le framework bootstrap, pour ne pas avoir a écrire des themes trop compliqués, permettre aux utilisateurs d'avoir des composants comme les boutons, les colonne, les carousels, le mobile first).. et de disposer des nombreux themes et plugins disponibles (en particulier, pour les tags et le datepicker)

Je pense qu'au vue du nombre de développeurs du projets et du temps que cela nécessiterai de rendre yeswiki "framework agnostique", c'est pas possible de le faire maintenant. Par contre dans l'idéal, je suis d'accord pour séparer le contenu et la mise en forme, mais pour une prochaine version, en gros chantier (et à plusieurs), après avoir corrigé la liste des bugs actuelle.

Pour le cdn de google, ok pour avoir cette fonctionnalité, si tu peux ouvrir un ticket spécifique, je pense que ce sera vite réglé (un parametre supplémentaire pour le fichier de conf.)

**Comment by mrflos** [comment]
Une méthode permet de charger le js et css a la demande, et les labels en question ne sont plus chargés. Je propose qu'on finisse de corriger les autres bugs et d'avoir une version cerco en RC pour valider le html de tout yeswiki à ce moment là
