### ISSUE TITLE
Modernizr encore necessaire ?

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#169]
Dans mon dernier thème en html5, je n'ai pas mis les balises head comme recommandé par google. (cela reste valide W3C et ça allège le code). Modernizr est perdu et met le bazar dans les javascripts qui suivent.

Est il possible de s'en passer ? sur le site les dernières news datent d'il y a deux ans et parlent de la V3 en test, j'imagine que la bibliotheque est abandonnée.

Un javascript de moins c'est toujours ça de pris.

**Comment by mrflos** [comment]
Hello, je pense que c'est nécessaire à la compatibilité avec les vieilles versions d'Internet explorer, c'est utilisé par exemple ici https://github.com/mrflos/yeswiki/blob/cercopitheque/tools/templates/libs/yeswiki-base.js#L15 pour avoir le responsive pour IE, et gérer les placeholder.

De plus, même si le site n'est pas à jour, le projet est très supporté : https://github.com/Modernizr/Modernizr , il s'agit par ailleurs de la 2ieme bibliothèque js la plus utilisée sur internet selon http://w3techs.com/technologies/overview/javascript_library/all !!

Pour info, tout ceci a été organisé de cette manière pour les templates par rapport au modèle de https://html5boilerplate.com/ utilisé pour les templates yeswiki.

**Comment by fbredow** [comment]
Pour quelles versions d'IE ? Est il encore pertinent de prendre en charge des versions antérieurs à Explorer 8 ? (Que MS lui meme ne supporte plus)
Pour les placeholder, est ce vraiment une fonctionnalité indispensable qui justifie l'ajout d'une biliothèque ? personnellement j'en doute.

A mon sens l'argument "c'est la deuxième plus utilisée" n'est pas recevable. En effet il suffit de regarder dans les journaux pour comprendre que le choix de la majorité n'est pas forcement representatif de la qualité de ce choix, surtout quand nous parlons de choix technique.

Qui a pris la décision d'utiliser html5boilerplate pour tous les templates YesWiki ? Ou est ce documenté ? Pour ma part je pars d'une feuille blanche ou d'un theme pré-existant en fonction des besoins.

**Comment by mrflos** [comment]
Pour l'instant, yeswiki supporte tous les navigateur à partir de ie6. Cela partait du constat que dans certaines institutions, et en afrique, il y avait encore des vieux pc qui utilisaient yeswiki.

Le choix technique d'utiliser modernizr c'est justement de disposer de classes css, et de fonctions javascript qui permettent de garder un maximum de compatibilité avec les anciens navigateurs, ou d'avoir la possibilité d'afficher des messages sur le support ou non d'une fonction.

Par contre ce n'est pas un choix bloquant pour la création des thèmes, si tu ne veux pas l'utiliser, c'est possible de faire sans. Pour le choix d'utiliser les conventions de html5boilerplate, c'est une décision prise pour les templates que j'ai fait moi, mais ce n'est pas une obligation de faire comme ca, et ce n'est pas documenté, j'ai en stock des bouts de docs pour tout cela, je compte bien les diffuser dans la doc.
