### ISSUE TITLE
Nombreux warnings et notice si le tools template est désactivé.

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#170]
Si le tools template est désactivé il n'y a plus de définition de "TEMPLATES_DEFAULT_CHARSET" ce qui provoque de nombreux warning et notice.

> Notice: Use of undefined constant TEMPLATES_DEFAULT_CHARSET - assumed >'TEMPLATES_DEFAULT_CHARSET' in /var/www/yeswiki/includes/i18n.inc.php on line 121
> Notice: Use of undefined constant TEMPLATES_DEFAULT_CHARSET - assumed >'TEMPLATES_DEFAULT_CHARSET' in /var/www/yeswiki/includes/i18n.inc.php on line 125
> Notice: Use of undefined constant TEMPLATES_DEFAULT_CHARSET - assumed 'TEMPLATES_DEFAULT_CHARSET' in /var/www/yeswiki/handlers/page/edit.php on line 154
> Warning: htmlspecialchars(): charset `TEMPLATES_DEFAULT_CHARSET' not supported, assuming utf-8 in /var/www/yeswiki/handlers/page/edit.php on line 154
> Notice: Use of undefined constant TEMPLATES_DEFAULT_CHARSET - assumed 'TEMPLATES_DEFAULT_CHARSET' in /var/www/yeswiki/wakka.php on line 785
> Warning: htmlspecialchars(): charset`TEMPLATES_DEFAULT_CHARSET' not supported, assuming utf-8 in /var/www/yeswiki/wakka.php on line 785

Considérons nous que le tool template ne doit plus être désactivé ? Sinon une simple définition par défaut de TEMPLATES_DEFAULT_CHARSET devrait résoudre le problème.

**Comment by mrflos** [comment]
Peut être on pourrait le définir en dehors de templates, par exemple dans les fonctions qui gèrent le multilinguisme et l'encodage (libs/i18n.inc.php)
