### ISSUE TITLE
[bazar] Problème lorsque l'on clique dans un bazarcarto

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#172]
Lorsque je clique sur un point dans une carto cela ouvre une bulle d'info dans la frame de la carte. Cette bulle remplie pratiquement toujours la frame de la carte. Cela perturbe pas mal les utilisateurs qui ne comprennent pas comment revenir en arrière. De plus les informations sont souvent tronquée et peu lisible (fonction de la taille de la carte).

Il me semble que c'est une regression par rapport au fonctionnement précedent.

Solution possible : Ouvrir une nouvelle fenêtre/onglet/popup avec la fiche.

Exemples de pages : 
- http://reseau-eau.educagri.fr/wakka.php?wiki=InitiativesLocales
- http://portailcoop.educagri.fr/wakka.php?wiki=PagePrincipale

**Comment by mrflos** [comment]
il y a maintenant une hauteur limite avec un ascenseur
