### ISSUE TITLE
[Bazar] Carto si deux point sont au meme endroits un seul apparait.

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#174]
Si l'on saisie la même adresse pour plusieurs fiches dans un formulaire, seul le dernier point apparaît les autres sont "cachés" dessous.

**Comment by furax37** [comment]
il suffit d'ajouter spider="true" ou cluster="true" et...

Le 22 avril 2015 15:47, Florestan Bredow notifications@github.com a écrit
:

> Si l'on saisie la même adresse pour plusieurs fiches dans un formulaire,
> seul le dernier point apparaît les autres sont "cachés" dessous.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/YesWiki/yeswiki/issues/174.

## 

Laurent MARSEAULT

http://www.outils-reseaux.org
http://www.euziere.org

**Comment by fbredow** [comment]
En fait c’était pas un bug mais une feature :) Le comportement par défaut est peut être a redéfinir, qu'en pensez vous ?
