### ISSUE TITLE
question mise à jour

### ISSUE THREAD

**Issue by gekette** [YesWiki/yeswiki#177]
Hello,
existe-t-il une mise à jour de cercopithèque ?
désolée de poster un message ici mais je venias juste télécharger une éventuelle dernière version et je ne suis pas sûre de savoir si la version proposé est plus récente que celles que j'ai instalées

Lila

**Comment by fbredow** [comment]
Bonjour, pour l'instant la version 'Cercopithèque' de YesWiki est la version en cours de développement elle n'est pas figé. Comparez la date du dernier commit (https://github.com/YesWiki/yeswiki/commits/cercopitheque)  avec la date à laquelle vous l'avez téléchargé pour savoir si des choses ont changé.
