### ISSUE TITLE
[Bazar] L'insertion de javascript dans un champs provoque des bugs d'affichage

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#179]
La balise de fermeture du javascript (`</javascript>`) ferme trop tôt le script inséré en bas de page contenant les fiches au format json.

Résultat : Toutes les données json qui suivent sont visible après le pied de page.

Le code qui était inséré : `<script>(function(d, s, id) {  var js, fjs = d.getElementsByTagName(s)[0];  if (d.getElementById(id)) return;  js = d.createElement(s); js.id = id;  js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.3";  fjs.parentNode.insertBefore(js, fjs);}(document, 'script', 'facebook-jssdk'));</script>`

Il fait parti du code fourni pour afficher une vidéo issue de facebook.

**Comment by mrflos** [comment]
Je n'ai pas réussi a reproduire le bug cf. https://yeswiki.net/?TestBugJavascript (aller en mode édition pour voir le js inséré).
Est ce corrigé entre temps?

**Comment by mrflos** [comment]
fermé car sans doute plus d'actualité
