### ISSUE TITLE
slider wikifié cause des erreurs dans bazar ???

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#182]
Je crois qu'il doit y avoir un bug dans le slider wikifié de la page header
sur les wikis où il est présent, j'ai à chaque fois un bug avec bazar... 
une des fiches bazar (peu importe le id) ne se comporte pas normalement
à savoir, pas moyen de voir la page, ni de la modifier, ni de la deleter car elle montre, ouvre ou delete la page bazar qui contient la fiche
voir par ex : 1er image du slider de novatrices http://coop-site.net/novatrices
http://coop-site.net/novatrices/wakka.php?wiki=BazaR&vue=consulter&action=recherche (tu choisis slider) et la dernière fiche est problématique... 

j'ai le même sur http://coop-site.net/rochefort/wakka.php?wiki=BazaR
chercher les fiches slider et voir la dernière nommée 0 / si tu essaies de l'éditer tu verras ce qui se passe

**Comment by gatienbataille** [comment]
En fait c'est pas sur car j'ai pas eu sur un autre wiki avec slider... mais par contre je ne sais pas du tout comment virer la fiche qui pose problème...

**Comment by mrflos** [comment]
on a mis a jour wiki et effacé les pages qui posaient probleme directement par la base de données
