### ISSUE TITLE
problèmes avec Gererdroits

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#183]
Quand on appelle l'action {{gererdroits}}
en haut de l'action apparaît :  
Une liste déroulante présentant les thèmes du wiki et un bouton indiquant = "Sélection du thème"
A mon avis c'est un reliquat du GererThemes lors de sa transformation en gererdroits

Voir sur cette page : http://coop-site.net/rochefort/wakka.php?wiki=GererDroits
![capture d ecran 2015-12-16 a 21 20 35](https://cloud.githubusercontent.com/assets/7147716/11852894/e8875b46-a43a-11e5-8de8-614f2f88e399.png)

**Comment by mrflos** [comment]
ok, en fait c'est le fonctionnement "normal", ca permet d'editer les droits par themes, mais c'est pas trop logique, je vais me tenter de faire le ménage.

**Comment by Cyrille37** [comment]
Sans rapport avec la question, mais j'ai débugué un peu ces 2 pages: #197 sur le commit 5ed461a
Il y avait un conflit à cause des 2 formulaires et des valeurs identiques dans $_POST

**Comment by Cyrille37** [comment]
Je ne trouve pas le problème.
Il est certainement corrigé.

**Comment by mrflos** [comment]
Moi j’ai un soucis, repéré par @gatienbataille aussi : on ne peut pas changer les droits des pages de l’installation, j’ai pas fouillé plus...

**Comment by Cyrille37** [comment]
Faut créer une issue pour s'en souvenir, dans la version cercopithèque.
Je pourrai y jeter un oeil (aïe).

**Comment by gatienbataille** [comment]
Hello
je viens de re tester avec la version cerco-dev et je peux modifier ou ajouter des droits mais uniquement sur les pages créés après l'installation. Les pages installées par défaut semblent ne pas "réagir" aux commandes passées via gérerdroits
je peux par contre leur attribuer des droits de manière classique (page par page)

**Comment by Cyrille37** [comment]
je re-ouvre le bug et vais changer son intitulé

**Comment by Cyrille37** [comment]
J'ai trouvé la raison. Dans _gererdroits.php_ la mise à jour de la BdD est faite avec un UPDATE, du coup s'il n'y a pas de ligne correspondante à mettre à jour dans le BdD, alors rien ne change.

Je vois comment corriger ça...

**Comment by Cyrille37** [comment]
Voilà, c'est corrigé (à tester dans tous les sens bien sûr).
Ça sera dispo sur **cercopithèque_dev** après le merge de #213
