### ISSUE TITLE
proposer un lien vers un doc web sans créer google doc dans extension google drive

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#184]
J'utilise l'extension google drive pour gérer des documents au sein d'une structure (colibris), je souhaiterai pouvoir faire des liens vers des docs déjà existant sans pour autant créer un google doc. Pour celaje souhaiterai que cette extension permette de choisir entre : créer un google doc, un google sheet, etherpad ou rien.

**Comment by mrflos** [comment]
bonjour cher monsieur, vous vous êtes trompé de dépôt, l'extension googledrive étant présente dans le dépôt yeswiki-external-extension ...
Comme il n'y avait pas d'url dans votre remontée de bug, je n'ai pas pu vérifier si mon correctif fonctionnait.
Si vous pouviez aller chercher sur le bon dépôt la version mise a jour et tester, je vous en serai extrêmement reconnaissant.

Amicalement
