### ISSUE TITLE
Garder le squelette (avec les pages spéciales associées) lors de la création d'une page

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#185]
Lorsqu'on crée une page, il serait sympa que la nouvelle page créé hérite du squelette "complet" de la page d'où elle a été créée.

sous entendu toutes les pages spéciales que l'on a indiqué dans les paramètres avancés du thème (pagemenuspeciale, pageheaderspeciale...)

**Comment by J9rem** [comment]
Salut @gatienbataille ,

je crois que c'est maintenant implanté dans Doryphore.
pourrais-tu le vérifier et fermer l'issue si OK toi.
Merci

**Comment by gatienbataille** [comment]
salut, 
selon un petit test rapide avec version doryphore 2021-01-27-4
la création d'une page sur une page avec des "pages spéciales associées" (putain ça devient complexe ce truc ;-)
ça fonctionne "à moitié"
il garde bien le squelette (si deux col, il garde bien les deux col) MAIS
si sur la page de départ (où on a créé la nouvelle page) il y avait un pageheaderSpecial ou pageFooterSpeial
ça fonctionne pas trop, il reprend le squelette "classique" avec le pageheader et footer "de base"

c'est pas très grave... mais c'est vrai que quand tu as associé à ton wiki, un "intranet" avec un autre menuhaut par ex, ben à chaque ajout dans cette partie intranet, tu dois lui dire que le menuhaut c'est ça plutot que le "de base"

mais encore une fois, c'est pas si grave

merci !

**Comment by J9rem** [comment]
OK merci pour la clarification.

Commentaire pour le dev qui s'en chargera : ajouter les metadatas des pages spéciales dans les données GET ou POST qui sont transmises aux handlers /edit et mettre à jour ce handler pour pouvoir les utiliser

**Comment by J9rem** [comment]
Tu vas être content @gatienbataille , il va maintenant être possible d'importer les pages spéciales lors de la création d'un page.
