### ISSUE TITLE
bazarliste facette donne des mauvais résultats avec des id numériques

### ISSUE THREAD

**Issue by mrflos** [YesWiki/yeswiki#186]
- Filtres : les identifiants numériques proches, comme 1, 10, 11, 12 sont comptabilisés quand on filtre sur l'id 1
- Avec le thème par défaut, les accordéons ne sont pas stylés : CORRIGE

**Comment by Cyrille37** [comment]
Si toujours d'actualité, peux-tu créer 1 issue pour pb style accordéons et modifier titre et comment de celle-ci ?? Merci ;-)
