### ISSUE TITLE
Erreur 324 "net err_empty_response"

### ISSUE THREAD

**Issue by fodevaux** [YesWiki/yeswiki#187]
Sur notre serveur domainepublic.net, nous recevons régulièrement des erreurs 324 "net err_empty_response" lorsque nous nous connectons à nos wiki. Cette erreur apparait généralement après avoir navigué ou édité le wiki pendant 3-4 minutes.

Ce n'est qu'après 2-3 minutes que l'on peut consulter à nouveau le wiki.

![gjfhhidd](https://cloud.githubusercontent.com/assets/10889235/12971876/27b287b4-d0a0-11e5-89ae-9c09a6cabb8c.png)

Avez-vous une idée d'un problème de config qui pourrait entraîner cela ?

Vous pouvez tester le problème ici: http://wikivdt.reseautransition.be/wakka.php?wiki=PageTest 
Pour reproduire rapidement le problème, vous pouvez ouvrir plusieurs onglets et naviguer sur différentes pages de ce wiki.

**Comment by mrflos** [comment]
Bonjour,

Je n'ai pas réussi a reproduire le problème en allant sur http://wikivdt.reseautransition.be/wakka.php?wiki=PageTest avec le navigateur chrome version 48.

L'autre site ne semble plus exister, y a t'il un moyen de reproduire le bug de façon systématique?

**Comment by fodevaux** [comment]
Bonjour,

Merci pour ce suivi.

L'erreur n'est pas facile à reproduire, mais j'y suis arrivé ce matin en 2 minutes.
A tester sur ce site: http://wikiformation.reseautransition.be/wakka.php?wiki=PagePrincipale (merci de ne pas modifier le contenu)
Ouvrir plusieurs pages de ce site et les éditer (5 onglets ouverts dans un browser et 5 onglet dans un browser "navigation privée"). Rafraichier ou naviguer sur le site pendant à partir des 10 onglets. L'erreur 324 devrait se produire au bout de 2-3 minutes.

**Comment by ddeenniiss** [comment]
Bonjour,

J'essaie de débugger ce problème, la seule chose que je vois est une segmentation fault dans les logs d'apache. Est-ce qu'il y aurait un mode débug qui permettrait de logger les erreurs ? 

Merci
Denis

**Comment by mrflos** [comment]
Bonjour,

On peut changer le fichier de configuration pour mettre debug_mode a "on" plutôt que off, mais cela indique plutôt les temps de chargements et les requetes SQL. 

Peut être mettre un error_reporting(E_ALL); au debut de wakka.php?

Désolé je n’ai pas de piste pour ce problème..

**Comment by mrflos** [comment]
Vous avez réussi a trouver quelque chose?
