### ISSUE TITLE
Problèmes pour accéder à certains boutons de l'éditeur 

### ISSUE THREAD

**Issue by fodevaux** [YesWiki/yeswiki#188]
Sur ce wiki http://goo.gl/OWbdWF avec le thème bootstrap, 1col, amelia, 
les boutons d'édition du texte situés sur la moitié droite de l'écran (lien, joindre un fichier) ne sont pas cliquables.

Il semble que l'élément "uploadModal" se retrouve devant ces boutons.

Comment corriger ce problème ?

Merci d'avance,

François

**Comment by mrflos** [comment]
bonjour,

J'ai rajouté un style css pour accèder aux boutons: la fenêtre modale des options de l'upload restait bizarrement  par dessus avec ce css.

Les changements sont ici http://www.etterbeekentransition.be/bacapousses/wakka.php?wiki=PageFooter/edit

Je vais mettre a jour le theme bootstrap vers la version 3, il semblerait que cela corrige le probleme.

**Comment by fodevaux** [comment]
Parfait,ça a bien résolu le problème, merci beaucoup Florian !
