### ISSUE TITLE
[bazar] Paramètre pagination de bazarliste

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#189]
Le paramètre "pagination" fait doublon avec le paramètre "nb" mais n'est pas documenté. 
- A supprimer ? 
- Conservé pour la compatibilité ? (dans ce cas documenter avec la mention déprécié peut être)

**Comment by mrflos** [comment]
normalement ils ne sont pas pareils :

nb = nombre de resultats a afficher
pagination = ajoute une pagination après x résultats

{{bazarliste nb="25" pagination="10"}} devrait afficher 2 pages de 10 résultats et une page avec 5 résultats

Ce serait donc plus a documenter qu'a supprimer.

**Comment by mrflos** [comment]
complété ici : http://yeswiki.net/cercopitheque/wakka.php?wiki=ActionBazarliste
