### ISSUE TITLE
[bazar] bazarliste paramètre "pagination" : passer en javascript pour rester compatible avec les facettes

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#190]
Si le paramètre nb est spécifié, les filtres ne mettent pas a jour le nombre de page. Si à l'origine il y a 20 éléments sur deux pages et qu'après filtrage il n'en reste que 5, ils sont toujours répartis sur deux pages. Si ils étaient tous sur la même page, une page vide reste.

**Comment by mrflos** [comment]
je pense que tu voulais dire paramètre pagination, mais en effet, avec la pagination, il ne filtre que les résultats visibles a l'écran, il faudrait que la pagination soit faite en javascript plutot qu'avec la bibliothèque PEAR, a réfléchir

**Comment by Cyrille37** [comment]
Salut,
Comment puis-je reproduire le cas ? (_pour debugger_)

**Comment by mrflos** [comment]
Il suffit d’utiliser le paramètre des facettes et et le paramètres nb sur un grand nombre de données, la pagination ne doit plus être faite par php, mais par javascript, pour que toutes les données soient bien présentes dans la page chargée.
Ca risque d’être dur a debugguer, mais a voir!

**Comment by GDoukhan** [comment]
Hello vraiment gênant comme petit bug pour faire un affichage un peu propre quand on veut utiliser des facettes. 
Car personnellement en corollaire, j'ai eu le problème que si je ne mettais pas de pagination la page ne se chargeait pas (page blanche) avec 25 fiches environ et 4 facettes.

**Comment by J9rem** [comment]
Je propose de clore cette issue car les soucis évoqués sont maintenant réparés avec les templates bazar dynamic (doryphore 4.1.5 et après)

**Comment by J9rem** [comment]
fixed by:
 - https://github.com/YesWiki/yeswiki/commit/d6d8908e18a682ff1dc4af824d2ad60d6f8aad09 (card dynamic)
 - #805 
 - #918
