### ISSUE TITLE
[bazar] bazarcarto : id est un paramètre obligatore

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#191]
Son absence ne provoque aucun message d'erreur et la carte ne s'affiche pas.
Il devrait y avoir un message d'erreur.

**Comment by Cyrille37** [comment]
Salut
Dans la doc il est question du paramètre "_id_" mais dans le [code](https://github.com/YesWiki/yeswiki/blob/cercopitheque/tools/bazar/actions/bazarcarto.php)  je ne vois que "_idtypeannonce_".
Est-ce le même (automatiquement renommé ailleurs?) ?

**Comment by mrflos** [comment]
Alors pareil c’est pour la retrocompatibilité

le parametre s’appelle encore « idtypeannonce », mais il est plutôt initialisé par id, mais si pas de id alors idtypeannonce, cf.
https://github.com/YesWiki/yeswiki/blob/cercopitheque/tools/bazar/libs/bazar.fonct.php#L4173 https://github.com/YesWiki/yeswiki/blob/cercopitheque/tools/bazar/libs/bazar.fonct.php#L4173

**Comment by Cyrille37** [comment]
@daiko Le paramètre "id" n'est pas obligatoire. Soit on indique des identifiants de fomulaires pour sélectionner des données à afficher, soit en l'absence de "id" toutes les données sont récupérées.

http://yeswiki.net/wakka.php?wiki=ActionBazarcarto
