### ISSUE TITLE
backgroundimage et footer (theme yeswiki grey)

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#192]
![bug_backgroundimage_footer](https://cloud.githubusercontent.com/assets/1093091/13923217/f8052bc6-ef7f-11e5-9e2e-c36889974bf6.png)

background image ne fonctionne pas dans le footer. (avec le parametre bgcolor)
Même problème dans la page principale.

**Comment by mrflos** [comment]
ce bug ne sera pas corrigé, les nouveaux themes sont plus souples sur la configuration du fond de page, et avec du css, on peut se faire son adaptation si nécessaire
