### ISSUE TITLE
information état connexion (authentification)

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#193]
YesYes,

Quand on est connecté sur YesWiki (cercopitheque), on ne le sait pas : 
- dans le menu bouton "petite roue" il n'y a pas le nom ou autre information
- il est écrit "Se Connecter" au lieu de "Se Déconnecter"

**Comment by Cyrille37** [comment]
Ok, le contenu de ce menu est la page wiki "PageRapideHaut" qui est générée à l'installation avec du contenu en dur.

**Comment by mrflos** [comment]
Ya des possibilités d'affichage avec l'action login, on va revoir ce menu pour qu'il soit moins en dur (pas d'html, login avec état de connexion) je vais faire une proposition

**Comment by Cyrille37** [comment]
Chouette !
Où fait-on les propositions ? Ici ?

**Comment by mrflos** [comment]
J'ai fait une proposition ici https://github.com/YesWiki/yeswiki/blob/cercopitheque_dev/setup/doc/PageRapideHaut.txt pour utiliser {{login}}, si tu peux tester @Cyrille37 apres un git pull, ce serait formidable!
