### ISSUE TITLE
template par défaut pour fiche formulaire [bazar]

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#199]
Salut,
Pour permettre d'afficher une _fiche_ selon un _template_ sans avoir pour chaque _fiche_ à sélectionner le _template_, on pourrait ajouter au _formulaire_ un champs _template_. Ce _template_ serait utilisé par défaut pour l'affichage des _fiches_.
L'utilisateur pourrait toujours changer le _template_ pour une _fiche_ via l'outil "gestion du site".

**Comment by mrflos** [comment]
Si un "template" c'est un thème graphique associé avec squelette et style css c'est possible en ajoutant une ligne metadatas au formulaire:  
`metadatas***colibris***1col.tpl.html***colibris.bootstrap.min.css***`

**Comment by mrflos** [comment]
il est aussi possible de faire un template fiche sur mesure avec fiche-<id>.tpl.html
