### ISSUE TITLE
bazar/actions bazarcarto.php et map.php sont identiques

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#200]
Salut,
Dans bazar/actions _bazarcarto.php_ et _map.php_ sont identiques. Peut-on supprimer _map.php_ ou bien est-ce par soucis de compatibilité qu'il est présent ?
Auquel cas ce le contenu de _map.php_ pourrait être un simple include de bazarcarto.php ?

**Comment by mrflos** [comment]
C’est par soucis de retro-compatibilité mais si l’include marche, ca serait mieux!

**Comment by Cyrille37** [comment]
En fait BazarCarto est un raccourci de BazarListe + template="map.tpl.html"
