### ISSUE TITLE
Permettre les retours de lignes dans le tag action [cercopitheque][amélioration]

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#201]
Salut
Quand il y a beaucoup de paramètres (attributs) dans un tag _action_ ça serait bien de pouvoir mettre des retours à la ligne (\n) entre les attributs.

**Comment by Cyrille37** [comment]
Ça fonctionne ...
SAUF quand il y a un espace juste après un saut de ligne ... Impossible de trouver la solution.

Exemple qui fonctionne:
`{{bazarcarto categorienature="" id="" lat="" lon=""
zoom="" typecarto="" width="" height="" query="" choixcarte="true" }}`

Exemple qui ne fonctionne pas (un espace avant _zoom_):
`{{bazarcarto categorienature="" id="" lat="" lon=""
 zoom="" typecarto="" width="" height="" query="" choixcarte="true" }}`

**Comment by mrflos** [comment]
Dommage, c’était une bonne idée.. 

Je pense de le formatter wakka.php traque les lignes qui commence par un espace (qui sont ensuite changées soit en listes soit en paragraphe décalé)

Pas d’idée présentement, a part peut être revoir l’expression régulière qui capte les actions pour la rendre multiligne?

**Comment by mrflos** [comment]
voir https://github.com/YesWiki/yeswiki/blob/cercopitheque/formatters/action.php#L40 https://github.com/YesWiki/yeswiki/blob/cercopitheque/formatters/action.php#L40
et https://github.com/YesWiki/yeswiki/blob/cercopitheque/formatters/wakka.php#L389 https://github.com/YesWiki/yeswiki/blob/cercopitheque/formatters/wakka.php#L389
et rajouter /m pour multi-lignes?

**Comment by Cyrille37** [comment]
Effectivement, dans formatters/waka c'est la regex "**indented text**" qui match ...

**Comment by Cyrille37** [comment]
Ça fonctionne bien avec les tags **action** mais je **n'ai pas** testé les autres traitements du **formatter** ... Logiquement ça ne devrait pas avoir d'incidence sur les autres éléments de syntaxe...

**Comment by mrflos** [comment]
merged!! Merci @Cyrille37 !!
