### ISSUE TITLE
version Php pour cercopithèque ?

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#205]
Salut
Quelle est la **version minimale de Php** pour la version **cercopithèque** ?
Le README dit Php > 5.0.

**Comment by mrflos** [comment]
Si l'on considère l'ajout prochain de https://github.com/YesWiki/yeswiki-extension-autoupdate qui a des namespace et autoload, la version minimale serait 5.3, et peut etre plus, ce serait a tester.

Mon avis sur le sujet, serait d'essayer de garder a minimum la compatibilité avec les version minimales supportées, cf. http://php.net/supported-versions.php et si possible, si ce n'est pas trop compliqué le plus bas possible. Php > 5.3 me parrait bien comme entrée en matiere. et recommander > 5.6 ou 7.

**Comment by Cyrille37** [comment]
Php 5.3 apporte de bonnes choses pour les dévs, ça me va ;-)
Faut-il mettre à jour le README.md ?

**Comment by mrflos** [comment]
+1 pour le README

**Comment by Cyrille37** [comment]
see #209

**Comment by mrflos** [comment]
merged.
