### ISSUE TITLE
[cercopithèque][perf] tout passer en UTF-8

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#207]
Salut,
J'ai regardé l'affichage de la page d'accueil par défaut avec un profiler et 8% du temps (451 calls) est passé à la conversion de iso-8859 vers utf-8.
Ça ne me semble pas beaucoup de boulot de passer cercopithèque en utf-8 et supprimer ces conversions. Je peux m'y coller ?

**Comment by mrflos** [comment]
Ah! J'aimerais bien a l'occasion que tu me montres comment tu fais du profiling, je serais curieux de savoir les performances de bazarliste et les conversions iso vers utf8 puis json.

Je pense qu'il faudrait le faire, mais cela me parait assez gros comme chantier, car il faudrait passer toutes les tables mysql aussi en utf8...

Lors du passage en multilingue, j'ai passé le gestion de l'affichage par défaut en utf8 tout en gardant la base de données en latin1, d'ou les conversions.

C'est une prochaine étape nécessaire de passer a full UTF-8 mais il faudrait qu'on puisse mettre a jour l'existant sans que tout se casse (par exemple avec une fonction de mise a jour des tables lors de la mise a jour), et je pense que c'est périlleux.

En tout cas, cela pourrait etre un objectif de la prochaine version majeure, doryphore.

**Comment by Cyrille37** [comment]
Je mets ça de côté :

Définition du charset par défaut:
`ALTER DATABASE dbname CHARACTER SET utf8 COLLATE utf8_general_ci ;`

Puis pour chaque table définir le charset ET convertir les données:
`ALTER TABLE tbl_name CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci ;`

Retrouver l'encodage des tables

```
SELECT T.table_name, CCSA.character_set_name FROM information_schema.`TABLES` T,
       information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA
WHERE CCSA.collation_name = T.table_collation
  AND T.table_schema = "schemaname"
```

Je vais faire des essais pour voir ce qu'il est possible de proposer pour **cercopithèque** de pas trop compliqué.

Au fait, où sont les infos sur **doryphore** ? Des specs & requirements qlq part ?

**Comment by mrflos** [comment]
C’est beau le SQL!

Pour les specs, rien d’écrit encore, on finalise encore cercopitheque mais en gros c’est une version pour les devs avec comme idées :
- réécriture ou redécoupage de yeswiki
- autoload des class
- PSR généralisé
- services RESTFUL
- passage au markdown

Et dans l'idéal
- Intégration continue et unit test

Mais avant d’en arriver la, se donner le temps d’experimenter avec les extensions yeswiki, et réfléchir a ce qui est essentiel

**Comment by Cyrille37** [comment]
Concertation à propos du sujet (UTF-8).
cc @daiko @gatienbataille 

Je propose de passer **tout yeswiki en utf-8**:
- supprimer les traitements: _convert() & co
- faire un petit outil de conversion des tables vers utf-8 à lancer à la main pour ceux qui en auraient besoin après mise à jour.

Tout le monde y gagnera. Pour l'utilisateur ça sera aussi un mieux.

**Par exemple** tu m'as envoyé un dump de yeswiki.net, et bien dans le fichier tous les accents sont cassés.
![selection_001](https://cloud.githubusercontent.com/assets/368965/17300461/c8d2716e-5812-11e6-96d6-69552f788810.png)
Du coup ça doit être aussi une galère pour les utilisateurs pour manipiler les sauvegardes, migrations, copies...

**Comment by mrflos** [comment]
C’est sur que ca serait bien de le faire, mais faut vraiment avoir un outil pour faciliter la mise a jour.
Peut être un handler /checkinstall
Qui vérifierai l’encodage et proposerai de faire la bascule
Il pourrait aussi verifier quelques trucs utiles, comme les droits d’accès en écriture de certains dossier ou autre

**Comment by mrflos** [comment]
Hello @Cyrille37 , normalement, actuellement, yeswiki lors d'une nouvelle install est en utf8 coté php et utf8mb4 coté mysql (et donc support des emojis!!), sur la branche dev, j'ai un handler /dbutf8 (reservé aux admins) qui fait la conversion de latin1 vers utf8mb4 pour les tables et les données (il ajoute aussi le charset de la bdd au fichier wakka.config.php).

Si tu peux faire un test de conversion d'un wiki, voir s'il ne t'a pas perdu tes données et tous tes accents (fais sur des données de test, hein!!), et si tu peux vérifier si cela a effectivement améliore les perfs, ce serait génial!!

Merci d'avance!

Amitiés

**Comment by assanecom** [comment]
Salut, problème d'installation de yeswiki cercopitheque sur Ubuntu, voici
l'erreur affiche:

 AVERTISSEMENT : le fichier de configuration wakka.config.php n'a pu être
créé.Veuillez vous assurez que votre serveur a les droits d'accès en
écriture pour ce fichier. Si pour une raison quelconque vous ne pouvez pas
faire ça, vous devez copier les informations suivantes dans un fichier et
les transférer au moyen d'un logiciel de transfert de fichier (ftp) sur le
serveur dans un fichier wakka.config.php directement dans le répertoire de
YesWiki. Une fois que vous aurez fait cela, votre site YesWiki devrait
fonctionner correctement.

**Comment by gatienbataille** [comment]
erreur assez classique et à mon avis non liée à Ubuntu, faut aller voir sur le serveur pour ouvrir les droits d'accès, sinon le wakka-config ne peut se créer.. et donc pas de wiki possible
