### ISSUE TITLE
[cercopithèque][i18n] langue EN écrase FR (bug)

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#208]
Salut,
Lors de l'action actions/**textsearch**.php, le bouton 'SEARCH' a pour valeur "Search" ou "Search database" (_yeswiki_en.php_) au lieu de "Chercher" (_yeswiki_fr.php_). Je me suis promené sur le Net et le problème est bien présent sur des yeswiki en ligne.
![selection_001](https://cloud.githubusercontent.com/assets/368965/17099464/d21ea422-5268-11e6-8df0-eb57d2e70a18.png)

Effectivement en traçant les appels on voit bien que **EN est chargé après FR** : 
[25-Jul-2016 13:00:25 Europe/Paris] .../yeswiki-cercopitheque/lang/yeswiki_fr.php
[25-Jul-2016 13:00:25 Europe/Paris] .../yeswiki-cercopitheque/lang/yeswiki_en.php

**Comment by Cyrille37** [comment]
Argh... Bizarre ... Ça viendrait de mon navigateur ...

Dans les préférences il y a bien dans l'ordre "FR_FR", "FR", "EN_US", "EN"
et pourtant `_SERVER["HTTP_ACCEPT_LANGUAGE"] = en-US,en;q=0.5`

**Comment by mrflos** [comment]
J’essaye de t’informer comment Yeswiki fait la gestion des langues :
Le français est la langue par défaut, le tableau de langue contient systématiquement d’abord la langue française, puis si la page est dans une autre langue, celle ci écrase le tableau français (si les traductions sont incomplètes, on trouve des bout en francais).

Pour savoir la langue utilisée dans une page (par ordre de traitement, mais de memoire..) :
- une langue est passée en %_GET[‘lang’]
- un triple metadata assigne une langue a la page
- la langue par défaut dans wakka.config.php
- une fonction de libs/i18n.inc.php regarde les préférences du navigateur

**Comment by Cyrille37** [comment]
Merci Florian. J'avais vu ça dans le code et du coup vu que HTTP_ACCEPT_LANGUAGE n'était pas celui que je pensais à la vue des préférences de mon FireFox:
![firefox prefs](https://cloud.githubusercontent.com/assets/368965/17100459/c04c04a0-526e-11e6-8a6e-1f37ba8ab31d.png)

Et pourant:
`$_SERVER["HTTP_ACCEPT_LANGUAGE"] = en-US,en;q=0.5`
![http exchanges](https://cloud.githubusercontent.com/assets/368965/17100579/876650cc-526f-11e6-8c44-478ac76b41e9.png)

**Comment by mrflos** [comment]
T’as pas une extension firefox qui prend le dessus? Genre une pour bidouiller les headers

**Comment by Cyrille37** [comment]
Je viens de désactiver tous les modules ... toujours pareils.
Tant pis, je fais avec, maintenant que je suis au courant... :-(
Je vérifierai les traductions avec Chromium ;-)
Merci du support morale :-P

**Comment by Cyrille37** [comment]
Firefox bug on Ubuntu:
https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1527663
