### ISSUE TITLE
[bazar][carto] placer point adresse: zoomer sur le point trouvé

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#217]
Quand on clique sur "_cliquer ici pour placer le lieu sur la carte_" et qu'une adresse est trouvée, il faudrait que la carte zoome (un peu?) sur le point.

**Comment by J9rem** [comment]
@Cyrille37 je sais que cette issue est un peu vieille. Elle est affectée à cercopitheque. Mais comme nous n'allons plus maintenir cecopitheque au profit de doryphore. Est-ce que la fonctionnalité est présente dans doryphore et répond à ce que tu avais identidié ?

j'avais l'impression que oui.

**Comment by Cyrille37** [comment]
Hello
Merci pout ton attention :-)
Ça fait si longtemps ... Je clos ce ticket.
