### ISSUE TITLE
yeswiki_release depuis la config au lieu du code

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#224]
Bonjour bonjour,
L'action "**yeswikiversion**" prends ses valeurs "yeswiki_version" et "yeswiki_release" depuis la configuration, qui est un espace pour l'utilisateur.
Pourquoi ne pas prendre ces valeurs depuis les constantes définies dans wakka.php ?
@mrflos une raison ? ou bien je fais la modif ?
Cheers.

**Comment by mrflos** [comment]
Non, les deux sont nécessaires : en cas de mise a jour, wakka.php ou l'auto-updater peut savoir que la version du fichier de conf et la version du wiki diffère et donc appliquer des traitements et finir par mettre la version du fichier de conf a la bonne valeur pour signifier que le wiki est a jour.

Je sais pas si je suis clair.. Tu me diras 😄

**Comment by Cyrille37** [comment]
Ok, ça me semble impeccable !

À propos de ta remarque https://github.com/YesWiki/yeswiki/pull/221#issuecomment-235908676
On ne peut pas mettre à jour la version dans la config via le git ;-) puisque la config est générée à l'installation.
Faut-il mettre à jour dans un autre fichier du code ou seulement dans wakka.php ?

**Comment by mrflos** [comment]
Juste wakka.php, mais je croies que c’est meme pas la peine, car avec @daiko on va mettre en place les scripts de generations des archives, et ce script mettra a jour le wakka.php.

Une fois l’infrastructure en place on pourra détailler le fonctionnement.

**Comment by Cyrille37** [comment]
C'est chouette ;-)
