### ISSUE TITLE
extension captcha ne fonctionne plus ?

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#225]
Je n'arrive pas à faire fonctionner https://github.com/YesWiki/yeswiki-extension-captcha

Il est marqué en bas à droite de la page "_Protection anti-spam active_" et quand je "save" une page j'ai le message d'erreur "_Cette page n'a pas été enregistrée car vous n'avez pas entré le mot de vérification_" ;  mais **il n'y avait pas de champs pour ce mot**.

**Comment by mrflos** [comment]
Oui, je ne l’ai jamais utilisée, apparement c’est cassé..

**Comment by Cyrille37** [comment]
Argh... "_Protection anti-spam active_" provient de l'extension "**hashcash**" pas de "**captcha**".

**Comment by Cyrille37** [comment]
new issue https://github.com/YesWiki/yeswiki-extension-captcha/issues/1

**Comment by Cyrille37** [comment]
@mrflos Du coup à quoi sert "hashcash" ? Comment ça fonctionne ? J'ai pas trouvé grand chose sur yeswiki.net ... C'est bien l'outil pour éviter le spam ?

**Comment by mrflos** [comment]
cf. https://fr.wikipedia.org/wiki/Hashcash https://fr.wikipedia.org/wiki/Hashcash

C’est un antispam qui est basé sur du javascript, mais qui ne nécessite pas de manipulation de l’utilisateur, juste javascript doit être activé.
Hélas les robots qui émulent un navigateur passent outre…

**Comment by Cyrille37** [comment]
Merci.
Et à quoi sert "**password_for_editing**" ? C'est bien une autre option pour protéger l'édition ?

**Comment by mrflos** [comment]
C’est une nouvelle feat demandée, et pas encore documentée, on va demander a @gatienbataille de voir pour la doc! ;)

En gros on rentre « password_for_editing » dans le fichier de wakka.config.php en lui donnant une valeur, et ensuite, en mode edition, il sera systématiquement demandé (sauf aux admins identifiés) avant de proposer l’accès a l’edition.
C’est un mot de passe global, que l’on peut proposer au groupe des utilisateurs, cela évite des spams, sans forcement pousser les gens a s’identifier et gérer les droits des pages.
Cela n’annule pas la gestion des droits page par page, c’est une sécurité complémentaire.

**Comment by gatienbataille** [comment]
@mrflos 
possible de rajouter un param en plus qui permettrait d'afficher une phrase "perso" juste au dessus ou en dessous du champ mot de passe général pour l'édition ?

ce qui permettrait par ex d'indiquer
- "Vous souhaitez contribuer ou modifier mais avez égaré le mot de passe, prenez contact avec ...."
  ou 
- "Mot de passe oublié ? un indice... c'est le titre de notre projet" 
  (suppose que les robots ne lisent pas et que les turcs ne maitrisent pas le français ;-)

à voir ??

**Comment by mrflos** [comment]
@gatienbataille on peut ajouter password_for_editing_message a la configuration, ainsi que 

  'use_hashcash' => true,
  'use_nospam' => true,
  'use_alerte' => true,
  'use_captcha' => true,

Pour activer les différentes securités, et donc le captcha est intégré

**Comment by gatienbataille** [comment]
J'ai fait une doc sommaire sur http://yeswiki.net/wakka.php?wiki=SpamWakka
@mrflos je vois pas trop ce que fait alerte

**Comment by mrflos** [comment]
Si alerte est activée, on peut tester aller en mode edition d’une page, et écrire un bout de texte sans sauver.

Si l’on ferme l’onglets du navigateur, une alerte devrait indiquer « Attention vous allez perdre des données, etes vous sur? »
