### ISSUE TITLE
KILLER FEATURE ;-) Suivre la vie du wiki grâce à un mail récapitulatif à fréquence choisie

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#228]
Hello

Lorsque l'on anime un projet avec un yeswiki, il est **très important de pouvoir suivre** ce qui s'y passe et réagir (corriger, relancer, promouvoir) vers la communauté.  Ceci permet de maintenir la dynamique du projet. 

Il est aussi important que **chaque membre de la communauté puisse suivre** la vie du wiki.

Actuellement ceci n'est possible que via le flux rss MAIS
- c'est pas si évident en terme de suivi, ni très clair et 
- ce n'est clairement pas à la portée des membres du réseau qui pour la plupart ne savent pas ce qu'est un flux rss 

Il serait FANTASTIQUE de pouvoir demander à yeswiki d'envoyer à fréquence régulière (un paramètre au choix pour chacun ? jour/semaine/mois/jamais) ce qui s'est passé sur le wiki durant cet interval et TOUT CA VIA UN MAIL ;-) 

Avec par exemple comme contenu : 
- les dernières pages "normales" modifiées (liens clicables) ou créés 
- les fiches bazar créés 
- les derniers users créés ou modifiés
- ...

Vous en pensez quoi ? @mrflos @Cyrille37 @furax37 @LouiseQuincaillere 
Moi je trouve que ça simplifierait bcq bcq bcq la vie des animateurs de réseaux sous yeswiki...

J'ai vu cette fonctionnalité sur l'outil Mobilizator et c'est vraiment très très pratique

**Comment by Cyrille37** [comment]
Bonjour Gatien/@gatienbataille

Effectivement ce "Summary" ou "Digest" serait un vrai plus. Beaucoup d'outils proposent d'être notifié par email à chaque changement mais je n'en connais pas qui propose un résumé d'une période par email.

Réflexion du tech:
- Le code fait la synthèse des modifications par pages/formulaires/fiches.
  - une seule et même période pour tout le wiki, aux utlisateurs de s'y abonnée ou non
- Exécution:
  - le déclencheur s'exécute à chaque appel du wiki (wakka.php)
    - proposer d'autres options (comme pour Wordpress) : exécution via crontab ou appel http
  - si c'est le moment d'envoyer
  - il calcule le résumé et rédige le mail
  - il envoie les mails
    - problème du nombre de destinataires
      - grouper par paquet de x destinataires
      - proposer d'autres options : une  adresse de mailing-list, utilisé la queue de Postfix ou Exim, ...

**Comment by mrflos** [comment]
Hello,

Oui en effet, ca serait bien utile!
Pour une version rapidement en place, je verrai bien un handler /digest, (avec en paramètre $_GET[‘period’] daily|weekly(par défaut)|monthly]) qui lorsqu’il est appelé, récupère tous les changements de la période J-7 a J (j-30 a J pour le monthly, ou j-1 a j pour daily), ce handler génère juste l’affichage et peut être appelé du TableauDeBord (lien vers changements de la semaine, du jour, du mois)
Ensuite, un cron envoie un mail a une liste de diffusion précisée (yeswiki-daily@exemple.com, yeswiki-weekly@exemple.com yeswiki-monthly@exemple.com ) qui contient juste le contenu du handler.

Idéalement, plutôt qu’un cron, un déclencheur tous les lundis, tous les 1er du mois et tous les jours, qui vérifie un triple last-monthly-sent  (ou last-daily-sent, ou last-weekly-sent) contenant la date et une base de données des abonnés, mais cela me parait plus compliqué..

Peut être ya moyen de faire une petite cagnotte et de demander a un développeur de le programmer moyennant petite rémunération et glorification ? :)

**Comment by gatienbataille** [comment]
hello

@Cyrille37 l'idéal serait qu'on puisse choisir la fréquence car suivant qu'on est animateur ou simple membre, le besoin est assez différent... et si on prend journalier (qui convient bien à l'animateur) ça risque de noyer l e membre

@mrflos j'aime assez l'idée du handler... est ce que travailler avec un cron ne rend pas l'install du wiki plus compliquée pour le non geek ? 

Moi je suis partant pour alimenter la cagnotte... en tant qu'animateur de quelques yeswikis, ça m'aiderait pas mal... et je suis sur que ça aiderait aussi plein d'autres

**Comment by Cyrille37** [comment]
Pour le déclencheur (http, cron) il faut lire un peu comment c'est fait dans Wordpress, de mémoire c'est un sujet bien traité.
- https://tommcfarlin.com/wordpress-cron-jobs/
- https://codex.wordpress.org/Category:WP-Cron_Functions

_là j'ai pas le temps, désolé de seulement vous laisser des liens_

**Comment by mrflos** [comment]
Il est possible de le faire avec https://cron-job.org , je laisse a @gatienbataille le plaisir d'éventuellement le documenter ;)
