### ISSUE TITLE
[carto] ajouter des fonds et des layers (params: providers & layers)

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#229]
Ajouter, dans le L.Control traditionnellement en haut à droite sur les cartes Leaflet, des layers (Overlay) provenant d'autres sources:

**param "layers"**:
- du geojson contenu dans une page wiki
- du geojson contenu sur un site externe (ex: umap)

Une fois fait, c'est très facile d'ajouter d'autres fonds de carte (Baselayer).

**param "providers"**:
- décoder une liste dans le paramètre "provider" de Bazar.

**Comment by mrflos** [comment]
yes!

peut être une action {{leaflet ..}}?
avec en param une ou plusieurs url geojson? 
et un param fond de carte

Et pour finir un handler /geojson pour bazar, pour avoir les contenus des fiches en format geojson! (on a le droit de rêver :) )

**Comment by Cyrille37** [comment]
Ben pour l'instant je fais grossir les options de BazarListe car elle propose déjà tout ce dont on a besoin.
Une nouvelle action (comme BazarCarto) qui ne fait rien de spéciale ça embrouille.

Mais j'ai peut-être pas tout compris de ton idée ??

![selection_001](https://cloud.githubusercontent.com/assets/368965/17243658/42642a50-557e-11e6-837c-087fa4096ca2.png)

**Comment by Cyrille37** [comment]
in PR #231

**Comment by Cyrille37** [comment]
Et voilà
![selection_002](https://cloud.githubusercontent.com/assets/368965/17247412/74f93ad6-5593-11e6-8b5d-a295ebd26cb0.png)

**Comment by Cyrille37** [comment]
Argh! "git" n'a pas ajouté le nouveau plugin leaflet. Ça doit venir de ma dernière modification du fichier .gitignore ... Je regarde

**Comment by mrflos** [comment]
Ok je comprends mieux, en effet c’est sympa, mais va falloir le documenter et mettre des exemples.

Moi par geojson, je comprenais ajouts de marqueurs issus de sources extérieures seulement.
Du coup j’imaginait une action wiki qui afficherait la carte, et qui présenterai des points venus de différentes sources, et avec un handler /geojson, on pourrait avoir les données bazar d’un autre wiki comme source.

**Comment by Cyrille37** [comment]
**.gitignore corrigé**.
Du coup j'ai **mergé dans cercopitheque_dev** car on risquait de perdre du travail avec des fichiers ignorés qui ne le devaient pas.
La négation avec des exceptions est un peu verbeuse ...
Le bon fichier **.gitignore pour ignorer tous les tools sauf certains** :  https://github.com/YesWiki/yeswiki/blob/e0d6b18301ad7e56374c1f272c0811d8479bdb3e/.gitignore
