### ISSUE TITLE
avertir utilisateur si ferme page en édition avec modification

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#235]
Il manque une fonctionnalité (_en plus de la preview ;-)_) : quand on est en mode édition d'une page et que l'on a fait des modifications il faudrait avertir l'utilisateur quand il fait autre chose que "Sauver".

Exemple sur Dokuwiki : 
![quitteeditionalert](https://cloud.githubusercontent.com/assets/368965/17269509/b427972c-564a-11e6-83b2-1e4482ba09c1.png)

**Comment by mrflos** [comment]
Ca a déja été développé mais abandonné y compris par les personnes l'ayant commandée car comme on dit "Trop de popup tue la popup" 😄 

On peut cependant le récupérer ici https://github.com/YesWiki/yeswiki-extensions-deprecated/tree/master/alerte

**Comment by Cyrille37** [comment]
Ben je trouve ça indispensable pour ne pas perdre son travail par mégarde. Tous les logiciels (sauf Blender) signale à l'utilisateur qu'il a du travail en cours qu'il va perdre s'il continu.

Peut-être le mettre dans le "core" des tools (comme bazar) mais désactivé par défaut (wakka.config.php) ?

**Comment by mrflos** [comment]
Oui,

Ce que j’aimerais a terme, c’est avoir un tools « core » safety (ou security ou tweaks4edit :) ) comprenant :
- hashcash
- despam
- ipblock
- captcha
- alerte
  …

Avec le minimum vital et non intrusif d’activé, et le reste a ajouter au fichier de conf.

Penses tu que ca a du sens ou alors le plus modulaire est mieux?

**Comment by Cyrille37** [comment]
Oui, je trouve que ça a du sens de tout mettre dans un "security" tool.
Mais c'est un sacré boulot ;-(

**Comment by mrflos** [comment]
Yep c'est fait !

 'use_alerte' => true, // ou false 

A mettre dans le fichier de conf, true par defaut, et ne s'active que si le contenu a été modifié
