### ISSUE TITLE
[bazar][carto] ajout collections d'icones pour les markers

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#236]
Voir comment proposer les "maki-icons" ou d'autres collections.
Peut-être seulement documenter suffit ?
- https://www.mapbox.com/maki-icons/
- http://www.sjjb.co.uk/mapicons/contactsheet
- https://mapicons.mapsmarker.com/
- http://www.easyicon.net/iconsearch/map/

**Comment by mrflos** [comment]
Cool ces icônes, je ne connaissais pas.
En téléchargeant un zip a partir de https://www.mapbox.com/maki-icons/
Ils livrent un fichier iconset-all_maki_icons.json a inclure, de 130ko tout de meme, qui contient toutes les icones et leur path svg.

Je me demande si cela pourrait pas etre fait dans une extension, qui soit verifie la presence d'une classe maki pour charger les icones, soit qui ajoute un css avec les classes pour maki dedans

**Comment by Cyrille37** [comment]
En tout cas il y a du travail ;-)
Dans l'extension: une autre possibilité est de construire un png avec tous les icônes et les placer avec css.

À réfléchir (ce que je n'ai pas encore fait ;-) )
_J'ai ajouté quelques liens dans le 1er comment._

**Comment by mrflos** [comment]
Oui a garder sous le coude, mais ce que j’aimais avec ce kit, c’est le fait d’avoir du svg, c’est vachement mieux que les png, ca gère les écrans retina, on peut changer de couleur en hackant le svg, etc

**Comment by mrflos** [comment]
c'est maintenant plus facile a faire car il suffit d'associer des classes aux champs, et il me semble que c'est documenté
