### ISSUE TITLE
[login] ajout paramètre "lostpasswordurl"

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#238]
Ajout du paramètre "**lostpasswordurl**" à l'action "**login**" du tool "login".
Si le paramètre est présent, le template "**login/presentation/default.tpl.html**" affiche un bouton "mot de passe perdu?" sous le bouton "s'inscrire".

**Comment by mrflos** [comment]
Hello je regardais pour #193 et je me demande s'il ne faut pas le mettre en opt-in
Je pense que c'est pas forcement la peine d'en faire un parametre, car c'est toujours utile, par contre faut le rendre visible par défaut.

**Comment by Cyrille37** [comment]
Je l'ai mis en paramètre car il faut indiquer un "WikiName" qui inclue l'action {{lostpassword}}.
_Mais je n'ai peut être pas bien compris ton explication ?_

**Comment by mrflos** [comment]
Ok pour le paramètre, mais juste je me disais que cette fonction de recuperation de mot de passe doit être toujours présente, car très utile!

Je propose de créer une page MotDePassePerdu a l’install, que ce soit la valeur par défaut du paramètre, et de verifier les templates de login, pour que ce soit toujours present.

**Comment by Cyrille37** [comment]
Yes U CAN !

;-)

**Comment by mrflos** [comment]
DONE
