### ISSUE TITLE
[bazar] option "barregestion" ne fonctionne pas

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#239]
Dans action "BazarListe" le paramètre "**barregestion**" ne fonctionne pas.

**Comment by Cyrille37** [comment]
Normal, dans la doc il est écrit "true" ou "false" alors que dans la fonction getAllParameter() est testé "0" ou "no" ou "non"...

**Comment by mrflos** [comment]
Il est implémenté la : http://jardiniersdunous.org/wakka.php?wiki=CartoJardiniers http://jardiniersdunous.org/wakka.php?wiki=CartoJardiniers

**Comment by mrflos** [comment]
ok je peux corriger ca!

**Comment by Cyrille37** [comment]
Je suis en cours de le faire ;-) => **Label "En Cours"**

**Comment by mrflos** [comment]
trop tard..

**Comment by Cyrille37** [comment]
J'ai fait des modifs : ajout de la fonction **getParameter_boolean()** que l'on pourra utiliser pour tous les boolean.

**Pense à faire un pull**, _j'ai résolu le conflit de nos 2 modifs simultanées_

**Comment by Cyrille37** [comment]
Oups. J'avai oublié de merger ma branche dans cercopitheque_dev PR #241
