### ISSUE TITLE
[bazar] paramètre "random" non documenté

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#240]
Le paramètre "random" de Bazar n'est pas documenté sur http://yeswiki.net/wakka.php?wiki=ActionBazarliste

**Comment by mrflos** [comment]
J'ai mis une ligne dans la doc http://yeswiki.net/wakka.php?wiki=ActionBazarliste

**Comment by Cyrille37** [comment]
chouette ;-)
