### ISSUE TITLE
[git] .gitignore et wp-hashcash.key

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#242]
J'ai modifié le **.gitignore** pour que git suive certains tools _(ceux du "core"_) et pas les autres (_extensions_).
Mais ça ne fonctionne pas avec le fichier : tools/hashcash/secret/**wp-hashcash.key** ...

**Comment by mrflos** [comment]
Oui j’ai déjà eu le souci, mais je n’arrive pas non plus a faire en sorte qu’il ne soit pas suivi..

**Comment by Cyrille37** [comment]
il y a 2 problèmes:
- le .gitignore qui ne fonctionne pas comme ça avec ce fichier
- ce fichier devrait être ailleurs car c'est une donnée dynamique.

**Comment by mrflos** [comment]
oui, a mettre dans le dossier cache ?

**Comment by Cyrille37** [comment]
oui

**Comment by mrflos** [comment]
A tester

**Comment by Cyrille37** [comment]
Merci 😊
**Je suis hors ligne jusqu'au 22/08**
