### ISSUE TITLE
[bazar] barregestion et droit dans baz_voir_fiche() ne fonctionne pas

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#243]
Quand la barre de gestion des activée "{{bazarliste **barregestion**="true ...}}", dans la fonction "**baz_voir_fiche**()" il y a un **test sur le droit d'édition** qui ne semble pas fonctionner.

J'ai essayé: la barre d'édition est affichée pourtant quand je clique sur "_modifier_" ou "_supprimer_" je tombre sur le message "_Vous ne pouvez pas accéder à cette page par le handler spécifié._". Ce qui dit bien que je n'ai pas le droit, donc la barre d'édition ne devrait pas être affichée sur le test dans "baz_voir_fiche()" fonctionnait ...

**Comment by mrflos** [comment]
Tu as changé sur ton wiki les droits du handler /edit ?
C’est possible que la Methode hasAccess ne contrôle que les acls des pages…

**Comment by Cyrille37** [comment]
piste d'investigation:
- lors de l'affichage des fiches dans la liste, on a bien un appel à **baz_a_le_droit()**
- quand on affiche la fiche en édition avec le handler "**/edit**" il n'y a pas d'appel à **baz_a_le_droit()**

**Comment by mrflos** [comment]
baz_a_le_droit, je pense que c’est vieux, normalement il devrait laisser la gestion des droits a wiki avec la méthode hasAccess(‘write’)

**Comment by Cyrille37** [comment]
Avec ACL "/edit" = "+"

**Comment by Cyrille37** [comment]
Le handler "**/edit**" ne semble pas faire appelle à **Waka::HasAccess()** ...

J'ai mis un error_log juste au début de Waka::HasAccess() et je le vois passer en vue mais pas en "/edit".

Je continue l'investigation.

**Comment by mrflos** [comment]
C’est que pour bazar?

**Comment by Cyrille37** [comment]
Pour l'instant je suis sur Bazar, je ne sais pas pour le reste.
Je suis en train de chercher et corriger ...

**Comment by mrflos** [comment]
Ici ya bien un test :
https://github.com/YesWiki/yeswiki/blob/cercopitheque/tools/bazar/handlers/page/__edit.php#L34 https://github.com/YesWiki/yeswiki/blob/cercopitheque/tools/bazar/handlers/page/__edit.php#L34

par contre :
https://github.com/YesWiki/yeswiki/blob/cercopitheque/tools/bazar/libs/bazar.fonct.php#L3095 https://github.com/YesWiki/yeswiki/blob/cercopitheque/tools/bazar/libs/bazar.fonct.php#L3095
retourne true!!!!!!!!!

je serai pour éradiquer cette fonction et passer par les méthodes wiki, mais au minimum, on peut faire le hasAccess dans baz_a_le_droit

Je vais partir, la, je reprendrai sur les taches lostpassword , diaporama, et factorisation security
A plus

**Comment by Cyrille37** [comment]
C'est étrange.
Quand j'affiche une fiche "_wakka.php?wiki=MaisonDeLEmploiDuChinonais/edit_" il y a beaucoup d'appel à Wakka::HasAccess() mais aucun avec le WikiName de la fiche demandée
```
HasAccess privilege:[write], tag:[], user:[]
HasAccess privilege:[write], tag:[], user:[]
HasAccess privilege:[write], tag:[], user:[]
HasAccess privilege:[write], tag:[], user:[]
HasAccess privilege:[write], tag:[], user:[]
HasAccess privilege:[write], tag:[], user:[]
HasAccess privilege:[write], tag:[], user:[]
HasAccess privilege:[read], tag:[PageHeader], user:[]
HasAccess privilege:[read], tag:[PageHeader], user:[]
HasAccess privilege:[write], tag:[PageHeader], user:[]
HasAccess privilege:[read], tag:[PageTitre], user:[]
HasAccess privilege:[read], tag:[PageTitre], user:[]
HasAccess privilege:[write], tag:[PageTitre], user:[]
HasAccess privilege:[read], tag:[PageMenuHaut], user:[]
HasAccess privilege:[read], tag:[PageMenuHaut], user:[]
HasAccess privilege:[write], tag:[PageMenuHaut], user:[]
HasAccess privilege:[read], tag:[PageRapideHaut], user:[]
HasAccess privilege:[read], tag:[PageRapideHaut], user:[]
HasAccess privilege:[write], tag:[PageRapideHaut], user:[]
HasAccess privilege:[write], tag:[], user:[]
HasAccess privilege:[read], tag:[PageFooter], user:[]
HasAccess privilege:[read], tag:[PageFooter], user:[]
HasAccess privilege:[write], tag:[PageFooter], user:[]
HasAccess privilege:[write], tag:[], user:[]
HasAccess privilege:[write], tag:[], user:[]
HasAccess privilege:[write], tag:[], user:[]
HasAccess privilege:[write], tag:[], user:[]
HasAccess privilege:[write], tag:[], user:[]
```

**Comment by Cyrille37** [comment]
Argh. J'ai déplacé le error_log après la définition des valeurs pas défaut, et c'est mieux ;-)
```
HasAccess privilege:[write], tag:[MaisonDeLEmploiDuChinonais], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[MaisonDeLEmploiDuChinonais], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[MaisonDeLEmploiDuChinonais], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[MaisonDeLEmploiDuChinonais], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[MaisonDeLEmploiDuChinonais], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[MaisonDeLEmploiDuChinonais], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[MaisonDeLEmploiDuChinonais], user:[CapitaineHaddock]
HasAccess privilege:[read], tag:[PageHeader], user:[CapitaineHaddock]
HasAccess privilege:[read], tag:[PageHeader], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[PageHeader], user:[CapitaineHaddock]
HasAccess privilege:[read], tag:[PageTitre], user:[CapitaineHaddock]
HasAccess privilege:[read], tag:[PageTitre], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[PageTitre], user:[CapitaineHaddock]
HasAccess privilege:[read], tag:[PageMenuHaut], user:[CapitaineHaddock]
HasAccess privilege:[read], tag:[PageMenuHaut], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[PageMenuHaut], user:[CapitaineHaddock]
HasAccess privilege:[read], tag:[PageRapideHaut], user:[CapitaineHaddock]
HasAccess privilege:[read], tag:[PageRapideHaut], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[PageRapideHaut], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[MaisonDeLEmploiDuChinonais], user:[CapitaineHaddock]
HasAccess privilege:[read], tag:[PageFooter], user:[CapitaineHaddock]
HasAccess privilege:[read], tag:[PageFooter], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[PageFooter], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[MaisonDeLEmploiDuChinonais], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[MaisonDeLEmploiDuChinonais], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[MaisonDeLEmploiDuChinonais], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[MaisonDeLEmploiDuChinonais], user:[CapitaineHaddock]
HasAccess privilege:[write], tag:[MaisonDeLEmploiDuChinonais], user:[CapitaineHaddock]

```

**Comment by Cyrille37** [comment]
Bon, c'est quand même à changer.
**Mais j'avais certainement le problème** #244 avec des lignes d'**acls qui étaient des chaînes vides**. Je ne sais pas trop s'il y a un rapport, mais peut-être bien ;-)
