### ISSUE TITLE
handler /deletepage droits différent de /edit ?

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#246]

**Comment by mrflos** [comment]
Le /deletepage est réservé a l'auteur (owner) de la page et au groupe @admins

**Comment by Cyrille37** [comment]
Et concernant Bazar ? En fait c'est avec bazar que j'ai eu la surprise, avec la "barregestion"

**Comment by mrflos** [comment]
C’est a dire?
Normalement les fiches bazar sont soumises aux meme règles que n’importe quelle pageWiki.

**Comment by Cyrille37** [comment]
Voilà, c'est bien ça, je viens de refaire un essai.
Donc ce qui ne va pas c'est la **barre de gestion** qui, si l'utilisateur à droit de "write" propose le bouton "modifier" et "**supprimer**", alors qu'il n'a pas le droit de "supprimer" car il n'est ni admin, ni owner.

**Comment by mrflos** [comment]
Ok j’ai push un Hotfix

**Comment by Cyrille37** [comment]
Super !! Ça fonctionne on dirait :-) Merci !
