### ISSUE TITLE
URL pour récupérer un seul champ d'une fiche

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#249]
> Est-il possible d'avoir un URL pour récupérer un seul champ d'une fiche ?
> On fourni dans l'url l'ID de la fiche et l'ID du champ et en réponse on a le contenu du champ.
> 
> Il y a une action pour bazar `{{valeur url="<url_fiche_bazar>" champs="<nom_du_champs>"}}` qui permet d'aller chercher une valeur, mais autrement, par url, ce n'est pas possible..

**Comment by J9rem** [comment]
Bonjour @Cyrille37 ,

a priori avec la toute dernière version doryphore, il serait possible de récupérer un seul champ d'une fiche de cette manière (à tester).

`https://www.example.com/?api/forms/{formId}/entries/json/{entryId}&fields={field_name1},{field_name2}`

en remplaçant :
- `{formId}` par le numéro du formulaire où se situe la fiche
- `{entryId}` par l'identifiant de la fiche 
- `{field_name1}` par le nom du champ concerné

Pour tester : https://yeswiki.net/?api/forms/49/entries/json/CommentFairePourRemplirUnChampTagAvecDe&fields=bf_titre

**Comment by J9rem** [comment]
Je clos cette issue car elle est résolue (certes elle reste à documenter)
