### ISSUE TITLE
[bazar]Utilisation d'un champ date (jour) comme facette dans bazarliste

### ISSUE THREAD

**Issue by GDoukhan** [YesWiki/yeswiki#251]
Un champ 'jour' n'est pas utilisable comme critère de recherche facette avec bazarliste.
Ou en tout cas lorsque j'essaye de le mettre en place, il n'apparait pas (http://www.territoires-paca.fr/wakka.php?wiki=BourseEmploi)

**Comment by mrflos** [comment]
Dans la version actuelle, seuls les champs bazar de type listes, checkbox, checkboxfiche et listefiche peuvent etre utilisés comme facette.

Ce serait en effet bien qu'a terme on puisse le faire avec des dates et des champs numérique et un slider.

Je change l'intitulé en feature pour le faire un jour peut etre.

**Comment by gatienbataille** [comment]
En fait, il est possible de filtrer sur tous les champs mais le filtrage sur les dates (toutes différentes) ne sert pas à grand chose
