### ISSUE TITLE
facette qui déconne avec des ID de liste en chiffre (dépassant 10)

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#253]
Quand on a utilisé des ID sous forme de chiffres et que la liste contient plus de 10 valeurs
on rencontre un souci avec facette

quand on lui demande d'afficher les fiches avec un ID=1, elle affiche aussi celle avec un ID=contenant un 1 (donc 10, 11, 12.. 21...)
idem pour l id=2 qui affiche du coup tout ce qui contient un 2 dans son id
et la suite, vous avez compris ;-)

voir un exemple sur http://levolti.be/wakka.php?wiki=Utiliser

**Comment by mrflos** [comment]
reparé
