### ISSUE TITLE
captcha sans lettre ou chiffre à recopier ...

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#254]
Hello

avec un wiki sous cerco-dev, j'ai rencontré un problème avec captcha.
il m'était demandé de recopier le code mais l'image ne contenait ni chiffre, ni lettre... 
et ce même si je rafraichissait la page pour avoir un autre captcha...

du coup impossible de faire "sauver"
la protection ultime contre le spam ;-)

![capture d ecran 2016-08-25 a 13 33 12](https://cloud.githubusercontent.com/assets/7147716/17997871/7d3d5990-6b71-11e6-80fc-4a92b699d9f8.png)

**Comment by mrflos** [comment]
As tu ajouté des mots ou gardé la configuration avec les mots par défaut?

**Comment by gatienbataille** [comment]
euh... comprends pas bien la question
voilà le wakka config actuel
  'password_for_editing' => '4escaut',
  'password_for_editing_message' => 'nom de notre unite : 4es...t',
  'use_hashcash' => true, //ne pas toucher pour l'instant
  'use_nospam' => true, // ne pas toucher pour l'instant
  'use_alerte' => true,
  'use_captcha' => false, // j'ai désactivé du coup

**Comment by mrflos** [comment]
corrigé
