### ISSUE TITLE
BUGS avec des pages intégrant des iframe

### ISSUE THREAD

**Issue by Laurent-UNIT** [YesWiki/yeswiki#255]
Bonjour, nous avons plusieurs wikis qui tournent avec cercopithèque et voici les problèmes rencontrés 
- lorsqu'une page intègre un framapad ou un framindmap, impossible de l'éditer sous peine de tomber sur une page "erreur 404". Erreur récente, comportement constaté depuis 2 mois environ
- lorsqu'une page intègre une feuille de calcul google sheet, on peut la lire mais impossible de cliquer sur d'autres onglets ensuite, la navigation est comme pétrifiée, plus aucun lien n'est fonctionnel. La seule solution est de cliquer sur le nom du site qui renvoie à la page d'accueil, tout le reste étant inactif. Erreur déjà ancienne, plus de 6 mois.
  Bravo pour le boulot magnifique, c'est très utile pour les écovillages :-) N'hésitez pas à me joindre pour toute précision au 06 17 46 17 02
  on vous aime

**Comment by fbredow** [comment]
Idem a l'autre question, auriez vous l'URL d'une page présentant le problème ?

**Comment by Laurent-UNIT** [comment]
je ne sais pas si cela va être opérant, mais voici une page qui bug sur le site, dont j'ai copié intégralement le back-office pour le coller sur la page dont voici l'URL ci-après : 
http://www.universite-transition.org/wiki-uniT/wakka.php?wiki=PageTissage 
j'ai du effectuer cette opération car le site sur lequel les pages bugguent est réservé aux habitants du HDB, je ne peux pas fournir les codes d'accès
Après avoir vérifié son comportement, la page que vous allez voir sur le "mauvais" site ne rejoue pas le bug (j'ai pourtant également copié le thème afin de coller au plus près à la réalité, ne vous étonnez pas d'une mise en page bizarre avec un menu blanc sur blanc, ça vient de là), il doit donc s'agir d'une erreur quelque part sur le site du HDB
ce qui est étrange c'est que j'ai effectué toutes les mises à jour, rien n'y fait
désolé pour le dérangement, je vais être plus attentif à poster de vrais problèmes pour tout le monde si j'en découvre
bien à vous,
LB

**Comment by mrflos** [comment]
Merci de votre proposition de tester les fonctionnalités de YesWiki, n'hésitez pas a revenir nous solliciter au cas ou, je ferme cette "issue" en attendant
