### ISSUE TITLE
Pas possible de créer des listes à puces

### ISSUE THREAD

**Issue by Laurent-UNIT** [YesWiki/yeswiki#256]
Bonjour, le code tout simple pour créer des listes à puces ne fonctionne pas lorsqu'on assigne au texte un code couleur entre deux balises span style

Voilà, merci :-)

**Comment by fbredow** [comment]
Bonjour, il nous faut un peu plus d'informations comme par exemple l'URL du wiki et la méthode d'installation.

**Comment by Laurent-UNIT** [comment]
voilà l'url : http://www.la-ferme-des-enfants.com/wiki-mut/wakka.php?wiki=PageCaroucayoU 

j'ai installé ce wiki via le serveur FTP ce matin et tout fonctionne bien à part ça :-)

**Comment by Laurent-UNIT** [comment]
désolé, j'ai déjà répondu directement sur la page, j'espère que cela ne fera pas doublon, mais au cas où :

voici l'url de la page 

j'ai installé cette version de Cercopithèque_dev ce matin via Filezilla, et tout s'est très bien passé

bien à vous, bravo pour le boulot :-)



Le 20 sept. 2016 à 12:09, Florestan Bredow <notifications@github.com> a écrit :

> Bonjour, il nous faut un peu plus d'informations comme par exemple l'URL du wiki et la méthode d'installation.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--

Laurent Bouquet
Directeur
www.universite-transition.org

**Comment by Laurent-UNIT** [comment]
bon, j'ai trouvé une astuce temporaire, à savoir entourer chaque ligne avec la balise 
span style color : ça me génère un retour à la ligne, sans toutefois créer de puce, mais c'est déjà bien pour le quart d'heure ;-)

**Comment by fbredow** [comment]
En regardant l'historique de la page : 

```
""<span style="color:#6C0277;">
Périmètres et redevabilités de la commission :
 - Décider au consentement de l’occupation des logements et mettre à jour cette gestion autant que de besoin ;
 - Faire remonter les besoins liés à cette zone (aménagements, maintenance, rénovation, etc.) aux instances concernées (Commission Patrimoine, Cercle Gérance de la SC HDB, CA de l’asso FDE, Plénière, GT, etc…) ;
 - Porter l’ensemble des éléments importants discutés en commission mais ne faisant pas l’objet de propositions  dans le point information de chaque plénière ;
 - Assurer une transparence des échanges grâce à l’envoi de tous les comptes rendus sur la page du wiki prévue à cet effet.
</span>""
```

Il est normal que les tirets ne soient pas interprétés, tout ce qui est entre "" et "" n'est pas interprété.
