### ISSUE TITLE
En mode intégré ( /iframe ) on ne peut pas modifier les pages

### ISSUE THREAD

**Issue by matcho** [YesWiki/yeswiki#257]
Salut,

Il semble qu'en mode /iframe, on ne puisse pas éditer les pages, pas en double-cliquant dedans en tout cas.
Pourtant ce serait super de pouvoir éditer en mode intégré ! On pourrait imaginer le template d'édition classique, sans les décorations.

Certes en mode intégré le menu de connexion est masqué. Pour les wiki dont le droit d'édition est restreint, ça ne changerait rien : si on n'est pas identifié, on ne peut pas éditer; pour les wiki publics par contre (ou pour lesquels l'utilisateur s'est identifié par un autre moyen), ça permettrait d'éditer et ce serait bien cool.

Qu'en dites-vous ?

Amicalement,
Mathias (Tela Botanica)

**Comment by mrflos** [comment]
Merci pedobear (lol) pour cette proposition de feature!  
Dis moi si je peux t'aider a l'implémenter.

**Comment by mrflos** [comment]
l’édition dans une iframe est désormais possible (handler /editiframe)
