### ISSUE TITLE
facette compatible avec calendrier

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#264]
priorité 1 : désir de pouvoir utiliser facette avec calendrier mais aussi de pouvoir mettre une couleur en fonction d'une catégorie
priorité 2 : exporter du flux ical
priorité 3 : insérer et afficher un flux ical

**Comment by mrflos** [comment]
priorité 1 possible, pour les 2 autres, je propose de fermer pour l'instant et de créer des issues séparées quand on aura testé le bazar semantique
