### ISSUE TITLE
non affichage des glyphes-icônes

### ISSUE THREAD

**Issue by ya3B** [YesWiki/yeswiki#278]
Bonjour !
Je ne parviens pas à insérer de glyphes-icônes dans mes pages yeswiki Cercopithèque avec du code html.
Le problème semble être aussi présent dans la page de documentation, où les exemples n'apparaissent pas : https://yeswiki.net/wakka.php?wiki=Bootstrap232glyphes#

**Comment by mrflos** [comment]
Yeswiki est basé maintenant sur bootstrap 3, et les icones ont changé de nom, voir https://getbootstrap.com/docs/3.3/components/
