### ISSUE TITLE
Templates bazar

### ISSUE THREAD

**Issue by fodevaux** [YesWiki/yeswiki#279]
Où trouver les différents templates bazar (ex:material-card.tpl.html) ?
La doc ou le site n'en parle pas, il me semble.
Merci !

**Comment by fbredow** [comment]
Bonjour, pour obtenir de l'aide sur l'usage de YesWiki la mailing list est plus adaptée (infos@yeswiki.net)

**Comment by fodevaux** [comment]
Parfait, merci !
