### ISSUE TITLE
Le menu de certains thèmes se referme directement sur un petit écran

### ISSUE THREAD

**Issue by fodevaux** [YesWiki/yeswiki#280]
Sur un petit écran (smarphone), le menu de certains thèmes se referme directement. Pas possible donc de naviguer sur de tels sites. Ex: http://wiki.transistore.be (à tester sur smartphone)

**Comment by fbredow** [comment]
Bonjour, est il possible de donner la liste des thèmes affectés ?

**Comment by fodevaux** [comment]
Bonjour,
Il s'agit de "amelia.bootstrap.css"  squelette "1col.tpl.html"

François-Olivier Devaux  |  *+32 (0)485/022.950*  |  fodevaux@gmail.com

2017-01-18 16:29 GMT+01:00 Florestan Bredow <notifications@github.com>:

**Comment by mrflos** [comment]
Bonjour, il faut passer au theme bootstrap3 , qui possede aussi le style amalia, sans les bugs!
