### ISSUE TITLE
Repenser la conservation des pages/versions

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#281]
Actuellement les versions supplémentaires de pages sont supprimées si elles ont plus de 90j. Même si cette valeur est paramétrable ce n'est pas satisfaisant.

Trouver une solution plus pérenne (conserver a minima les X dernières et supprimer les autres si elles ont plus de Y jours par exemple. Changer le comportement par défaut et tout garder ?)

A discuter avec les usagers.
(la branche refactoring ne supprime actuellement plus aucune ancienne version)

**Comment by mrflos** [comment]
Hello, pour garder trace de ma pensée :+1: pour changer le comportement par défaut sur tout conserver, et un paramétrage possible dans le fichier de configuration sur la date et/ou le nombre de versions.

Dans un monde idéal, ca serait top de tout garder, mais de concentrer les modifications : garder un changement par mois qui contient toutes les modifications du mois, par exemple (je pense que c'est chaud a programmer, mais c'est juste de la tempête de cerveau).

**Comment by mrflos** [comment]
le paramètre `pages_purge_time` permet de changer le comportement, il est à 365 jours par défaut.
