### ISSUE TITLE
[BazaR] Action Copier/Coller un Formulaire

### ISSUE THREAD

**Issue by Rom1deTroyes** [YesWiki/yeswiki#282]
Pour gagner du temps, avoir la possibilité de Copier/Coller un formulaire éviterai d'avoir à copier/coller chaque champ séparément.

**Comment by mrflos** [comment]
Est ce que un bouton cloner dans l'interface des formulaires résoudrait ce problème?

**Comment by mrflos** [comment]
pour doryphore derniere version ya un bouton dupliquer le formulaire
