### ISSUE TITLE
[BazaR] Importer et Renommer

### ISSUE THREAD

**Issue by Rom1deTroyes** [YesWiki/yeswiki#283]
Si on importe un Formulaire qui existe déjà depuis un autre YesWiki, on a un avertissement : 
> Attention, cet identifiant et le titre de ce formulaire existent déja, si vous le sélectionnez, il sera écrasé.

Pouvoir changer l'ID/Titre permettrai de l'importer sans écraser ce qui existe.

Au passage, en important/renommant un Formulaire de son propre site, on peut faire un copier/coller (cf issue #282 !)

**Comment by mrflos** [comment]
bonne idée, je labellise en feature!
