### ISSUE TITLE
[BazaR] Widget : Code action wiki {\{

### ISSUE THREAD

**Issue by Rom1deTroyes** [YesWiki/yeswiki#284]
Quand on veut créer un Widget depuis un Formulaire du BazaR, et qu'on veut récupérer le code YesWiki pour l'afficher, celui-ci commence par `{\{` et finit par `}\}` (au lieu de `{{` et `}}`)

> Code action wiki a copier coller dans une page de ce site
> `{\{bazarliste id="1" width="100%" height="600px" template="liste_accordeon.tpl.html" provider="OpenStreetMap.Mapnik" groups=""}\}`

Du coup, il faut le ré-éditer.

YesWiki tout frais, version cercopithèque Git (commit e7ce2ce) hébergé sur du mutualisé OVH.
Mozilla FireFox 45.6.0 / Debian Jessie

**Comment by mrflos** [comment]
c'est corrigé sur la branche cercopitheque_dev, si tu peux tester, je peux par la suite le mettre a disposition sur la branche stable. Merci!
