### ISSUE TITLE
[BazaR] Les formulaires dont l'id vaut zéro provoque des affichages de résultats vides

### ISSUE THREAD

**Issue by nylnook** [YesWiki/yeswiki#288]
Salut à tous, et bravo pour votre immense travail sur Yeswiki !

Je débute dans Yeswiki, et mon premier formulaire (importé) avait une "id=0"... à l'affiche des résultats avec "bazarliste", ou avec "calendrier" (voir aussi le bug #263), ils ne s'affichent pas toujours (notament pour le calendrier).
Nicolas Geiger (formateur Animacoop et Yeswiki à Gap), me signale que c'est récurrent.
Avec une id=1 ou plus, tout fonctionne correctement.

je m'excuse de ne pas être plus précis dans mon rapport...

**Comment by mrflos** [comment]
Merci du retour, la version de développement corrige le problème en empêchant la création de modèles avec 0 comme id. 
Si vous souhaitez la tester, elle est disponible ici https://github.com/YesWiki/yeswiki/archive/cercopitheque_dev.zip
