### ISSUE TITLE
Les wikis créés dans des ferme à wiki ont des flux RSS invalides

### ISSUE THREAD

**Issue by nylnook** [YesWiki/yeswiki#289]
Re-bonjour,

il semble que les wikis créés dans des fermes ne produisent pas de flux RSS valides... par exemple http://ferme.animacoop.net/wikis/formawiki/wakka.php?wiki=DerniersChangementsRSS/xml

`Erreur d’analyse XML : aucun élément trouvé
Emplacement : http://ferme.animacoop.net/wikis/formawiki/wakka.php?wiki=DerniersChangementsRSS/xml
Numéro de ligne 1, Colonne 39 :<?xml version="1.0" encoding="UTF-8"?>
--------------------------------------^`

dans un wiki indépendant et seul, cela fonctionne.

Merci encore

**Comment by fbredow** [comment]
Bonjour, ce problème n'est pas lié à YesWiki mais à la version de YesWiki utilisée dans cette ferme. Il faut contacter l'administrateur de cette ferme pour qu'il mette à jour la ferme et les wikis.

**Comment by nylnook** [comment]
Ok, mes excuses pour la fausse alerte !
