### ISSUE TITLE
[Attach] Limiter la longueur des noms de fichier

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#290]
Les fichiers qui ont un nom de plus de 100 caractères ne peuvent être archivés dans un fichier Tar. C'est un format très utilisé pour les sauvegardes et cela peut poser problème.

**Comment by mrflos** [comment]
Pas le temps de faire cela, et pas une priorité, du coup je le bloque, mais toute pull request sera regardée avec intérêt!

**Comment by fbredow** [comment]
Pourquoi ne pas le laisser ouvert dans la catégorie "fonctionnalités" ? En plus pas une priorité ? alors que cela peut avoir des effets de bord sur des systèmes de sauvegarde ou lors de copie ? Sans compter la difficulté a retrouver ses petits dans cette liste interminable de fichiers qui font un concours a celui qui a le plus long ? ;)

Bon ok c'est pas le truc le plus urgent, mais je ne pense pas qu'on puisse le ranger sous le tapis pour autant :p

**Comment by mrflos** [comment]
Je pense que tu sais très bien que peu de devs participent au développement de YesWiki, pour ma part je me concentre sur d'autres taches, si pour plus de visibilité tu préfères laisser l'issue ouverte, je suis ok pour cela, mais elle restera avec le statut bloqué. Si cela te semble important pour tes besoins de backup, n'hésites pas a contribuer plutôt que de faire la liste exhaustive des choses qui ne te vont pas.

**Comment by gatienbataille** [comment]
sujet plus d'actualité
