### ISSUE TITLE
{{bazarcarto}} doesn't work

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#291]
Action {{bazacarto}} doesn't work. We have to use {{bazarliste id="12" template="map.tpl.html"}} but documentation say "use {{basacarto}}".

I don't know if the problem comes from the doc or if it's a bug. 

En français : l'action bazarcarto ne marche pas, on doit passer par un template de bazarlist pour le faire fonctionner. Je ne sais pas bien si c'est la doc qui n'est pas à jour, ou si c'est un bug à résoudre. Dans tous les cas si ce n'est pas fixer ce serait top de mettre l'action qui fonctionne dans la doc en attendant mais je n'ai pas les droits de mdif sur yeswiki.net

Romain

**Comment by mrflos** [comment]
Saint Cloud Béret Basque for the repport of the issue. 😄 

This bug is no more present in the developpement branch , https://github.com/YesWiki/yeswiki/archive/cercopitheque_dev.zip we will release as soon as possible.

Best regards
