### ISSUE TITLE
Cartogoogle - probleme de crédits fond de carte

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#292]
Bonjour,
Lors de la saisie d'un formulaire, le fond de carte pour placer géographiquement une saisie ne crédite plus le fond de carte (c'était bien le cas avant) et n'apparaît en bas à droite de la carte que le lien vers leaflet.
![capture du 2017-07-06 12 06 19](https://user-images.githubusercontent.com/12220999/27906430-c658b876-6243-11e7-94ea-9cb3f8568d5d.png)

**Comment by mrflos** [comment]
c'est corrigé
