### ISSUE TITLE
conflit entre image et fichier dans les fiches bazar

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#293]
texte***bf_titre***Titre***60***255*** *** *** ***1***0*** 
image***bf_image***image***140***140***600***600*** ***0*** *** *** 
fichier***piecejointe***piece jointe ***8000000*** *** *** *** ***0*** ***ne pas dépasser 8 Mo

dans ce type de formulaire, la fonction image ne fonctionnera pas, pas d'upload possible. dès que la ligne fichier est enlevée, tout fonctionne.

visiblement ça correspond à https://yeswiki.net/forum/593/les-images-de-mon-formulaire-ne-sont-pas-prises-en-compte?show=593#q593

amitiés

**Comment by mrflos** [comment]
corrigé sur la branche dev
