### ISSUE TITLE
Replier les champs de tri

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#294]
Hello,
La commande pour replier d'origine les champs de tri lors de l'affichage de fiches bazar ne semble pas fonctionner.
groupexpanded="false" ou groupexpanded="true" ou groupexpanded="False" ou groupexpanded="True" ne modifie pas les champs de tri qui restent d'origine déroulés.
Romain

**Comment by mrflos** [comment]
Salut @RomainLalande 
T'as essayé group**s**expanded="true" plutôt que groupexpanded="true" ?

**Comment by RomainLalande** [comment]
Ah oui il manquait un "s" ! Et pour replier j'ai mis false et ça fonctionne, merci :-)

**Comment by mrflos** [comment]
Cool! je ferme donc l'issue, merci du test!

**Comment by RomainLalande** [comment]
Du coup il faudrait modifier la doc sur cette page : https://yeswiki.net/wakka.php?wiki=BazarFacette   
Et sur cette page : https://yeswiki.net/wakka.php?wiki=BazarFacetteRecherche
Je ne peux pas le faire (pas les droits) - mon nom de compte : RomainLalande
@mrflos

**Comment by mrflos** [comment]
Je t'ai donné un accès admin au site, puis je te mettre a contribution pour modifier la doc sur ce sujet?
Merci d'avance

**Comment by RomainLalande** [comment]
@mrflos super merci ! C'est modifié :)
