### ISSUE TITLE
Problème avec le mode 'STRICT_TRANS_TABLES' de mariadb

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#296]
Si le mode 'STRICT_TRANS_TABLES' est actif (comportement par défaut des dernières versions de mariadb) 

Comportement attendu : Enregistrement de la page

Ce qui se passe : Lors de l’édition d'une page une erreur SQL apparaît faisant remarquer que la colonne 'body_r' de la table 'pages' n'a pas de valeur par défaut. Le contenu de la page est alors supprimé.

Solutions : 
 - Supprimer la colonne 'body_r' qui ne semble pas utilisée.
 - Donner une valeur par défaut à la colonne. (soit lors de la création de la table, soit pour chaque requête créant/modifiant une page)

**Comment by mrflos** [comment]
Hello @daiko cool de te voir par ici!  
Je ne sais pas ce qui est le mieux, la première est sans doute la plus efficace, mais ne change rien aux wikis déjà installés, la deuxième semble plus longue a implémenter..

**Comment by mrflos** [comment]
Ok fait sur cercopitheque_dev la methode SavePage() mettait déjà une valeur vide, seul à l'installation il n'y avait pas de valeur par défaut.
