### ISSUE TITLE
écran blanc avec lostpassword (cerco-dev)

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#297]
testé sur plusieurs wiki sous cerco-dev / lostpassword fonctionne MAIS renvoie un écran blanc.
voir sur yeswiki.net par exemple

**Comment by mrflos** [comment]
Il s'agit d'une page non créée : MotDePassePerdu avec dedans `{{lostpassword}}`
Je l'ai mis dans yeswiki.net a la main.

Il faudrait tester l’installation de zero pour voir si la page se créé bien, normalement oui
