### ISSUE TITLE
iframe de la ferme vers un autre wiki marche pas

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#298]
lorsque l'on essaie de faire un iframe d'une page d'un wiki venant de la ferme vers un wiki hors de la ferme, ça fonctionne pas

**Comment by mrflos** [comment]
Tu as regardé si c'est pas une histoire de d'inclusion d'iframe http dans du https ?  
Regardes la console du navigateur dans les outils de developpements
