### ISSUE TITLE
pb pour faire gérer les droits

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#300]
http://lped.info
à priori dernière cerco_dev
impossible de bouger les droits dans une page, quand je clique sur Enregistrer
je reviens sur l'écran d'origine avec des étoiles partout

**Comment by mrflos** [comment]
Corrigé dans la dernière release de cerce_dev http://repository.yeswiki.net/cercopitheque_dev/yeswiki-cercopitheque_dev-2017-09-22-39.zip <http://repository.yeswiki.net/cercopitheque_dev/yeswiki-cercopitheque_dev-2017-09-22-39.zip>
Pourrais tu tester et fermer l’issue si ca marche?

**Comment by furax37** [comment]
alors, visiblement les droits de la page sont bien pris en charge, par contre, quand je re clique sur permissions, ça ne correspond pas. 
Dans GererDroits, ça ne correspond pas
Je peux changer les droits dans GererDroits et là ça fonctionne

**Comment by furax37** [comment]
problème mieux cerné mais toujours persistant malgré mise à jour, à mon avis problème grave et urgent 
Quand je met les éléments dans la case droits d'écriture, ça enregistre les éléments dans droits de lecture et ça met un blanc dans droits d'écriture...
bref ça décale les droits... warning

**Comment by mrflos** [comment]
Peux tu voir encore avec la derniere version sur repository?
