### ISSUE TITLE
Faire le ménage dans les extensions et themes, et s'assurer que l'auto-update fonctionne

### ISSUE THREAD

**Issue by mrflos** [YesWiki/yeswiki#302]
L'outil de mise a jour automatique va être intégré par défaut, il faut vérifier que tout fonctionne comme prévu.

**Comment by J9rem** [comment]
Bon a priori, c'est bon pour cette fonctionnalité non ?
Pouvons-nous la clore ?

**Comment by mrflos** [comment]
yes!
