### ISSUE TITLE
concaténation dans titre fiche bzar

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#303]
retour du forum, bug confirmé de mon côté

Notamment avec Bazar, car quand je crée des fiches, celles-ci portent toutes un nom genre "BfNomBfPrenom". J'utilise le système de concaténation de champs pour le titre, le titre est bon une fois la fiche créée, mais j'ai l'impression que cela pose un problème au niveau du nom. Où je ne fais pas ce qu'il faut, auquel cas, j'espère que vous pourrez m'aider !

Exemple de mon formulaire :

titre***{{bf_nom}} à {{bf_ville}}*** ***
texte***bf_nom***Nom de l'événement***60***255*** *** *** ***1***0*** 
texte***bf_ville***Ville***60***255*** *** *** ***1***0***
Qui me donne donc des événements avec des pages nommées BfNomABfVille(1, 2, 3 ou 4 etc...)

**Comment by mrflos** [comment]
corrigé depuis le temps!
