### ISSUE TITLE
Iframe montre l'ensemble du wiki (menu, bandeau...)

### ISSUE THREAD

**Issue by geigerni** [YesWiki/yeswiki#304]
La version Yeswiki_Dev a un petit bug : lorsqu'on met une page en Iframe dans un site (genre wordpress), elle s'intègre parfaitement. Mais dès qu'on fait une action sur cette page (validation formulaire Bazar, clic sur un lien interne etc...), ça fait apparaître l'ensemble du wiki, avec la bandeau, le menu etc...
Ce n'était pas le cas avant et c'était mieux :-)

Iframe dans Wordpress avant action
![capture du 2017-10-09 14-00-28](https://user-images.githubusercontent.com/26959048/31356538-a9baab98-ad3e-11e7-987e-a6fb143ff834.png)

Iframe dans Wordpress #après action
![capture du 2017-10-09 14-01-13](https://user-images.githubusercontent.com/26959048/31337528-021556f0-acfc-11e7-960d-4191f0989f54.png)

**Comment by mrflos** [comment]
Ok, problème sérieux..
C'est que sur les interactions avec des fiches bazar ou sur tous les passages d’édition à consultation?

**Comment by geigerni** [comment]
Oups, 1er capture écran était pas la bonne, sorry.

Pour te répondre, ça se produit après toute interaction dans la page, y compris un simple clic sur URL. Si tu veux te rendre compte par toi-même, je l'ai laissé actif ici : http://www.collecti.cc/test-iframe-yeswiki/

**Comment by geigerni** [comment]
OK, j'ai corrigé la page de test sous wordpress :  http://www.collecti.cc/test-iframe-yeswiki/
Résultats : 
- le clic vers page interne au même wiki (ce wiki n'étant pas la version de Dev je crois) = OK 
- le clic vers wiki version Dev = PB
- action sur formulaire bazar = PB

**Comment by mrflos** [comment]
corrigé recemment
