### ISSUE TITLE
problèmes de fichiers .pub qui ne passent pas dans bazar

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#305]
Par contre avec attach, ça fonctionne bien...

Quand on veut mettre des docs en base de données. Voir :
https://ferme.yeswiki.net/wikis/GuideBrl/wakka.php?wiki=ConsulPres
 
La fiche Agroécologie apparait, mais pas le fichier. Par contre si on met un PDF, ca marche.

**Comment by mrflos** [comment]
Oui c'est confirmé..  
Il y a une liste de type de fichiers autorisés et .pub n'est pas dedans:  
cf. https://github.com/YesWiki/yeswiki/blob/cercopitheque_dev/tools/bazar/libs/bazar.fonct.misc.php#L207  

On pourrait le rajouter si besoin, qu'en penses tu?
