### ISSUE TITLE
Petits bug bazar formulaire

### ISSUE THREAD

**Issue by mrflos** [YesWiki/yeswiki#306]
1) le message "Votre fiche a bien ete saisie" n'apparait plus
 2) les cases a cocher a saisir obligatoirement ne sont pas controlees
 3) le parametre barregestion ne marche pas

**Comment by J9rem** [comment]
@mrflos toujours d'actualité cette issue ?

**Comment by mrflos** [comment]
c'etait un memo lors d'un sprint, je clos
