### ISSUE TITLE
Ajouter un image fait planter la page

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#308]
Après avoir ajouté une image, ce message d'erreur apparaît a la place de la page : 

`Fatal error: Uncaught Error: Call to undefined function imagecreatefromjpeg() in /var/www/html/wiki/tools/attach/libs/class.imagetransform.php:303 Stack trace: #0 /var/www/html/wiki/tools/attach/libs/class.imagetransform.php(489): imageTransform->create_image_from_source_file() #1 /var/www/html/wiki/tools/attach/actions/attach.class.php(1072): imageTransform->resize() #2 /var/www/html/wiki/tools/attach/actions/attach.class.php(447): attach->redimensionner_image('files/ArduinO_A...', 'files/ArduinO_A...', 209, 209) #3 /var/www/html/wiki/tools/attach/actions/attach.class.php(578): attach->showAsImage('files/ArduinO_A...') #4 /var/www/html/wiki/tools/attach/actions/attach.php(125): attach->doAttach() #5 /var/www/html/wiki/tools/prepend.php(78): require('/var/www/html/w...') #6 /var/www/html/wiki/wakka.php(1272): WikiTools->IncludeBuffered('attach.php', '<div class="ale...', Array, 'tools/toolsmng/...') #7 /var/www/html/wiki/formatters/wakka.php(393): Wiki->Action('attach') #8 [internal function]: WikiniFormatter->callback(Ar in /var/www/html/wiki/tools/attach/libs/class.imagetransform.php on line 303`

[Image qui pose problème.](https://daiko.fr/Arduino.jpg)

La version utilisée est la toute dernière de YesWiki ce jour (git pull sur la branche cercopitheque)

**Comment by mrflos** [comment]
Il doit manquer l'extension php qui gere GD si l'erreur est `Call to undefined function imagecreatefromjpeg()`

**Comment by fbredow** [comment]
GD est installé et cela fonctionne une fois l'image convertie en PNG.

**Comment by mrflos** [comment]
pas reproductible ni ici https://ferme.yeswiki.net/wikis/TestSo/wakka.php?wiki=PagePrincipale ni la https://yeswiki.net/wakka.php?wiki=BacASable avec l'image en question.

**Comment by fbredow** [comment]
Autant pour moi, GD était compilé sans le support JPEG.
Merci.
