### ISSUE TITLE
[bazar] Flux RSS n'affiche pas les modifications dans l'ordre antechronologique

### ISSUE THREAD

**Issue by LudovicParenty** [YesWiki/yeswiki#311]

**Comment by mrflos** [comment]
il me semble que c'est resolu, tu confirmes @LudovicParenty ?

**Comment by LudovicParenty** [comment]
Oui, de ce que je vois, c'est dans le bon ordre, par contre, je ne saisie pas pourquoi j'ai une différence entre DerniersChangements et DerniersChangements/rss (sur ce dernier, il n'y a pas toutes les modifications, loin de là).  Exemple : https://www.coordinaction.net/?DerniersChangements (je me fais spammer d'ailleurs...)
Et je ne suis pas sûr que l'inscription à la syndication fonctionne bien (avec Thunderbird, je n'y arrive pas mais c'est peut-être moi qui ne sais pas bien faire...), ça marche sur firefox par contre.

**Comment by mrflos** [comment]
@LudovicParenty pourrais tu confirmer que https://www.coordinaction.net/?DerniersChangementsRss/xml fonctionne (c'est la veritable url du flux rss general, /rss concernant que bazar)

**Comment by LudovicParenty** [comment]
@mrflos  Oui, ça marche quand on utilise la bonne URL !
J'arrive à intégrer dans thunderbird, c'est top !

Juste, en utilisant le widget, ça n'a pas l'air de marcher (pas toutes les modifs y compris de bazar), mais bon, c'est plus accessoire...

**Comment by gatienbataille** [comment]
plus d'actu avec nouvelle version
