### ISSUE TITLE
Paramètre ebook generator addinstalledpage

### ISSUE THREAD

**Issue by GDoukhan** [YesWiki/yeswiki#312]
Le paramètre addinstalledpage devrait permettre d'afficher ou non dans la liste des pages proposées à la génération de l'ebook les pages par défaut du wiki (menus et autres).
La valeur par défaut est 0 et là tout va bien, les pages par défaut ne sont pas affichées.
Si on ajoute addinstalledpage="1" plus aucune page n'apparait dans la liste des pages pour l'Ebook

**Comment by mrflos** [comment]
je ferme, je pense qu'il faut ouvrir dans l'extension publication une issue, mais il me semble que le soucis est réglé
