### ISSUE TITLE
URL raccourcie

### ISSUE THREAD

**Issue by geigerni** [YesWiki/yeswiki#313]
Exemple https://yeswiki.net/?TacheS

Je propose de l'ajouter en lien dans l'encadré "Installer, configurer et mettre à jour", à la racine de https://yeswiki.net/?DocumentatioN (...mais vous pouvez ne pas être d'accord sur cet emplacement ?)
:-)

**Comment by mrflos** [comment]
Il y a déjà un champs url courte qui présente les solutions pour carrément tout cacher avec un htaccess ou une règle nginx alors qu'en effet, par défaut sans avoir a toucher au serveur, on peut réécrire dans le fichier `wakka.config.php` le parametre `base_url` pour que seul reste a la fin le point d'interrogation.
