### ISSUE TITLE
Champ "Listefiches" qui appelle les fiches d'un wiki externe 

### ISSUE THREAD

**Issue by geigerni** [YesWiki/yeswiki#314]

**Comment by J9rem** [comment]
Il y a une documentation ici : https://yeswiki.net/?LierFormulairesEntreEux
@geigerni est-ce suffisant ?

**Comment by geigerni** [comment]
étant donné que je ne me souviens plus exactement de pourquoi j'avais mis ce ticket à l'époque, et que je vois en effet que la doc semble complète... on peut clore ce sujet !
