### ISSUE TITLE
Vérifier que tous les champs du "formulaire de la mort" soient bien documentées

### ISSUE THREAD

**Issue by geigerni** [YesWiki/yeswiki#317]
Dans ce formulaire ( https://cocotier.xyz/wikidev/?FormulaireDeLaMort ), tous les champs possibles y sont, mais tous ne sont pas bien documentés.
A mettre à jour ici donc : https://yeswiki.net/?FormulaireSoimeme

**Comment by gatienbataille** [comment]
plus d'actualité suite au bazar form builder
