### ISSUE TITLE
réactiver la fonction cartogoole des formulaires sur base de coordo GPS

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#320]
Cela fait plusieurs fois qu'on me demande de pouvoir utiliser la fonction cartogoogle des formulaires sur base de coordo GPS plutôt que sur base d'une adresse. Ces demandes émanent surtout des gestionnaires de terrain (parcs naturels et contrat rivière) pour qui il est compliqué de déposer un point sur base d'une adresse (en pleine forêt par ex). 
Il semble que cette fonction existait avant et a été désactivée notamment suite des "soucis" de type de coordo GPS. 
Serait-il enviseagble de réactiver cette fonctionnalité, même restreinte (un type de coordo gps et puis c'est tout) ? 
je veux bien documenter et tester le tout mais je ne sais par contre réactiver

**Comment by mrflos** [comment]
normalement c'est dans la version de prod du jour, je te laisse verifier

**Comment by mrflos** [comment]
@gatienbataille je clos l'issue car tu m'as confirmé que ca marchait
