### ISSUE TITLE
img responsive par défaut sur image est non fonctionnel sous internet explorer

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#321]
Il semble que le responisve par défaut placé sur les images que l'on attache dans la wiki soit non fonctionnel pour IE. 
La même page avec 4 colonnes et des images dans les colonnes est OK sous chrome et firefox et non ok sur IE.
EX : http://galpaysdeherve.be/?CitoyennetE

**Comment by gatienbataille** [comment]
je sais que IE ne respecte pas les standards du web 
mais bon, il reste quand même un beau paquet d'irréductibles qui l'utilise... 
parfois par obligation dans leur structure...

**Comment by mrflos** [comment]
as tu pu tester si cela ne venait pas de la classe zoom?

**Comment by mrflos** [comment]
plus personne ne supporte IE, même microsoft, donc je ferme
