### ISSUE TITLE
Le paramètre debug ne doit pas bloquer l'affichage des erreurs dans les logs

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#325]
Actuellement, si debug est à 'no' dans wakka.config.php plus aucune erreur n’apparaît dans les logs. Ce fonctionnement est contre-intuitif et non documenté (D'après la documentation :  "active le mode de débogage si passé à la valeur 'yes' (infos sur le nombre de requêtes et temps écoulé, pour les développeurs).")
Il me semble très important que l'administrateur du serveur puisse choisir les erreurs apparaissant dans les logs. 

Cela impacte aussi l'affichage des messages d'erreur sur les pages. Là aussi c'est un paramétrage qui doit se faire au niveau du serveur, le forcer est contre productif.

**Comment by mrflos** [comment]
Ok, je ne vais forcer l'affichage que dans le cas ou le mode debug est actif, et laisser la config serveur par defaut pour le no.

Merci du feedback <3

**Comment by mrflos** [comment]
fait pour la branche dev et prod

**Comment by fbredow** [comment]
Merci. :)
