### ISSUE TITLE
[bazar] Failed opening required 'Pager/Pager.php' 

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#326]
Le message complet :  
`Fatal error: require_once(): Failed opening required 'Pager/Pager.php' (include_path='.:/usr/share/php') in /var/www/XXXXXXXXX/tools/bazar/libs/bazar.fonct.php on line 3707`

Après mise a jour d'un site en prod avec la branche cercopitheque.
Il y a un appel a bazarcarto dans la page.

**Comment by fbredow** [comment]
Juste pour préciser, le soucis apparaît dès que l'on fait appel au paramètre pagination.

**Comment by mrflos** [comment]
fixed, même si la pagination par bibliothèque pear sera dépréciée en faveur d'une solution en javascript compatible avec les facettes.
