### ISSUE TITLE
[Contact] cliquer sur envoyer n'a pas d'effet

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#327]
La validation d'un formulaire contact n'a aucun effet, et le message d'erreur suivant apparaît dans les logs : 

> AH01071: Got error 'PHP message: PHP Fatal error:  Cannot redeclare send_mail() (previously declared in /var/www/XXXXXXXXXXXXXX/includes/email.inc.php:12) in /var/www/XXXXXXXXXXXXXX/tools/contact/libs/contact.functions.php on line 165\n', referer: https://XXXXXXXXXXXXXX/?ParametresUtilisateur

La version utilisée est celle de la branche master.

**Comment by mrflos** [comment]
je pense que tu as un autre problème que juste la fonction en double, car cela ne devrait pas impacter le bon déroulement de l'envoi de mail, ca marche sur d'autres sites, et le send_mail est executé apres les tests de validation. Ceci dit, le dernier commit sur dev et master corrige le soucis cf. https://github.com/YesWiki/yeswiki/commit/2cf3962652b3902a648583742d0b9682863ddf72

**Comment by fbredow** [comment]
Effectivement, j'ai dû aussi modifier mon template qui fonctionnait avant. (ajout de la classe ajax-mail-form à la balise "form").
