### ISSUE TITLE
[contact] L'action contact ne fonctionne pas dans un template (fonctionne uniquement si utilisée dans une page)

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#328]
Ajout dans la page de "{{contact mail="contact@monprojet.eu"}}". 
Le formulaire apparaît correctement mais à la validation de celui ci j'obtiens le message d'erreur : "Vous devez entrer une adresse mail pour le destinataire." 
Les données saisies sont dans l'ordre : "Daiko", "daiko@daiko.fr", "message de test", et "sdfEQSDQSDQSDQSDQSDQS"

Ce n'est pas un problème de configuration du serveur, les mails pour retrouver un mot de passe partent bien. (testé sur serveur en prod, et environnement de développement)

**Comment by mrflos** [comment]
N'est ce pas un problème avec ton template spécifique? Est il bien comme celui par défaut https://github.com/YesWiki/yeswiki/blob/cercopitheque/tools/contact/presentation/templates/complete-contact-form.tpl.html


en particulier sur les champs cachés
```
<input type="hidden" name="nbactionmail" value="<?php echo $nbactionmail; ?>" />
<input type="hidden" name="entete" value="<?php echo $entete; ?>" />
<input type="hidden" name="type" value="contact" />
```

**Comment by fbredow** [comment]
{{contact mail="contact@monprojet.eu"}} <-- pas de template spécifié et les trois champs cachés apparaissent bien dans le html de la page.

**Comment by mrflos** [comment]
Cela fonctionne chez moi avec la version de dev et la master, avec tes données saisies, juste en mettant {{contact mail="contact@colibris-outilslibres.org"}}
 Verifies que les les fonctions de tools/contact/libs sont a jour , ainsi que tools/contact/handlers/page/mail.php

**Comment by fbredow** [comment]
Après test complémentaire, le problème apparaît lorsque  l'action contact est appelé dans le squelette du thème. Si je l'appelle dans la page, ça fonctionne.
C'est nouveau, l'année dernière cela fonctionnait lorsque j'ai mis en ligne ce site.
Les fichiers indiqués sont bien à jour.

**Comment by mrflos** [comment]
les actions contact et autres liées aux mails cachent l'email destinataire lors de l'appel ajax, et le handler /mail scannent le contenu de la page pour trouver la correspondance. Donc cela n'est plus possible de mettre des actions relatives aux mails dans le theme, faut passer par une action {{include page="ContactMail"}} dans le theme pour que cela refonctionne.  
Si tu voies une solution qui n'affiche pas le mail destinataire lors de l'appel du handler, pull request welcome!

**Comment by fbredow** [comment]
C'est triste. D'une part cela créé une exception. D'autres part ça casse des cas d'utilisation sans prévenir.
Surtout qu'un simple appel a l'handler raw permet de récupérer le mail destinataire.

**Comment by mrflos** [comment]
oui c'est super triste, mais pas le temps de revenir dessus présentement.

**Comment by mrflos** [comment]
corrige sur la version dev
