### ISSUE TITLE
Supprimer les !important dans les CSS

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#332]
De nombreuses occurrences de !important existent un peu partout dans le code css (noyau et extensions).
Elles limitent certaines personnalisations dans les thèmes et il est ~~impossible~~ difficile de les contourner.

A la lecture, j'ai l'impression que c'est souvent pour écraser des propriétés CSS issues de Bootstrap. Une solution serait de charger bootstrap.css en premier pour ne plus avoir besoin de mettre des !important. 

C'est pratique pour résoudre rapidement un soucis mais a long terme cela engendre encore plus de soucis.

(Exemple : Mon point de blocage actuel : la ligne 85 "margin: 0 18px 18px 0 !important;" dans tools/attach/presentation/styles/attach.css cela concerne les images ajoutées avec attach)

**Comment by mrflos** [comment]
J'ai enlevé les !important sur les alignements d'image sur la dev, ils ne semblent pas interférer avec les déclarations bootstrap.
Pour info, même si ce n'est pas une bonne pratique, il est possible de surclasser les déclarations avec !important en utilisant des sélecteurs plus forts, comme ceux sur les id sur les conteneurs : 
`#mon-id .attached_file.attach_left, #mon-id .attached_file.left {margin: 50px 30px !important; }`
