### ISSUE TITLE
Problèmes d'accents persistants (tables déjà en utf8)

### ISSUE THREAD

**Issue by LudovicParenty** [YesWiki/yeswiki#333]
Les problèmes d'accents n'apparaissent pas systématiquement :

Exemple :
https://www.coordinaction.net/?AuClairDuQuartier/
https://www.coordinaction.net/?VoirtemoignagesRNHP  (template accordéon : Au clair du quartier)

**Comment by mrflos** [comment]
Corrigé sur la version du 3 mai
