### ISSUE TITLE
Caractères "grecs" remplacé par des ??

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#334]
Lorsque j'édite une page, et que je saisie des caractères "grecs" ceux-ci sont remplacés par des points d'interrogation lors de l'enregistrement.
Exemple de texte : "Ένα Ευρωπαϊκό δίκτυο για την επιμόρφωση των φορέων της Εκπαίδευσης για το Περιβάλλον και την Αειφόρο Ανάπτυξη, με στόχο τη στήριξη των δράσεων της κοινωνίας πολιτών προς την οικολογική μετάβαση και την αειφορία."

Ces caractères s'affichent normalement si affiché sans passer par la base de données (ex : template). (dans la base de données c'est des choses comme : "Î¤Î± Î½Î­Î± Î¼Î±Ï‚" qui apparaissent).

Je ne suis pas sûre de moi, mais il me semble avoir testé l'année dernière avant de commencer ce site et à ce moment cela fonctionnait.

**Comment by mrflos** [comment]
Si le wiki est assez ancien, les tables sont en latin1, et donc cela ne marchera pas.

En installant un nouveau wiki, tu auras les bases en utf8_unicode et cela marchera.
Sinon, apres avoir fait un backup, tu peux mettre a jour ton wiki et faire le handler /dbutf8 , qui passe les tables en utf8_unicode et ajoute le dbcharset utf8mb4 au fichier de configuration.
Par contre je ne suis pas sur que la conversion des textes existants avec des caractères spéciaux se passe toujours a la perfection, donc bien sauver la db avant.

**Comment by fbredow** [comment]
Ça fonctionne (la migration s'est passée sans soucis). Peut être est il nécessaire de communiquer sur cette info, pour les gens utilisant des wikis dans une langue autre que le français ça peut faire des blagues.

**Comment by mrflos** [comment]
bravo tu vas maintenant pour mettre des émoji dans yeswiki cf. https://coop.tools/?BacASable  
On va le documenter, puisque apparemment cela marche!
