### ISSUE TITLE
Droits d'accès du champ bazar avec limitation @admins ne fonctionne pas

### ISSUE THREAD

**Issue by antoine37120** [YesWiki/yeswiki#335]
Pour cet exemple de champs :
radio***ListeValidation***Validée*** *** ***1*** *** ***1***1*** ***@admins
Le champ apparait quand même dans le formulaire de création de la fiche.
Je ne trouve pas la partie du code censée vérifier cette option des champs. Ou est-elle ?

**Comment by Cyrille37** [comment]
il est possible que cette limitation ne fonctionne que pour l'affichage en mode lecture mais pas en mode édition ?

**Comment by Cyrille37** [comment]
En fait en mode édition il y a bien du code, mais il met la valeur à vide sans cacher le control de saisie du champ.
Dites @mrflos @furax37 , utilisez-vous cette fonctionnalité ? On dirait qu'elle ne fonctionne pas ...

**Comment by Cyrille37** [comment]
Aïe. En patchant le code pour trouver une solution :
Si on affiche pas le champs, pour qu'il ne soit pas dans les données du POST, et bien la donnée est écrasée avec la valeur par défaut au moment du traitement du formulaire ...

**Comment by mrflos** [comment]
hello,
En effet il faut revoir le fonctionnement de cette fonction car les champs apparaissent aussi en /raw et autres soucis, il faut tout mettre a plat..
Je vais faire un label refactoring bazar et mettre les issues dedans.

**Comment by geigerni** [comment]
Yo,
Il me semble maintenant que la 12eme fonctionne (par ex, si je ne suis pas @admins, je ne peux voir le champ lorsque je niavigue sur le wiki).
Par contre, la 13eme zone (qui sert à cacher un champ en mode encodage du formulaire) semble ne pas marcher tout le temps, non ?

**Comment by mrflos** [comment]
en effet, ce n'est pas encore corrigé présentement..
