### ISSUE TITLE
Pb action login sur version cerco 2018-03-20-1

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#336]
Il y a un bug dans l'url lorsqu'on se connecte via {{login}} 
voir http://pratic-coop.fr/wiki avec wikiadmin / pwd testlogin
l'url prend la forme suivante http://pratic-coop.fr/wiki/wiki

**Comment by geigerni** [comment]
Je confirme

**Comment by fbredow** [comment]
Même problème ici. Et cela se produit aussi en passant par la page ParametresUtilisateur.

**Comment by mrflos** [comment]
la version dev corrige le soucis normalement, cf. https://repository.yeswiki.net/cercopitheque_dev/yeswiki-cercopitheque_dev-2018-05-01-1.zip si c'est bon je fais une release pour la prod
