### ISSUE TITLE
[Bazar] import liste avec ID non-numériques

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#337]
Hello, Salut,

Quand on importe des données Bazar qui comportent une liste avec des ID alphanumériques, et bien la liste n'est pas importée (en tout cas les fiches Bazar sont là, mais pas les données de la liste en question).

**Comment by mrflos** [comment]
hello, en effet, il faut d'abord importer les listes (tu peux importer les listes par une url yeswiki source), ensuite l'import des données fera apparaitre les valeurs des listes, le CSV seul ne suffit pas, il faut le templates du formulaire + les listes du formulaire importés au préalable.  
Je laisse l'issue car en effet, on ne devrait importer qu'un seul fichier, mais a terme il faudra peut être que ce soit un zip avec aussi les listes dedans, et les fichiers et images jointes associées.

**Comment by Cyrille37** [comment]
Je ferme l'issue, le problème est plus étrange que ça.
