### ISSUE TITLE
[bazar] Les membres du groupe @admins ne peuvent editer les fiches

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#339]
J'ai créé un nouveau compte et je l'ai ajouté au groupe @admins. Et lorsque je parcours les fiches les boutons modifier et supprimer n'apparaissent pas. Le double-clic ne fonctionne pas non plus.
 - version du wiki identique à la branche cercopitheque actuelle. 
 - Le compte est bien connecté

Pas de soucis avec le compte WikiAdmin pour le faire.

**Comment by mrflos** [comment]
Je viens de tester avec la version dev actuelle, sur des listing avec le template accordeon, le bouton supprimer apparait bien.
