### ISSUE TITLE
Trouver une manière de rendre plus sexy les résultats de recherche

### ISSUE THREAD

**Issue by GDoukhan** [YesWiki/yeswiki#341]
Actuellement les résultats du moteur de recherche générique sont systématiquement les ChatMot de chaque page ou fiche bazar.
Ce serait chouette d'avoir quelquechose de plus compréhénsible. Par exemple pour les fiches bazar qui ont un champ titre ou bf_titre, le substituer au ChatMot ou pour les pages qui ont du texte en titre1 le substituer de la même manière.

**Comment by J9rem** [comment]
fixed by #968
