### ISSUE TITLE
YesWiki et initialisation des sessions

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#343]
Il devrait y avoir un appel à session_start() lors de l'initialisation de YesWiki. 

Aujourd'hui le seul appel que je trouve est au sein de bazar (tools/bazar/libs/vendor/Pager/Common.php:1604), et lorsque je l'appelle au sein d'une extension ça déclenche le warning suivant : 

> Warning: session_set_cookie_params(): Cannot change session cookie parameters when session is active in /var/www/html/etreserasmus.eu/includes/YesWikiInit.php on line 268

Si je n'appelle pas start_session toute modification de $_SESSION dans l'extension est perdue après rechargement de la page.
Je vois bien que YesWiki passe par des cookies pour la gestion de la connexion, mais cela me semble un peu overkill pour mon usage (stocker temporairement la langue choisie)

**Comment by mrflos** [comment]
J'ai pas compris ton besoin, tu veux ajouter session_start() après avoir initialisé les parametres cookies dans includes/YesWikiInit.php ?

**Comment by fbredow** [comment]
Idéalement oui, mais le problème est l'appel tardif a session_set_cookie_params() dans le code qui générera un warning.

J'ai l'impression plus globalement qu'il y a un soucis avec la gestion des sessions. Sachant que $_SESSION est utilisé dans bazar il y a sûrement des choses qui ne fonctionnent pas comme elles devraient vu que $_SESSION est remis à zéro à chaque rafraîchissement de page, ce qui n'est pas le fonctionnement attendu. A confirmer naturellement...
