### ISSUE TITLE
Les mot de passes sont chiffrés avec md5 dans la base de données

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#344]
En cas de fuite de base de données c'est un sérieux problème de sécurité. Surtout connaissant nos utilisateurs qui utilisent le même mot de passe partout. 

Aujourd'hui il faut utiliser [password_hash](http://php.net/manual/fr/function.password-hash.php)
Sources : 
 - https://medium.com/@svanas/why-an-unsalted-md5-hash-is-bad-practice-6a0d7d017856
 - https://www.zdnet.com/article/md5-password-scrambler-no-longer-safe/ 
 - https://security.stackexchange.com/questions/19906/is-md5-considered-insecure 

Une solution pourrait être de tester le chiffrement à la connexion et si il est encore en md5, en changer. (transparent pour l'utilisateur)
Ou alors tout simplement demander a l'utilisateur de changer son mot de passe à la première connexion avec un mot de passe chiffré en md5. (plus contraignant pour l'utilisateur, mais peut permettre un peu de changement dans ses mots de passes)

**Comment by sylvainboyer** [comment]
Oups,
@daiko Je n'avais pas vu cela.
À intégrer dans `/includes/WikiUser.class.php` une fois que `Feat_user_class` aura été mergé.

**Comment by VeveQNV** [comment]
Bonjour, pour mes besoins je suis en train de le faire. Je souhaite également rajouter une validation par mail à l'inscription. Je suis également en train de le faire. Si le code vous intéresse, je vous le proposerais.

**Comment by VeveQNV** [comment]
Pour md5 et les anciens comptes, j'utilise la table triples pour mémoriser l'algo de hashage. S'il n'est pas présent, j'utilise md5 pour la vérification, je mets à jour le hash dans la table user et l'algo dans la table triples

**Comment by J9rem** [comment]
@VeveQNV nous allons attendre la fusion de #935 avant de nous emballer sur un nouveau format de gestion des mots de passe.
Ca va être pour bientôt, la communauté ayant validé la diffusion de cette fonctionnalité dans `4.3`

A partir de ce moment, nous pourrons établir des spécifications de développement basées sur la résolution des bugs encore présents (spec. à valider au sein de la communauté des développeurs dans le respect des règles de codage existante - qui ne sont peut-être pas visible dans le dépôt Github - travaux en cours sur ce point aussi)

**Comment by mrflos** [comment]
@VeveQNV je suis de l'avis de @J9rem et de valider la PR #935 pour changer de méthode de hashage.  
Par contre d'amener dans le futur une création de compte avec mail de validation est une très bonne idée.  
Afin d'éviter des discussions trop longues à postério, on essaye de faire des spécifications entre dev pour voir comment intégrer cette contribution, si t'as le temps et l'envie d'aller vers cela, on pourrait s'en parler à l'occasion.

**Comment by VeveQNV** [comment]
@J9rem @mrflos Je suis en train de voir comment vous proposer d'intégrer mes modifications à partir du refactor de la #935. 

C'est dommage que nous n'ayons pas pu en parler plus tôt. Je ne suis pas pour l'utilisation de la technique proposée par les developpeurs de Symphony. 

Sauf erreur, leur méthode ne prend pas en compte l'existence de plus de 2 hashers : soit les comptes sont dans une ancienne version soit ils sont dans la nouvelle et ils sont convertis à la connextion. Ils voient les changements comme des phases de migration.

Le probleme c'est qu'il peut en réalité exister des utilisateurs avec un compte en md5, un autre avec un compte en bcrypt, l'autre en argon etc... Nous ne pouvons pas certifier que cela n'arrive pas. Nous ne pouvons pas certifier que nous ne changerons pas nous même rapidement l'algorithme utilisé et créer ainsi cette situation.

**Comment by VeveQNV** [comment]
https://symfony.com/doc/5.2/security/password_migration.html

**Comment by VeveQNV** [comment]
Au temps pour moi, je pense que j'avais mal lu. Je vais continuer d'investiguer... Je supprime mon message pour vous éviter des lectures inutiles.

**Comment by VeveQNV** [comment]
Je reviens sur le point que j'ai evoqué en commentaire puis supprimé : est-ce que le paramètre migrate_from ligne 28 du fichier PasswordHashFactory devrait inclure dors et déjà bcrypt au cas où PHP ou symphony modifie l'algo par défaut utilisé ? @J9rem

Et sinon, j'ai modifié la taille du password à la main dans la base de donnée et le système a correctement mis à jour mon ancien mot de passe md5. Super !

**Comment by J9rem** [comment]
@VeveQNV en mettant `auto`, la migration se fera en automatique car `symfony` garde sous l'étiquette `auto` les anciens algorithmes `auto` afin de permettre la migration.

En fait, en mettant d'autres valeurs, c'est pour le cas où nous souhaitions forcer par défaut un algo. qui n'est pas dans `auto` et ainsi indiquer qu'il faudrait aussi le prendre ne compte lors des migrations.

mais en l'état, faisant simple déjà non ? et facile à maintenir, genre `auto`

Pour la base de données, il te suffisait de faire un `/update` en tant qu'admin pour que ça se fasse tout seul.

**Comment by J9rem** [comment]
je clos cette issue car la fusion de #935 et génération de `doryphore-test 2022-07-26-6` permet une migration progressive des comptes des usagers de MD5 vers l'algorithme le plus récent retenu par `symfony/security-core` tout en assurant une mise à jour automatique à chaque identification depuis les éventuels algorithmes intermédiaires que `symfony/security-core` aurait utilisé si le nom du dernier algorithme utilisé venait à changer.
