### ISSUE TITLE
[bug] folder "files" is not empty

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#348]
Hello

The "files" folder is ignored (.gitignore) but in branch "cercopitheque" there are files ...

Cheers

**Comment by mrflos** [comment]
this is the wished behaviour!
Some default backgrounds are distributed, but all addition to this folder should not be taken in account.
Do you think this should be avoided? It's possible to add exceptions for some files if needed.

**Comment by mrflos** [comment]
added a line to .gitignore on dev branch to fix this, available in dev branch
