### ISSUE TITLE
[bazar][bug] Export liste

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#351]
Salut,
il semble y avoir un bug dans l'export

J'installe un frais YesWiki début mai depuis git@github.com:YesWiki/yeswiki.git

Je fais une liste bazar "Repas" => "ListeRepas":
![image](https://user-images.githubusercontent.com/368965/40713419-2afdba2e-6400-11e8-8fb8-a618c31c16fe.png)

Un formulaire "Inscription" avec pour template:
```
texte***bf_titre***Nom***255***255*** *** *** ***1***1*** ***
radio***ListeRepas***Repas midi*** ***1*** *** *** ***1***1*** ***
```

Je saisi une fiche, qui donne comme affichage:
![image](https://user-images.githubusercontent.com/368965/40713618-b2401234-6400-11e8-9cb5-aeae7b920361.png)

et comme body :
```
{
"bf_titre":"Elle & Lui",
"radioListeRepas":"oui",
"id_typeannonce":"1",
"id_fiche":"ElleLui",
"createur":"WikiAdmin","date_creation_fiche":"2018-05-30 11:48:44","statut_fiche":"1","date_maj_fiche":"2018-05-30 11:48:44"}
```

Ensuite je vais dans export, je choisi export "Inscription" qui donne:
```
"datetime_create","datetime_latest","Nom *","Repas midi *"
30/05/2018 11:48:44,30/05/2018 11:48:44,"Elle & Lui",
```
Et paf ! pas de valeur pour "Repas midi *".
J'ai fais le même essai en changeant les valeurs de la liste "Repas" par des valeurs numériques mais ça fait pareil : pas de valeur à l'export.

Cyrille.

**Comment by mrflos** [comment]
Je croies que ce sont les éléments radios qui ne sont pas supportés par
l'export, je voies ou changer mais je ne pourrais pas regarder cette
semaine, mais ce sera facile a mettre a jour
