### ISSUE TITLE
Agenda n'affiche pas si event sur plusieurs journées

### ISSUE THREAD

**Issue by geigerni** [YesWiki/yeswiki#352]
Lorsqu'on crée une fiche dans un calendrier ET qu'on choisit "événement à la journée", l'agenda affiche l'événement sur le nombre de jours -1.
Ex : je rentre un event de 3 jours avec "événement à la journée", l'agenda n'affichera que 2 jours.

NB : le problème n'a pas lieu lorsqu'on indique une heure de début et heure de fin sur la fiche-bazar.

**Comment by gatienbataille** [comment]
plus d'actu avec nouvelle version
