### ISSUE TITLE
Calendrier qui génère un flux Ical ou CalDav

### ISSUE THREAD

**Issue by geigerni** [YesWiki/yeswiki#355]
Yo, 
Le besoin, moult fois rencontré dans les projets de territoire, est d'avoir un {{calendrier}} qui génère un vrai flux d'agenda (CalDav, Ical...), de sorte à ce que ça alimente automatiquement d'autres agendas classiques (Google agenda, framagenda ou autre...)
Pour l'instant, les projets d'agenda de territoire/agenda inter-structures que je rencontre échoue principalement pour cette raison

**Comment by geigerni** [comment]
Ou au moins un truc qui permettent de gérer la récurrence des événements.
Aujourd'hui, si mon club organise un cours de Yoga tous les mercredis, je suis obligé de saisir 52 fois le même événement sur 1 an....

**Comment by J9rem** [comment]
alors il me semble que la PR #765 va permettre de répondre au besoin (au moins de façon basique) pour l'xport ical

**Comment by J9rem** [comment]
Tu feras attention @seballot il y avait 2 besoins dans cette issue:
 - générer les flux ical (résolu par #765 )
 - "Aujourd'hui, si mon club organise un cours de Yoga tous les mercredis, je suis obligé de saisir 52 fois le même événement sur 1 an.." en gros pouvoir créer des évènements récurrents => non résolu (PR en cours https://github.com/YesWiki/yeswiki/pull/1098)
 
 Je ne sais pas si tu as créé une tâche "priorité" correspondant aux évènements récurrents et dans ce cas, je veux bien le lien dans cette PR pour garder une trace.

**Comment by seballot** [comment]
Salut Jerem ! comme indiqué sur le framateam, j'ai fermé sans regardé les issues vieilles de plus de 4 ans (une dizaine, dont celle-ci, j'en pouvais plus de cette liste interminable ah ah). Mais si tu penses que les propositions de cette issue sont encore pertinente, n'hésites pas à créer les posts correspondant sur priorites.yeswiki.net !

**Comment by J9rem** [comment]
Actuellement, je ne travaille pas avec `priorites.yeswiki.net` et comme je vois qu'il n'y a pas de tâche correspondante sur priorites.yeswiki.net pourrais-tu y créer une tâche "évènements récurrents" ? comme tu l'as fait pour toutes les autres issues, merci

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/42/des-evenements-recurrents

**Comment by mrflos** [comment]
@J9rem je sais que le collaboratif n'est pas ton fort, mais je trouve ca abusé que tu demandes a Sebastian, qui s'est farci 100+ issues github pour permettre aux gens d'aller voter pour des fonctionnalités, d'ajouter la tienne, que tu as déja developpé par ailleurs (pour tes clients).  
Merci @seballot d'avoir fait l'effort, mais c'est pas parce que Jeremy est en posture de non-collaboration qu'il faut faire des choses pour lui.
Il a été validé par l'asso que pour que les membres de la commu puissent voter, c'est sur [https://priorites.yeswiki.net](https://priorites.yeswiki.net) que cela se passe, donc cette regle vaut aussi pour Jeremy et ses clients.

**Comment by J9rem** [comment]
Merci @seballot pour ton suivi de cette issue qui contenait une issue masquée :wink:
