### ISSUE TITLE
[Bazar] Sur l'action bazar les paramètres 'pagination' et 'groups' sont incompatibles

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#357]
Lorsque je filtre les résultats et que j'utilise pagination, la pagination ne prend pas en compte que le nombre de résultats change. Lorsque l'on change de page, les filtres sont oubliés.

Exemple : https://reseau-eau.educagri.fr/?RessourCes&facette=checkboxListeTypeDeRessource=4

Résultat attendu : l'ensemble des résultats apparaît sur la première page (pagination=40 et 17 résultats attendus). Si plusieurs pages sont disponibles, je devrais avoir accès a la deuxième page des filtres.

Ce qui se passe : Seuls deux résultats apparaissent sur la première page. Il y a 12 pages, lorsque je clique sur une autre page le filtre disparaît.

**Comment by mrflos** [comment]
cf #190 . Je ferme cette issue, puisque elle est déja présente ailleurs.
