### ISSUE TITLE
[Yeswiki] Plusieurs warning dans les logs à la fin de l'installation

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#358]
`Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/yeswiki-bazar-pagination/includes/i18n.inc.php on line 148`

` Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/yeswiki-bazar-pagination/includes/i18n.inc.php:148) in /var/www/html/yeswiki-bazar-pagination/setup/header.php on line 40`

`Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/yeswiki-bazar-pagination/includes/i18n.inc.php:148) in /var/www/html/yeswiki-bazar-pagination/setup/writeconfig.php on line 85`

Ils apparaissent a l'affichage de la page validant l'installation ( après la création de "wakka.config.php"). Ce n'est pas critique, mais peut que cela cache autre chose.

**Comment by mrflos** [comment]
Je ne voies plus cette erreur depuis que l'install et la création du fichier de configuration se font directement. Le problème est il encore d'actualité?
