### ISSUE TITLE
[attach] Ne reconnais les SVG en tant qu'image.

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#359]
Tous les navigateurs gèrent ce format maintenant, ce serait pratique de pouvoir l'utiliser dans YesWiki.

**Comment by mrflos** [comment]
C'est sensé etre reconnu : cf . https://github.com/YesWiki/yeswiki/blob/cercopitheque/tools/attach/actions/attach.class.php#L74

**Comment by mrflos** [comment]
je ferme cette issue, je viens de tester avec succes sur https://yeswiki.net/?BacASable
