### ISSUE TITLE
{{setwikidefaulttheme}} ne fonctionne que si plusieurs thèmes dispo

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#362]
il semble que la gestion du thème par défaut ne fonctionne vraiment que qund plusieurs thème ssont dispo sur lewiki

s'il y a juste le theme yeswiki (et rien dans le dossier themes), on ne peut alors voir les squelettres ou style dans {{setwikidefaulttheme}}

par contre si on ajoute un theme dans le dossier themes
alors ça devient fonctionnel...

**Comment by RomainLalande** [comment]
UP :-) 
C'est vrai que nous avons ce retour assez souvent et ce serait un chouette truc à débugguer <3

**Comment by J9rem** [comment]
Normalement ça fonctionne avec la dernière version de Doryphore.
Peux-tu vérifier @gatienbataille ?
Si OK, je te laisse clore cette issue.

**Comment by J9rem** [comment]
C'est réparé, je clos l'issue
