### ISSUE TITLE
erreur d'accord dans facette

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#364]
dans les vue facette
on a un message en bleu qui dit 
Il y a 1 fiche(s) correspondante(s) à vos filtres .

il est mal accordé
correspondant est invariable dans ce cas
je veux bien corriger mais je sais pas où chercher ;-(

**Comment by mrflos** [comment]
justement ya des parenthèses pour marcher dans les 2 cas!

J'avoues que c'est triché un peu..

**Comment by mrflos** [comment]
en effet "correspondant" devrait être invariable dans ce cas.

**Comment by mrflos** [comment]
passé en prod sur la version Cercopitheque 2019-02-13-1, merci!
