### ISSUE TITLE
Put releases on GitHub ?

### ISSUE THREAD

**Issue by benrubson** [YesWiki/yeswiki#366]
Hi,

Could it be possible to put releases on your GitHub releases' section ?
https://github.com/YesWiki/yeswiki/releases

Only the old ones from 2016 are there, not the new ones.
It is very convenient to have them there, as we can then subscribe for new releases thanks to GitHub, and also automate new versions retrieval.

Thank you very much 👍

**Comment by mrflos** [comment]
Thanks for your feedback, we will discuss this issue with the members of the YesWiki team IRL from 6 to 8 dec.

**Comment by benrubson** [comment]
Good news, thank you @mrflos.

**Comment by benrubson** [comment]
Closing this for now, feel free to reopen if needed. Thank you.
