### ISSUE TITLE
Improve french geoloc

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki#367]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Improve french geoloc
https://framagit.org/Artefacts/ATable-guide-web/commit/4ae1b4b61c41a3b4004d6231a8e34a9ff44a98d9

**Comment by J9rem** [comment]
Je clos cette issue car depuis `doryphore 4.4.0`, la géolocalisation est plus précise et permet de prendre en compte les arrondissements des ville ou de détecter le champ qui ne correspond pas à une adresse pour trouver le point de géolocalisation qui correspond aux autres champs.

Il est conseillé de séparer la saisie des adresses en `bf_adresse`, `bf_adresse1` `bf_code_postal`, `bf_ville` pour que la géolocalisation détecte plus facilement chaque champ et puisse les trier.
