### ISSUE TITLE
Bug template glossaire

### ISSUE THREAD

**Issue by Ljbouere** [YesWiki/yeswiki#368]
Le template glossaire ne fonctionne pas il renvoit l'erreur suivante 
Fatal error: Cannot redeclare cleanString() (previously declared in /home/yeswikinsu/yeswiki.net/themes/tools/bazar/templates/glossaire_yeswiki.tpl.html:3) in /home/yeswikinsu/yeswiki.net/themes/tools/bazar/templates/glossaire_yeswiki.tpl.html on line 3

**Comment by mrflos** [comment]
corrigé sur le site de yeswiki.net, mais est ce que ce template est utilisé ailleurs?
