### ISSUE TITLE
Supression google font

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#369]
**Description**
Supprimer la police google des thèmes de yeswiki.

**Comment by RomainLalande** [comment]
Bon après avoir exploré un peu avec @sylvainboyer  , déjà ça concerne l'extension bootstrap3, pas le dépot yeswiki/yeswiki. 
Ensuite, ce qu'il faudrait faire : 

- Mettre les font dans le dossier theme/font en "dur"
- Modifier la première ligne des fichiers de css de façon a fabriquer une url qui pointe sur le fichier de police (mais est-ce possible de récupérer bas_url dans le css ? ! )

Du coup c'est à voir quoi...

**Comment by RomainLalande** [comment]
Bon après avoir exploré un peu avec @sylvainboyer  , déjà ça concerne l'extension bootstrap3, pas le dépot yeswiki/yeswiki. 
Ensuite, ce qu'il faudrait faire : 

- Mettre les font dans le dossier theme/font en "dur"
- Modifier la première ligne des fichiers de css de façon a fabriquer une url qui pointe sur le fichier de police (mais est-ce possible de récupérer bas_url dans le css ? ! )

Du coup c'est à voir quoi...

**Comment by Sebbaz** [comment]
Salut,
> Bon après avoir exploré un peu avec @sylvainboyer , déjà ça concerne l'extension bootstrap3, pas le dépot yeswiki/yeswiki.
> Ensuite, ce qu'il faudrait faire :

Cool, merci d'avoir amorcé le travail dans le dépôt vivant :)

Sur le fond, si une dépendance pose problème, c'est quand même un problème à prendre en compte par Yeswiki : choisir une dépendance, c'est un choix éditorial. Surtout pour la version distribuée par défaut, histoire d'avoir une version de base un minimum fonctionnelle et qui garanti le respect de la légistlation et le service fourni.

Effectivement la dépendance ne se trouve pas directement dans le dépôt mais dans yeswiki-theme-base, plus précisément ici : https://github.com/YesWiki/yeswiki-theme-base/blob/b092fbc23e53bd1681935e5e5fd5fb531c6187eb/styles/base.bootstrap.min.css#L1

> Mettre les font dans le dossier theme/font en "dur"
> Modifier la première ligne des fichiers de css de façon a fabriquer une url qui pointe sur le fichier de police (mais est-ce possible de récupérer bas_url dans le css ? ! )

En principe, modifier l'url dans [@import](https://developer.mozilla.org/fr/docs/Web/CSS/@import#syntaxe) suffit, il faut mettre une référence relative par rapport au fichier css de bootstrap modifié, pas besoin d'utiliser la fonction url(). Quelque chose comme `@import ../fonts/fichier` [cf. yeswiki-theme-margot qui fait ça correctement](https://github.com/YesWiki/yeswiki-theme-margot/blob/0c9fc2d4155dad994656637db0ee3df7bc12f23c/styles/margot.css#L5)

Autrement la dernière version de Bootstrap 3.3.7 n'embarque pas la dépendance vers la fonte déposée sur le CDN de Google, peut-être qu'une mise à jour serait suffisante ?

NB : La semaine dernière, [la justice allemande a interdit l'utilisation des fontes Google hébergées sur leurs serveurs](https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/) pour les problèmes de [vie privée et géopolitiques](https://www.laquadrature.net/2019/05/23/audience-contre-le-privacy-shield-devant-le-tribunal-de-lue/) que ça pose. 

https://social.imirhil.fr/@aeris/107716276397225915

Ca vaut aussi potentiellement pour les CDN américains comme Clouflare comme ceux qu'on trouve sur le site vitrine de Yeswiki Je n'ai pas pris le temps de voir d'où ces références viennent. S'il faut avoir une discussion sur l'usage des CDN américains, pas sûr que je réponde tout de suite. Il me semble que c'est important que prendre en compte le respect de la vie privée dans le design d'un logiciel, en tenir compte au même titre de l'ergonomie et l'ouverture (etc.).

**Comment by mrflos** [comment]
Bonjour,
Nous sommes ok sur le principe, mais nous manquons de forces vives et de temps pour revoir les dépots en question.  
Mon point de vue, c'est que de proposer une pull request sur les thèmes incriminés serait plus rapide que de se lancer dans une grande discussion ou tout le monde est d'accord.

**Comment by mrflos** [comment]
je m'occuperais de l'appel cdn sur le site de yeswiki.net.  
Toute PR sur https://github.com/YesWiki/yeswiki-theme-bootstrap3 sera reviewé rapidement pour mise en ligne sur les dépots de yeswiki.

**Comment by mrflos** [comment]
(et sur https://github.com/YesWiki/yeswiki-theme-base du coup aussi, et sans doute d'autres à vérifier)

**Comment by J9rem** [comment]
Je clos cette issue car
1. le thème `margot` embarque ses propres polices
2. la page `LookWiki` permet de définir des `preset` de thème avec le thème `margot` et que la création de ces presets importe automatiquement en local la police concernée pour éviter d'utiliser un CDN peut scrupuleux de la vie privé. 

Version concernée yeswiki `doryphore 4.3.0` et ultérieures
