### ISSUE TITLE
Template Galerie_photo_tpl.html

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#370]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lorsque l'on réduit la fenêtre d'affichage, le texte sort du cadre

**Comment by mrflos** [comment]
Ok, j'ai modifié le code pour qu'il soit fonctionnel (et j'ai viré bootstrap, en theorie c'est plus facile de changer la grille maintenant)
