### ISSUE TITLE
Gestionnaire de médias

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#373]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Créer une nouvelle action Attach avec gestionnaire de médias

**Comment by patemoll** [comment]
J'abonde dans ce sens. En particulier, gérer des versions de fichiers me semble indispensable pour faire de la documentation partagée. Ce n'est en effet pas très rassurant de savoir qu'une version est simplement écrasée lorsqu'une version plus récente est mise en ligne.
Je ne connais pas la méthode ou l'endroit pour pouvoir discuter avec la communauté YesWiki. Merci de me dire si ce n'est pas le lieu.

**Comment by mrflos** [comment]
Il existe déjà un gestionnaire de fichier dans yeswiki qui gère l'historique, juste cette fonctionnalité n'est accessible qu'au propriétaire de la page (il faut passer par le handler /filemanager ).  
L'idée de cette issue est de créer un outils de sélection plus visuel, comme le gestionnaire de media de wordpress, par exemple.

**Comment by patemoll** [comment]
Bonjour Florent. Merci de ta réponse rapide et efficace.
Tout va bien donc :-)

**Comment by patemoll** [comment]
Ok merci. Je vais l'utiliser un peu pour me faire une idée.

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/39/gestionnaire-de-media
