### ISSUE TITLE
Gestion des utilisateurs

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#374]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Une gestion des utilisateurs facilitée, il suffit de récupérer le code produit pour le guide ATABLE

**Comment by RomainLalande** [comment]
Idée de permettre du drag and drop en plus

**Comment by sylvainboyer** [comment]
Dans la page, il y a 
```
===Liste des utilisateurs===
{{Listusers2}}
```
et le fichier action en PJ
[listusers2.zip](https://github.com/YesWiki/yeswiki/files/2659923/listusers2.zip)

**Comment by sylvainboyer** [comment]
J'ai renommé Listusers2 en userstable et l'ai intégré aux actions de la version de développement.
Il suffit de mettre 
```
===Liste des utilisateurs===
{{userstable}}
```
dans la page GererUtilisateurs.

**Comment by mrflos** [comment]
hello, j'ai pas encore testé l'action, mais idéalement, il ne faudrait en avoir qu'une seule:
 - faudrait tester si cela marche avec a minima les fonctions d'avant et une meilleure interface
 - renommer usertable.php en listusers.php comme ca tous les wikis obtiendront la nouvelle version

**Comment by sylvainboyer** [comment]
@mrflos Pour moi, ce sont deux choses différentes.
Avec listusers tu récupères la liste des utilisateurs (name, email, date).
Avec userstable, tu récupères en plus les groupes d'appartenance de chaque user (name, group(s), email, date). Et c'est présenté sous forme de tableau.
C'est pourquoi, je n'ai pas osé remplacé la version listusers par la nouvelle. Mais si tu penses que ça le fait, pourquoi pas ?

**Comment by mrflos** [comment]
Non, en effet, trop différent, mais pour l'instant cela manque de fonctionnalités pour être ajouté dans la partie admin de YesWiki, il faudrait qu'en tant que membre du groupe admins, l'on puisse éditer et supprimer les utilisateurs existants, voire en créer des nouveaux et les associer à un groupe existant ou nouveau groupe.  
On peut laisser le fichier mais se garder l'issue pour un jour commencer a faire un vrai outil de gestion des utilisateurs (mais va falloir réfléchir à comment lors de la suppression, dissocier le contenu créé par l'utilisateur, l'enlever des groupes, etc)

**Comment by sylvainboyer** [comment]
@mrflos @RomainLalande OK sur tous les points

**Comment by mrflos** [comment]
Pour la suppression d'un user:
 - gérer le cas des groupes dans lequel il est présent (empêcher la suppression du user s'il est seul membre d'un groupe)
 - pour les pages dont il est Owner , mettre a NULL

**Comment by sylvainboyer** [comment]
## Spécifications
(MrFlos & SylvainBoyer)
### Au niveau de l'interface
- Sur la page `GererUtilisateurs`
  - On part du tableau de `{{userstable}}`.
    - Sur chaque ligne de user, on ajoute un bouton `Modifier`. Ce bouton envoie sur la page de modification de l'utilisateur.
    - On fait en sorte que le nom de l'utilisateur ne soit pas compris comme un lien.
  - On ajoute la possibilité de supprimer un groupe.
- Sur la page de modification de l'utilisateur, on ajoute un bouton `Supprimer` accessible uniquement aux membres de `@admins`.
### Conséquences de l'action de `suppression` d'un utilisateur
En mode transactionnel (ou équivalent => si échec à un endroit quelconque, on retourne à l'état d'origine (annulation de toutes les actions))
1. Pour chaque groupe dont l'utilisateur est membre :
   1. Si l'utilisateur est le seul membre du groupe, 
      1. message "La suppression de cet utilisateur est impossible car c'est l'unique membre du groupe`@Machin`. Faîtes en sorte que ce ne soit plus le cas avant de tenter à nouveau de le supprimer."
      2. On annule toute la suppression. `Rollback` => retour à l'état d'origine.
   2. Sinon, l'utilisateur est retiré du groupe (mode transactionnel)
2. Pour chaque page dont l'utilisateur est propriétaire, mettre l'ownership à `null`
###  Conséquences de l'action de `suppression` d'un groupe
En mode transactionnel (ou équivalent => si échec à un endroit quelconque, on retourne à l'état d'origine (annulation de toutes les actions))
1. Si le groupe n'est pas vide
   1. message "La suppression de ce groupe est impossible car il n'est pas vide. Faîtes en sorte que ce ne soit plus le cas avant de tenter à nouveau de le supprimer."
   2. On annule toute la suppression. `Rollback` => retour à l'état d'origine.
2. Sinon, si le groupe a, seul, les droits (lecture, écriture ou commentaire, au moins un) sur au moins une page,
   1. message
      - "La suppression de ce groupe est impossible car il est le seul a avoir des droits sur les pages suivantes. Faîtes en sorte que ce ne soit plus le cas avant de tenter à nouveau de le supprimer."
      - suivi de la liste des pages concernées.
   2. On annule toute la suppression. `Rollback` => retour à l'état d'origine.
3. sinon,
   1. suppression de la mention du groupe dans la table ` _acls`
   2. suppression du groupe

**Comment by mrflos** [comment]
> Sinon, suppression du groupe. @mrflos y-a-t-il des conséquences à prévoir/gérer ?

Le groupe peut exister dans un certain nombre de définitions de droits des pages (table <prefixe>_acls), il faudra aussi supprimer les references au groupe dans la table <prefixe>_acls

**Comment by sylvainboyer** [comment]
@mrflos Et comme ça ? => voir ci-dessus

**Comment by sylvainboyer** [comment]
Fonctionnalités apportées par le commit de la branche `Feat_User_Class` de `cercopitheque_dev`.
Variation par rapport aux spécifications ci-dessus, lors de la suppression d'un utilisateur, owner est remplacé par une chaîne vide (au lieu de null).
