### ISSUE TITLE
le paramètre groups de l'action bazar ne fonctionne pas avec des champs de type checkboxfiche.

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki#376]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Dans ma page j'ai 
```
{{bazar id="1" vue="consulter" voirmenu="0" groups="checkboxListeTypeCarte, checkboxfiche2"  titles="Type de carte, Territoire" }}
```
dans le formulaire j'ai
```
checkboxfiche***2***Projet(s) de territoire concerné(s)*** *** *** *** *** ***1***0*** *** ***
```
Quand j'affiche en `raw` une fiche, j'ai `"checkboxfiche2":"LeCollectifDesGarrigues"`
Et le résultat est là : http://boyer.earth/?BacASable

**Comment by mrflos** [comment]
passé en prod sur la version Cercopitheque 2019-02-13-1, merci!
