### ISSUE TITLE
action nav et évolution des ChatsMots

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#377]
Bug / Bogue

**Description**
Pour info, la nouvelle manière de nommer les pages pose problème avec l'action nav. on doit ajouter un "?" avant le nom pour que ça fonctionne : ex : {{nav links="?Qui-produit-quoi-ou, . 
Doit-on faire évoluer la doc ou plutôt le code lié à l'action ? 
(remonté par @furax37  )

**Comment by mrflos** [comment]
corrigé sur la dev, a tester!
