### ISSUE TITLE
problème pour télécharger un fichier son => un ? fout le b...

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#378]
quand on upload un ficher son en mp3, un élégant petit lecteur s'affiche dans la page. petit soucis, quand on cherche à le télécharger par le truchement de l'icône élégamment proposée et bien ça bug. La faute à un ? de trop qui se place dans le lien et qui pose soucis. Et voilà pour le soucis

**Comment by furax37** [comment]
Et il est possible que cela pose aussi un soucis pour la lecture mais pas sur. Si nous poussons la logique, il est possible que ça plante aussi la lecture et upload des flv mais pas testé

**Comment by mrflos** [comment]
Corrigé sur la dev, a tester!

**Comment by mrflos** [comment]
passé de prod sur la version Cercopitheque 2019-02-13-1, merci!
