### ISSUE TITLE
Régression sur 2019-02-13-1  – Import CSV en double

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki#379]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
J'ai installé la dernière release de YesWiki. Et j'ai noté que la création d'un formulaire aboutit (à nouveau, parce que je pensais que ça avait été corrigé) à sa création en double,
l'importation d'un fichier CSV aboutit bien à la création parfaite de toutes les fiches, mais en double (l'analyse de la bdd montre qu'il a d'abord créé toutes les pages avant de recommencer).

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
2019-02-13-1

**Comment by dhebert91** [comment]
J'ai le même problème la dernière version cercopitheque_dev 
Version du Wiki : 2019-06-28-1
A priori, le problème se situe dans /tools/bazar/libs/bazar.fonct.php

**Comment by mrflos** [comment]
corrigé sur la version 2019-08-15-1
