### ISSUE TITLE
Régression sur 2019-02-13-1 – Changement de langue d'installation

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki#380]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
J'ai installé la dernière release de YesWiki. Et j'ai noté un comportement étrange de l'installeur.
Si je modifie la langue proposée dans l'installeur je suis directement redirigé sur "cette page n'existe pas".

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
2019-02-13-1

**Comment by J9rem** [comment]
@sylvainboyer est-ce toujours d'actualité avec la dernière mise à jour ?

**Comment by sylvainboyer** [comment]
Je n'ai pas vérifié sur la dernière version. Mais j'ai testé récemment sur une version antérieure et cela fonctionnait correctement.
