### ISSUE TITLE
Envoyer tous les mails à partir d'une adresse configurée dans wakka.config.php

### ISSUE THREAD

**Issue by marc-farre** [YesWiki/yeswiki#385]
**Type de demande (ne garder qu'une ligne)**
Nouvelle fonctionnalité

Faire en sorte que tous les mails envoyés par YesWiki le soient avec une adresse expéditeur paramétrée dans wakka.config.php

Utiliser la balise "Reply-to" pour permettre de répondre à des mails envoyés par des utilisateurs.

Avoir une adresse "Reply-to" par défaut dans wakka.config.php pour les mails systèmes qui pourra être différente de celle de l'expéditeur (afin de gérer des répondeurs automatiques).

**Comment by mrflos** [comment]
disponible avec le parametre `contact_reply_to` a rajouter dans la conf (disponible en dev, je clos l'issue quand c'est en prod)

**Comment by marc-farre** [comment]
Excellent, merci Flo ! @acheype ce serait bien de mettre à jour les Wikis sur cette nouvelle version quand tu auras le temps !

**Comment by acheype** [comment]
J'avais complètement oublié de régler ce soucis.

La solution que tu proposes florian avec le contact_reply_to, force ce champ avec toujours la même valeur. On n'aurait alors plus un reply_to qui s'adapte avec l'adresse mail de la fiche bazar à laquelle l'utilisateur écrit.

Cf le PR pour fixer de la même manière un champ 'from' et adapté le reply-to avec l'adresse de l'utilisateur :
`Permet la configuration d'un champ 'contact_from' dans le wakka.config.php qui fixe un champ 'from' pour tous les mails envoyés par bazar. Le champ 'reply-to' est alors ajouté avec l'adresse de l'utilisateur qui envoie le message.
Cela permet d'éviter que certains mails soient reconnus en tant que spam car les fournisseurs de mail s'attendent à ce que l'adresse du champ 'from' soient du même nom de domaine que le serveur dont provient le mail.`

Ce devrait être un comportement par défaut, mais je vous laisse en juger.

**Comment by gatienbataille** [comment]
Hello, bon en version productowner de base (qui comprend pas trop le code je veux dire) pour moi y a un enjeu premier a d'abord réparer l'envoi de mail (tout court) au départ des yeswikis. Les ajouts smtp dans le wakka sont moyennement fonctionnels. Suis ok avec la remarque ci-dessus (contact_from et reply-to)

**Comment by acheype** [comment]
Sur nos yeswiki, on n'a pas de soucis en paramétrant les variables 'contact_mail_func',  'contact_smtp_host', 'contact_smtp_port', 'contact_smtp_user' et  'contact_smtp_pass'.
Après on n'est pas passé à la version de dev. Tu parlais pour quelle version @gatienbataille ?

**Comment by gatienbataille** [comment]
salut, version cerco (et cerco-dev) moi j'utilise ces param aussi mais avec moi de succès visiblement (je passe par smtp de sendinblue...) et vous ?

**Comment by acheype** [comment]
Oupps sorry, j'ai zappé de te répondre. Ben c'est bizarre car on utilise aussi sendinblue sur cerco !
Un soucis de ce module, c'est qu'on a aucun message d'erreur qui remonte en cas de problème de config, ou simplement d'adresse mal renseignée par l'utilisateur. Ca me semblerait important de l'améliorer dans ce sens.

**Comment by gagzzz** [comment]
Related to #431 :)
(enfin plutôt, #431 est un doublon de celle-ci on dirait)

**Comment by acheype** [comment]
D'ailleurs ce ticket n'est pas clos, je le fais de ce pas.
