### ISSUE TITLE
button avec new-window ne fonctionne pas

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki#386]
La doc (https://yeswiki.net/?DocButton), dit qu'on peut paramétrer un bouton pour qu'il ouvre la cible dans une nouvelle (comme `target="_blank"`).
Quand j'essaye, cela ne fonctionne pas.
- Dans `tools\templates\actions\button.php` la classe du bouton se retrouve dans `$class`. Je ne sais pas ce qui est fait de cette variable ensuite.
- Dans `tools\templates\libs\yeswiki-base.js`, on a (l. 245) : `$('.new-window').attr('target', '_blank');`
Cela dépasse mes capacités actuelles en JS.

**Comment by mrflos** [comment]
cela marche pourtant sur https://yeswiki.net/?DocButton (cf. exemple en bas de page).

Confirmes tu le bug? Arrives tu a le reproduire?

**Comment by sylvainboyer** [comment]
Je viens de tester à nouveau et cela fonctionne. Du coup, j'ai repassé tout les ""<a..."" que j'avais mis sur mes wikis en {{button...}} à nouveau et cela fonctionne. 
Quelque a dû bouger d'un côté ou de l'autre.
