### ISSUE TITLE
Hériter les pages spéciales lors de la création de nouvelles pages

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#387]
Alors, voilà un comportement qui me ferait kiffer de la mort qui tue

- je créé une PageMenuHautBis
- Cette page je lui met comme PageMenuHaut, PageMenuHautBis
-Et miracle, toutes les pages créées depuis ce nouveau menu ont comme PageMenuHaut PageMenuHautBis.
Comme le look, les Pages spéciales sont héritées dans les pages créées à partir de celle ci...

On a le droit de rêver avec yeswiki ;-)

**Comment by J9rem** [comment]
résolu
