### ISSUE TITLE
envoyer un mail

### ISSUE THREAD

**Issue by FredOdass** [YesWiki/yeswiki#388]
pour envoyer un mail le lien type [[accueil@outils-reseaux.org Envoyer un mail]] ne fonctionne pas...

**Comment by furax37** [comment]
[[mailto:accueil@outils-reseaux.org Envoyer un mail]] fonctionne par contre

**Comment by FredOdass** [comment]
Ah ben oui, en effet, merci!
Je vais corriger la doc du coup!!
... sauf que je suis allée trop vite : voir sur la doc... ça n'a pas l'air de fonctionner mieux...

**Comment by furax37** [comment]
bizarre, ça fonctionne sur un autre site même version de wiki.
conflit avec une autre action ???
