### ISSUE TITLE
Bug Bazar ChaMot

### ISSUE THREAD

**Issue by mlodeve** [YesWiki/yeswiki#389]
Lorsqu'on écrit un ChatMot dans un textelong un petit crayon et un petit V apparaît. Si on clique sur le "V" la fiche crée s'enregistre mais ... vide
voilà pour ce petit rapport. Merci :)

**Comment by furax37** [comment]
En fait c'est le nouveau comportement normal, peut-être pas très intuitif 
si tu cliques sur le crayon, tu créés une nouvelle page
si tu cliques sur le v, tu indiques que tu souhaite que ça reste un mot normal (dans ce cas, deux guillemets sont ajoutés avant et après le mot) Si tu supprimes ces guillemets, tu reviens à une page wiki normale

**Comment by mlodeve** [comment]
Oui ok Laurent, mais je parle du bug de cette nouvelle fonctionnalité dans une fiche bazar ! 
exemple https://colibris-wiki.org/rdvprojetpasdeporte/?Testbugbazar1/edit
à tester sur la page Testbugbazar2 et Testbugbazar3 ....

**Comment by mlodeve** [comment]
je viens de voir qu'il y a eu un test sur les pages Testbugbazar2 et Testbugbazar3... c'est vous Laurent ?

**Comment by mrflos** [comment]
Bonjour nous avons décidé avec @furax37 de supprimer ce lien V qui ne marche pas dans tous les cas, et qui déroute les utilisateurs.  

Merci de votre retour

**Comment by mlodeve** [comment]
Bonjour Florian oui je suis d'accord avec ce choix 
bien à vous 

S. 


----- Mail original -----

De: "Florian" <notifications@github.com> 
À: "YesWiki/yeswiki" <yeswiki@noreply.github.com> 
Cc: "mlodeve" <idealodeve@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 28 Juin 2019 17:04:37 
Objet: Re: [YesWiki/yeswiki] Bug Bazar ChaMot (#389) 



Bonjour nous avons décidé avec @furax37 de supprimer ce lien V qui ne marche pas dans tous les cas, et qui déroute les utilisateurs. 

Merci de votre retour
