### ISSUE TITLE
[Bazar] Gérer les regexp dans les query

### ISSUE THREAD

**Issue by toddoli** [YesWiki/yeswiki#390]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
L'utilisation de regexp dans les query de bazarliste n'est pas fonctionnel.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
Cercopithèque

"query=MonTexte" fonctionne très bien, par contre "query=.*Texte" ne fonctionne pas alors que c'est proposé dans la documentation: https://yeswiki.net/?DocQuery

**Comment by mrflos** [comment]
Merci du retour, en effet, je voies dans le code que les REGEXP des requetes sql ont étés enlevées, je regarde pour les remettre quand .* est présent dans la query.
