### ISSUE TITLE
fbclid

### ISSUE THREAD

**Issue by toddoli** [YesWiki/yeswiki#391]
Si l'utilisateur arrive avec un lien du site depuis une page Facebook, qui ajoute lâchement un paramètre `?fbclid=xxxxxxxxxxxxxxxx` derrière l'URL, le site retourne un

> Le nom de la page est incorrect.

Tel quel, impossible donc de lier une page facebook à un yeswiki :(

Exemple: http://www.sourcesasarcm.tk/?fbclid=IwAR05CHZxuD9TJAHqAWXNTSQOGI5_8wSet_0gNkQD7OtOFywFzVlZtG3pcR4

**Comment by mrflos** [comment]
Je n'ai pas de compte facebook pour tester mais je transmet a @gatienbataille ou @furax37 pour tester.

**Comment by gatienbataille** [comment]
hello oui je confirme le bug, c'est bien ça, facebook ajoute un param qui bloque l'affichage

**Comment by toddoli** [comment]
J'ai testé le correctif. Ça amène bien vers le site web cette fois mais sur

> Cette page n'existe pas encore, voulez vous la créer ?

Plutôt que d'amener faire l'accueil du site. Possible de changer ça ?

**Comment by toddoli** [comment]
Sous Doryphore le problème est à nouveau présent.
