### ISSUE TITLE
[Bazarliste] pas de pagination malgré le paramètre pagination

### ISSUE THREAD

**Issue by toddoli** [YesWiki/yeswiki#392]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lorsqu'on affiche une bazarliste et qu'on souhaite une pagination, il semblerait qu'il soit possible d'utiliser le param "pagination", or je ne l'ai encore jamais vu fonctionner. Exemple:
`{{bazarliste id="2" pagination="5"}}`

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
Cercopithèque 2019-06-28-1

**Comment by mrflos** [comment]
corrigé sur la version 2019-08-15-1  
Attention : ce parametre est incompatible avec les facettes
