### ISSUE TITLE
Suppression de thème lors de la mise à jour de YesWiki > version 2019-06-28-1

### ISSUE THREAD

**Issue by dhebert91** [YesWiki/yeswiki#393]
Le thème que j'avais installé dans  /tools/templates/themes a été supprimé lors de mise à jour que je viens d'effectuer pour passer en version 2019-06-28-1

**Comment by mrflos** [comment]
C'est le comportement normal (sans doute pas bien documenté..), les thèmes doivent être ajoutés a la racine du wiki dans le dossier `themes`, et les templates bazar dans `themes/tools/bazar/templates`.  

Les répertoires de la distribution yeswiki sont supprimés lors de la mise à jour...

J’espère que tu n'as rien perdu? 😢

**Comment by mrflos** [comment]
pour eviter la confusion, je vais deplacer le thème yeswiki par défaut dans le dossier `themes` a la racine, il ne restera que ce dossier `themes` (pour les thèmes à télécharger) et le dossier `custom/themes` (pour les thèmes déclinés ou sur mesure)
