### ISSUE TITLE
Possibilité d'envoi de fiche par mail à plusieurs destinataires

### ISSUE THREAD

**Issue by toddoli** [YesWiki/yeswiki#394]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Nouvelle fonctionnalité

**Description**
La doc "[Créer son formulaire soi-même](https://yeswiki.net/?FormulaireSoimeme)" propose d'envoyer automatiquement la fiche remplie à UNE adresse mail. Serait-il possible d'ajouter la fonctionnalité d'envoyer la fiche remplie à PLUSIEURS adresses mail ?

J'ai essayé diverses méthodes au niveau du 6ème champ de champs_mail, 2 mails séparés par une virgule ou un point virgule mais le mail ne s'envoie que si un seul email est renseigné. 

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
Cercopithèque

**Comment by mrflos** [comment]
Hello, 
La solution proposée est un peu une bidouille, donc de rajouter dans ce champs email caché d'autres emails cela me semble pas perenne..

J'ai rajouté un label refactoring bazar, qui est un chantier encore à ses prémices, mais de rajouter la feature "Envoyer la fiche créée aux emails suivants, directement dans les paramètres du formulaire" me parait une bonne idée.

Comme ca ne va pas sortir avant 2020, une solution de secours consisterait a utiliser la syntaxe existante, mais envoyer vers un alias d'email, qui lui pourra etre configuré pour envoyer sur plusieurs emails.

**Comment by toddoli** [comment]
C'est ce que j'ai fait. J'envoie à une framaliste mais effectivement une solution plus pérenne sera meilleure.
