### ISSUE TITLE
Possibilité de faire des calculs sur les chiffres stockés dans Bazar

### ISSUE THREAD

**Issue by toddoli** [YesWiki/yeswiki#396]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Ce serait top de pouvoir utiliser les données numériques pour en faire quelques calculs de base (somme, moyenne, graph...) à partir de données stockées dans les formulaires Bazar. Après c'est difficile de faire un choix de fonctionnalité et j'ai pas vraiment d'idée de comment faire ça simplement.

**Comment by furax37** [comment]
Et bien c'est possible : https://wiki.ressourcerie.fr/?BacASable
je met le template utilisé dans github afin que tu vois comment on s'y est pris

**Comment by toddoli** [comment]
Merci @furax37 j'ai hâte de voir ça par contre ton lien est HS.

**Comment by furax37** [comment]
https://github.com/YesWiki/template-calcul/blob/master/dea.tpl.html
j'ai mis l'exemple de template ici 
et le lien fonctionne chez moi, il fait des sommes et des moyennes de contenus de champs de fiches bazar.

**Comment by toddoli** [comment]
Merci! Ok je vois, c'est pas vraiment une fonctionnalité YesWiki par contre, c'est du code php mais merci quand même!
Le wiki était down au moment où je le regardais mais il est en ligne à présent :)

**Comment by sylvainboyer** [comment]
Sinon, c'est typiquement le genre de choses qu'on pourrait faire avec la table de triplets qu'on envisage pour Bazar objet

**Comment by J9rem** [comment]
Un nouveau template 'tableau' vient d'être déployé cet après-midi dans `doryphore`.
Il permet de faire un calcul dynamique de la somme d'une colonne à partir des données.
Ca répond en partie au besoin pour la somme.
Pour les autres calculs, le template est tout neuf donc il ne les a pas intégrés.

Si le nouveau template répond à la philosophie du besoin, nous pourrions alors clore la présente issue et n'ouvrir que des petites issues pour les ajouts de fonctionnalités sur le template tableau

**Comment by J9rem** [comment]
la PR #920 a permis d'introduire la possibilité de faire des calculs sur les valeurs champs avec la plupart des fonctions mathématiques:
`sin` `sinh` `cos` `cosh` `tan` `tanh` `abs` `acos` `acosh` `asin` `asinh` `atan` `atanh` `exp` `log10` `deg2rad` `rad2deg` `sqrt` `ceil` `floor` `round` `+` `-` `*` `/` `%` `^`

Je pense que ça résout une grande partie du besoin donc je clos l'issue.

Pour le deuxième besoin d'afficher les données sous forme de graph, je pense qu'il faudrait faire une issue spécifique en précisant exactement le type de graph voulu
