### ISSUE TITLE
[Bazarliste][Query] Impossible de faire une query avec plusieurs paramètres

### ISSUE THREAD

**Issue by toddoli** [YesWiki/yeswiki#397]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Si je suis la Doc [DocQuery](https://yeswiki.net/?DocQuery) Je devrais pouvoir faire:
`{{bazarliste id="7" query="listeListeStatutincident=1|listeListeStatutincident=2|listeListeStatutincident=3|listeListeStatutincident=4|listeListeStatutincident=5"}}`
ou
`{{bazarliste id="7" query="listeListeStatutincident=1,2,3,4,5"}}`
Or ni l'un ni l'autre ne fonctionnent. J'ai un filtre vide Par contre avec une seule clé c'est à dire
`{{bazarliste id="7" query="listeListeStatutincident=1"}}`
Ça fonctionne bien.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
Cercopithèque

**Comment by mrflos** [comment]
corrigé sur la version 2019-08-15-1
