### ISSUE TITLE
Champ obligatoire pas controlé sur checkbox

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#398]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Dans formulaire bazar - si checkbox obligatoire on a bien la présence de l'étoile en saisie mais on peut valider sans rien cocher

**Additionnal informations / Informations complémentaires**
- version of YesWiki / Version du Wiki : 2019-06-28-1 
- url to see the problem or an example / https://foodtroc-pnrse.fr/?InscriptionFoodtroc

**Comment by mrflos** [comment]
corrigé sur la version 2019-08-15-1
