### ISSUE TITLE
Impossible d'éditer une page depuis la 2019-08-15-1

### ISSUE THREAD

**Issue by toddoli** [YesWiki/yeswiki#400]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Depuis la MàJ en 2019-08-15-1 il est impossible d'éditer et sauvegarder n'importe quelle page. Lorsque l'on clique sur "Sauver" la réponse est systématiquement 

> La page ne peut pas être enregistrée.
Vous avez peut-être double cliqué sur le bouton "Sauver", entrainant 2 sauvegardes consécutives trop rapprochées, ou laissé la page ouverte en mode édition trop longtemps.
Pour enregistrer vos modifications, veuillez copier le contenu, rafraichir la page et coller votre page modifiée à nouveau.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
2019-08-15-1

**Comment by mrflos** [comment]
Ok, my mistake, fixed in 2019-08-15-1
