### ISSUE TITLE
Ne pas remplacer les favicons lors des mises à jour 

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki#401]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Lorsqu'on fait une mise à jour, on remplace systématiquement les favicon (en tout cas, c'est ce que j'ai constaté).
Il serait intéressant pour les gens qui ont modifié leur wiki en lui appliquant une favicon spécifique, de pouvoir conserver celle-ci.
Donc, lors des mises à jour, 
_- ne pas écraser les favicons du wiki,_
ou (mais c'est plus compliqué à mettre en œuvre mais c'est une idée comme ça)
_- offrir à un moment lors de la mise à jour, à côté du bouton "mettre à jour" un bouton "mise à jour personnalisée" qui offre le choix (checkbox) des choses à remplacer ou pas (favicon, templates, ou je ne sais quoi)._
ou (c'est plus dans l'esprit de ce qu'on fait par ailleurs sur YesWiki)
_- prévoir un endroit où mettre les favicons spécifiques (endroit où on va les chercher en priorité et qui n'est pas écrasé lors des mises à jour, cf. templates bazar spécifiques)._

**Comment by mrflos** [comment]
Je suis pour la troisième option, avec une action dans les thèmes genre {{favicon file="favicon.png"}} qui regarde si le fichier existe dans files/favicons et sinon se reporte sur le fichier dans le theme.

Idéalement, il faudrait dans l'admin de yeswiki avoir une action {{adminfavicon}} réservée aux admins qui permette l'upload du favicon au bon endroit.

**Comment by sylvainboyer** [comment]
Je comprends la seconde phrase.
En ce qui concerne la première, je ne vois pas ce que tu cherches à faire (affecter une favicon pour la page en cours uniquement ?)

**Comment by J9rem** [comment]
En fait, si tu as un thème margot.
En mettant les favicons dans le dossier `custom/themes/margot/images` normalement ça reste présent à chaque mise à jour.

**Comment by sylvainboyer** [comment]
Génial.
Merci les gars :1st_place_medal:
