### ISSUE TITLE
Le générateur de widget de bazar ne fonctionne plus

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#407]
Bug / Bogue

**Description**
Dans bazar, la page qui permet de générer un widget à partir d'un formaulaire bazar ne fonctionne plus.
Au lieu d'afficher une prévisualisation des données dans la partie de droite, il est afficher la liste des formulaires bazar.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : 2019-08-21-1  (mais également constaté sur version 2019-09-10-1 )
- exemple sur ce wiki https://adrets-asso.fr/?BazaR/widget&id=5
- screenshot / capture d’écran
![Capture widget bug](https://user-images.githubusercontent.com/37141192/67161500-77dc2380-f35b-11e9-8379-b609cfccd37a.PNG)
- logs

**Comment by mrflos** [comment]
corrigé!
