### ISSUE TITLE
Afficher la page TableauDeBord génère une erreur MySQL

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki#411]
**Type of issue / Type de demande**
Bug / Bogue

**Description**
- Sur au moins deux Wikis installés récemment, lorsqu'on cherche à afficher la page TableauDeBord, on obtient une erreur du type `Query failed: SELECT body FROM asso_pages WHERE latest = 'Y' AND comment_on='' AND body LIKE '{"%' AND tag IN (SELECT DISTINCT resource FROM yeswiki_triples WHERE value = "fiche_bazar" AND property = "http://outils-reseaux.org/_vocabulary/type") (Table 'assoatabpnyes.yeswiki_triples' doesn't exist)`.
- Problème signalé également sur le forum YesWiki [là](https://yeswiki.net/forum/?qa=1802/query-failed-select-body-from-yeswiki_cercopitheque__pages&show=1802#q1802).
- La page s'affiche avec les handlers `/raw` ou `/edit`.
  Si on la modifie avec le `/edit`, le problème persiste.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
  - yeswiki-cercopitheque-2019-08-19-1
  - yeswiki-cercopitheque-2019-08-21-1
  - yeswiki-cercopitheque-2019-09-10-1
- url to see the problem or an example / url pour voir le probleme ou un exemple
  https://assoatable.org/?TableauDeBord
- screenshot / capture d’écran
![screenshot20191024](https://user-images.githubusercontent.com/26927575/67478214-e4a53580-f65b-11e9-8625-5a7a66766987.png)

**Comment by mrflos** [comment]
c'est corrigé dans la dev je pense

**Comment by sylvainboyer** [comment]
Ce qui met en évidence que lors des revues de release, il faudra mentionner le cas échéant dans chaque issue la release par laquelle elle est traitée.

**Comment by mrflos** [comment]
yes, en l'occurence le commit a un titre explicite, https://github.com/YesWiki/yeswiki/commit/4b0ce90571d811567bce8f4b78c76a92213702d8#diff-0b759b37993565879ba6c9cfefe16175 mais il nous faudrait releaser plus souvent..

**Comment by sylvainboyer** [comment]
Bon, on tient le bon bout :-)
