### ISSUE TITLE
L'action bazarlisteexterne ne fonctionne plus

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#417]
Bonjour, 
L'action bazarlisteexterne documentée ici (https://yeswiki.net/?ActionBazarliste) ne fonctionne pas. 
Elle ne renvoie que les titres des fiches et pas leur contenus, comme on peut le constater là : https://formations.osons.cc/dla93/?PagePanel . 
Bonne journée !
Romain

**Comment by J9rem** [comment]
Et toujours pas avec Doryphore 2021-02-04-2

**Comment by J9rem** [comment]
En cours, .... branche dédiée de travail

**Comment by J9rem** [comment]
L'action a été remplacée sur doryphore par une amélioration de bazarliste : https://yeswiki.net/?ActionBazarlisteDonneesExternes
Je me permets de clore l'issue donc.

**Comment by acheype** [comment]
je me suis permis de corriger de simples fautes de frappe dans la doc.
il reste ligne 50 :  `- la formule entrée dans le paramètre //id// de %%""{{bazarliste id="}}""%% est %%https://www.example.com|z->y%%` qui semble avoir un soucis avec les ""

**Comment by J9rem** [comment]
C'est corrigé. Merci pour ta vigilance @acheype
