### ISSUE TITLE
Syntaxe tableau non reconnue

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#418]
J'ai installé deux wikis tout frais : 
 - un depuis le dépôt github branche cercopitheque
 - un depuis l'archive du site

Dans les deux cas la syntaxe pour faire des tableaux n'est plus reconnue et s'affiche telle quelle.
Testé avec l'exemple présent dans la documentation du site.

php 7.3 dans les deux cas mais cela fonctionne avec cette version pour des versions plus anciennes de YesWiki.

**Comment by mrflos** [comment]
hello, c'est corrigé dans la dev, mais on ne va pas sortir rapidement de nouvelle version de cercopitheque car des gros travaux sont en cours...  

tu peux patcher l'expression régulière  a la dernière ligne de tools/tableaux/formatters/wakka__.php :
```php
$plugin_output_new = preg_replace_callback("/(\[\|.*?\|\])/msu", 'wakka2callbacktableaux', $plugin_output_new);
```

**Comment by fbredow** [comment]
Ça ne semble pas résoudre le problème. La fonction callback n'est pas appelée.
J'ai aussi tenté de changer le fichier par celui de la version cercopitheque_dev.

Je rate quelque chose ?

**Comment by mrflos** [comment]
bizarre . apparement seul le ^ a été enlevé de l'expression et le flag unicode ajouté cf. https://github.com/YesWiki/yeswiki/commit/5d0537d2f24abed2bb740bc25db712acac724803#diff-21243474d785baa957a01c3bc0a5a251
