### ISSUE TITLE
redirection d'une fiche bazar après modification ou suppression

### ISSUE THREAD

**Issue by FredOdass** [YesWiki/yeswiki#421]
une fois une fiche modifiée et validée on arrive sur la page de la fiche : ce serait bien d'arriver sur une page qu'on pourrait choisir, du type redirecturl pour les formulaires

**Comment by J9rem** [comment]
Bonjour @FredOdass ,
je ne sais pas si nous parlons de la même chose.
Dans la plupart des versions YesWiki cercopitheque ou doryphore, il est possible de configurer l'action bazar comme ceci.
`{{bazar voirmenu="0" vue="saisir" id="1" redirecturl="http://localhost/?PagePrincipale" }}`
(voir [documentation](https://yeswiki.net/?BazarAfficherFormulaireSaisie))

Est-ce que ça correspond à l'issue ou est-ce que la demande est d'ajouter un nouveau champ dans un formulaire pour pouvoir configurer une redirection pour chaque fiche qui est appelée à la fin de la modification d'une fiche ?
