### ISSUE TITLE
suppression de plusieurs fiches bazar

### ISSUE THREAD

**Issue by FredOdass** [YesWiki/yeswiki#422]
Nouvelle fonctionnalité

supprimer plusieurs fiches bazar en même temps serait bien pratique (par exemple lorsqu'on a fait plusieurs tests de nouveaux formulaires).

**Comment by J9rem** [comment]
Salut @FredOdass ,

avec la dernière version de Doryphore, est-ce que tu confirmes que la nouvelle fonction de suppression de toutes les fiches d'un formulaire répond à ton besoin ?

**Comment by mrflos** [comment]
Je croies que le besoin de @FredOdass ,  ce n'est pas de tout supprimer (ce qui est en effet possible avec l'icone gomme dans l'interface bazar des formulaires), mais de supprimer un ensemble de fiches sélectionnées.

**Comment by J9rem** [comment]
Je vais profiter de cette issue pour parler spécification pour la suppression groupée de plusieurs fiches.
Le nouveau template [`tableau.tpl.html`](https://github.com/YesWiki/yeswiki/blob/doryphore/tools/bazar/presentation/templates/tableau.tpl.html) permet d'afficher toutes les fiches sous forme de tableau avec les facettes et d'avoir les boutons modifier/supprimer en bout de ligne (facultatif).
Il serait possible d'ajouter quelques choses pour faciliter la suppression groupée de plusieurs fiches.

Je propose:
 - [x] ~~ajouter un bouton en haut de la colonne d'administration "Suppression groupée"~~
 - [x] ajouter un bouton en **bas** de la colonne d'administration "Suppression groupée"
 - [x] ajouter en haut de cette colonne une case "cocher tout"
 - [x] ajouter en bas de cette colonne une case "cocher tout"
 - [x] ~~ajouter en fin de chaque ligne une case à cocher que si l'utilisateur est propriétaire de la page ou admin~~
 - [x] ajouter en **début** de chaque ligne une case à cocher que si l'utilisateur est propriétaire de la page ou admin
 - [x] ~~lors du clic sur "Suppression groupée" un script `javascript` affiche une message de confirmation avec la liste des pages à supprimer~~
 - [x]  lors du clic sur "Suppression groupée" un script `javascript` affiche une message de confirmation **sans** la liste des pages à supprimer **mais avec les termes "pages sélectionnées" en popup/modal**
 - [x] si confirmation, le script `javascript` fait des requêtes `DELETE`sur la route `?api/pages/{tag}`
 - [x] pendant l'exécution du script, le contenu de la fenêtre modale est mis à jour avec une barre de progression de type bootstrap
 - [x] pendant l'exécution du script, le contenu de la fenêtre modale est mis à jour avec les erreurs éventuelle
 - [x] ~~en fin de script, affichage via `toast` d'un message indiquant la liste des pages correctement supprimée pendant 4s.~~
 - [x] en fin de script, la modale ne se ferme pas automatiquement
 - [x] ~~puis rechargement de la page active pour rafraîchir la liste~~ 
 - [x] à la fermeture de la modale, la page est rechargée (et non mise à jour via jquery pour avoir des données à jour)
 - [x] ~~si erreur, il y a affichage d'un message fixe avec la liste des suppressions corrects et celles des suppressions ratées, lors du clic de sortie de ce message, il y a rafraîchissement de la page.~~
 
 Qu'en pensez-vous ? @mrflos @acheype 
 Je cocherai la case pour chaque point quand nous aurons eu un échange suffisant pour définir le statut comme accepté ou refusé ou modifié. Je mettrai en barré les propositions non retenues ou modifiées.

**Comment by acheype** [comment]
Tes specs me semblent bien convenir. Je me demande juste si c'est utile de lister toutes les pages lors de la confirmation de la suppression avec le toast de 4s. Ca ne risque pas de faire un peu chargé niveau texte ? Mentionner uniquement "les pages sélectionnées" me paraîtrait suffisant.

**Comment by J9rem** [comment]
@acheype remarque pertinente sur le toast message. je prends

**Comment by mrflos** [comment]
Hello je me permet de proposer des ajustements UI/UX a prendre ou a laisser en fonction du temps disponible pour le faire. Les grandes lignes, faire un peu comme phpmyadmin, et passer d'un toast a une modale, qui permet de mieux suivre le déroulement de l'action (important pour une action d'admin, et le toast si on n'est pas attentif pendant les 4s, on loupe l'info) :

> - ajouter un bouton en haut de la colonne d'administration "Suppression groupée" 

il faut mieux mettre les bouton d'action en bas du tableau, c'est plus logique car il faut parcourir le tableau pour sélectionner les pages et donc le mettre a la fin est cohérent. Aussi ya moins de "pollution" visuelle en haut du tableau pour celleux qui viennent juste explorer le tableau (le bouton de suppression peut faire peur)

> - ajouter en haut de cette colonne un case "cocher tout" 

du coup c'est bien de l'avoir en haut et une deuxieme en bas (comme phpmyadmin)

> - ajouter en fin de chaque ligne une case à cocher que si l'utilisateur est propriétaire de la page ou admin 

plutot en début de ligne, non? comme phpmyadmin

> -  lors du clic sur "Suppression groupée" un script javascript affiche une message de confirmation avec la liste des pages à supprimer

YES une popup plutôt (voir la suite)

> - si confirmation, le script javascript fait des requêtes DELETEsur la route ?api/pages/{tag} 

YES

> - en fin de script, affichage via toast ... 

pour moi il faut rester sur la popup de confirmation active et mettre une barre de progression qui est le composant progress bar de bootstrap (comme ca a chaque retour de requete ajax de progression, tu augmente le % de progression et si erreur, tu l'affiches dans la popup)

> - puis rechargement de la page active pour rafraîchir la liste 

du coup c'est plutôt un bouton de fermeture qui apparait pour fermer la modale. Idéalement lors du clic de fermeture de modale, on pourrait effacer en jquery les lignes concernant les pages pour eviter de recharger la page

> - si erreur, il y a affichage d'un message fixe avec la liste des suppressions corrects et celles des suppressions ratées, lors du clic de sortie de ce message, il y a rafraîchissement de la page 

du coup c'est déja visible dans la popup dans ma proposition

**Comment by J9rem** [comment]
Waouh super tes apports @mrflos tout me va

**Comment by J9rem** [comment]
@mrflos @acheype , j'ai mis à jour la proposition en cochant les cases pour les lignes qui semblaient validées pour acceptation ou modification/suppression, j'ai barré les propositions retirées ou modifiées, j'ai ajouté avec une case non cochée, les nouveautés.

Qu'en dites-vous ?
j'ai une préférence pour forcer le rechargement de la page à la fermeture de la modale plutôt que de faire un nettoyage en jquery car ce sera pas assez stable à mon goût (est-ce qu'il y a plusieurs tables ? gestion des filtres, ....bref trop de cas de tests) pour la maintenance c'est beaucoup plus simple de recharger

**Comment by J9rem** [comment]
Pour l'histoire du rafraîchissement des données via jquery, je préfère attendre qu'on passe ce template en dynamic.
une fois que ce sera fait, ce sera alors très facile de rafraîchir des données locales sans erreur.

**Comment by mrflos** [comment]
Oui ok pour moi, c'est vrai qu'en vuejs ce sera bien plus facile, et merci d'avoir intégré mes suggestions, et d'avoir proposé ce temps de specs! <3

**Comment by J9rem** [comment]
Je clos cette issue vu que la fonctionnalité est fusionnée dans doryphore-dev
