### ISSUE TITLE
update efface le contenu de /custom/themes

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki#427]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lorsqu'on fait une mise à jour du wiki, cela efface le contenu de /custom/themes. On perd donc les personnalisations.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki 2019-12-09-1

**Comment by sylvainboyer** [comment]
Pour moi, c'est corrigé lors d'un passage de cercopitheque 2020-06-05-1 en doryphore 2020-10-13-1
@mrflos, penses-tu que le problème soit réglé est qu'il faille clore cette issue ?

**Comment by mrflos** [comment]
yes, je clos, merci
