### ISSUE TITLE
Impossible de cocher les cases de la page droit d'accès sous le thème Margot

### ISSUE THREAD

**Issue by Zheelnat** [YesWiki/yeswiki#428]
Tout est dans le titre.

**Comment by J9rem** [comment]
Bonjour @Zheelnat ,
est-ce que ce problème est survenu avec la version Cercopitheque ou Doryphore  de YesWiki ?
_Pour le savoir, rendez-vous sur la page `Gérer site`_

**Comment by Zheelnat** [comment]
Salut Jérémy,
C'est Antoine de zoomacom. On s'était vu à Vedène.
Je sais plus trop j'ai fait remonter cette issue y'a déjà pas mal de temps.
Du coup je dirais cerco.
Bonne journée.

**Comment by J9rem** [comment]
Salut Antoine,

effectivement, sous cercopithèque avec le thème Margot, il y avait un souci avec les cases à cocher à certains endroits.
Il y a eu des modifications de thème Margot ces derniers temps qui ont a priori corrigé ces soucis.
Est-ce que tu pourrais faire une mise à jour du thème margot avec ta session cercopithèque pour voir si ça résout le souci ?

Sinon si le problème persiste, vu que nous ne faisons plus que les correctifs de sécurité sur cercopithèque, je te propose de:
- soit passer sur Doryphore si c'est possible pour toi
- soit changer le thème associé à cette page et choisir par exemple le thème Colibris. C'est ce que je faisais avant de passer sous Doryphore, j'allais dans 'éditer la page'>'thème'>...

SI ceci te convient et résout ton problème, je te laisse clore cette issue ou m'indiquer que je peux la clore (si tu n'en as pas les droits).
sinon je veux bien des détails sur le bug.
