### ISSUE TITLE
Une seule {{bazarliste}} possible par page sans changer de template

### ISSUE THREAD

**Issue by Djiock** [YesWiki/yeswiki#429]
** Type de demande **
Bug / Bogue

**Description**
Sur notre YesWiki depuis la mise à jour en PHP 7.3 et dans la foulée celle de YesWiki en 2019-12-09-1 nous nous sommes aperçu que sur des pages où nous affichions des {{bazarliste}} avec requêtes sur Bazar seule la première de ces balises fonctionnait...
Après de longues recherches et aucune entrée log correspondante (Apache ou PHP, mode ALL) j'ai vu que si on change de template à chaque balise, là ça s'affiche. Mais il suffit de vouloir remettre un template juste une fois supplémentaire pour que la balise avec ce nouvel appel template ne s'affiche pas. Dans la source on voit que rien n'est généré, comme si YesWiki ne parsait pas la balise.
Donc pour pouvoir utiliser le même template la solution que j'ai trouvée est de dupliquer les fichiers tpl.html voulus et les appeler un par un dans les balises.
Comme j'ai indiqué je ne vois aucune erreur dans les logs PHP et Apache sur le serveur, rien d'anormal excepté l'absence des <div> de la liste voulue dans le HTML.
J'ai testé avec les thèmes par défaut, idem.

**Informations complémentaires**
- version de YesWiki : 2019-12-09-1
- url pour voir le problème ou un exemple : https://transition.enercoop.fr/GrosElectro (page avec le contournement), je peux fournir un accès à notre serveur de test avec une page sans le contournement au personnes qui aimeraient vérifier.
- logs : si seulement...

**Comment by sylvainboyer** [comment]
@mrflos J'ai constaté ça aussi. 
Sais-tu 
- si c'est corrigé dans Doryphore et 
- sinon, où je dois regarder pour réparer ?

**Comment by mrflos** [comment]
cela semble marcher sur une version doryphore cf. https://yeswiki.net/?TestBazarListeMultiple
https://yeswiki.net/?TestBazarListeMultiple/raw

**Comment by sylvainboyer** [comment]
Nickel !
Donc Issue à clore à la sortie de Doryphore

**Comment by mrflos** [comment]
Merci pour ce rapport détaillé @Djiock en tout cas, et désolé que cela ne produise pas d'erreur
j'essaye de trouver le commit qui fait la résolution de bug, mais y en a trop en la version cercopitheque et celle de dev...
Si vous avez un environnement pour tester, peut être passer sur la version cercopitheque du 29 février (dernière stable)?

**Comment by sylvainboyer** [comment]
J'ai constaté le problème justement sur une cercopithèque dernière version du  2020-02-29-1.

**Comment by Djiock** [comment]
@sylvainboyer merci ça m'évite le test ;)
@mrflos l'essentiel c'est que le contournement fonctionne ! En attente de Doryphore donc, ou peut-être une nouvelle Cercopithèque. Merci !
