### ISSUE TITLE
souci de filtre facette sur [idtypeannonce]

### ISSUE THREAD

**Issue by hadide** [YesWiki/yeswiki#430]
Il semble que lorsqu'on utilise un filtre facette sur idtypeannonce (parce que plusieurs formulaires sont appelés), tous les formulaires du wiki apparaissent dans le filtre, pas uniquement ceux appelés dans l'action bazar.
Exemple :
`{{bazar voirmenu="0" vue="consulter" id="2,7,9,12" colorfield="id_typeannonce" color="orange = 2, green = 7, blue = 9, red = 12" template="map.tpl.html" groups="checkboxListeTerritoireProJeunesse,id_typeannonce" titles="Territoires,Type d'acteur" filterposition="left"}}`
 je me retrouve avec tous les formulaires du wiki, pas uniquement les 2,7,9 et 12
https://reseaujeunesse73.fr/?PageTestActeurs

**Comment by mrflos** [comment]
réparé depuis
