### ISSUE TITLE
email.inc.php ne gère pas le champ From correctement (en mode SMTP)

### ISSUE THREAD

**Issue by gagzzz** [YesWiki/yeswiki#431]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Le champ From: d'un email est vérifié par l'opérateur lors d'envois en SMTP, or YesWiki met le contenu entré par l'utilisateurice dans ce champ et ne vérifie pas la réponse du serveur, affichant donc "votre message a bien été envoyé" même lorsque le serveur le refuse.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : fraichement installée en octobre 

Pour résoudre ce problème sur mon yeswiki j'ai édité email.inc.php et — ligne 58 — changé ça:
```
//original:  $mail->setFrom($mail_sender, $name_sender);
$mail->setFrom($addresse_mail, $name_sender + ' ($mail_sender)');
```
où $adresse_mail est l'adresse indiquée dans wakka.config.php, à la ligne "contact_smtp_user".

Pouvez-vous rendre ce comportement par défaut?
Ça permettrait aussi de mieux gérer les spams (envoyer depuis le serveur via php entraine souvent une mise en spam).

merci!

**Comment by mrflos** [comment]
Bonjour,
Merci de cette proposition!  
Dans ce cas, lorsqu'on recoit le mail, l'émetteur est il bien $mail_sender plutot que le user smtp et quand on lui répond, la réponse est elle bien envoyée à $mail_sender plutot que le user smtp ?

**Comment by gagzzz** [comment]
Salut,
j'ai corrigé l'issue car j'avais loupé un saut de ligne donc comprendre ma modif était difficile.

En gros de nos jours il est très malvenu de mettre n'importe quoi dans "From:", en raison de la lutte antispam. Donc plutôt que d'avoir un "From:" rempli par l'user envoyant un message, on le set en dur (avec la variable $addresse_mail que l'on rempli dans wakka.config.php), et le nom affiché est le nom entré par l'user et son email entre parenthèses.

Et ça serait top que ça soit comme ça par défaut lors de l'utilisation de smtp à la place des fonctions de mail de l'OS.

Par contre en effet, il faudrait aussi ajouter quelques champs, comme "Reply-to:" et y mettre $mail_sender afin qu'on puisse répondre facilement par mail.


Voilà, je peux apporter des précisions si besoin mais je n'aurais pas la motiv de patcher du code ni de contribuer autrement!

merci!

**Comment by acheype** [comment]
Salut gagzzz,

Jette un oeil ici, ça devrait t'intéresser ;)
https://github.com/YesWiki/yeswiki/pull/439

Le fix est sorti avec la dernière version Doriphore.

**Comment by gagzzz** [comment]
Merci, on peut continuer dans la MR directement.
