### ISSUE TITLE
{{editgroups}} Mise en forme / ergonomie

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#432]
Bonjour, 
Pour doryphore, il serait bien d'avoir une vue tableau des groupes, avec des boutons de gestion (supprimer, ajouter,...) en bout de ligne, à la manière de la table des utilisateurs.

**Comment by sylvainboyer** [comment]
@RomainLalande Peux tu décrire de manière plus précise comment tu verrais ce tableau ? qu'y a-t-il en lignes ? et en colonnes ? Quelles actions possibles ?

**Comment by RomainLalande** [comment]
> @RomainLalande Peux tu décrire de manière plus précise comment tu verrais ce tableau ? qu'y a-t-il en lignes ? et en colonnes ? Quelles actions possibles ?

J'imaginerais en colonne : 
 - nom du groupe
 - Noms des membres (bonus - avec une petite croix à coté de chaque pour les supprimer en direct)
 - Champs texte à remplir avec bouton "ajouter cet utilisateur" (bonus - auto-complétion à partir des user existants)
 - Bouton "supprimer ce groupe

Mes 2 cts

**Comment by sylvainboyer** [comment]
@RomainLalande , comme ça ?
| Groupe | Membres | Ajouter un membre | Actions |
| :--------- | :--------- | :--------- | :--------- |
| admins | MrFlos[-], RomainLalande[-] | (saisir un nouveau membre)[+] | [Supprimer ce groupe] |
| test | MrFlos[-], RomainLalande[-], SylvaiN[-] | (saisir un nouveau membre)[+] | [Supprimer ce groupe] |
|  |  |  | (saisir un nouveau groupe)[Ajouter un groupe] |

**Comment by RomainLalande** [comment]
Exactement ! <3

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/12/ameliorer-lux-sur-ladmin-de-yeswiki
