### ISSUE TITLE
Gitignore mess

### ISSUE THREAD

**Issue by nervo** [YesWiki/yeswiki#434]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Some files/directories are in the git repository or in the zip release, but are also git ignored.

* `tools/autoupdate/vendor/twig/twig/vendor` and `tools/autoupdate/vendor/twig/twig/composer.lock` are in the zip release, but git ignored here: https://github.com/YesWiki/yeswiki/blob/cercopitheque/tools/autoupdate/vendor/twig/twig/.gitignore

* `tools/autoupdate/composer.lock` is both on git master and in the zip release, but git ignored here https://github.com/YesWiki/yeswiki/blob/cercopitheque/tools/autoupdate/.gitignore

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
git master and/or 2019-12-09-1 zip release

**Comment by mrflos** [comment]
as we generate our zip with external tools, i'm not sure of what should be included or not in the repository:
- for the zip release on https://repository.yeswiki.net/cercopitheque/ it's normal to have the files in vendor and the autoload available, as this zip should be "plug and play" ;)
- for the files in the git repository, i'm ok to make it without the composer.lock and vendor, but we should  add instructions about where devs should use `composer install` to make the autoupdate work.

Do you have any suggestion about this ?
