### ISSUE TITLE
Point d'interrogation manquant dans l'URL

### ISSUE THREAD

**Issue by mbrasebin** [YesWiki/yeswiki#436]
Bonjour,

j'ai installé YesWiki pour tester en suivant cette documentation : https://yeswiki.net/?DocumentationInstallation
avec la version yeswiki-cercopitheque-2019-12-09-1 et j'ai un problème dans la prise en compte des URL.

En effet, lorsque l'installation se termine ou que je clique sur un lien du wiki, le ? qui se trouve après le /  n'apparaît pas dans l'URL ce qui fait que je me retrouve avec une erreur 404 à chaque fois que je navigue.
C'est à dire que j'ai ce genre de lien : http://localhost/testwikidata/PagePrincipale
au lieu de http://localhost/testwikidata/**?**PagePrincipale
Les pages fonctionnent en tapant directement la bonne URL.

Le problème apparaît aussi bien pour une installation sous Debian que sous Windows (avec Wamp). Dans les 2 cas je suis en PHP 7.3.

J'ai trouvé un moyen de contourner le problème en ajoutant un ? dans le fichier wakka.config.php 
  'base_url' => 'http://localhost/testwikidata/?'
Mais j'imagine que je ne suis pas supposé toucher à ça.

Je ne sais pas si c'est un bug, une configuration qui doit être changée dans le serveur ou un mauvais suivi de la documentation :).

Merci d'avance pour vos retours,

Mickaël Brasebin

**Comment by mrflos** [comment]
Bonjour, désolé du temps de réponse..  
Non, c'est normal de mettre le ? dans la base_url, ce qui est étrange, c'est qu'il ne l'a pas fait tout seul à l'installation : normalement par défaut il ajoute le ? a l'url du site
