### ISSUE TITLE
Permettre d'ajouter les couleurs ou icônes aux facettes

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki#440]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Quand on appelle des facettes avec les paramètres `iconfield` et `icon` ou `colorfield`, `color`, ce serait chouette d'avoir un paramètre optionnel en plus, par exemple `legend` (par défaut à 0).
Si `legend="1"`, alors un affiche dans les facettes les icônes et/ou couleurs définies dans les champs `icon` ou `color`.
On pourrait afficher, l'icône (dans le cas où `iconfield` est défini), ou un carré ou un rond dans la couleur (dans le cas ou seul `colorfield` et `color` sont définis) juste entre la case à cocher et le libellé.

**Additionnal informations / Informations complémentaires**

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/40/permettre-dajouter-les-couleurs-ou-icones-aux-facettes
