### ISSUE TITLE
Rendre les facettes avec `radiofiches` opérationnelles

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki#441]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Aujourd'hui les facettes sont opérationnelles pour une `listefiches`, mais pas pour une `radiofiches`. Dans ce cas, la facette s'affiche, mais ne fonctionne pas.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki => 2020-02-29-1

**Comment by J9rem** [comment]
@sylvainboyer je crois que ça fonctionne maintenant avec radiofiche

**Comment by sylvainboyer** [comment]
Je dois tester ou ça a déjà été fait ?

**Comment by J9rem** [comment]
Disons, que je n'ai pas exactement compris le bug avec les facettes. J'ai fait mes tests mais dans le doute, je préfèrerais que tu testes dans le cas où tu avais le souci pour m'assurer que c'est bien résolu dans ton contexte.

**Comment by sylvainboyer** [comment]
En fait, c'est un vieux machin, que je n'ai posé là que pour Doryphore.
Les facettes ne fonctionnaient pas correctement avec les champs radio (que ce soit avec une liste ou un formulaire). Je crois qu'il manquait un bout de code dans cercopitheque. Si les facettes sont implémentées pour les champs radio, alors c'est bon pour moi. Et je testerai la prochaine fois que j'ai un cas qui s'y prête (jusqu'à présent j'utilisais des listes dans ce genre de cas. Pas terrible)
