### ISSUE TITLE
Mettre un groupe dans un groupe et vice versa pour les droits d'accès fait planter le wiki

### ISSUE THREAD

**Issue by HPlesGravions** [YesWiki/yeswiki#442]
Warning: include_once(tools/syndication/lang/syndication_fr.inc.php): failed to open stream: No such file or directory in /web9/hplesgravillons/www/wiki/tools/syndication/wiki.php on line 13

Warning: include_once(): Failed opening 'tools/syndication/lang/syndication_fr.inc.php' for inclusion (include_path='tools/googledrive/libs/vendor/:.:/usr/local/lib/ZFramework') in /web9/hplesgravillons/www/wiki/tools/syndication/wiki.php on line 13

Fatal error: Allowed memory size of 205520896 bytes exhausted (tried to allocate 130968 bytes) in /web9/hplesgravillons/www/wiki/includes/YesWiki.php on line 1815

**Comment by mrflos** [comment]
ll faudra reproduire et voir comment empêcher le plantage intégral.

**Comment by mrflos** [comment]
Completed by #1138
