### ISSUE TITLE
Extension publication - Avoir comme un "panier de ressources"

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#445]
Hello, 

En testant publication, je me suis dit qu'une piste interessante d'évolution serait de pouvoir en naviguant sur un wiki ajouter avec un "+" à coter des fiches les fiches que l'on veut ajouter dans son panier, qui sont ainsi sauvegardée quand on va sur la page qui génère l'ebook.
Un peu comme e l'e-commerce quoi x)

Voilà voilà !

**Comment by mrflos** [comment]
je transfere sur les issues de publication
