### ISSUE TITLE
Warning affiché lors de l'affichage d'une fiche en mode /iframe

### ISSUE THREAD

**Issue by acheype** [YesWiki/yeswiki#449]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Le warning suivant est affiché : `Warning: preg_replace_callback(): Requires argument 2, 'encodingFromUTF8', to be a valid callback in /Users/adri/projects/yeswiki/tools/templates/libs/templates.functions.php on line 751`

**Additionnal informations / Informations complémentaires**
- cerco_dev

![image](https://user-images.githubusercontent.com/8435038/79262719-07d5d280-7e92-11ea-965a-21a7bfffbd2b.png)

**Comment by J9rem** [comment]
A priori, @acheype ce bug n'existe plus maintenant sous Doryphore ?

**Comment by acheype** [comment]
Oui c'est bon, je clos.
