### ISSUE TITLE
Affichage de textelong sans sauts de lignes

### ISSUE THREAD

**Issue by acheype** [YesWiki/yeswiki#450]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
On rentre dans un champ textelong, une première ligne, on saute une ligne et on écrit une deuxième ligne. Lors de l'affichage de la fiche, les sauts de lignes ne seront pas affichés dans le texte affiché.

**Additionnal informations / Informations complémentaires**
- cerco_dev

Cf champ **Formations ou expérience en lien avec la formation** qui devrait être affiché sur deux lignes :
![image](https://user-images.githubusercontent.com/8435038/79263514-40c27700-7e93-11ea-84e7-4b4616a31758.png)

**Comment by mrflos** [comment]
C'est pas un bug, c'est une fonctionnalité! (true story)

Pour éviter d'enregistrer des pages vides, yeswiki fait un trim sur les
contenus..

Si tu veux un saut de ligne, faut faire un truc genre :

`""""


saut de ligne après passage en html et sortie`

**Comment by acheype** [comment]
Ok pour le trim. Mais là, il y avait un **saut de ligne** entre _première ligne_ et _deuxième ligne_.

J'ai pas trop testé mais j'ai également l'impression que les mises en forme (si ajoutées sur le texte) ne sont pas prises en compte.

**Comment by sylvainboyer** [comment]
Je confirme qu'il s'agit d'un nouveau comportement qui oblige à saisir parfois, mais pas tout le temps, plusieurs retours à la ligne là où avant (et encore maintenant dans certains cas) il n'en faut qu'un.
Je n'ai pas encore trouvé la logique entre les différents cas.
Je me demande si ce n'est pas un comportement erratique de l'éditeur avec coloration syntaxique.

**Comment by acheype** [comment]
Je ne suis pas sûr qu'on parle du même soucis, car dans mon cas peu importe le nombre de ligne que tu sautes, il n'y a dans 100% des cas aucun retour à la ligne qui s'affiche.

Il manque à mon avis simplement un nl2br lors de l'affichage. Je n'ai pas pris le temps de regarder, et je me suis dit qu'en même temps, il devait y avoir un soucis de mise en forme quand l'utilisateur utilise la barre d'outil pour modifier le style. Et je n'ai pas bien compris le fonctionnement à ce niveau... ce sont de simples balises html qui sont alors insérées ?

**Comment by sylvainboyer** [comment]
Mon propos est que les nl2br ne sont pas aussi fréquents sur la version de dev
Il y a définitvement un truc à creuser et je soupçonne la coloration syntaxique.

**Comment by acheype** [comment]
Merci pour la précision. Si je comprends bien, tu parles toi de l'édition de page, et non de fiche bazar.

**Comment by sylvainboyer** [comment]
Oui, effectivement. J'avais mal lu ton message initial. Désolé.

**Comment by mrflos** [comment]
Je pense que maintenant ca marche!
