### ISSUE TITLE
[aceditor] Problème avec le bouton "Lien / Nouvelle Page" (cercopitheque)

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#457]
**Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lorsque je clique sur le bouton la fenêtre modale appairait bien. Mais lorsque je valide avec le bouton "insérer" le lien n'est pas ajouté dans la page.

**Informations complémentaires**
Remonté par une utilisatrice suite à la mise à jour d'un wiki et confirmé sur une installation fraîche de cercopithèque depuis github.

**Comment by J9rem** [comment]
Salut @daiko ,
la version cercopitheque n'est maintenu que pour les soucis de sécurité.
Est-ce que ce bug est aussi présent avec Doryphore ?
Sinon, nous risquons ne jamais corriger ce bug sur cercopitheque.
De plus, avec quel thème apparaît le bug ?

**Comment by fbredow** [comment]
Malheureusement je n'ai pas encore testé Doryphore. J'avoue ne pas être sûre depuis le temps mais il me semble que c'était avec le thème par défaut.

**Comment by J9rem** [comment]
Effectivement, la fonction en question (pourtant très utile), n'est présente que dans cercopitheque et pas dans Doryphore.
Il semble qu'il manque quelque chose dans [ACeditor.js#L644](https://github.com/YesWiki/yeswiki/blob/cercopitheque/tools/aceditor/libs/ACeditor.js#L644) pour que le lien soit recopié,

alors que dans Doryphore ça fonctionne [aceditor.js#L258](https://github.com/YesWiki/yeswiki/blob/doryphore/tools/aceditor/presentation/javascripts/aceditor.js#L258)

@mrflos es-tu OK pour que je fasse une tentative d'importation de ce module dans Doryphore en corrigeant le bug ?

**Comment by mrflos** [comment]
oui ca serait bien d'avoir l'interface pour les liens aussi dans doryphore, mais du coup il manque en effet l'insertion finale vers la textarea, qui se fait sans doute tres différement entre cerco et dory, vu que l'éditeur a changé..

**Comment by J9rem** [comment]
OK j'ai presque trouvé pour faire le correctif pour cercopitheque.
@mrflos serais-tu OK pour qu'exceptionnellement on déploie ce correctif ?
Puis je crée une Issue associée pour que nous pensions à le transférer dans Doryphore avec le tag : new-feature ou équivalent et nous arbitrerons plus tard pour savoir si elle fait partie des nouvelles fonctionnalités.

C'est pas trop différent sur Doryphore mais il y a quelques petits détails et tests à faire en plus.
Qu'en dis-tu ?

**Comment by mrflos** [comment]
Totalement pour, c'est un bug génant dans cercopitheque, et j'ai ma part de responsabilité dedans..  
Merci d'avoir regardé!

**Comment by J9rem** [comment]
résolu par #629 
et création de l'issue #630 pour ne pas oublier de mettre le menu dans doryphore
@daiko je te laisse testerquand il y aura un déploiement de la nouvelle version de cercopitheque puis clore cette issue

**Comment by J9rem** [comment]
a priori c'est résolu (par plusieurs testeurs)
