### ISSUE TITLE
[Bazar] Pb structure table nature suite MAJ (cercopitheque)

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#458]
**Type de demande** : Bug

**Description**
Suite à une mise a jour vers la dernière version de cercopitheque depuis un cercopitheque installé il y a un an. L'ajout d'un nouveau formulaire n'est pas possible.
L'erreur suivante apparaît : 
```sql
Query failed: INSERT INTO anicare_nature (`bn_id_nature` ,`bn_ce_i18n` ,`bn_label_nature` ,`bn_template` ,`bn_description` ,`bn_condition`) VALUES (1, "fr-FR", "VimeoVideos","texte***bf_titre***Nom prénom***255***255*** *** *** ***1***0***", "Videos hébergées sur Viméo", "") (Field 'bn_type_fiche' doesn't have a default value)
```
En regardant la base de donnée, la structure de la table nature a changé. Il y a beaucoup moins de champs.
Sur mon wiki en prod : bn_id_nature, bn_label_nature, bn_description, bn_condition, bn_ce_id_menu, bn_commentaire, bn_appropriation, bn_image_titre, bn_image_logo, bn_couleur_calendrier, bn_picto_calendrier, bn_template, bn_ce_i18n, bn_type_fiche, bn_label_class

Sur une installation fraiche : bn_id_nature, bn_label_nature, bn_description, bn_condition, bn_template, bn_ce_i18n

**Infos supplémentaire** ;
J'installe et je mets à jour depuis github avec git et je suis bien dans la branche cercopitheque.
Je n'ai pas trouvé d'infos à propos de ce changement dans la documentation. (https://yeswiki.net/?DocumentationMiseAJour)

[edit]Changer la structure de la table nature résout le problème. Sur ce site bazar n'est pas encore utilisé donc c'est facile. Le problème va être pour les sites ont déjà du contenu dans bazar.[/edit]

**Comment by mrflos** [comment]
Sur la version doryphore, il y a un handler /update pour gérer les changements de tables, sur la version cercopitheque, peut etre il manque un lien vers https://yeswiki.net/?RetablirUnBonFormatDeTableQuandOnAUnN ou un détail dans le changelog

**Comment by mrflos** [comment]
le handler /update a été intégré à cercopitheque version du 24 mai, il devrait faire les changements dans la bdd

**Comment by fbredow** [comment]
Super ! je teste dès que possible. merci

**Comment by sylvainboyer** [comment]
Le handler /update ne règle pas tout !
Sur un wiki passé de cercopitheque 2020-06-05-1 en doryphore 2020-10-13-1 *via* `{{update version="doryphore"}}, lorsque j'actionne le handler /update, j'obtiens une page blanche avec : 
```
Query failed: ALTER TABLE reseau__nature DROP IF EXISTS `bn_ce_id_menu`, DROP IF EXISTS `bn_commentaire`, DROP IF EXISTS `bn_appropriation`, DROP IF EXISTS `bn_image_titre`, DROP IF EXISTS `bn_image_logo`, DROP IF EXISTS `bn_couleur_calendrier`, DROP IF EXISTS `bn_picto_calendrier`, DROP IF EXISTS `bn_type_fiche`, DROP IF EXISTS `bn_label_class`, MODIFY COLUMN bn_ce_i18n VARCHAR(5) NOT NULL DEFAULT '' (You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF EXISTS `bn_ce_id_menu`, DROP IF EXISTS `bn_commentaire`, DROP' at line 1)
```
C'est le second wiki sur lequel je dois faire l'update de la BDD à la main :wink:

**Comment by seballot** [comment]
bon, un peu trop tard pour fixer je crois lol
