### ISSUE TITLE
{{lostpassword}}  erreur

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#459]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
L'action {{lostpassword}} ne fonctionne plus dans Doryphore. Message d'erreur "Il manque des arguments pour un objet de la classe \YesWiki\Database Wiki_config manque(nt)."

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore 2020-04-18-1
- url to see the problem or an example / url pour voir le probleme ou un exemple https://palmiers-pnpc.fr/?MotDePassePerdu
- screenshot / capture d’écran
- logs

**Comment by hadide** [comment]
En complément, problème de clé de validation (après avoir reçu le mail et cliqué sur le lien, message d'erreur sur la page http://wiki.agate-territoires.fr/sdaasp/?MotDePassePerdu&a=recover&email=cfae9ba98c557884d5bea2c88242468e&u=V2lraUFkbWlu 
![image](https://user-images.githubusercontent.com/34748793/89412555-98793c80-d727-11ea-85c7-608604e0072a.png)

**Comment by mrflos** [comment]
j'ai une version débugguée sur une branche a part, je vais la sortir pour doryphore, cela devrait corriger le soucis
