### ISSUE TITLE
Better handle errors when sending email

### ISSUE THREAD

**Issue by gagzzz** [YesWiki/yeswiki#464]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
In https://github.com/YesWiki/yeswiki/blob/development/includes/email.inc.php#L99, there is no "return false;" for the first catch block. And I think this block will catch the exception.
Also, the second block (`catch(\Exception)`) escapes the Exception class but I don't think it's needed as we already are in the global namespace here.

I realised this because even when sending message failed I would get a "message succesfully sent" notification.

Furthermore, PHPMailer can send pretty clear error messages, see https://stackoverflow.com/questions/2386544/error-handling-with-phpmailer, it would be great if those could be either logged somehow or shown to the user with a "get in touch with the webmaster at $contact_email" message :)

thanks!

**Comment by acheype** [comment]
Je m'étais fais la même remarque !

J'ai enfin pris le temps de régler ça. Cf https://github.com/YesWiki/yeswiki/pull/465.
