### ISSUE TITLE
[Agenda] Les facettes ne fonctionne plus dès qu'on clique sur une action

### ISSUE THREAD

**Issue by acheype** [YesWiki/yeswiki#468]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Dès qu'on clique sur une action, c'est à dire "flèche précédente", "flèche suivante", "bouton Jour", "bouton Mois" ou "bouton Année", le filtrage des facettes ne fonctionnent plus.

**Additionnal informations / Informations complémentaires**
Doriphore

Exemple après avoir appuyé sur la flèche droite (il s'affiche alors 0 fiche trouvée) :
![image](https://user-images.githubusercontent.com/8435038/84183563-61bad900-aa8c-11ea-8905-af95bf513975.png)

**Comment by furax37** [comment]
Facette n'a jamais été totalement fonctionnel dans agenda

**Comment by mrflos** [comment]
yes mais ya une piste avec des events javascript qui enverraient les parametres selectionnés des facettes, cela ferait marcher l'agenda et les cluster pour les cartes leaflet avec facette

**Comment by J9rem** [comment]
fixed by https://github.com/YesWiki/yeswiki/commit/1f6ff91f8e22771b8733378e8fd3803ef0c2923b
