### ISSUE TITLE
[BAZAR] (Unknown column 'bn_sem_context' in 'field list')  suite création formulaire doryphore

### ISSUE THREAD

**Issue by hadide** [YesWiki/yeswiki#472]
Suite à un passage à doryphore (sur plusieurs wikis), impossible de créer des formulaires

**Comment by acheype** [comment]
Slt, il faut lancer le handler /update. c'est à dire https://tonwiki.fr/?PagePrincipale/update si on le fait sur la page principale (peu importe sur quelle page).
