### ISSUE TITLE
theme dans custom non disponible partout

### ISSUE THREAD

**Issue by hailowise** [YesWiki/yeswiki#473]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Explain the bug or the feature / expliquer le bogue ou la fonctionnalité demandée
J'ai copier/collé un thème spécifique : `colibris-new` (non répertorié dans les thèmes par défaut) dans le dossier `custom/themes`. Suite à cela, sur la page : `?GererThemes`, le thème est visible dans : "Gérer les thèmes des pages" mais **n'est pas visible** dans : "Gérer le thème par défaut du wiki".

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : cercopitheque 2020-06-05-1
- url to see the problem or an example / url pour voir le probleme ou un exemple : https://colibris-universite.org/parcours-outilslibres/?GererThemes
- screenshot / capture d’écran :
- logs

**Comment by J9rem** [comment]
Le problème est toujours présent dans Doryphore 2021-02-04-2
action `{{gererthemes}}`

Dans la partie `Modifier les valeurs pour les pages sélectionnées` (`class="edit-theme-container"`), la liste des squelettes est bien remplie.

Dans la partie `Gérer le thème par défaut du wiki` quand il n'y a qu'un seul thème défini (le thème par défaut), alors la liste des squelettes est vide.

**Comment by J9rem** [comment]
Normalement c'est corrigé dans la dernière release de Doryphore.
Confirmez-vous @hailowise ?
si c'est OK je vous laisse clore cette issue.
