### ISSUE TITLE
Bug : handler listpages&tags= affiche parfois un résultat vide par erreur

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#476]
Le handler `listpages&tags=` affiche parfois un résultat vide par erreur
Cette erreur survient avec Doryphore du 6 aout 2020

**Comment by mrflos** [comment]
J'ai envoyé un fix dans la branch `development`  
Si tu utilises la branche dev, il faudra aussi faire un `composer install` dans `tools/autoupdate` pour que tout fonctionne

**Comment by J9rem** [comment]
Testé avec doryphore 2020-09-03-1
Bug toujours présent quand le tag commence par un espace. Peut-être faut-il empêcher la création de tags commençant par un espace ?

**Comment by acheype** [comment]
Super ! Oui, c'est pas normal de pouvoir créer un tag avec un espace, un trim() devrait être fait dessus.

**Comment by J9rem** [comment]
Euh j'ai fermé l'issue car il me semblait qu'il n'y avait plus de problèmes.... mais je n'ai rien corrigé.
Je crois que @mrflos avait fait le nécessaire il y a moment
