### ISSUE TITLE
Is not anymore possible to compare changes of a page.

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#477]
Bug / Bogue

**Description**
Lors de l'affichage des différentes versions d'une page, il n'est pas possible d'effectuer une comparaison.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore 2020-08-06-1
- Theme Margot 2020-04-03-1 
- (url privée pour le moment désolé)
Avant Cercopitheque, theme Colibris
![Avant Cercopitheque, theme Colibris](https://user-images.githubusercontent.com/67152407/91149229-1db69800-e6bb-11ea-8c8e-037e232d08d4.png)
Maintenant Doryphore, theme Margot
![Maintenant Doryphore, theme Margot](https://user-images.githubusercontent.com/67152407/91149405-5191bd80-e6bb-11ea-8354-23e4e845b8c7.png)

**Comment by mrflos** [comment]
Les input radio sont cachés par le css? En allant sur le handler /revisions directement apparaissent t'ils?

**Comment by J9rem** [comment]
le handler /revisions permet de les voir :
![image](https://user-images.githubusercontent.com/67152407/91179010-3daf8100-e6e6-11ea-9674-72e9bbb3d9c9.png)
mais à part le bouton Voir les différences, rien n'est cliquable, ....

je regarde pour le css car les boutons sont bien visibles

**Comment by J9rem** [comment]
En forçant à la main, tout fonctionne. Ca viendrait du css de margot https://github.com/YesWiki/yeswiki-theme-margot/blob/master/styles/components/checkboxes-radio.css
enfin c'est une première hypothèse

**Comment by J9rem** [comment]
En ajoutant ce code dans une page, tout est résolu.
```
""<style>
form[action$="diff"]>table>tbody>tr>td>input[type="radio"]:not(:checked), form[action$="diff"]>table>tbody>tr>td>input[type="radio"]:checked, form[action$="diff"]>table>tbody>tr>td>input[type="checkbox"]:not(:checked), form[action$="diff"]>table>tbody>tr>td>input[type="checkbox"]:checked {
    position: initial;
    opacity: 1;
    pointer-events: initial;
}
</style>""
```
