### ISSUE TITLE
Le template bazar annuaire_alphabetique.tpl.html ne gère pas la lettre É

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#478]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Le template bazar annuaire_alphabetique.tpl.html ne fonctionne plus si une fiche du formulaire appelé contient un bf_titre commençant par la lettre É .
Le bug disparaît en remplaçant la lettre É par E
exemple : bug si Équipe, pas de bug si Equipe

(la commande &debug ne donne rien)

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doyphore 2020-08-06-1

**Comment by mrflos** [comment]
Merci pour ce retour!
Tu pourrais essayer de faire une translittération sur le champ titre utilisé pour récupérer la première lettre?
```php
$titre = iconv('UTF-8', 'ASCII//TRANSLIT', $titreAvecAccent);
```

**Comment by J9rem** [comment]
Dans le fichier annuaire_alphabetique.tpl.html veux-tu dire ?
ou dans le formulaire bazar

**Comment by mrflos** [comment]
dans le template, par là :
https://github.com/YesWiki/yeswiki/blob/development/tools/bazar/presentation/templates/annuaire_alphabetique.tpl.html#L42
```php
  $fiche['bf_titre'] = trim($fiche['bf_titre']);
  $fiche['bf_titre'] = iconv('UTF-8', 'ASCII//TRANSLIT', $fiche['bf_titre']);
```

**Comment by mrflos** [comment]
je ne suis pas sûr du résultat, j'imagine que cela transforme les accents en lettre sans accent la plus proche.

**Comment by J9rem** [comment]
Bon `Éssai` devient `?ssai`, c'est moins grave mais pas encore l'effet recherché

**Comment by J9rem** [comment]
je propose de remplacer https://github.com/YesWiki/yeswiki/blob/development/tools/bazar/presentation/templates/annuaire_alphabetique.tpl.html#L43
`$firstChar = strtolower($fiche['bf_titre']{0});`
par
`$firstChar = mb_strtolower($fiche['bf_titre']{0});`
plus stable à mon goût
