### ISSUE TITLE
Pouvoir utiliser plusieurs fois checkboxfiche dans un formulaire avec le même id

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#479]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
L'utilisation de checkboxfiche plusieurs fois dans un formulaire fonctionne à merveille.
Mais, si deux checkboxfiche pointent vers le même identifiant de formulaire, alors il n'est pas possible de remplir la deuxième liste.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : doryphore 2020-08-06-1
- code du formulaire n°6 (dans Bazar):
`texte***bf_titre***Ressource*** *** *** *** ***text***1*** *** *** * *** * *** *** ***`
- code du formulaire n°7 (dans Bazar):
```
texte***bf_titre***Personne*** *** *** *** ***text***1*** *** *** * *** * *** *** ***
checkboxfiche***6***Ressource proposée<br>*** *** *** *** *** ***0*** *** *** * *** * *** *** ***
checkboxfiche***6***Ressource recherchée<br>*** *** *** *** *** ***0*** *** *** * *** * *** *** ***
```
Lors de la création d'une fiche pour le formulaire 7 : 
![creation d'un fiche](https://user-images.githubusercontent.com/67152407/91171544-f079e200-e6da-11ea-977f-82df706b14e2.png)
Un clic sur une case du bas, change l'état de la même case en haut mais ne fait rien dans celle du bas.

**Comment by mrflos** [comment]
Il y a un paramètre en 6ieme ou 7ieme position pour modifier l'id du champs afin de les distinguer et éviter que l'un écrase l'autre.

**Comment by J9rem** [comment]
Oui pour la base de données mais pour l'affichage : ils ont le même id de label à l'affichage pour saisir la fiche.
Lors de la saisie d'une fiche : les deux cases à cocher ont le même code (entre la zone haute et la zone basse) : 
```
<label for="ckbx_BavarderSurUnBanc">
<input type="checkbox" id="ckbx_BavarderSurUnBanc" value="1" name="checkboxfiche6propose[BavarderSurUnBanc]" class="element_checkbox"><span></span>Bavarder sur un banc               </label>
```
en cliquant sur le second panneau, le navigateur voit deux labels avec le même id et donc il ne modifie que le premier.

**Comment by J9rem** [comment]
réparé par #545
