### ISSUE TITLE
les actions nav et button nav n'ajoutent pas de lien dans la base sql yeswiki_links

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#480]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
les actions nav et button n'ajoutent pas de lien dans la base sql yeswiki_links
or c'est bien pratique pour pouvoir utiliser listpages/tree ou {{OrphanedPages}}

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore doryphore 2020-08-06-1

**Comment by mrflos** [comment]
Ok, en effet a voir pourquoi il ne les considère pas comme des pages wikis, peut etre a cause des guillemets autour?

**Comment by J9rem** [comment]
tout est bon maintenant.
