### ISSUE TITLE
Texte de l'aide (bouton point interrogation) dans Bazar : pas d'apostrohe

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#481]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Le texte de l'aide dans le point d'interrogation dans bazar ne gère pas les apostrophes.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki doryphore 2020-08-06-1
- ?BazaR&vue=formulaire&action_formulaire=modif&idformulaire=7#formbuilder
- code du formulaire n°7 :
```
texte***bf_titre***Personne*** *** *** *** ***text***1*** ***Test d'aide pour voir où c'est*** * *** * *** *** ***
checkboxfiche***6***Ressource proposée<br>*** *** *** ***propose*** ***0*** *** *** * *** * *** *** ***
checkboxfiche***6***Ressource recherchée<br>*** *** *** ***recherche*** ***0*** *** *** * *** * *** *** ***
```
Contenu du span pour l'aide en mode saisie : 
(accessible par l'adresse ?BazaR&vue=saisir&action=saisir_fiche&id=7)
`<span class="form-help fa fa-question-circle" title="Test d" aide="" pur="" voir="" où="" c'est'=""></span>`

**Comment by mrflos** [comment]
ah. il doit manquer un [htmlspecialchars](https://www.php.net/manual/fr/function.htmlspecialchars.php)

**Comment by acheype** [comment]
Salut,
De mémoire j'ai déjà corrigé ce soucis.
Cela fait partie des nombreux commits qu'il faut que je soumette.
Je le fais pour sûr d'ici le sprint yeswiki.

**Comment by J9rem** [comment]
A priori ça n'a toujours pas l'air bon avec la dernière version Doryphore, parlons nous de la même chose ?

**Comment by acheype** [comment]
Salut @J9rem,
Cela fait normalement parti des nombreux commit que j'ai soumis juste avant le sprint. Si tu peux confirmer à l'occaz que ça fonctionne (ou pas)...

**Comment by J9rem** [comment]
C'est bon @acheype ça me semble corrigé. Nous pouvons fermer l'Issue.

**Comment by J9rem** [comment]
Ca semble aussi fonctionner pour les virgules (même si bazar form builder ne semble pas le gérer pour le moment)

**Comment by acheype** [comment]
Ok merci pour la confirmation. Pour les ",", le wysiwyg avait tendance à supprimer les , mais pas systématiquement. A revérifier si c'est toujours le cas, car ça peut-être été déjà été corrigé par @seballot .
J'avais prévu de faire un tour de tous les petits trucs que j'avais remarqué avec le wysiwig, mais j'ai toujours pas trouvé le temps de m'en occuper.

Je ferme le ticket du coup.
