### ISSUE TITLE
Rendre le bouton point interrogation Bazar cliquable

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#482]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Le bouton point d'interrogation Bazar accessible à l'adresse `?BazaR&vue=saisir&action=saisir_fiche&id=7` n'est pas cliquable or c'est un comportement attendu par les utilisateurs, au moins pour afficher le contenu du titre.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki doryphore 2020-08-06-1 ; theme Margot
- le bouton est celui qui permet d'afficher `Test d'aide pur voir où c'est` en mode saisie de fiche
si le code du formulaire est
`texte***bf_titre***Personne*** *** *** *** ***text***1*** ***Test d'aide pur voir où c'est*** * *** * *** *** ***`

**Comment by mrflos** [comment]
ya une bibliothèque bootstrap popover plutot que tooltip qui ferait cela, apres je laisse les productowner @gatienbataille et @sylvainboyer définir le meilleur fonctionnement par défaut

**Comment by gatienbataille** [comment]
L'idée serait donc que l'info arrive après un clic et pas après survol simplement du ? 
je n'y vois pas d'inconvénient et c'est sans doute en effet plus clair (ou logique) pour l'utilisateur...

**Comment by sylvainboyer** [comment]
Je ne suis pas convaincu. Pour ma part, j'aime bien le comportement actuel (affichage lors du survol). Mais peut-être que je ne comprends pas le problème ?

**Comment by gatienbataille** [comment]
je pense que le souci "survol" vient de l'usage sur smartphone plus que sur ordi

**Comment by J9rem** [comment]
Bonjour Sylvain et Gatien,
l'idée est que sur Smartphone, effectivement, le survol est compliquée.
Ensuite, le tooltip actuel met du temps à s'afficher. Il ne s'affiche pas au survol mais en restant au moins une seconde sur place avec le thème Margot et Firefox.

Ce comportement risque de ne pas être le même selon les plateformes si on reste sur la propriété "title" sans configuration spécifique de temps d'affichage au survol.

A l'usage, les utilisateurs cliquent sur le point d'interrogations mais ne restent pas assez longtemps pour voir le message qui ne vient pas au clic mais au survol fixe.
Ils disent alors qu'il n'y a pas de message d'aide.

**Comment by gatienbataille** [comment]
donc ok pour moi pour cette modif, mais je laisse sylvain réagir au besoin

**Comment by J9rem** [comment]
En tout cas, merci pour votre argumentaire et votre suivi.

**Comment by sylvainboyer** [comment]
OK, je comprends.
Donc, sur le comportement, je suis d'accord.
Et sur l'architecture, je pense qu'il faut creuser dans le sens de la remarque de Florian (bibliothèque `bootstrap popove`).

**Comment by acheype** [comment]
Le fait d'afficher l'info-bulle qd on clique me semble une bonne idée pour
nos amis les smartphones. Seulement, le style doit également changer pour
que les desktop users soient invités à cliquer plutôt que de survoler
l'icône i. Ce qu'on voit sur les sites qui ont fait attention à leur UX,
c'est un soulignement discontinu du texte (discontinu pour ne pas être
confondu avec un lien classique). Cf cet exemple :
https://osvaldas.info/examples/elegant-css-and-jquery-tooltip-responsive-mobile-friendly/

On pourrait ainsi garder l'icône i et y ajoutant un texte ("Détails" par
exemple), le tout souligné de la sorte.

Ça doit être faisable avec la bibli bootstrap de Florian mais sinon on a
carrément des plugins jquery de ce style : https://tipso.object505.com

Et finalement je suis tombé aussi sur la fonctionnalité "Tooltip" qui est
fourni avec jquery-ui. Cette solution semble encore plus efficace, le texte
s'affiche dans une bulle lorsque l'utilisateur saisie dans la zone de
texte. Mais pas sûr qu'on puisse le mettre pour tous les types de champs
(liste, fichier...). Jetez un oeil ici pour vous faire une idée :
https://jqueryui.com/tooltip/

Le mar. 25 août 2020 à 18:24, Sylvain Boyer <notifications@github.com> a
écrit :

**Comment by sylvainboyer** [comment]
Bon, je rêve sûrement, mais...
Existe-t-il un moyen simple pour avoir le comportement actuel en "desktop" et le comportement que nous avons décrit sur terminal mobile (*screen size* ?)

**Comment by J9rem** [comment]
Je suis toujours partant de la simplicité plutôt que de la complexité et donc je ne demande pas à refaire le travail pour la version Desktop qui semble correspondre à vos attentes.
Toutefois, j'ai eu un retour utilisateur Desktop qui intuitivement a envie de cliquer sur ce bouton plutôt que de le survoler, .....
Ce que tu proposes Sylvain, ne répondra pas à l'attente de cet utilisateur qui a mon avis à l'habitude du smartphone et du clic.
Y a-t-il moyen de conserver la fonctionnalité de survol (fonctionnalité principale) et d'ajouter pour "Desktop + smartphone" la gestion du clic (fonctionnalité de secours) ?

**Comment by acheype** [comment]
Avoir l'affichage en survol en version desktop + l'affichage par clic en version smartphone est ce qui est proposé avec la librairie que je vous ai partagé plus haut : https://osvaldas.info/examples/elegant-css-and-jquery-tooltip-responsive-mobile-friendly/

**Comment by mrflos** [comment]
Que de commentaires, qu'est ce que cela va être quand on va parler refactoring bazar :)

Pour info : la tooltip bootstrap peut aussi être appelée par un clic cf. https://getbootstrap.com/docs/3.3/javascript/#tooltips paramètre `trigger` :
> How tooltip is triggered - click | hover | focus | manual. You may pass multiple triggers; separate them with a space.

Cela m'irait bien de ne pas rajouter une dépendance à une nouvelle librairie js au coeur de YesWiki, basée sur une dépendance à jquery (meme si bootstrap avant version 5 dépend aussi de jquery).

A terme, il me semble qu'il faudra réfléchir à quels sont les composants graphiques essentiels à yeswiki, et voir comment dans les thèmes yeswiki, laisser le choix des librairies que l'ont souhaite utiliser (jquery, bootstrap, ou vanilla js, etc..).

En attendant, il me parait plus simple de rajouter un trigger a l'existant, que d'implémenter une nouvelle lib sans avoir fait le tour de toutes les solutions existantes.

**Comment by acheype** [comment]
+1, puisque c'est déjà inclus dans la v3 de bootstrap autant utiliser ce composant !

**Comment by sylvainboyer** [comment]
+1

**Comment by J9rem** [comment]
Bon en attendant : code à ajouter dans les pages qui appellent des formulaires pour rendre le point d'interrogation cliquable:
```
""<script> 
/* Ajout du clic pour les tooltips des formulaires */
document.getElementsByTagName("body")[0].onload = function(){
$(document).ready(function(){
	$("span.form-help").each(function() {
		$(this).attr("onclick","$(this).tooltip('toggle')") ;
	  });
	});
};
</script>""
```

**Comment by J9rem** [comment]
On peut clore car pris en compte.
