### ISSUE TITLE
Bug : Les liens externes rajoutent automatiquement un retour à la ligne dans le code html.

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#483]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Les liens externes rajoutent automatiquement un retour à la ligne dans le code html.
le code  `Je veux me rendre sur la [[AccueiL page principale]], rapidement.`
produit le code html
`Je veux me rendre sur la <a href="https://colibris-wiki.org/56lorient/?AccueiL">page principale</a>, rapidement.`
C'est OK.
Mais le code `Je veux me rendre sur [[https://www.wikipedia.org/ Wikipedia]], rapidement.`
produit le code
```
Je veux me rendre sur <a href="https://www.wikipedia.org/">Wikipedia</a>
, rapidement.
```
Ce comportement est embêtant car le navigateur transforme le retour à la ligne en une espace entre le lien et la virgule, ce qui n'est le comportement attendu. 

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Cercopitheque et Doryphoe

**Comment by acheype** [comment]
Merci de d'avoir remonté dans le tracking, je l'avais déjà remarqué et ça fait un moment que veux le corriger. Je ne sais pas si tu seras au sprint yeswiki mais je prendrai perso du temps pour régler ce type de bug non bloquant mais chiant tout de même.

**Comment by acheype** [comment]
Et aussi, le bug concerne également les liens générés pas l'action {{attach ...}} !

**Comment by J9rem** [comment]
### Avant modification

Voici un exemple de page avec un lien interne AccueiL. Pas d'espace après le point.
```AccueiL.```
__HTML :__
```<a href="https://XXXXXXX/?AccueiL">AccueiL</a>. ```

Voici un exemple de page avec un [[AccueiL lien interne vers accueil]]. Pas d'espace après le point.
```[[AccueiL lien interne vers accueil]].```
__HTML :__
```<a href="https://XXXXXXX/?AccueiL">lien interne vers accueil</a>. ```

Voici un exemple de page avec un [[https://yeswiki.net/?AccueiL lien externe vers YesWiki]]. Un retour à la ligne après le point dans le html.
```[[https://yeswiki.net/?AccueiL lien externe vers YesWiki]].```
__HTML :__
```
<a href="https://yeswiki.net/?AccueiL">lien externe vers YesWiki</a>
. Un retour 
```

### Après modification

Voici un exemple de page avec un lien interne AccueiL. Pas d'espace après le point.
```AccueiL.```
__HTML :__
```<a href="https://XXXXXXX/?AccueiL">AccueiL</a>. ```

Voici un exemple de page avec un [[AccueiL lien interne vers accueil]]. Pas d'espace après le point.
```[[AccueiL lien interne vers accueil]].```
__HTML :__
```<a href="https://XXXXXXX/?AccueiL">lien interne vers accueil</a>. ```

Voici un exemple de page avec un [[https://yeswiki.net/?AccueiL lien externe vers YesWiki]]. Pas de retour à la ligne après le point dans le html.
```[[https://yeswiki.net/?AccueiL lien externe vers YesWiki]].```
__HTML :__
```
<a href="https://yeswiki.net/?AccueiL">lien externe vers YesWiki</a>. Pas
```

**Comment by acheype** [comment]
Bien vu !!
