### ISSUE TITLE
Incompatibilité CheckAccessLink et listpages

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#486]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
L'utilisation de checkaccesslink ne fonctionne pas quand on utilise le handler `/listpages&tags=example`

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki doryphore 2020-09-03-1 / checkaccesslink 2019-09-20-1 
- url to see the problem or an example / url pour voir le probleme ou un exemple
- screenshot / capture d’écran
- logs
`Notice: Undefined offset: 1 in /tools/bazar/libs/bazar.fonct.php on line 1707`

**Comment by mrflos** [comment]
corrigé depuis ... ..je ne suis pas quand.. mais plus d'erreur
