### ISSUE TITLE
function pointimage broken in cercopitheque 2020-06-05-1

### ISSUE THREAD

**Issue by toddoli** [YesWiki/yeswiki#494]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Explain the bug or the feature / expliquer le bogue ou la fonctionnalité demandée
Opening issue now but it was already there in previous versions of yeswiki. The function "pointimage" worked fine but now although the points do show up, clicking the points won't display title and description. 

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
cercopitheque 2020-06-05-1

- url to see the problem or an example / url pour voir le probleme ou un exemple
https://fabiencambi.hebfree.org/?PageSourceGeneral

**Comment by J9rem** [comment]
Hello @toddoli ,
I think the trouble is now solved with latest revision of yeswiki doryphore.
Is that right for yout  site ?

**Comment by toddoli** [comment]
Hey @J9rem,
Haven't got any running website with yeswiki at the moment :( Knowing your good work I assume it is right and will close that issue. I can always reopen it in case I find the same issue again sometime.
Thanks for the follow-up!
