### ISSUE TITLE
Create alias for bazar field carte_google ?

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#500]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
The bazar field **carte_google** contains the name `google `whereas `google `is not used.
Is-it possible to create an alias of this field without the name `google`.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore

**Comment by acheype** [comment]
Proposition qui va dans ton sens @J9rem , renommer **carte_google** par exemple en **carte** et laisser **carte_google** en alias pour la rétrocompatibilité.

**Comment by mrflos** [comment]
C'est déja le cas dans le code : https://github.com/YesWiki/yeswiki/blob/development/tools/bazar/libs/formulaire/formulaire.fonct.inc.php#L1941
carte_google est un alias de map.  
Il faudrait juste remplacer les références a carte_google dans le code et remplacer par map

**Comment by J9rem** [comment]
Je clos cette issue car elle a été résolue hier.
https://github.com/YesWiki/yeswiki/pull/734
