### ISSUE TITLE
Missing folder tools/autoupdate/vendor

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#501]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Bug de l'action {{update}} car le dossier "Vendor" n'est plus présent dans tools/autoupdate

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
Doryphore et Doryphore-developpement

**Comment by mrflos** [comment]
C'est normal si tu prends le code depuis github, il faut lancer `composer install` à la main dans le dossier tools/autoupdate,  c'est disponible clé en main sur le site yeswiki et le dépot officiel par contre

**Comment by MelanieMichel** [comment]
Ok merci
