### ISSUE TITLE
{{update version="doryphore"}} – TEMPLATE_NO_DEFAULT_THEME.

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki#503]
Lors d'un changement de version en utilisant `{{update version="doryphore"}}`, j'ai obtenu une page page blanche `TEMPLATE_NO_DEFAULT_THEME`. Plus de possibilité d'intervenir sur le wiki sans intervenir *via* FTP.
- Changement de version depuis la dernière version de cercopithèque.
- Il n'y avait pas de thème par défaut dans le `wakka.config.php`.
- Il n'y avait aucun sous dossier dans `/themes` (uniquement le fichier `EMPTY`). Ni dans `/custom/themes` (normal puisqu'il n'y avait rien avant le changement de version dans ce dossier).
- Pour débloquer la situation, j'ai copié un dossier `margot` que j'avais sur mon disque dur dans `/themes`. `Ctrl+Shift+R` et j'avais récupéré l'interface.

Je pense que ce n'est pas lié à #427 puisqu'en l'occurrence il n'y avait pas de personnalisation, on utilisait uniquement le thème par défaut de cercopithèque.

**Comment by J9rem** [comment]
Normalement c'est résolu.
