### ISSUE TITLE
Proposition de création d'un "services container"

### ISSUE THREAD

**Issue by srosset81** [YesWiki/yeswiki#508]
Pour le refactoring du Bazar, j'ai créé une classe `BazarFiche` qui s'occupe de gérer la récupération des fiches, mais aussi leur création, édition et suppression.

Il s'agit en fait d'un _service_ qui est instancié une fois et qu'on peut récupérer via `$GLOBALS['bazarFiche']`.

Il faudra bientôt que je crée un service similaire pour la gestion des formulaires.

Plutôt que de multiplier ce type de variables globales, je propose de créer une seule variable globale `$GLOBALS['services']`, qui permettra ensuite de récupérer les différents services via `$GLOBALS['services']->get('bazarFiche')`. Ce "services container" (inspiré de [Symfony](https://symfony.com/doc/current/service_container.html)) pourrait aussi être inclus dans l'objet Wiki global. 

Plus généralement, un service qui a besoin d'un autre service l'inclurait dans le constructeur:

```
class BazarForm
{
    protected $wiki;
    protected $bazarFiche; 

    public function __construct($wiki)
    {
        $this->wiki = $wiki;
        $this->bazarFiche = $wiki->services->get('bazarFiche');
    }
}
```

On pourrait aussi imaginer que chaque extension puisse inclure ses propres services, qui seraient chargés automatiquement au lancement et qui pourraient interragir avec les autres services. YesWiki pourrait les identifier par exemple en fonction de leur emplacement (`libs/services` ?) ou de leur nom (`BazarFiche.service.php` ?).

Qu'en pensez-vous ?

Je précise que l'idée n'est pas de copier Symfony, mais de s'inspirer des bonnes pratiques qui marchent ;-) Symfony s'est contruit presque entièrement autour des standards recommandés par la communauté PHP, via les [PSR](https://www.php-fig.org/psr/). Il y a d'ailleurs un PSR dédié au [Container Interface](https://www.php-fig.org/psr/psr-11/) qui ressemble un peu à ce que je propose.

Ping @mrflos @acheype @seballot @oncletom

**Comment by mrflos** [comment]
Etant spécialiste de la programmation fonctionnelle avant que ce soit la mode, et donc en partie coupable du bazar de fonctions dans yeswiki, cela me semble intéressant, et j'aime bien l'idée d'intégration des services auto-découverts dans les extensions.  

J'aime quand on a les choses utiles déjà disponibles "out of the box" sans devoir tout redéclarer dans chaque partie du code qu'on écrit, donc pour favorable a la proposition, sans vraiment mesurer les tenants et aboutissants.

**Comment by seballot** [comment]
Yop, oui ça à l'air une bonne amélioration !
Et oui ça serait bien que tous les services soient déclarés dans le même dossier (ou dans un dossier similaire dans l'extension) comme ça un dev peut facilement voir ce qui existe

**Comment by acheype** [comment]
Au top !
Et ça serait même chouette si tu pouvais implémenter les interfaces proposées par la PSR-11 explicitées dans ton lien !

**Comment by thom4parisot** [comment]
Carrément. 

Y'a déjà une convention d'organisation de fichiers dans le cœur et les extensions ? J'ai pas d'opinion sur le fait de suffixer en `.service.php` ou placer dans un répertoire `services/`.

À partir du moment où c'est "autoloadable", ça roule.

**Comment by srosset81** [comment]
Merci pour vos retours ! :-)
Je m'y attaque prochainement.

> Et ça serait même chouette si tu pouvais implémenter les interfaces proposées par la PSR-11 explicitées dans ton lien !

Yes je vais faire ça !

> Y'a déjà une convention d'organisation de fichiers dans le cœur et les extensions ?

Parfois c'est des suffixes (comme le nouveau `.api.php`), parfois des dossiers. Comme il y aura potentiellement plusieurs services par extension, ça vaudrait la peine de les mettre dans un dossier je pense.

**Comment by sylvainboyer** [comment]
Nickel,
Merci !

**Comment by gatienbataille** [comment]
bravo, j'ai rien compris mais je vous fait une totale délégation de confiance ;-)

**Comment by mrflos** [comment]
merged
