### ISSUE TITLE
Pb action {{publicationgenerator}}

### ISSUE THREAD

**Issue by hadide** [YesWiki/yeswiki#515]
Hello,
sur un doryphore version 2020-10-22-1
en appelant l'action publicationgenerator sur une page, page blanche et avec &debug j'ai

Warning: Invalid argument supplied for foreach() in /srv/data/web/vhosts/mednum73.fr/htdocs/tools/bazar/libs/BazarFiche.class.php on line 538

Notice: Trying to access array offset on value of type null in /srv/data/web/vhosts/mednum73.fr/htdocs/tools/bazar/libs/BazarFiche.class.php on line 271

Warning: Invalid argument supplied for foreach() in /srv/data/web/vhosts/mednum73.fr/htdocs/tools/bazar/libs/BazarFiche.class.php on line 538

Notice: Trying to access array offset on value of type null in /srv/data/web/vhosts/mednum73.fr/htdocs/tools/bazar/libs/BazarFiche.class.php on line 271

Warning: Invalid argument supplied for foreach() in /srv/data/web/vhosts/mednum73.fr/htdocs/tools/bazar/libs/BazarFiche.class.php on line 538

Notice: Trying to access array offset on value of type null in /srv/data/web/vhosts/mednum73.fr/htdocs/tools/bazar/libs/BazarFiche.class.php on line 271

Fatal error: Uncaught Error: Call to protected method YesWiki\BazarFiche::decode() from context '' in /srv/data/web/vhosts/mednum73.fr/htdocs/tools/bazar/libs/bazar.fonct.retrocompatibility.php:66 Stack trace: #0 /srv/data/web/vhosts/mednum73.fr/htdocs/tools/publication/actions/publicationgenerator.php(188): searchResultstoArray() #1 /srv/data/web/vhosts/mednum73.fr/htdocs/includes/YesWiki.php(1428): include('/srv/data/web/v...') #2 /srv/data/web/vhosts/mednum73.fr/htdocs/includes/YesWiki.php(1240): YesWiki\Wiki->IncludeBuffered() #3 /srv/data/web/vhosts/mednum73.fr/htdocs/formatters/wakka.php(339): YesWiki\Wiki->Action() #4 [internal function]: YesWiki\WikiniFormatter->callback() #5 /srv/data/web/vhosts/mednum73.fr/htdocs/formatters/wakka.php(66): preg_replace_callback() #6 /srv/data/web/vhosts/mednum73.fr/htdocs/formatters/wakka.php(492): YesWiki\WikiniFormatter->format() #7 /srv/data/web/vhosts/mednum73.fr/htdocs/includes/YesWiki.php(1428): include('/srv/data/web/v...') #8 /srv/data/web/vhosts/mednum73.fr/htdocs/includ in /srv/data/web/vhosts/mednum73.fr/htdocs/tools/bazar/libs/bazar.fonct.retrocompatibility.php on line 66

**Comment by mrflos** [comment]
je croies que c'est corrigé, en tout cas c'est plutôt a ouvrir du coté de l'extension publication, si ce n'est pas le cas, je ferme ici.
