### ISSUE TITLE
compléter le wysiwyg bazar avant tests ?

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#516]
J'ai installé le dernier doryphore (22 oct) pour tester le wysiswyg bazar https://cooptic.be/test
Avant de me lancer dans plusieurs tests, est-il envisageable de : 
 - [x] implémenter format nombre dans les formats du champ "texte" (ou enlever si pas encore ok)
 - [x] voir pourquoi le bouton aujourd'hui n'apparaît pas quand on le demande dans le champ date (ou enlever la fonction si pas encore ok)
 - [x] rajouter sympa en plus de ezmlm dans les options de liste de diffusion
- [x] le Name des champs est généré automatiquement genre image12385478, c'est pratique MAiS vachement chiant pour les templates qui attendent un bf_image, non ? 

Par ailleurs : 
 - je pige pas l'intérêt direct du champ couleur

Non lié au bazar-builder
 - je me demande si ce serait pas bien de faire fonctionner cartogoogle aussi avec un champ "code postal" là en l'état ça laisse à penser que ça fonctionne avec bf_adresse1 et/ou bf_ville , c'est tout... or parfois on n'a pas de bf_ville mais juste un bf_code_postal
 - Peut-être bug connu, mais actuellement un champ select qui va chercher dans un autre formulaire ne fonctionne pas chez moi

**Comment by seballot** [comment]
Salut @gatienbataille ! J'ai résolu la liste de case à coché

Pour les couleur, par exemple si tu fais un template custom d'actu, tu pourrais mettre l'arrière de plan de l'actu avec la couleur définie dans le champ "color" de la fiche. C'est sur c'est probablement pas le plus utilisé, mais ça coutait pas grand chose à le rajouter, et je pense pas que ça gene non?

Pour les autres demandes, si j'ai bien compris ça n'est pas lié au bazar-builder, donc mieux vaudrait créer une autre issue si tu veux bien !

**Comment by gatienbataille** [comment]
hello
super merci,
