### ISSUE TITLE
Fatal error: Call to undefined function YesWiki\boolval() in /home/odysseec/www/odysseewiki/includes/Database.class.php on line 45

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki#528]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Sur un Doryphore 2020-10-23, j'ai des choses qui ne s'affichent pas (ex. : le contenu de certains champs lors de l'affichage d'une fiche bazar, ou la page ParametresUtilisateur)
Dans tous ces cas, lorsque je fais un `&debug`, j'obtiens`Fatal error: Call to undefined function YesWiki\boolval() in /home/odysseec/www/odysseewiki/includes/Database.class.php on line 45`

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki **Doryphore 2020-10-23**
- url to see the problem or an example / url pour voir le probleme ou un exemple
Champ "sites web" présent dans la fiche (http://www.odyssee-creation.coop/odysseewiki/?CatherineGodart/raw) mais pas affiché (http://www.odyssee-creation.coop/odysseewiki/?CatherineGodart
- screenshot / capture d’écran
- logs

**Comment by mrflos** [comment]
pour le `boolval()` c'est lie a la version de php. 
pour le champ bf_sites en regardant sur http://www.odyssee-creation.coop/odysseewiki/?CatherineGodart/json&demand=forms&formid=1 je voies qu'il a un drole de type de champs "texte", cela devrait etre soit "wiki" soit "html"

**Comment by sylvainboyer** [comment]
**N° de version de PHP —** Donc, il faut qu'on modifie la documentation pour Doryphore. Parce que là c'est une 5.4.45.
**bf_sites —** Il était en wiki et j'ai voulu le passer en nohtml (en utilisant l'ancienne interface, mais je n'ai pas pû l'enregistrer (je ne me souvient plus du message d'erreur mais il me disait que "nohtml pas bon". J'ai donc utilisé l'interface graphique qui effectivement ne propose pas nohtml mais texte. Je pensais que c'était le nouveau comportement.

**Comment by mrflos** [comment]
pour la [doc d'install](https://yeswiki.net/?DocumentationInstallation) et le [readme dans github](https://github.com/YesWiki/yeswiki#installation), c'est bien php > 7.1 qui est indiqué

et pour l'interface graphique, "texte" n'est pas un valeur possible, c'est bien nohtml ou html ou wiki les options possibles

**Comment by acheype** [comment]
C'est un bug de FormBuilder que j'avais déjà remarqué, j'ai tout une liste à transmettre à Sebastian. Il faut que je fasse un ticket.

**Comment by sylvainboyer** [comment]
@acheype, cool, merci.
@mrflos, Pour l'upgrade, je propose de modifier l'action de manière à afficher un texte "attention le passage en doryphore requiert la version 7.1 de PHP" (affiché uniquement lorsqu'on est dans le cas d'un cerco avec un `{{update version="doryphore"}}`). Qu'en dis-tu ?

**Comment by mrflos** [comment]
bah c'est un peu lourd et devoir mettre le texte et de devoir le changer à chaque fois que les versions supportées de php changent.  
C'est la responsabilité de l'hébergeur d'etre a jour des versions supportées, c'est le cas pour toutes les distributions linux actuelles.  
Après on peut mettre un lien vers https://www.php.net/supported-versions.php et dire que yeswiki suit les évolutions de php pour coller au calendrier de support de versions de php, mais je pense que c'est pas la peine de le préciser outre mesure.

**Comment by sylvainboyer** [comment]
Effectivement, en redescendant en *cercopitheque* (dernière version 2020-06-05-1), tout roule. Je valide que le problème vient bien de la version de php présente sur le serveur.

**Un petit cas d'utilisation (histoire fictive de Sarah)**
- Sarah installe son wiki en suivant la [procédure d'installation](https://yeswiki.net/?DocumentationInstallation), elle a l'information sur la version de PHP nécessaire.
- Sarah, en tant qu'utilisateur *lambda*, se pose alors la question de la version de PHP de son serveur. Heureusement que la documentation lui indique qu'il faut vérifier la version de PHP, parce que sinon, elle ne se poserait pas cette question.
- Comme Sarah a fait son installation en juillet dernier, la version indiquée était 5.3 (changée le 17 août dans la documentation, et au passage cercopitheque semble tourner comme une horloge en 5.4).
- Un jour dans un futur proche, Sarah, se dit que *doryphore* a l'air trop cool.
- Elle lit la [documentation de migration](https://yeswiki.net/?Doryphore) et découvre qu'il suffit de modifier l'action `{{update}}`. Elle se dit : « ils sont trop forts chez YesWiki. Ils doivent gagner pleins de thunes tellement ils sont bons ! ».
- Sarah applique la documentation et elle a maintenant un super YesWiki en *doryphore*.

**Manque de bol,** Sarah, se débrouille super bien avec YesWiki, mais elle n'est pas développeur. Elle ne se pose pas la question de savoir si cette nouvelle version de YesWiki nécessite une version différente de PHP (elle ignore probablement ce qu'est PHP). Et même, au cas peu probable, où elle se poserait cette question, pourquoi ce qui était vrai en juillet (5.3) ne le serait plus aujourd'hui (7.1).Cette documentation, et ce soft sont tellement bien faits qu'on lui aurait certainement indiqué s'il fallait faire quelque chose de spécial.

Je pense qu'il faut, au minimum, modifier la documentation de migration. @gatienbataille qu'en dis-tu ?

**Comment by mrflos** [comment]
Je ne sais pas trop comment on accède à cette page (https://yeswiki.net/?Doryphore ) mais j'ai mis un encart, ainsi que sur la page officiel de la documentation https://yeswiki.net/?DocumentationMiseAJour .
