### ISSUE TITLE
Problèmes d'affichage des fiches de saisie bazar : chevauchements+texte d'aide

### ISSUE THREAD

**Issue by AudreyAuriault** [YesWiki/yeswiki#537]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Explain the bug or the feature / expliquer le bogue ou la fonctionnalité demandée
Lorsqu'on affiche un **formulaire de saisie Bazar**, 2 types de problèmes apparaissent :
![Capture d'écran 2020-11-16 12 03 53](https://user-images.githubusercontent.com/58287202/99245928-bb29ef80-2804-11eb-8ea0-56fab37d3058.png)

1-  Les lignes de réponses et de questions se chevauchent (voir la partie "en participant à cette rencontre")
2- Parfois le texte d'aide à la compréhension pour rédiger la réponse à la question est vide, et parfois automatiquement rempli de façon aléatoire.  Il s'agit du texte qui apparait en gris clair dans la case du texte à remplir. Ex : "Qui est ton père?" _Indiquez ici la taille de slip de votre père_  (voir par exemple "vos attentes" qui n'a pas de texte d'aide. 

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
- url to see the problem or an example / url pour voir le probleme ou un exemple
- screenshot / capture d’écran
- logs

**https://rnr-emmaus.xyz/?PageInscriptionformulaire&vue=saisir&action=saisir_fiche**

**Comment by AudreyAuriault** [comment]
Commentaire de @mrflos  sur le canal Famateam dev  : 
"ton bug en question, @laurentlem me l'avait soumis, et il est corrigé ici : https://github.com/YesWiki/yeswiki/commit/7fc793673eba393748b3bfea72f4f1487dba84ac
Le probleme : je ne sais pas comment mettre a jour ce wiki en production sachant que la version actuelle est trop fragile pour etre utilisée en prod.
J'avais proposé a laurent de modifier juste ce fichier en attendant sortie officielle
https://github.com/YesWiki/yeswiki/commit/7fc793673eba393748b3bfea72f4f1487dba84ac"

**Comment by seballot** [comment]
Salut Audrey ! 

Pour le 1) chevauchement, c'est que dans la création du formulaire, quand tu édite le champs "label" tu as du taper "Entrée" ce qui a inséré un saut de ligne (ça a ajouté un truc genre `<div><br></div>` qu'il faut enlever, soit via le constructeur graphique, soit avec le code du formulaire)

Pour le 2), le lien que tu me donnes, moi y'a rien qui s'affiche... t'en as un autre ? :) 

Et je pense qu'il faut que vous mettiez margot à jour aussi pour résoudre certain problèmes graphique

**Comment by J9rem** [comment]
> Pour le 1) chevauchement, c'est que dans la création du formulaire, quand tu édite le champs "label" tu as du taper "Entrée" ce qui a inséré un saut de ligne (ça a ajouté un truc genre `<div><br></div>` qu'il faut enlever, soit via le constructeur graphique, soit avec le code du formulaire)

Nous pourrions peut-être proposé quelque chose qui enlève automatiquement `<div><br></div>` pour simplifier la vie de tout le monde non ?

par contre, je ne sais pas du tout où se trouve le composant qui gère ceci.

**Comment by J9rem** [comment]
> Pour le 2), le lien que tu me donnes, moi y'a rien qui s'affiche... t'en as un autre ? :)

Le bon lien : https://rnr-emmaus.xyz/?PageInscriptionformulaire

**Comment by AudreyAuriault** [comment]
Bonjour à vous, 
merci pour le temps consacré!
J'ai viré tous les br qui trainaient  et ça donne la même chose...
Et Dory et Margot sont sur les dernières versions... 
C pas plutôt la piste de MrFlos, voir plus haut et l'issue ici : https://github.com/YesWiki/yeswiki/issues/537 ?
Ci dessous le code de mon formulaire : 
```
texte***bf_titre***Prénom et nom***60***255*** *** ***text***1*** *** *** * *** * *** *** ***
texte***bf_structure***Ma structure / communauté***60***255*** *** ***text***0*** *** *** * *** * *** *** ***
image***bf_image***Image de présentation (facultatif mais c'est plus sympa)***140***140***600***600***right***0*** *** *** * *** * *** *** ***
texte***bf_tel***Téléphone pro ou perso (visible uniquement des organisateurs)***10***20*** *** ***text***0*** *** ***@admins*** * *** *** ***
champs_mail***bf_mail***Email (visible uniquement des organisateurs)*** *** *** ***form*** ***1***1*** ***@admins*** * *** *** ***
texte***bf_ville***Ville***50***80*** *** ***text***1*** *** *** * *** * *** *** ***
labelhtml***<span style="color:#cc3333;">Il faut maintenant cliquer sur le bouton bleu pour placer votre point sur la carte </span><br>*** *** ***
carte_google***bf_latitude***bf_longitude*** *** ***
textelong***textarea_1605348336357***Vos attentes pour cette rencontre*** *** *** *** ***wiki***0*** *** *** * *** * *** *** ***
textelong***textarea_1605348327423***<span class="author-a-z72zz87zz88z2dz74zz68zpku2z82zz78z3nz72z">Des contraintes techniques à signaler ? (Ex : qualité du wifi, pas de caméra...)</span>*** *** *** *** ***wiki***0*** *** *** * *** * *** *** ***
checkbox***ListeParticipationemotion***En participant à cette rencontre...*** *** *** *** *** ***0*** *** *** * *** * *** *** ***
textelong***textarea_1605348416911***Expression libre (une remarque, quelques mots sur vous,...)*** *** *** *** ***wiki***0*** *** *** * *** * *** *** ***
labelhtml***<h3>Il ne vous reste plus qu'à valider ! </h3>*** *** ***
```

**Comment by seballot** [comment]
toujours rien pour moi :(

![image](https://user-images.githubusercontent.com/17404254/99258641-2b427080-2819-11eb-9d6b-8ef98de6f9b0.png)

**Comment by J9rem** [comment]
> 
> 
> toujours rien pour moi :(

il te faut juste cocher la case puis valider en fait.
C'est l'écran standard quand l'option de validation de formulaire est activée

**Comment by seballot** [comment]
Ah ah ok pardon :) 

Je ferai un fix dans la semaine !

**Comment by seballot** [comment]
Ok j'ai fait un fix pour les saut de ligne

Concernant les problème d'affichage, je confirme que c'est fixé dans la dernière version de margot, mais surement qu'elle n'a pas été packagée et donc pas dispo via l'interface de mise à jour de yeswiki
