### ISSUE TITLE
Display content depending on ACL

### ISSUE THREAD

**Issue by toddoli** [YesWiki/yeswiki#549]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Si ça n'existe pas déjà ce serait super d'avoir une action qui permette d'afficher du contenu (bouton, HTML, ou autre...peu importe) uniquement pour tel ou tel utilisateur (suivant une ACL quoi). Dans mon cas par exemple je souhaite afficher un bouton "ajouter un évènement" à un calendrier qui mène vers la bonne page d'admin mais que ce bouton ne s'affiche que pour les @admins évidemment.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
Doryphore

**Comment by acheype** [comment]
Salut,
Ce que tu demandes existes déjà, pour n'importe quel d'un formulaire tu peux définir des droits (acls) en lecture et écriture pour n'importe quel champ : positions 12 et 13. 

![2020-11-24 12-15 - Capture d'écran](https://user-images.githubusercontent.com/8435038/100026336-eb682400-2dea-11eb-905d-49254ff38730.png)
Avec le constructeur graphique, ce sont les champs Peut être lu et Peut être saisi par.
Dans ton cas, pour faire un bouton, il te faut ajouter un champ labelhtml.

**Comment by mrflos** [comment]
et si c'est pour du contenu dans un page wiki classique, on peut utiliser dans doryphore `{{section visibility="@admins" ...}}` .  
ATTENTION : ca cache en mode rendu des pages, mais pas en édition.

**Comment by toddoli** [comment]
Trop cool merci! C'est pas documenté alors.

**Comment by acheype** [comment]
C'est un peu documenté ici : https://yeswiki.net/?ChampsPossibles dans 'L'utilisation de chacune des treize zones' mais de manière générale, y'a pas mal de truc à améliorer sur la doc. N'hésite pas à y participer notamment sur ce point.

**Comment by toddoli** [comment]
Ça roule @acheype. Cela dit mon issue ne concernait pas les 13 champs possibles d'un formulaire. Ça c'est assez clairement documenté et ça fonctionne bien mais @mrflos a répondu à ma question et je testerai. C'est bien du contenu libre genre texte, bouton etc...que je souhaite cacher selon l'utilisateur et l'option visibility semble bien répondre à ça :) Par contre elle est pas du tout documentée donc je testerai et je regarderai comment ajouter ça à la doc ;) Merci!

**Comment by toddoli** [comment]
J'ai testé ça
```
{{section  visibility="@admins"}}
""<a href="?PageAjoutBureau" class="btn btn-primary">Ajouter un membre du bureau</a>""
{{end elem="section"}}
```
Et visiblement ça fonctionne pas. Voir la page [https://www.sourcesasarcm.fr/?PageBureau](https://www.sourcesasarcm.fr/?PageBureau)

**Comment by mrflos** [comment]
@seballot , c'est bien comme cela la syntaxe du parametre visibility ?

**Comment by acheype** [comment]
@toddoli ah ok autant pour moi, je sais pas pourquoi j'ai cru que c'était pour les formulaires...

j'ai testé ton code et il fonctionne. Seulement cette fonctionnalité a à peine un mois (du 24/10) et il faut mettre à jour ton wiki avec la toute dernière version de doryphore qui est disponible [ici](https://yeswiki.net/?TelechargementS).

Ce n'est pas encore documenté, ni proposé dans les paramétrage du constructeur graphique de composant. Ca vaudrait le coup de l'y ajouter également.

**Comment by acheype** [comment]
Ah j'oubliais, tu as aussi ce type de bouton (qui peut être un lien avec nobtn="1") :

```
{{button link="GererSite" text="Home" hideifnoaccess="true"}}
```

qui cache le lien quand l'utilisateur n'a pas les acls pour voir la page.

Ni documenté non plus, ni intégré au constructeur graphique de composant...

**Comment by seballot** [comment]
Yop! bien vu y'avais pas la doc de hideifnoaccess dans l'action builder, corrigé ! (visibility était déjà documenté)

**Comment by acheype** [comment]
:+1: 
ah oui en effet, j'avais pourtant testé sur section mais quand je cochais "Paramètres avancées", aucune autre option ne s'affichait. Je viens de réessayer et là ça s'affiche bien... étrange

**Comment by toddoli** [comment]
> j'ai testé ton code et il fonctionne. Seulement cette fonctionnalité a à peine un mois (du 24/10) et il faut mettre à jour ton wiki avec la toute dernière version de doryphore qui est disponible [ici](https://yeswiki.net/?TelechargementS).

Je viens de mettre à jour, je suis donc sous **doryphore 2020-11-23-2** et j'ai toujours le même souci. C'est quoi le bout de code que je vérifie si le code est bien à jour ?

**Comment by acheype** [comment]
bizarre car les actions section.php et button.php comporte bien ces options !! as-tu aussi testé aussi le bout de code pour {{button}} ?
tu dois pouvoir créer l'action {{section}} avec le constructeur graphique, le champ visibilité apparaît dans les paramètres avancés.

**Comment by toddoli** [comment]
@acheype Idem pour {{button}} et justement j'ai lu dans ton post précédent que c'était intégré au constructeur graphique et je vois rien c'est quand même louche...

**Comment by acheype** [comment]
dans docs/actions/ il y a le fichier section.yaml, tu devrais y retrouver la chaîne de caractère "visibilité". C'est avec ce fichier que {{section}} affiche ses paramètres dans le constructeur graphique.

pour {{button}}, c'est normal qu'il n'y soit pas, sebastian vient tout juste de l'ajouter.

**Comment by acheype** [comment]
Pardon, "visibility" ou "Visible par" pour les chaînes à vérifier...

**Comment by J9rem** [comment]
Bonjour @toddoli 
est-ce qu'avec toutes ces réponses et la mise à jour de la documentation de [{{section}}](https://yeswiki.net/?SecTion) nous avons répondu à votre issue et pouvons donc la clore ?

**Comment by toddoli** [comment]
Merci de relancer @J9rem j'avais complètement mis de côté. Très bizarre je pense rien avoir fait depuis et ça fonctionne oui.

En tout cas cette syntaxe fonctionne. Si on ne fait pas partie du groupe "admins" le bouton ne s'affiche effectivement pas.
```
{{section visibility="@admins"}}
""<a href="?PageAjoutBureau" class="btn btn-primary">Ajouter un membre du bureau</a>""
{{end elem="section"}}
```

J'ai aussi testé ça mais celle là ne fonctionne pas (pas grave pour moi car moins flexible de toute façon:
```
{{button link="?PageAjoutBureau" class="btn btn-warning" text="Ajouter un membre du bureau" hideifnoaccess="true"}}
```

**Comment by J9rem** [comment]
@toddoli super si ça fonctionne.
Pour l'action `button` il y a eu un bug temporaire sur les versions doryphore de mi-janvier.
Il est résolu par ce [commit](https://github.com/YesWiki/yeswiki/commit/8f2eb069f82e214c3b9723aafc4e39f4ee27c7d5) qui sera propagé dans les prochaines release de Doryphore et déjà sur le dépôt Github.
Est-ce que nous pouvons considérer que cette issue est close ? ou y a-t-il un point encore à voir ?
Merci pour le suivi Fabien

**Comment by toddoli** [comment]
On peut clairement considérer l'issue close :) Merci!
