### ISSUE TITLE
je ne veux pas que mon wiki soit indexé !!!

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#551]
sauf erreur de ma part, j'ai installé un joli doryphore en cochant la case pour que mon wiki ne soit pas indexé sur le web.
j'ai promis cela à l'équipe avec laquelle je travaille et quelque semaines plus tard, ils commencent à se trouver sur notre moteur de recherche favori...
vérifications faite : 
 - le fichier robot.txt ne comportait que User-Agent: *   donc pas de Disallow: /
 - wakka.config.php ne comportait pas 'meta' => array('robots' => 'noindex, nofollow'),

Mon wiki était donc bien indexable.

donc besoin de confirmation de ce bug et éventuellement, soit on ne fait plus la promesse de soustraire le wiki à l'indexation, soit on trouve la parade magique ;-)

**Comment by mrflos** [comment]
bug confirmé, c'est moi qui avait mis l'option, je vais voir pour que ca marche en vrai

**Comment by J9rem** [comment]
Je clos cette issue car elle a été résolue par #753
