### ISSUE TITLE
Refacto Feuille de Route

### ISSUE THREAD

**Issue by seballot** [YesWiki/yeswiki#552]
### Itération 3

- [x] **Formulaires** : continuer le split de de formulaire.fonct.php en différents Fields. Copier juste le code php, ne pas transformer en template twig pour le moment
- [x] **Formulaire** : Adapter le FactoryField pour lire tous les fichier fields dans toutes les extensions
- [x] **Controllers** : Introduire le concept de controller, voir #550 
- [x]  **Documentation** : peaufiner l'extension d'example `hello-world`
- [x] **ListManager** : gestion des listes
- [x] **Api** : utiliser un Controller

### Itération 4

- [x] **Bazar.fonct.php** : continuer à le spliter, en utilisant des Controller comme le `ListeController`
- [ ] **Documentation** : améliorer la doc pour les devs
- [ ] **Objets Form**: plutôt que se promener dans le code avec un array hyper complex et illisible, tout mettre dans un objet Form.
- [ ] **Extension**: virer la classe YesWikiPlugins, renommer tous les plugins en extensions, y compris le dossier /tools.
- [ ] **Maintenance mode**: lorsque le wakkaconfig `maintenance_mode` est à true, ne charger aucune extension.
- [ ] Permettre d'utiliser $this->wiki dans les BazarField

### Des pistes pour continuer

- **Alias**: pouvoir définir des alias (comme les fields) pour les actions, handlers et formatters.
- **Form builder** : faire en sorte qu'il utilise les champ Field
- **Extensions** : qu'est ce qui est considéré comme le coeur? est ce que ce qui tout le code coeur doit être dans la même dossier ou est ce qu'on garde du code dans différents dossier/extensions ? est ce que le code coeur reste à la racine ou est ce qu'on créé une extension appelée `core` ? est ce que les extensions non coeur sont dans des repos séparées ou est ce qu'on les met toutes dans le repo yeswiki ? 
- **YesWiki** : continuer à refactoriser la classe YesWiki, extraire le code dans des services dédiés
- **Documentation API**: Utiliser les annotations pour générer automatiquement la documentation des endpoints API

**Comment by srosset81** [comment]
Selon ce que j'ai compris de nos discussion "Bazar : splitter bazar.fonct en utilisant un controller" ira dans cette tranche.
Le but est clairement de réduire le fichier bazar.fonct.php. Au début les controlleurs pourront être de simples services appelés depuis BazarAction.

De même pour "Documentation : améliorer la doc pour les devs, peaufiner l'extension d'example hello-world": j'aurai dû le faire dans la tranche précédente, il ne faut pas tarder avec ça.

**Comment by seballot** [comment]
Ok, ça me parait beaucoup mais comme tu veux !! :)

J'ai ordonné par ce qui me semble être par priorité

**Comment by srosset81** [comment]
Je n'ai pas réussi à tout terminer, je me suis concentré sur le nettoyage du fichier `bazar.fonct.php`, qui me semblait être la priorité depuis le début, et de loin le travail le plus lourd. Il reste seulement les fonctions d'export et d'import à passer dans un controlleur (900 lignes) et sinon quelques petites fonctions utilitaires à dispatcher dans des services (300 lignes).

**Comment by mrflos** [comment]
i archive this as soon there will be a new one
