### ISSUE TITLE
Php 7 est requis

### ISSUE THREAD

**Issue by seballot** [YesWiki/yeswiki#553]
J'ai vu qu'on utilise dans le code l'operateur phph `??` qui n'est présent que à aprtir de php7

de même, twig v3 requiert php7 (on peut passer à twig 2.7 pour être compatible php5)

Je me dis que ça peut être un problème pour certains wiki qui sont toujours en php5? ou pas?

**Comment by seballot** [comment]
pour `??` on peut facilement se faire une petit fonction qui fait la meme chose, genre https://stackoverflow.com/questions/5836515/what-is-the-php-shorthand-for-print-var-if-var-exist

**Comment by mrflos** [comment]
avec @acheype on a mis php > 7.3 comme requis pour doryphore (dans composer et la doc).
le support officiel de php 7.2 s’arrête dans 2 jours  cf. https://www.php.net/supported-versions.php, par ailleurs pour le lms, j'ai utilisé des fonctions > 7.2.

Ce qui reste a faire, c'est dans l'action d'update, vérifier la version de php pour autoriser ou pas le passage à doryphore.

**Comment by seballot** [comment]
ok top ! :)
