### ISSUE TITLE
Propriétés manquantes du form builder

### ISSUE THREAD

**Issue by srosset81** [YesWiki/yeswiki#559]
## `utilisateur_wikini`

J'ai découvert un nouveau paramètre pour le champ utilisateur_wikini, le numéro 5.
Il permet d'envoyer un mail à une liste de discussion lorsqu'un utilisateur est créé.
Il n'est pas pris en compte dans l'action builder https://github.com/YesWiki/yeswiki/blob/doryphore/tools/bazar/presentation/javascripts/form-edit-template.js#L510

## `textlong`

Pour le champ textlong, la propriété "Nombre de caractères max" est défini par le numéro 6.
(Le champ habituel, le 4, étant utilisé pour définir le nombre de lignes)
C'est aussi manquant de l'action builder
(Il y a un compteur de nombre de caractères restant, qui ne marche que pour la syntax nohtml)

## `bookmarklet`

Pour le champ bookmarklet, il y a deux propriétés 3 et 4 qui doivent correspondre à un champ d'URL et de description:
https://github.com/YesWiki/yeswiki/blob/doryphore/tools/bazar/libs/formulaire/formulaire.fonct.inc.php#L2477-L2478
Pour l'instant, dans le form builder, il y a un champ 3 "value" et pas de champ 4:
https://github.com/YesWiki/yeswiki/blob/doryphore/tools/bazar/presentation/javascripts/form-edit-template.js#L515

**Comment by srosset81** [comment]
## `listefiche`

Il manque deux options:
- Il est possible de mettre un URL le nom (colonne 1, qui ne doit alors pas être converti), afin d'aller chercher les données sur un URL distant. L'URL doit être de type `https://domain.com/?BazaR/json&demand=entries`
- Si dans la colonne 3, on a la valeur "fiche", on affiche le contenu de la fiche directement.

**Comment by J9rem** [comment]
Je clos cette issue car soit les remarques ont été prises en compte, soit les remarques ne correspondent plus au code actuel car plusieurs refactors sont passés par là.
Merci en tout cas pour avoir identifié ces points à l'origine.
