### ISSUE TITLE
mauvais affichage de résultats pour la recherche du mot "bazar"

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#575]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lors de la recherche d'un mot ([icône loupe dans la barre de navigation](https://yeswiki.net/?AccueiL#search))
la recherche du mot `bazar` fait planter l'affichage des résultats

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore version après 2020-11-30-4 et peut-être avant aussi
- url to see the problem or an example / url pour voir le probleme ou un exemple https://yeswiki.net/?phrase=bazar&wiki=RechercheTexte
- screenshot / capture d’écran
![image](https://user-images.githubusercontent.com/67152407/102709723-2572fb80-42ad-11eb-90dc-2c41488dffa7.png)
![image](https://user-images.githubusercontent.com/67152407/102709729-33c11780-42ad-11eb-988e-293bde47e144.png)
![image](https://user-images.githubusercontent.com/67152407/102709736-4c313200-42ad-11eb-934f-243a2c426b35.png)

**Comment by mrflos** [comment]
c'est comme quand tu tapes `google` dans google ? 😱

**Comment by J9rem** [comment]
Il y a des chances oui

**Comment by J9rem** [comment]
Je clos cette issue car avec les améliorations de `{{newtextsearch}}` ne font une requête sql que sur 100 résultats maintenant ET il n'y a un rendu que des 25 premières pages ce qui évitera de surcharger le serveur (toutefois, si l'action `{{redirect page=}}`) est présente dans une des premières pages, la redirection aura lieu, ...
