### ISSUE TITLE
[feature][bazar] Linked Data (json-ld) included in html page (if defined)

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#576]
New feature / Nouvelle fonctionnalité

What about using microformats for events description ?

Les [microformats](https://microformats.io/) (parfois abrégés _μF_) sont un ensemble de conventions pour intégrer une sémantique en HTML et fournir une API utilisable par les moteurs de recherche, les agrégateurs et d'autres outils (© [MDN](https://developer.mozilla.org/fr/docs/Web/HTML/microformats)). 

Il y a un ensemble de [sujets couverts par les microformats](http://microformats.org/wiki/Main_Page).

Par exemple le `h-event` aurait tout à fait leur place sur une telle page qui liste des d'événements : https://wiki.solidaritesjeunesses.org/?PageFormationsAvenir

Je n'ai pas regardé depuis longtemps YesWiki pour voir comment les associer aux champs dans les formulaires Bazar... Je vais essayer de jeter un œil dans la semaine à venir :crossed_fingers: 

cc @sylvainboyer @RomainLalande

**Comment by sylvainboyer** [comment]
Salut Cyrille,
Sympa de te voir ici.
Je pense qu'il faut que tu discutes avec @srosset81 qui a fait des choses dans ce registre.
Merci pour la notification

**Comment by srosset81** [comment]
Salut @Cyrille37 
De ce que je lis, [Google supporte trois formats](https://webmasters.stackexchange.com/questions/48586/what-are-the-advantages-of-schema-orgs-microdata-vs-microformats-et-al) pour ce type de données structurées, dont le microformat, qui n'est d'ailleurs pas le format le plus recommandé.
Le microformat est le seul qui a son propre vocabulaire, alors que les deux autres formats (microdata et RDFa) peuvent s'appuyer sur n'importe quelle vocabulaire (ontologie).
Il y a aussi une variante [RDFa Lite](https://www.w3.org/TR/rdfa-lite/) qui a l'air particulièrement simple à utiliser.

[YesWiki permet déjà de typer les données via une ontologie](https://yeswiki.net/?RendreYeswikiSemantique). Ce ne serait à mon avis pas très compliqué d'ajouter le format RDFa ou RDFa-lite aux fiches Bazar qui sont typées sémantiquement. Cela donnerait même plus de valeur à ce typage sémantique, puisque cela permettrait un meilleur indexage. :+1:

**Comment by Cyrille37** [comment]
Bonjour Sébastien,

J'avais cru lire que Google et consors préféraient le microformats, mais pas de soucis pour un autre protocole tant qu'il est utilisé par les indexeurs des moteurs de recherche. Je vais lire la doc que tu pointes et faire des essais avec les outils d'évaluation SEO. À bientôt donc :-)

**Comment by Cyrille37** [comment]
Bonjour Sébastien,

J'avais cru lire que Google et consors préféraient le microformats, mais pas de soucis pour un autre protocole tant qu'il est utilisé par les indexeurs des moteurs de recherche. Je vais lire la doc que tu pointes et faire des essais avec les outils d'évaluation SEO. À bientôt donc :-)

**Comment by Cyrille37** [comment]
Excellent, le JSON-LD est implémenté dans Bazar et reconnu des outils SEO. J'essaye donc tout ça :-)

**Comment by Cyrille37** [comment]
Dans la [doc de YesWiki](https://yeswiki.net/?RendreYeswikiSemantique) il y a toujours activitystreams et possiblement schema.org (ex `***title, schema:name
`). Est-il possible d'utiliser seulement une description schema.org sans son équivalent activitystreams (ex `***, schema:pathophysiology` [pathophysiology](https://schema.org/pathophysiology)) ?

**Comment by srosset81** [comment]
@Cyrille37 Oui bien sûr, ActivityStreams c'est juste pour faire du ActivityPub, aucun intérêt dans ton cas :-)

**Comment by Cyrille37** [comment]
Le json-ld n'est pas rendu dans la page html d'une fiche quand le semantique est activé et renseigné ?? Est-il seulement accessible via l'API ??

```
<script type="application/ld+json">
{
	"@context": "https://schema.org",
	"@type": "Event",
        "name": "Mon 1er event",
        ...
}
</script>
```

Merci encore à toi :-)

**Comment by srosset81** [comment]
Oui il est affiché dans l'API, j'ai ajouté cette fonctionnalité surtout pour faciliter l'interoperabilite entre plateformes. Je pense que ce doit être facile d'ajouter ce bout de code via une extension (fichier type action__.php)

**Comment by Cyrille37** [comment]
Oui ça serait bien que ce soit automatiquement ajouté aux listes et fiches bazar quand du sémantique est défini.

notes:
- [Google Search supporte les données structurées au format json-ld](https://developers.google.com/search/docs/guides/intro-structured-data)
- [Votre page est-elle compatible avec les résultats enrichis ?](https://search.google.com/test/rich-results)

**Comment by seballot** [comment]
salut ! je crois que on est déjà pas mal niveau json-ld and sémantique avec yeswiki, surtout que que quasi eprsonne l'utilise, donc je ferme :)
