### ISSUE TITLE
[bazar] certains champs ne sont plus rendus comme avant

### ISSUE THREAD

**Issue by acheype** [YesWiki/yeswiki#579]
Voici quelques soucis que j'ai remarqué suite au dernier refacto bazar :

- [x] le champ bf_titre n'est plus affiché en tant que titre de la fiche mais comme un champ classique (avec son label). Avant, il me semble qu'il y avait un h1 (ou ça changeait en h3 parfois, mais je n'ai jamais su pourquoi). Cela me paraît une chouette évolution que le champ soit écrit comme les autres champs dans un div avec un data-id mais il faudrait traduire l'affichage en titre au niveau css (bazar.css + adaptations margot)

- [x] le champ labelhtml fonctionne bien pour le code html spécifié à la saisie mais pas pour celui affiché à la consultation

- [x] la balise titre, qui permet de renseigner automatiquement bf_titre, fait planter la sauvegarde de la fiche quand on fait référence à un autre champ (exemple : {{bf_nom}})

Voici un exemple de formulaire qui regroupe les trois soucis :

```
titre***{{bf_nom}} {{bf_prenom}}*** ***
texte***bf_nom***Nom***50***100*** *** ***text***1*** *** *** * *** * *** *** ***
texte***bf_prenom***Prénom***50***100*** *** ***text***1*** *** *** * *** * *** *** ***
labelhtml***<h3>Informations Pratiques</h3>*** ***<h3>Informations Pratiques</h3>***
labelhtml***<h5>Les informations qui suivent ne seront visibles que des utilisateur·rices enregistré·e·s</h5>*** *** ***
champs_mail***bf_email***Email*** *** *** ***form*** ***1***1*** *** * *** * *** *** ***
```

Et voici deux copies d'écran qui montre le soucis de l'affiche de titre : affichage en page classique et affichage en modale
![2020-12-19 08-18 - Capture d'écran_1](https://user-images.githubusercontent.com/8435038/102791238-fc369600-43a6-11eb-91fe-98bdd0bf5163.png)

![2020-12-19 08-18 - Capture d'écran](https://user-images.githubusercontent.com/8435038/102791253-048ed100-43a7-11eb-85dd-ca0390512b54.png)

**Comment by srosset81** [comment]
Merci je regarde ça :-)

**Comment by srosset81** [comment]
C'est corrigé ici: https://github.com/YesWiki/yeswiki/pull/584
Merci pour le bug report détaillé, c'est typiquement le type de problème qu'il est difficile de détecter pendant du refacto... et pourtant c'était des gros bugs !

**Comment by Cyrille37** [comment]
Je ne sais pas si ça un rapport mais au cas où :

J'ai puller la branche `Doryphore`, fait une installation toute fraîche ce matin, poser l'action bazar `{{bazarliste id="2" template="agenda" }}` sur la page d'accueil, ça fonctionne très bien.
Par contre l'affichage d'une fiche agenda donne une page presque vide
![image](https://user-images.githubusercontent.com/368965/102809247-f1d5c580-43c1-11eb-81f2-db1c493d301b.png)

Mais vu les commits qui arrivent cette fin d'après-midi ça ira peut être mieux :-)

Cheers.

**Comment by acheype** [comment]
@Cyrille37 Je n'ai pas de soucis de mon côté à visualiser une fiche de type agenda.

@srosset81 Ok, merci pour la correction, je valide ça refonctionne bien :+1: 
J'en profite pour te remonter deux remarques :

-  pour bf_titre, tu as corrigé en faisant un twig particulier qui écrit un h1. Comme je te le mettais plus haut, je trouvais ça sympa d'avoir un code html identique à un champ texte et un rendu particulier au niveau des css. Ca aurait notamment permis de pouvoir plus facilement personnalisé le titre suivant les utilisations (juste en rajoutant du css, ou encore avoir à la fois le label + la valeur dans html['bf_titre'] aurait son intérêt). @mrflos, tu as un avis là-dessus ?

- ce n'est pas tout à fait en lien avec ces bugs, mais je trouverais cela chouette si tu arrivais à uniformiser l'accès qu'on a aux différents objets du tableau $fichebazar. En effet ['values'] s'accède via les clés qui correspondent à l'id du champ, tandis que pour ['form']['template'] et ['form']['prepared'] c'est par de simples index. Rendre tous ces tableaux accessible via l'id du champ, en plus de rendre le code plus propre, permettrait surtout de s'affranchir pour les templates de fiche de devoir passer par $i pour  accéder d'un tableau à l'autre (parfois ce n'est même pas possible et on est obligé de recréer une structure pour stocker cet index, cf l'helloword que j'ai écris pour la PR de bazar template). Qu'en penses-tu ?

**Comment by srosset81** [comment]
> * pour bf_titre, tu as corrigé en faisant un twig particulier qui écrit un h1. Comme je te le mettais plus haut, je trouvais ça sympa d'avoir un code html identique à un champ texte et un rendu particulier au niveau des css. Ca aurait notamment permis de pouvoir plus facilement personnalisé le titre suivant les utilisations (juste en rajoutant du css, ou encore avoir à la fois le label + la valeur dans html['bf_titre'] aurait son intérêt). @mrflos, tu as un avis là-dessus ?

Je fais du refacto, c'est-à-dire que je réécris bêtement ce qui existe. Du coup il faudra faire une issue s'il y a des propositions d'amélioration.

> * ce n'est pas tout à fait en lien avec ces bugs, mais je trouverais cela chouette si tu arrivais à uniformiser l'accès qu'on a aux différents objets du tableau $fichebazar. En effet ['values'] s'accède via les clés qui correspondent à l'id du champ, tandis que pour ['form']['template'] et ['form']['prepared'] c'est par de simples index. Rendre tous ces tableaux accessible via l'id du champ, en plus de rendre le code plus propre, permettrait surtout de s'affranchir pour les templates de fiche de devoir passer par $i pour accéder d'un tableau à l'autre (parfois ce n'est même pas possible et on est obligé de recréer une structure pour stocker cet index, cf l'helloword que j'ai écris pour la PR de bazar template). Qu'en penses-tu ?

Ce tableau est un enfer, la solution proposée (et que je suis censé faire pendant cette itération), c'est d'utiliser un objet `Form`.

**Comment by mrflos** [comment]
@acheype pour les titres je trouve cela plus logique qu'il garde ces spécificités de titre, surtout syntaxe html (balise `<h1>` ou `<h2>`). Il me semble que le cas d'usage ou tu voudrais récupérer le label + la valeur, tu pourrais faire un field titre custom dans le folder custom.  
Après, dans l'idéal, un jour il faudrait des méthodes pour récupérer des valeurs de champs d'une fiche, en mode formaté html ou brut, mais c'est une autre histoire.  

Pour le tableau form, il me semble que @srosset81 va en effet prochainement bosser là dessus, et je suis d'accord avec @acheype que quand on peut, autant avoir les clés des champs plutot que des index numériques!

**Comment by acheype** [comment]
> tu pourrais faire un field titre custom dans le folder custom.

yep mais dans ce cas on aurait pu avoir un affichage standard du champ direct avec $html['bf_titre].
bref, c'était juste une idée et juste d'avoir ton retour là-dessus me suffit, les deux façons de faire ont leur avantage. donc je  préfère ne pas créer de ticket d'amélioration, ce n'est pas ce qui manque les idées d'amélioration ;)

ah oui, c'est vrai @srosset81 qu'on avait dit que t'allais bosser sur ce big objet Form ! Voici donc ce cas d'utilisation qu'il peut être pertinent d'avoir en tête.
