### ISSUE TITLE
Version du Wiki et mise à jour

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#580]
Bug / Bogue

**Description**

YesWiki fraîchement installé depuis github branche doryphore annonce la version 2020-01-22-1 qui ne colle pas avec ce qui est affiché par l'outil de mise à jour qui lui annonce 2020-11-30-4

![image](https://user-images.githubusercontent.com/368965/102792557-f5108780-43a8-11eb-9932-7f56f58a3d0d.png)

**Additionnal informations / Informations complémentaires**

Aussi, dans la doc d'installation depuis le git il faut ajouter l'exécution de composer dans le dossier `tools/autoupdate`.

**Comment by mrflos** [comment]
Pour la doc tu parles des fichiers md dans le code? dans le site yeswiki c'est précisé sur https://yeswiki.net/?PageCreer ![image](https://user-images.githubusercontent.com/124845/102807373-91e61b80-43cf-11eb-840f-e3e8d1a76c38.png)

Pour les numéros de version, ca marche avec les archives générées sur https://repository.yeswiki.net mais je garde l'issue ouverte : on va passer a semver et ce sera plus facile de dumper le numéro de version dans git, car là c'est une constante qui traine quelque part..

**Comment by Cyrille37** [comment]
Pour le `composer install`, il est tellement habituel que je n'ai pas lu la phrase en dessous, qui indique un chemin particulier :-)
