### ISSUE TITLE
[bazar] Valeurs par défaut des champs mal initialisées

### ISSUE THREAD

**Issue by acheype** [YesWiki/yeswiki#588]
Exemple [ici](https://github.com/YesWiki/yeswiki/blob/dae39e103612774d8bb621624b48586a37841423/tools/bazar/fields/TextareaField.php#L28) mais il y a pas mal d'autres initialisations dans les classes Field qui utilisent l'opérateur Null coalescent (??) et ont normalement le même soucis :
values est intialisée avec  "" quand il n'y a pas de chaîne de caractère déclarée pour les différentes descriptions du champ, ainsi l'opérateur Null coalescent renvoi toujours la première opérande.

Soit on change les initialisations, soit on change la manière d'initialiser $values. La deuxième solution me paraît plus adaptée, car le code est plus court pour les initialisations avec le Null coalescent mais surtout on irait vers une programmation plus objet et ce sera alors plus facile à modifier dès lors qu'on changera les descriptions de champs en *** avec du Yaml.
Si seulement on pouvait bannir petit à petit de YesWiki toutes ces chaînes vides qui marquent une valeur inexistante...

**Comment by srosset81** [comment]
D'accord avec toi @acheype. Il faudrait revoir la méthode `FormManager::parseTemplate`, que j'avais juste copier-coller.
