### ISSUE TITLE
[bazar] Impossible de renseigner à nouveau une image qui n'est pas trouvée 

### ISSUE THREAD

**Issue by acheype** [YesWiki/yeswiki#596]
Lorsqu'on édite une fiche existante qui a une image de renseignée et que celle-ci n'existe plus, un message d'erreur s'affiche qui nous invite à rafraîchir la page pour que la base s'actualise.
Mais suite au rafraîchissement, on a toujours le même message d'erreur...

![2021-01-07 07-34 - Capture d'écran](https://user-images.githubusercontent.com/8435038/103931208-367e9200-5120-11eb-9b6e-ee01c695a202.png)

**Comment by srosset81** [comment]
Bien vu, j'avais oublié un TODO https://github.com/YesWiki/yeswiki/pull/599
