### ISSUE TITLE
Ecran blanc suite MAJ 2021-01-02-7

### ISSUE THREAD

**Issue by hadide** [YesWiki/yeswiki#597]
Type de demande
Bug

Description
Suite à une mise à jour d'un wiki de doryphore 2020-10-23-7 (de mémoire) vers doryphore 2021-01-02-7, écran blanc..

Informations complémentaires
https://wiki.hinaura.fr
avec debug :
Notice: Undefined index: wiki in /srv/data/web/vhosts/wiki.hinaura.fr/htdocs/tools/webhooks/wiki.php on line 46

Fatal error: Uncaught Error: Call to a member function getBaseUrl() on null in /srv/data/web/vhosts/wiki.hinaura.fr/htdocs/tools/webhooks/wiki.php:46 Stack trace: #0 /srv/data/web/vhosts/wiki.hinaura.fr/htdocs/includes/YesWiki.php(1731): include() #1 /srv/data/web/vhosts/wiki.hinaura.fr/htdocs/includes/YesWiki.php(97): YesWiki\Wiki->loadExtensions() #2 /srv/data/web/vhosts/wiki.hinaura.fr/htdocs/index.php(69): YesWiki\Wiki->__construct() #3 {main} thrown in /srv/data/web/vhosts/wiki.hinaura.fr/htdocs/tools/webhooks/wiki.php on line 46

**Comment by acheype** [comment]
Salut,
Je viens de regarder rapidos, et l'erreur se produit car tu n'as pas la bonne version de l'extension webhooks. Tu as la branche cercopitheque d'installé et il faut que tu mettes la [branche doryphore](https://github.com/YesWiki/yeswiki-extension-webhooks).

Je ne sais pas si c'est possible de l'installer directement depuis l'interface Mise à jour de "Gestion du site", mais @mrflos travaillait dessus.

Aussi tu risques d'avoir d'autres soucis si tu veux faire fonctionner les webhooks car il y a [cette branche](https://github.com/YesWiki/yeswiki-extension-webhooks/tree/adapt-to-bazar-refactoring-2) qui n'a pas encore été intégré à doryphore et cette branche intègre des changements qu'il y a eu récemment au niveau de bazar.

A ta place, je récupèrerai le code de cette dernière branche ou si tu n'utilises pas webhooks, je désactiverai l'extension en attendant.

**Comment by hadide** [comment]
Merci beaucoup @acheype ! Suite à l'ajout via ftp de la branche webhook indiquée, j'ai 

Query failed: UPDATE wikhinaura_pages SET body = regexp_replace(body, '"createur":".*?",', '') (FUNCTION wiki_hinaura.regexp_replace does not exist)

qui s'affiche lors que j'utilise le handler /update.

J'ai donc supprimer pour l'instant l'extension :)
Merci encore !

**Comment by acheype** [comment]
ça ce n'est pas lié au webhook, @mrflos a rajouté dans le update.php cette requête que j'avais faite pour mettre à jour les données suites à des modifs qu'on a fait dans bazar.

apparement, la requête ne passe pas chez tout le monde... 

`regexp_replace` ne semble pas reconnu chez toi pourtant elle semble exister sur mysql ou mariadb.

quelle version de mysql ou de mariadb as-tu ?
et tu sais ce qu'est 'wiki_hinaura' chez toi @hadide ?
