### ISSUE TITLE
Filtre Facette ne se déplie plus

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#598]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
les facettes restent pliées suite à mise à jour yeswiki

**Additionnal informations / Informations complémentaires**
- doryphore 2021-01-02-7
- url to see the problem or an example / https://syalinnov.org/?CartoProjets

**Comment by acheype** [comment]
C'est certainement dû au refactoring de bazar.

Perso voici un exemple où cela se produit. L'utilisation de *groups* et *titles* ne fait rien.
 
`{{bazarliste id="1" template="liste_accordeon.tpl.html" groups="checkboxListeEnjeuxDuFaireEnsemble" titles="Cette difficulté est-elle liée à un ou plusieurs enjeux du faire ensemble listés ci-dessous ?" groupsexpanded="undefined"}}`

J'ai un double warning qui donne une indication où il peut y avoir un soucis :
`PHP Notice: Undefined index: id in /home/adri/projects/yeswiki/tools/bazar/libs/bazar.fonct.php on line 1750
PHP Notice: Undefined index: id in /home/adri/projects/yeswiki/tools/bazar/libs/bazar.fonct.php on line 1750`

@srosset81 tu pourrais y jeter un oeil ?

**Comment by srosset81** [comment]
OK je vois ça au plus tard demain

**Comment by srosset81** [comment]
Je n'arrive pas à reproduire en me basant sur la branche doryphore... les facettes s'affichent et peuvent bien se plier et se déplier. Problème déjà corrigé ?
En tout cas je n'ai pas encore refactoré `baz_rechercher`, c'est normalement le prochain sur ma liste.

**Comment by srosset81** [comment]
Par contre il y a un problème d'affichage du nom des facettes, c'est l'ID qui s'affiche. Je regarde ça.

**Comment by srosset81** [comment]
Voilà une PR pour l'affichage problématique des labels lorsqu'il s'agit d'une liste https://github.com/YesWiki/yeswiki/pull/602
A voir si ça corrige aussi le problème de pliage/dépliage ?

**Comment by acheype** [comment]
Yep c'était ça !!

Avant (impossible d'ouvrir la facette) :
![2021-01-12 02-00 - Capture d'écran](https://user-images.githubusercontent.com/8435038/104317836-cf295f00-54de-11eb-9134-bb78e2bae508.png)

Après :
![2021-01-12 02-01 - Capture d'écran](https://user-images.githubusercontent.com/8435038/104317885-e2d4c580-54de-11eb-81e5-3df059241cab.png)

Thanks, je merge du coup !
