### ISSUE TITLE
Problème MAJ Doryphore 

### ISSUE THREAD

**Issue by hadide** [YesWiki/yeswiki#603]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité
Bug / Bogue

**Description**
Suite à une mise à jour de wikis vers la version doryphore 2021-01-11-3, écran blanc (un des wikis est tout neuf, sans contenu original, justement pour tester)

**Additionnal informations / Informations complémentaires**
- doryphore 2021-01-11-3
- http://carto.hinaura.fr/?PagePrincipale
- logs
Fatal error: Uncaught Error: Call to undefined function YesWiki\loadTemplates() in /srv/data/web/vhosts/carto.hinaura.fr/htdocs/includes/YesWiki.php:1776 Stack trace: #0 /srv/data/web/vhosts/carto.hinaura.fr/htdocs/includes/YesWiki.php(97): YesWiki\Wiki->loadExtensions() #1 /srv/data/web/vhosts/carto.hinaura.fr/htdocs/index.php(69): YesWiki\Wiki->__construct() #2 {main} thrown in /srv/data/web/vhosts/carto.hinaura.fr/htdocs/includes/YesWiki.php on line 1776

**Comment by acheype** [comment]
@hadide on dirait un soucis dans ton installation.
est-ce que tu es sûr d'avoir bien mis à jour tous les dossiers ? car là il cherche une fonction qu'il devrait trouver dans /tools/template/libs/templates.functions.php

**Comment by acheype** [comment]
et si tu veux que le soucis des facettes soit résolu, il te faut la dernière version d'aujourd'hui.

**Comment by hadide** [comment]
je suis passé par le menu mise à jour / extension... ok je teste avec la version d'aujourd'hui ! merci

**Comment by hadide** [comment]
@mrflos @acheype  j'ai de nouveau le souci, suite au passage de carto.hinaura.fr de la 2021-01-21 à la 2021-01-24-3

Fatal error: Uncaught Error: Call to undefined function YesWiki\loadTemplates() in /srv/data/web/vhosts/carto.hinaura.fr/htdocs/includes/YesWiki.php:1416 Stack trace: #0 /srv/data/web/vhosts/carto.hinaura.fr/htdocs/includes/YesWiki.php(96): YesWiki\Wiki->loadExtensions() #1 /srv/data/web/vhosts/carto.hinaura.fr/htdocs/index.php(69): YesWiki\Wiki->__construct() #2 {main} thrown in /srv/data/web/vhosts/carto.hinaura.fr/htdocs/includes/YesWiki.php on line 1416

**Comment by mrflos** [comment]
pour parer au plus urgent, pourrais tu tester de mettre par ftp la derniere version doryphore téléchargeable sur https://repository.yeswiki.net/doryphore .  
La derniere au 26 janvier est https://repository.yeswiki.net/doryphore/yeswiki-doryphore-2021-01-24-3.zip 
Si cela résout ton problème, peut etre completer la doc et donner la procédure de sauvetage.  
Dans un deuxieme temps, si tu pouvais installer un wiki martyr sur ton serveur et me donner un acces ftp et WikiAdmin, je pourrais appronfondir pour voir ce qui casse

**Comment by EdmondAgate** [comment]
Hello
Nb : on a pas encore échangé mais je travaille depuis peu avec Adrien et me suis permis de prendre le relais, Adrien étant en réunion toute l'aprem ;)
Merci beaucoup pour le retour, le transfert ftp a effectivement fixé le problème du wiki !
Etant nouveau, je ne suis pas certain, quand tu parles de la doc à compléter : tu parles bien de cette page https://yeswiki.net/?DocumentationInstallation ?
Encore merci en tout cas

**Comment by mrflos** [comment]
Hello @EdmondAgate , enchanté!  
Je pensais plutot à https://yeswiki.net/?Doryphore qui avait été diffusé dans la newsletter. Merci si t'as le temps de documenter les cas problématiques!

**Comment by J9rem** [comment]
Je m'occupe de ce souci avec @EdmondAgate car il me semble qu'il y a un souci avec le serveur en fait.

**Comment by J9rem** [comment]
Bon le souci est dû au dossier tools/template qui ne peut être supprimé par la mise à jour s'il n'a pas les droits 777.
Est-ce que @mrflos tu sais pourquoi ?
En tout cas, @EdmondAgate peut maintenant rendre les mises à jour plus facile en changeant manuellement les droits du dossier tools/template à 777.

**Comment by mrflos** [comment]
j'ai fais un `git ls-files --stage` dans le dossier tools de mon dépot git yeswiki, mais apparemment les fichiers sont bien enregistrés soit en 755 ou 644 , et ne devraient pas poser de problème..  
Sur le serveur, un `ls -al` indique quoi comme permission et user:group ? Et sur du yeswiki "fresh install" tout juste envoyé par ftp?

**Comment by EdmondAgate** [comment]
En fait je suis même pas certain au final que le passage en 777 du dossier résout tous les problèmes de MAJ. J'ai refait des tests ce matin et autant ça a fonctionné pour certains wiki autant pour d'autres je me retrouvre encore avec des erreurs et cette fois le dossier tools/template au 3/4 vide (avec seulement le dossier libs/vendor/fontawesome... tout le reste ayant disparu à la MAJ). pas de différent avec un wiki fresh install par ftp malheuresement.
Pour répondre à la question ça donne :
drwxrwxr-x 3 root hosting-user 3 Apr 7 11:30 testwiki.hinaura.fr

**Comment by J9rem** [comment]
Oui pour moi ça vient d'un souci lors de la copie des fichiers de libs/vendor/fontawesome.

**Comment by EdmondAgate** [comment]
Merci en tout cas pour le coup de main la dessus...

**Comment by EdmondAgate** [comment]
ouais dans le log ça mets un souci de dossier non vidé... (la seule solution serait donc la suppresion manuelle...)
[03-May-2021 11:31:41 GMT] PHP Warning:  rmdir(/srv/data/web/vhosts/testwiki.hinaura.fr/htdocs/tools/templates/libs/vendor/fontawesome-5/svgs/solid): Directory not empty in /srv/data/web/vhosts/testwiki.hinaura.fr/htdocs/tools/autoupdate/app/Files.php on line 113
[03-May-2021 11:31:42 GMT] PHP Warning:  rmdir(/srv/data/web/vhosts/testwiki.hinaura.fr/htdocs/tools/templates/libs/vendor/fontawesome-5/svgs): Directory not empty in /srv/data/web/vhosts/testwiki.hinaura.fr/htdocs/tools/autoupdate/app/Files.php on line 113
[03-May-2021 11:31:42 GMT] PHP Warning:  rmdir(/srv/data/web/vhosts/testwiki.hinaura.fr/htdocs/tools/templates/libs/vendor/fontawesome-5): Directory not empty in /srv/data/web/vhosts/testwiki.hinaura.fr/htdocs/tools/autoupdate/app/Files.php on line 113
[03-May-2021 11:31:42 GMT] PHP Warning:  rmdir(/srv/data/web/vhosts/testwiki.hinaura.fr/htdocs/tools/templates/libs/vendor): Directory not empty in /srv/data/web/vhosts/testwiki.hinaura.fr/htdocs/tools/autoupdate/app/Files.php on line 113
[03-May-2021 11:31:42 GMT] PHP Warning:  rmdir(/srv/data/web/vhosts/testwiki.hinaura.fr/htdocs/tools/templates/libs): Directory not empty in /srv/data/web/vhosts/testwiki.hinaura.fr/htdocs/tools/autoupdate/app/Files.php on line 113

**Comment by J9rem** [comment]
Je laisse la main @mrflos pour cet aspect. Car je ne comprends toujours pas le souci.

**Comment by mrflos** [comment]
Juste pour avoir un peu de contexte, c'est sur tous les wikis installés sur cet hébergement ou au cas par cas?  
Quel est l'hébergeur? OVH?

**Comment by EdmondAgate** [comment]
Merci @mrflos ! ALors tout est chez Gandi en "simple hosting".
Alors ça me semble etre sur tous les wiki, mais j'avoue que le comportement se produit pas à toutes les MAJ sans que je trouve une raison (j'avais a un moment donné le sentiment que c'était entre certaines versions de wiki, mais ça semble se répéter). Dans le doute on avait repris un espace vierge d'hébergement sur gandi avec un wiki vierge depuis ftp, et même situation... On a aussi exclu l'option manque de RAM (dans le doute).

**Comment by mrflos** [comment]
est ce que tu pourrais faire un fichier php avec  
```php
<?php
phpinfo();
```
Pour me donner en particulier le `max_execution_time` de php pour gandi (si le temps d'execution du script est trop court, il ne finalise pas la suppression et recopie des fichiers de yeswiki).

A voir aussi si en mettant dans ce fichier, la valeur de `max_execution_time` passe bien à 300 secondes
```php
<?php
@ini_set('max_execution_time', 300);
@set_time_limit(300);
phpinfo();
```

Ce n'est qu'une piste parmi d'autres, mais au moins on saura..

**Comment by EdmondAgate** [comment]
avec plaisir ! alors c'était a 180 pr max_excution_time ms j'ai pu modifier a 300 
http://testwiki.hinaura.fr/phpinfo.php

sans que ça change qq chose (le dossier tool/templates et toujours au 3/4 vide...) http://testwiki.hinaura.fr/?GererMisesAJour&debug

**Comment by J9rem** [comment]
Je clos cette issue car a priori avec la nouvelle structure des dossiers /syles et /tooles/templates, il n'y a plus de bugs à la mise à jour
