### ISSUE TITLE
[Installation] Sur une connexion chiffrée (https) la mise en page du formulaire d'installation est cassée

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#605]
Bogue

**Description**
Lors de l'installation d'un nouveau wiki (cercopithèque, dernière version à cette date) la mise en page du formulaire de configuration ne s'affiche pas correctement. Dans Firefox a l'onglet "Réseau" tous les scripts JS sont marqués en "mixed block".
Ce que je comprend c'est que maintenant si l'on accède à un site en https, les références en http sont bloquées.
Même résultat avec Chromium.

**Informations complémentaires**
- version de YesWiki : cercopitheque-2020-06-05

**Comment by J9rem** [comment]
@daiko est-ce que cette issue est toujours d'actualité ?

**Comment by J9rem** [comment]
Vu que la version officielle est maintenant doryphore, je clos cette issue
