### ISSUE TITLE
[mail] Envoi de mail ne fonctionne pas depuis un domaine sans entrée MX dans la zone DNS.

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#606]
Bogue ou Nouvelle fonctionnalité ? je ne sais pas.

**Description**
Par défaut YesWiki envoie un mail depuis l'adresse "no-reply@host.domain.tld". Hors par mesure de sécurité certains serveurs SMTP vérifient si host.domain.tld a bien une entrée MX dans la zone DNS (je ne connais pas la fréquence mais cela semble courant). Si ce n'est pas le cas le mail est rejeté (dans mon cas avec un mauvais message d'erreur concernant le destinataire (RCPT)).

Pour corriger le problème il faut forcer l'adresse d'envoi (FROM) avec le paramètre 'BAZ_ADRESSE_MAIL_ADMIN' dans wakka.config.php. Malheureusement je n'ai pas trouvé ce paramètre dans la documentation. De plus ce paramètre est préfixé "BAZ" et donc semble s'appliquer uniquement à bazar. Ce n'est pas le cas : il concerne, au moins, aussi l'envoi de mail en cas de mot de passe perdu. 

Je propose de créer un paramètre "mail_from" qui servira dans le cœur et dans les extensions et de le documenter :). (sûrement à harmoniser avec les autres paramètre concernant l'envoi de mail préfixé eux aussi avec "BAZ")
Je pense qu'il serait intéressant de faire apparaître ce paramètre par défaut dans le fichier de configuration et de le préremplir avec "no-reply@domain.tld". Sans mettre le 'host' : il y a de fortes chances que cela fonctionne dans un  plus grand nombre de cas.

** Informations complémentaires**
- version de YesWiki : cercopitheque-2020-06-05
- extrait du log (caviardé) : 
```
php_1    | 172.23.0.3 -  13/Jan/2021:17:27:29 +0000 "GET /index.php" 200
php_1    | msmtp: recipient address xxxxxx@xxxxxx.xx not accepted by the server
php_1    | msmtp: server message: 553 5.1.8 <xxxxxx@xxxxxx.xx>... Domain of sender address noreply@test.cxxxxxx.xx does not exist
php_1    | msmtp: could not send mail (account default from /etc/msmtprc)
php_1    | msmtp: recipient address xxxxxx@xxxxxx.xx not accepted by the server
php_1    | msmtp: server message: 553 5.1.8 <fxxxxxx@xxxxxx.xx>... Domain of sender address noreply@test.xxxxxx.xx does not exist
php_1    | msmtp: could not send mail (account default from /etc/msmtprc)
php_1    | 172.23.0.3 -  13/Jan/2021:17:27:34 +0000 "POST /index.php" 200
```

**Comment by acheype** [comment]
slt !

J'avais justement rajouté le paramètre 'contact_from' pour ce type de besoin mais il n'est pas non plus documenté. Tu peux l'essayer sur ta version puisque c'était en mars 2020.
