### ISSUE TITLE
[Bazar] Erreur à l'enregistrement puis à l'affichage d'une fiche comportant une checkboxfiche vide

### ISSUE THREAD

**Issue by acheype** [YesWiki/yeswiki#607]
Essai avec l'option tags ou drag&drop, j'obtiens la même erreur :

```
PHP Fatal error: Uncaught TypeError: Return value of YesWiki\Lms\CourseStructure::getField() must be of the type string or null, array returned in /home/adri/projects/yeswiki/tools/lms/libs/CourseStructure.php on line 71
PHP Warning: htmlspecialchars() expects parameter 1 to be string, array given in /home/adri/projects/yeswiki/tools/bazar/libs/bazar.fonct.php on line 1029
```

Puis quand je vais voir ce que bazar a enregistré, on voit qu'il initialise mal une checkboxfiche vide :

```
{"bf_titre":"essai",...
"checkboxfiche1201bf_activites":{"END_INDEX NO_CHANGE_IT":"0"},
"id_typeannonce":"1202"," ... }
```

**Comment by J9rem** [comment]
Est-ce que c'est résolu avec ce [commit](https://github.com/YesWiki/yeswiki/commit/e35eb9b8506a18cf7604466fd54b0de19b45aca1) ? pouvons-nous alors clore cette issue ?

**Comment by acheype** [comment]
j'ai testé, cela fonctionne.
je n'ai pas pris le temps de comprendre le code.
