### ISSUE TITLE
Use of `REGEXP_LIKE` in MySQL query does not meet with MySQL version pre-requisite (5.6)

### ISSUE THREAD

**Issue by thom4parisot** [YesWiki/yeswiki#612]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**

Bug / Bogue

**Description**

Quand je mets à jour YesWiki, je tombe sur cette erreur :

```
Query failed: UPDATE pnthbis_pages SET body = regexp_replace(body, '"createur":".*?",', '') (FUNCTION pnth.regexp_replace does not exist)
```

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : doryphore-2021-01-24-3

[La fonction `regexp_replace` n'existe pas dans MySQL 5.6](https://dev.mysql.com/doc/refman/5.6/en/regexp.html). Elle apparaît dans MySQL 8.0.

Il y a un choix de version minimum de MySQL à faire, ou revoir la migration… je ne me rends pas compte de l'état du parc informatique hébergeant les YesWiki.

**Comment by acheype** [comment]
Merci pour ton retour, on avait déjà en vu en plus que certains avait des soucis de maj liée à cette fonction mais on n'a pas eu le temps de s'en occuper.

Suite au choix qu'on avait fait pour supprimer le champ createur car redondant, j'avais écris cette requête pour faciliter les mises à jour et flo l'avait rajouté. Mais en effet, il faut faire le choix, soit fixer la version minimal de MySql à 8, soit changer de manière de mettre à jour.

Sachant que MySQL 8 est sorti en 19 April 2018.
![2021-01-25 11-59 - Capture d'écran](https://user-images.githubusercontent.com/8435038/105697567-00eded00-5f05-11eb-8bfd-80a61f6044f5.png)

**Comment by thom4parisot** [comment]
Une date importante a l'air d'être "Février 2021" comme "fin de support" de MySQL 5.6 : ça veut dire qu'après cette date, y'a totale légitimité à ne plus supporter cette version, et donc migrer vers une autre — 5.7 ou 8. Mais MySQL 5.7 est proche de 5.6, et a encore 2 ans de durée de vie.

[WordPress supporte encore MySQL 5.6](https://wordpress.org/about/requirements/), par exemple.

Je ne me rends pas compte des différences entre ces 2 versions majeures de MySQL, et l'état du parc d'hébergement (est-ce que les hébergeurs ont déjà encouragé les gens à migrer vers une version plus récente ?).

Je ne verrais pas cette question sur "la version 8 a déjà 3 ans" mais "qu'est-ce qu'on s'engage à supporter ? Qu'est-ce que ça provoque comme impact chez nos utilisateur·ices ?"

**Comment by MelanieMichel** [comment]
Hello. petit retour d'utilisateur... effectivement changer de version MYSQL n'est pas à la portée d'un utilisateur lambda qui a installé son wiki sur un hébergement mutualisé.
Par exemple chez  OS2Switch actuellement MYSQL 5.7 
 ou OVH encore en MYSQL5.6 apparemment

**Comment by mrflos** [comment]
vu que la version 5.7 est supportée encore jusqu'en octobre 2023, on a 2 ans et demi pour revoir la facon de faire la mise a jour ;).  
J'avais regardé vite fait, mais sans les regexp, obligé de charger toutes les pages, et de sauver avec la modif, ce qui est peut etre long et dangereux...  
Vu que garder cette donnée sur le createur n'engendre pas de bugs, seriez vous ok de tester la version de mysql et de ne faire que la mise a jour si mysql > 8 ou mariadb > 10 ?  
Dans ce cas je pourrais le faire.

**Comment by thom4parisot** [comment]
Complètement, si y'a pas d'enjeu, cool de faire tourner cette requête seulement si la version du moteur le permet.

Et si la mise à jour d'un document "supprime" cette valeur lors du prochain enregistrement, ça se règlera petit à petit en attendant une mise à jour de la base de données.

**Comment by acheype** [comment]
go alors !

> Et si la mise à jour d'un document "supprime" cette valeur lors du prochain enregistrement, ça se règlera petit à petit en attendant une mise à jour de la base de données.

Y'a un autre "bug" ou mauvaise façon de faire qui fait que la sauvegarde fait un merge des anciennes valeurs avec les nouvelles... donc en l'état actuel, ça ne se réglera malheureusement pas petit à petit.
Mais à nous de corriger cela.

**Comment by thom4parisot** [comment]
Merci @MelanieMichel pour ton retour, et merci @mrflos de confirmer que c'était pas une montée en pré-requis nécessaire. Le correctif est tout simple du coup !

**Comment by mrflos** [comment]
merci a toi @oncletom pour le patch!
