### ISSUE TITLE
Impossible de supprimer un groupe dans page GererUtilisateurs

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#616]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Concerne l'action {{editgroups}} et plus précisemment "deletegroup"
Pour supprimer un groupe il est nécessaire de d'abord supprimer les users attachés.
Meme après avoir supprimé les users du groupe le message suivant apparait : ONLY_EMPTY_GROUP_FOR_DELETION.

Il semble que WikiAdmin reste ataché à tous les groupes mais pas moyen de l'enlever même en étant WikiAdmin...

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : doryphore 2021-01-24-3

**Comment by MelanieMichel** [comment]
Le bug semble résolu avec la version Doryphore 2021-02-04-2
A vérifier tout de même dans le code il reste un var_dump qui traine car la requete de suppression du groupe s'affiche
"$sql=UPDATE dory202009_acls SET list = REPLACE ......"
C'est pas grave grave, mais un coup de ménage sera le bienvenu

**Comment by J9rem** [comment]
Effectivement, la requête SQL est affichée par cette ligne : https://github.com/YesWiki/yeswiki/blob/doryphore/actions/EditGroupsAction.php#L141
@mrflos est-ce qu'on garde l'affichage de la requête sql ?

**Comment by mrflos** [comment]
ben non!

**Comment by J9rem** [comment]
C'est corrigé https://github.com/YesWiki/yeswiki/commit/0da27c59556cfbfd9543ce9e881c6d89ea198941
Je clos cette issue donc.
