### ISSUE TITLE
créer un test pré-install doryphore qui s'assure de php7.3

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#621]
**créer un test pré-install doryphore qui s'assure de php7.3**
New feature / Nouvelle fonctionnalité

**Description**
Quand on passe de Cerco à Doryphore sur un serveur qui n'est pas en php7.3, s'engage un grand moment de solitude.
page qui nous indique qu'il faut le serveur ad'hoc mais impossible de revenir en arrière...
Proposition de créer, avant de lancer la procédure de mise à jour à proprement dite, de faire un test qui ne lance pas l'installe mais envoie un message indiquant que le serveur doit être mis à jour pour pouvoir continuer

**Additionnal informations / Informations complémentaires**
- passage de cerco à dory

**Comment by J9rem** [comment]
@furax37 c'est résolu, donc je me permets de clore cette issue
