### ISSUE TITLE
Quand le <br> s'invite dans les formulaires bazar

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#622]
**Quand on ajoute un champ dans un formulaire bazar un <br> est rajouté en fin de label**
Bug / Bogue

**Description**
Quand on ajoute un champ dans un formulaire bazar un <br> est rajouté en fin de label
`textelong***textarea_1611757379897***super zone de texte<br>*** *** *** *** ***wiki***0*** *** *** * *** * *** *** ***`

**Additionnal informations / Informations complémentaires**
- Doryphore

**Comment by J9rem** [comment]
Ah désolé @furax37 pour cette partie c'est @seballot

**Comment by gatienbataille** [comment]
je rajoute le fait que se rajoute de manière quasi automatique et systématique une ligne ""titre de la fiche" en bas de chaque formulaire. et même si enlevé, ça revient
problème, ça rend régulièrement le rendu du contenu du formulaire impossible

**Comment by mrflos** [comment]
ca avait été corrigé, tu es sur que c'est encore le cas dans la dernière version?

**Comment by gatienbataille** [comment]
ben.. le wiki est sous doryphore 2021-02-04-2
et ya encore ça dans les formulaires... 
bon je les enlève et vois s'ils reviennent

```
textelong***textarea_1610456434591***Infos pratiques <br>*** *** *** *** ***wiki***1*** *** *** * *** * *** *** ***
textelong***textarea_1612343237567***Site internet de la source<br>*** *** *** *** ***wiki***0*** *** *** * *** * *** *** ***
```

**Comment by J9rem** [comment]
> 
> 
> je rajoute le fait que se rajoute de manière quasi automatique et systématique une ligne ""titre de la fiche" en bas de chaque formulaire. et même si enlevé, ça revient
> problème, ça rend régulièrement le rendu du contenu du formulaire impossible

Bon @gatienbataille pour être sûr d'avoir bien compris :
 - tu constates qu'il y a toujours avec doryphore 2021-02-04-2 l'apparition du <br>.
 - tu ne constates plus l'ajout automatique d'un champ `titre` lors de l'édition d'un formulaire alors que ce bug était présent dans les versions précédentes.
 
 Confirmes-tu ?

**Comment by gatienbataille** [comment]
bon les br étaient encore présents et les champ titre à la fin du formulaire aussi
mais je ne parviens pas à savoir s'ils étaient là avant la mise à jour vers dernière version (et donc ce serait ok)

j'ai donc nettoyé les formulaires des br et autre titre fiche et je te tiens au jus s'ils réapparaissent malgré le fait que je suis maintenant sur la dernière version de doryphore 2021-02-04-2

**Comment by J9rem** [comment]
a priori réparé par https://github.com/YesWiki/yeswiki/commit/2da7b57eb675afe555c447c4bdd92f76bd05e25e, il n'y a plus qu'à attendre la prochaine release
