### ISSUE TITLE
importation de listes depuis un autre wiki, ça manque de cases

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#623]
**pas de cases pour importer les listes depuis un autre wiki**
Bug / Bogue

**Description**
Quand on souhaite importer des listes depuis un autre wiki, seule la case importer toutes les listes est disponible. je ne peux pas les importer listes par listes, les cases à cocher manquent contrairement à la possibilité d'importer des formulaires.
Ce bug est associé à margot car quand on utilise un autre thème, tout rentre dans l'ordre.

**Additionnal informations / Informations complémentaires**
- doryphore __avec le thème Margot__
- screenshot / capture d’écran

**Comment by gatienbataille** [comment]
je confirme le bug sur dernière version doryphore 2021-27-01-04

**Comment by gatienbataille** [comment]
se résoud temporairement en passant par un autre thème que margot

**Comment by J9rem** [comment]
J'ai fait un [commit](https://github.com/YesWiki/yeswiki/commit/085f3288955cf7d3bd72be13f7016c79a1c26ccd) directement sur Doryphore pour répondre à l'issue.
