### ISSUE TITLE
Mais il est où, hein, le crayon ? (sur un air de richard gotainer)

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#624]
**le petit crayon a disparu quand on créé une nouvelle page qui est vide**
Bug / Bogue

**Description**
Normalement, une page wiki créée à l'aide d'un ChaMot ou d'un [[Nouvellepage Nouvelle Page]] vide est matérialisée par un petit crayon qui est bigrement absent...
**Additionnal informations / Informations complémentaires**
- doryphore

**Comment by J9rem** [comment]
Fix déjà proposé dans le commit https://github.com/YesWiki/yeswiki/pull/626/commits/517fcf36fde502751f5e2f2cdfcd95473ba2ae0c mais je préfère pour celui-ci voir si Florian voit des effets de bords avant de fusionner.

**Comment by J9rem** [comment]
Est-ce qu'on peut clore cette issue @furax37 ?
