### ISSUE TITLE
Pages Spéciales, un comportement très spécial

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#625]
**Quand on appelle une PageHeader particulière, l'image pourtant téléchargée est à nouveau proposée au téléchargement**
Bug / Bogue

**Description**
Un site qui a une jolie page Header comportes des parties au sein desquelles nous souhaiterions afficher une PageHeaderPratique
Quand on l'appelle directement tout se passe bien  : https://formationcivamgard.fr/?PageHeaderPratique
Quand on appelle cette page dans en tant que page Header, ça demande à re-télécharger l'image... : https://formationcivamgard.fr/?PraTiques1

**Additionnal informations / Informations complémentaires**
- dory

**Comment by J9rem** [comment]
@furax37 j'ai normalement résolu le bug avec la PR#666, je clos
