### ISSUE TITLE
Invalid argument supplied for foreach() … in `bazar/services/Guard.php`

### ISSUE THREAD

**Issue by thom4parisot** [YesWiki/yeswiki#627]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**

Bug / Bogue

**Description**

Quand je me rends sur https://cocotier.xyz/?WeekNotes/rss (cc @furax37), j'obtiens ce message en début du RSS : 

```
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/clients/client5/web28/web/tools/bazar/services/Guard.php</b> on line <b>75</b><br />
```

Ça rend le flux RSS impossible à parser.

**Additionnal informations / Informations complémentaires**
- version of YesWiki : `doryphore 2021-01-26-1`

**Comment by J9rem** [comment]
normalement résolu par #671

**Comment by thom4parisot** [comment]
Je confirme, c'est OK après mise à jour 🙂 

Merci !
