### ISSUE TITLE
t'as le style coco (sauf après une liste à puce)

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#634]
**En mode édition, pas de coloration syntaxique des titres après une liste à puce**
Bug / Bogue

**Description**
en mode édition, on voit le style s'afficher quand on met un titre du style ===titre===
quand ce titre est après une liste à puce, le style est inopérant
===titre en couleur===
 - et hop
 - et hup
 - et hip
===nouveau titre qui ne sera pas mis en couleur===
 - et re hop
 - et re hup
alors que 

===titre en couleur===
 - et hop
 - et hup

===nouveau titre sera en couleur===
 - et re hop
 - et re hup

**Additionnal informations / Informations complémentaires**
doryphore

**Comment by J9rem** [comment]
Bon en fait, ça n'est pas un bug, car pour indiquer la fin d'une liste, il faut une ligne vide.
