### ISSUE TITLE
le html dans une liste bazar n'est plus interpreté 

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#636]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lorsqu'on met du HTML dans la valeur d'un élément d'une liste par exemple une  icone pour illustrer ou un lien vers une page de documentation), le code n'est pas interprété lorsqu'on affiche le formulaire (saisie ou consultation) .

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : doryphore 2021-01-27-4
- url to see the problem or an example / url pour voir le probleme ou un exemple
Par exemple sur ce formulaire en saisie :
 https://cliketik.fr/?ProDucteur

**Comment by J9rem** [comment]
@MelanieMichel je te signalerai la nouvelle version de Doryphore pour que tu puisses tester si j'ai trouvé tous les endroits

**Comment by J9rem** [comment]
@MelanieMichel peux-tu confirmer que c'est résolu avec les dernières mises à jour pour que je puisse clore cette issue ? merci

**Comment by MelanieMichel** [comment]
Merci @J9rem c'est tip top avec dernière mise à jour
