### ISSUE TITLE
Le composant "bazarliste" ne détecte pas les champs de type "datedeb"

### ISSUE THREAD

**Issue by thom4parisot** [YesWiki/yeswiki#638]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**

Je viens d'insérer ce bout de code pour afficher les données Bazar du formulaire "Agenda", créé par défaut lors d'une installation YesWiki. À ma grande surprise, je ne peux sélectionner de "champ de date pour le début", ni pour trier les résultats.

![image](https://user-images.githubusercontent.com/138627/106608597-e4852c80-6564-11eb-87e5-9b1519c99763.png)

Il n'y a d'ailleurs aucun champ de tri qui apparait : 

![image](https://user-images.githubusercontent.com/138627/106608823-28783180-6565-11eb-9a90-5a398a15124b.png)

Voici pourtant un extrait du formulaire :

```
texte***bf_titre***Nom de l'événement***60***255*** *** ***text***1*** *** *** * *** * *** *** ***
textelong***bf_description***Description***40***10*** *** ***wiki***0*** *** *** * *** * *** *** ***
listedatedeb***date_1612273148330***Champ Date*** *** *** *** *** ***0*** *** *** * *** * *** *** ***
listedatedeb***bf_date_debut_evenement***Début de l'événement*** *** *** *** *** ***1*** *** *** * *** * *** *** ***
texte***bf_horaire***Horaire de début<br>***60***255*** *** ***text***0*** *** *** * *** * *** *** ***
```

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki celle en date du 1er février 2021

**Comment by mrflos** [comment]
Depuis le refacto. de @srosset81 ,  le tableau des formulaires qui contenait des données formatées dans un champs "prepared" renvoies des object plutot qu'un tableau de valeur, et il me semble que c'est cela qui casse le fonctionnement des champs.  
Je n'ai pu investiguer que jusque là, ya un handler `/tools/bazar/handlers/page/bazar_api.php` appelé en ajax par l'actionbuilder qui utilise encore les anciennes fonctions et qui donc n'envoie pas les valeurs au bon format (mon hypothèse).

EDIT: c'est a propos des facettes, pour les champs date j'ai pas regardé, j'ai juste voulu laisser une trace.

**Comment by mrflos** [comment]
sans doute en lien avec #645

**Comment by J9rem** [comment]
Salut @oncletom ,

effectivement, il semble que c'était en lien avec #645.
Est-ce résolu avec la dernière version Doryphore ?

**Comment by J9rem** [comment]
Je clos cette issue. J'espère que tu n'as plus le bug @oncletom

**Comment by thom4parisot** [comment]
Yes c'est bueno, trop bien merci 🙂 

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/138627/108592903-a2375a00-7370-11eb-999c-a72123a74510.png">
