### ISSUE TITLE
Tu me fais tourner la tête (quand ma photo est de travers dans un formulaire bazar)

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#641]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Trouver une astuce pour que les photo dans un formulaire bazar ne soient pas tournées dans tous les sens. Les gens pensent qu'elle est dans le bon sens mais à la sauvegarde, elle s'avère tournée. je les reprends via gimp mais quand beaucoup de saisies...

**Additionnal informations / Informations complémentaires**
- Doryphore

**Comment by J9rem** [comment]
je clos cette issue car corrigée par #948
