### ISSUE TITLE
 le formulaire de contact bazar ne fonctionne pas depuis une iframe

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#642]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Dans une fiche bazar dont le champ mail propose d'envoyer un mail via yeswiki, **affichée en pop up** le lien généré n'est pas bon **quand on clique sur "envoyer le message"** et incite donc à créer une nouvelle page.

https://cocotier.info/repit/?email=lm%40furax37.org&subject=test+de+message&message=mon+message&submit=&mail=bf_mail
il manque il manque <nompage>/mail&mail=....

**Additionnal informations / Informations complémentaires**
- doryphore

**Comment by J9rem** [comment]
Salut @furax37 
j'essaie de reproduire le bug sur la dernière version de Doryphore et je ne l'ai pas.
As-tu un nom de version spécifique ?
Peux-tu me donner le lien vers la fiche concernée ?

**Comment by furax37** [comment]
https://cocotier.info/repit/?email=laurent%40marseault.info&subject=re+test+re+test&message=test+de+message&submit=&mail=bf_mail
toujours le même problème avec la dernière version de dory : 
https://cocotier.info/repit/?TrombiAnnuaire
teste depuis la fiche de sébastienne Clavel

**Comment by J9rem** [comment]
@furax37 j'ai beau essayé le site dans tous les sens, je n'arrive jamais à reproduire le lien que tu as donné.
Ce lien : https://cocotier.info/repit/?email=lm%40furax37.org&subject=test+de+message&message=mon+message&submit=&mail=bf_mail est faux mais normalement il n'est jamais généré par le site.

**Comment by furax37** [comment]
Alors, tu vas sur la page trombi du site
https://cocotier.info/repit/?TrombiAnnuaire
tu vas sur la fiche de sébastienne Clavel qui va s'ouvrir en pop up
là tu cliques sur le bouton pour lui envoyer un mail
tu remplis tous les champs et tu clique sur envoyer et là...

**Comment by J9rem** [comment]
C'est bon, j'ai pu reproduire le souci en local.
Ça vient du fait que la fenêtre modal ne charge par les scripts mais uniquement le composant de classe CSS "page".
Sauf que selon les templates .tpl.html, les scripts sont parfois déjà chargés (comme accordion et map) et d'autres non comme trombinoscope.

**Comment by furax37** [comment]
trop fort !!!

**Comment by J9rem** [comment]
Par contre chaud à corriger ça transpire de mon côté, ...

**Comment by J9rem** [comment]
a priori ça fonctionne maintenant avec le dernier commit.

**Comment by J9rem** [comment]
C'est réparé, donc je me permets de clore l'issue. Ok pour toi @furax37 ?
