### ISSUE TITLE
Dans /edit > composants > "bazarliste" ... le choix des facettes ne s'affiche plus

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#645]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug

**Description**
Lors de l'édition d'une page (handlers `/edit`), en cliquant sur le bouton `composants` (module de l'extension aceditor), en choisissant "afficher les données d'un formulaire", il n'est pas possible de pouvoir choisir des facettes pour les filtres.
Toutefois, il semble que ça fonctionne en entrant "à la main" les paramètres dans le texte de la page.
 
**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore 2021-02-04-2

**Comment by gatienbataille** [comment]
commentaire par rapport aux facettes dans dory avec le composeur graphique bazar
j'ai rencontré plusieurs wikis avec difficulté # aux facettes 
en fait les difficultés venaient non pas de la facette mais du titre des ListeListe ou checkbox

dans le composeur bazar, quand on demande un checkbok ou une liste
si on garde son habitude "de user", on nomme le champ (en plus du label)
et ça, ça fout la merde car du coup dans l'appel à la facette
faut pas juste mettre checkbokListeNomliste mais y ajouter le nom du champ aussi
checkbokListeNomliste => checkbokListeNomliste_nomduchamp

du coup le user lambda quand il construit sa facette ben ça il le sait pas... (moi je passe par /raw sur la fiche pour voir)

est ce gérable ? genre empêcher de nommer le champ si c'est une liste ou un checkbox ou ... une autre piste

**Comment by J9rem** [comment]
@furax37 est-ce que tu peux tester si ça fonctionne avec la prochaine release ?

**Comment by J9rem** [comment]
A priori les facettes sont revenues
