### ISSUE TITLE
bazarliste calendrier.tpl et agenda.tpl impossible d'afficher les dates avant 1970

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#648]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
BUG

**Description**
`{{bazaliste template="calendrier" ...}}` et `{{bazaliste template="agenda" ...}}` n'affichent pas les dates avant 1970.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore 2021-02-04-2

**Comment by furax37** [comment]
et certaines fois, je n'arrive pas à stabiliser le bug, la date proposée est cette de 1970

**Comment by J9rem** [comment]
Salut @furax37 ,
j'ai refait le test avec la dernière version 2021-02-12.
J'ai l'impression que ça fonctionne.
Confirmes-tu ?

**Comment by furax37** [comment]
j'ai toujours ce comportement mais sans arriver à stabiliser le bug

**Comment by furax37** [comment]
1970-01-01 toujours cette satanée date proposée...
![Screenshot_2021-04-29 Secoueur de cocotiers](https://user-images.githubusercontent.com/1269848/116608719-d3657500-a933-11eb-9067-d9620b8cdb36.png)

**Comment by J9rem** [comment]
Est-ce que @furax37 tu peux changer cette date par la suite ?

**Comment by J9rem** [comment]
@furax37 peux-tu me donner la version de doryphore que tu utilises pour avoir cette satanée date ?

**Comment by J9rem** [comment]
Est-ce que tu pourrais @furax37 m'envoyer le lien vers le site qui plante ?
ainsi que le numéro du formulaire concerné ?

je pense que le correctif est actif depuis quelque temps mais il te faudrait aller modifier le formulaire et le réenregistrer pour que tout rentre dans l'ordre.
toutefois, je peux me tromper.

**Comment by J9rem** [comment]
A priori, ce souci sera réparé dans la prochaine release @furax37

**Comment by J9rem** [comment]
@furax37 je vais bbientôt clore cette issue car je pense qu'elle est réoslue
