### ISSUE TITLE
impossible de se déconnecter du wiki

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#649]
en version doryphore 2021-02-04-2

connexion au wiki sans souci mais lors de la déconnexion, 
 - même si tout semble se passer "normalement"
- message vous êtes déconnecté apparaît 

mais en fait, on est pas déconnecté ;-(
seul moyen, quitter le wiki et relancer un nouvel onglet

constaté sur 2 wikis différents

**Comment by J9rem** [comment]
@gatienbataille est-ce que tu peux confirmer que ça ne se produit plus avec les dernières versions Doryphore ?
Pense bien à faire attention à différencier:
 - ne pas se déconnecter quand c'est le compte admin qui vient de faire la mise à jour
 - ne pas réussir à se déconnecter pour un autre compte qui se connecte après la mise à jour

**Comment by mrflos** [comment]
et faire les test en nav privée, pour éviter d'avoir des cookies qui trainent!

**Comment by gatienbataille** [comment]
ok je teste sur dernière version (pour instant le user super admin ça semble passer)
je teste maintenant pour des users "basiques" et donc aussi en nav privée

**Comment by gatienbataille** [comment]
ok je confirme avec doryphore 2021-02-10-3

en mode normal et en mode nav privée
OK avec le compte user de celui qui a créé le wiki
ok avec des users basiques

merci !

**Comment by J9rem** [comment]
Ce qui est cool, c'est que je n'ai rien fait ....
(je pense que c'était dû à la grosse mise à jour du refacto qui changeait des trucs aussi dans la gestion des cookies, ....)
