### ISSUE TITLE
redirecturl ne semble  plus fonctionner sous doryphore 2021-02-04-2

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#650]
testé sur 2 wikis différents 

si redirecturl dans les param du bazar vue saisir => alors la fiche est bien enregistrée 
MAIS
- le redirecturl ne fonctionne pas 
- on revient directement sur la page (mode saisir et donc sans avoir non plus l'aperçu de la fiche enregistrée)

je mets en prioritaire sans savoir si c'est une bonne idée mais je crois que ce param est assez bien utilisé...

**Comment by J9rem** [comment]
@gatienbataille est-ce que ça marche maintenant ? (patiente peut-être avec la prochaine release)

**Comment by gatienbataille** [comment]
test fonctionnel avec doryphore 2021-02-10-6 : merci !
