### ISSUE TITLE
souci avec facette quand on nomme un champ checkbok ou liste 

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#651]
j'ai rencontré plusieurs wikis avec difficulté # aux facettes
en fait les difficultés venaient non pas de la facette mais du titre des ListeListe ou checkbox

dans le composeur graphique bazar, quand on demande un checkbok ou une liste
si on garde son habitude "de user", on nomme le champ (en plus du label)
et ça, ça fout la merde car du coup dans l'appel à la facette
faut pas juste mettre checkbokListeNomliste mais y ajouter le nom du champ aussi
checkbokListeNomliste => checkbokListeNomliste_nomduchamp

du coup le user lambda quand il construit sa facette ben ça il le sait pas... (moi je passe par /raw sur la fiche pour voir)

est ce gérable ? genre empêcher de nommer le champ si c'est une liste ou un checkbox ou ... une autre piste

**Comment by J9rem** [comment]
@gatienbataille ta remarque est pertinente.
Par contre, je me permets de dire que ça n'est pas un bug mais une nouvelle fonctionnalité et je change le label en conséquence.
Si vraiment, tu penses que c'est un bug (ça plante quoi) alors je te laisse remettre le label bug, je comprendrais.

L'idée est vraiment de faire le tri entre ce qui plante (urgent avec des degré de priorité différents) de ce qui est nouveau (pouvant être urgent et prioritaire mais que je ne ferrai pas dans la presta de debug)

**Comment by gatienbataille** [comment]
Salut

Excellente remarque, en effet ce n'est pas un bug, juste un changement dans la pratique qui induit les users en erreur.
Ok avec toi donc
par contre c'est vraiment gênant à l'usage car "de facto" ça bloque presque l'usage des facettes ;-(

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/38/bazar-and-facettes-simplifier-le-nommage-et-lutilisation-des-champs-checkbox-et-liste
