### ISSUE TITLE
une facette de type tags s'affiche en mode raw au lieu de trier par listes

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#652]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug

**Description**
si dans un formulaire on a
```
tags***bf_tags***Mots clés*** *** *** *** *** ***0*** ***texte d aide*** * *** * *** *** ***
```
puis qu'on appelle la facette en question dans une page
```
{{bazarliste id="17" groups="bf_tags" titles="Mots clés"}}
```

la liste est affichée en mode texte !

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore 2021-02-04-2
- 
![image](https://user-images.githubusercontent.com/67152407/107058543-0ab10380-67d5-11eb-885c-0c7196778a94.png)

**Comment by mrflos** [comment]
c'est pas sensé marcher, facette ne marche qu'avec les listes (et listefiche) et checkbox (et checkboxfiche)

**Comment by mrflos** [comment]
mais cela serait une belle avancée que cela accepte d'autres types de champs!

**Comment by J9rem** [comment]
ok je le passe en proposition si c'est du nouveau ;-)

**Comment by J9rem** [comment]
C'est corrigé
