### ISSUE TITLE
la redirection après la création d'une fiche bazar ne fonctionne pas à tous les coups

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#653]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug

**Description**
Le redirection après création d'une fiche bazar permet par défaut d'afficher cette fiche.
Dans plusieurs cas, on revient sur la page de création d'une nouvelle fiche.
```
{{bazar vue="saisir" id="1" voirmenu="0"}}
```

le paramètre `redirecturl` ne semble pas pris en compte.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore 2021-02-04-2

**Comment by mrflos** [comment]
doublon avec #650

**Comment by J9rem** [comment]
effectivement, je clos celle-ci
