### ISSUE TITLE
Un mot-clé avec accent ne peut être filtré via l'attribut `query` de `{{bazarliste}}`

### ISSUE THREAD

**Issue by thom4parisot** [YesWiki/yeswiki#655]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**

Bug / Bogue

**Description**

J'ai créé des événements d'agenda, dont certains contiennent les mots clés "Agenda21" et "Comité21".

![image](https://user-images.githubusercontent.com/138627/107388869-8d4c0280-6af6-11eb-8c31-2128d3e86325.png)

J'étais surpris de ne pas obtenir de résultats en utilisant un mot-clé accentué : 

```
{{bazarliste id="2" template="liste_liens_date" champ="bf_date_debut_evenement" ordre="desc" query="bf_tags=Comité21" }}
```

![image](https://user-images.githubusercontent.com/138627/107389182-dbf99c80-6af6-11eb-9abf-083576dd0dcf.png)

Alors que si j'utilise un mot-clé non-accentué, j'obtiens bien le résultat attendu :

```
{{bazarliste id="2" template="liste_liens_date" champ="bf_date_debut_evenement" ordre="desc" query="bf_tags=Agenda21" }}
```

![image](https://user-images.githubusercontent.com/138627/107388982-aa80d100-6af6-11eb-8b68-a248ebb3d815.png)

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : dernier doryphore en date

**Comment by J9rem** [comment]
Normalement c'est corrigé avec la dernière release Doryhore.
Est-ce O pour toi @oncletom ?
Si OK, je te laisse clore cette issue.

**Comment by J9rem** [comment]
Je clos l'issue car c'est maintenant résolu.
