### ISSUE TITLE
[Doryphore] Fatal error à l'edition d'une page.

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#656]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Après une installation fraiche de YesWiki, j'obtiens une erreur fatale lorsque je tente d'éditer une page. La constante GLOB_BRACE ne sembe pas définie.

**Additionnal informations / Informations complémentaires**
- version of YesWiki : Doryphore 2021-02-08-3
- Le message d'erreur :
```
Fatal error: Uncaught Error: Undefined constant "GLOB_BRACE" in /var/www/html/doryphore/tools/aceditor/actions/actions_builder.php:10 Stack trace: #0 /var/www/html/doryphore/handlers/page/edit.php(179): include() #1 /var/www/html/doryphore/includes/YesWiki.php(777): include('/var/www/html/d...') #2 /var/www/html/doryphore/includes/services/Performer.php(168): YesWiki\Wiki->runFileInBuffer('handlers/page/e...', NULL) #3 /var/www/html/doryphore/includes/YesWiki.php(744): YesWiki\Core\Service\Performer->run('edit', 'handler', Array) #4 /var/www/html/doryphore/includes/YesWiki.php(1204): YesWiki\Wiki->Method('edit') #5 /var/www/html/doryphore/index.php(70): YesWiki\Wiki->Run('PagePrincipale', 'edit') #6 {main} thrown in /var/www/html/doryphore/tools/aceditor/actions/actions_builder.php on line 10
```

**Comment by mrflos** [comment]
A priori `GLOB_BRACE` est une constante système de php et sur https://www.php.net/manual/en/function.glob.php ils disent que cela n'existe pas sous Solaris, c'est ton cas?  

Sinon à priori on peut convenir de n'appeler que les fichiers yaml en .yaml plutôt que yml et dans ce cas, et plus besoin d'utiliser cette option.

**Comment by fbredow** [comment]
Nop pas de Solaris chez moi mais je suis sur PHP 8. Peut être ça. Pour être exact c'est un container docker php:8.0-fpm-alpine

**Comment by fbredow** [comment]
Alors c'est pas PHP 8 mais Alpine qui ne connaît pas GLOB_BRACE (https://github.com/wp-media/wp-rocket/issues/146) et ce qui était un warning sous PHP 7 devient une erreur sous PHP 8.

**Comment by fbredow** [comment]
J'ai remplacé par :
```php
$docFiles = glob('docs/actions/*.y*ml');
$extenstionDocFiles = glob('tools/**/actions/documentation.y*ml}');
$docFiles = array_merge($docFiles, $extenstionDocFiles);
```
ça fonctionne mais j'ai un peu peur des effets de bord... les options de patterns semblent limitée. Sinon :
```php
$docFiles = array_merge(
    glob('docs/actions/*.yml'), 
    glob('docs/actions/*.yaml'),
    glob('tools/**/actions/documentation.yml'), 
    glob('tools/**/actions/documentation.yaml')
);
```
Mais `glob` semble gourmand, c'est pas très bon de l'utiliser autant.

**Comment by mrflos** [comment]
yep j'ai carrément viré le support des .yml apres avoir demandé l'avis sur le channel dev sur framateam
