### ISSUE TITLE
[Doryphore] Bouton copier ne fonctionne pas dans la page d'edition d'un composant.

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#657]
Bug / Bogue

**Description**
Le bouton "Copier" n'a pas d'effet quand je créé un composant (bouton, sommaire, étiquette...). 

D'ailleurs j'ai tenté de l'utiliser car je n'ai pas vu le bouton "insérer dans la page" dans un premier temps. Comme il est gris il est plus visible. Peut être mettre une couleur sur le bouton insérer dans la page pour le rendre plus visible. (il me semble plus important)

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : Doryphore 2021-02-08-3

**Comment by J9rem** [comment]
C'est réparé. Est-ce que je peux clore l'issue @daiko ?

**Comment by fbredow** [comment]
Merci pour la réparation ! naturellement tu peux fermer :)
