### ISSUE TITLE
[Doryphore] Warning lors de l'edition d'une étiquette

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#658]
Bug / Bogue

**Description**
Lorsque j'édite une étiquette des warning apparaissent (cf capture d'écran). Ils n’apparaissent que parce que j'ai activé la visualisation des erreurs mais l'accès à un élément inexistant d'un tableau peut poser problème.

**Additionnal informations / Informations complémentaires**
- version de YesWiki : Doryphore 2021-02-08-3
![yeswiki-bug-etiquette](https://user-images.githubusercontent.com/1093091/107488334-815c5100-6b87-11eb-82ec-7b4edf2aa5be.png)

**Comment by fbredow** [comment]
Même message d'erreur sur le composant "Encadré"

![yeswiki-bug-encadre](https://user-images.githubusercontent.com/1093091/107489815-5ffc6480-6b89-11eb-915d-b53fede5492d.png)

**Comment by acheype** [comment]
Oui ce n'est pas étonnant, YesWiki en regorge. Et en tant que dev, je peux te témoigner que j'en enlève fréquemment.
La chasse au warning est vraiment une activité à part ;)

Merci de les remonter comme tu le fais.
A ta place je ferais tout de même attention à ne pas laisser en prod l'affichage des warnings car il y en a toujours qui peuvent ressurgir, et ce même s'il y a eu une vrai extermination ces derniers mois.

**Comment by fbredow** [comment]
Je te rassure ce n'est pas en prod :) c'est sur mon environnement de dev (d'où le php8)

**Comment by J9rem** [comment]
a priori, le dernier commit sur Doryphore corrige ce souci dû au nouveau handler render.
@daiko je te laisse clore cette issue dès que tu auras pu tester que c'est bon soit sur la prochaine release soit avec un git clone si c'est ton truc

**Comment by J9rem** [comment]
Je clos cette issue car je sais que c'est corrigé.
