### ISSUE TITLE
[Doryphore] Composant syndication : deprecated + fatal error

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#659]
Bug / Bogue

**Description**
Lorsque je veux ajouter un flux RSS via la barre d'outils, la page d’édition du flux fait apparaître deux messages d'erreur (Cf capture d'écran)
Malheureusement il n'y a pas moyen de les copier coller ni de les voir en entier.

**Additionnal informations / Informations complémentaires**
version de YesWiki : Doryphore 2021-02-08-3

![yeswiki-bug-syndication](https://user-images.githubusercontent.com/1093091/107489123-8bcb1a80-6b88-11eb-8cff-7ec544faa73e.png)

**Comment by J9rem** [comment]
Merci @daiko pour ce signalement. Le bug est-il toujours présent avec la dernière version ?

**Comment by furax37** [comment]
testé, ça fonctionne, je propose de clore cette issue
