### ISSUE TITLE
les labels des facettes ne sont pas triées dans l'ordre alphabétique

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#660]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité
c'est presque un bug

**Description**
les facettes ne sont pas triées dans le même ordre avec un affichage random
`{{bazarliste id="1" template="trombinoscope.tpl.html" random="1" groups="checkboxfiche5,checkboxfiche6ressources,checkboxfiche8recherche" titles="Organisations,Ressources,Recherche" groupsexpanded="undefined"}}`

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore 2021-02-10-3

**Comment by mrflos** [comment]
@EdmondAgate va tester de mettre `natcasesort($list['label']);`
dans  `tools/bazar/services/BazarListeService.php` vers la ligne 197, avant `foreach ($list['label'] as $listkey => $label) {`
