### ISSUE TITLE
deletepage pour une fiche en mode modal ne renvoit pas sur la page courante

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#661]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug (petit bug)

**Description**
Bug non prioritaire : deletepage sur une fiche  en mode modal ne renvoit pas sur la page courante

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore 2021-02-10-3

**Comment by acheype** [comment]
finalement c'était bcp plus galère que ce que je croyais au début.

j'ai du modifier comment sont appelé les modalbox dans le yeswiki-base.js, elles appellent avec l'argument incomingUrl (impossible sinon à l'intérieur d'avoir la page affichée par le navigateur).
ça fonctionne bien maintenant avec les fiches bazar ainsi que les pages classiques (barreredaction doit être affiché pour pouvoir effectuer la suppression)

je pense qu'il faudrait généraliser le fait de passer l'argument incomingurl car il me semble qu'il y a d'autres endroits où la logique de navigation est coupée.

résolu par a30fe92
