### ISSUE TITLE
colorfield et color ne fonctionnent plus sous dory doryphore 2021-02-10-6

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#663]
Sur ce wiki https://cooptic.be/test/?FacetteRessource (constaté sur plusieurs wiki sous dernière version)

test avant mise à jour sous dory 2020-10-22-1 : colorfield et color fonctionnent
![Capture d’écran 2021-02-10 à 20 59 33](https://user-images.githubusercontent.com/7147716/107564949-50aa0500-6be3-11eb-8ad0-a130bdda1476.png)

après mise à jour, les couleurs ont disparu ;-(
![Capture d’écran 2021-02-10 à 21 00 28](https://user-images.githubusercontent.com/7147716/107564954-53a4f580-6be3-11eb-8845-2ba129cc0ccc.png)

**Comment by J9rem** [comment]
Je prends car je sais d'où ça vient et j'ai ma part dans le bug

**Comment by J9rem** [comment]
les couleurs sont revenues https://github.com/YesWiki/yeswiki/commit/9e57e0b30a80a65b874b3267b25f5ca9dbf9280e
