### ISSUE TITLE
action-builder colormapping iconmapping no autoupdate of values and bug whan deleting color

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#665]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
BUG

**Description**
Lors de l'utilisation de l'action builder pour bazarliste
s'il y a usage de colormapping avec colorfield
ou de iconmapping avec iconfield

1) par défaut, la liste pour sélectionner la valeur associée à une couleur (ou un icône) est vide et elle n'est pas rafraichie lors du changement ou du choix de colorfield (iconfield)
2) lors de la suppression de la première ligne si on configure plusieurs couleurs, alors il y mise à zéro de la liste de sélection de la ligne suivante.
3) la liste apparaît même quand il n'y a pas d'options disponibles

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore 2021-10-6
- 
![image](https://user-images.githubusercontent.com/67152407/107634691-3a935780-6c6a-11eb-95de-60b047281075.png)
![image](https://user-images.githubusercontent.com/67152407/107634735-4bdc6400-6c6a-11eb-9cd6-dc0e1045d624.png)

après suppression de la première ligne
![image](https://user-images.githubusercontent.com/67152407/107634779-60206100-6c6a-11eb-9efe-182ffe45c596.png)

**Comment by furax37** [comment]
je confirme ;-)

**Comment by J9rem** [comment]
Résolu
