### ISSUE TITLE
bug sur creation utilisateur si existe déjà un user avec ce mail

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#672]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Concerne le champ bazar de  type utilisateur_wikini
Lors de l'enregistrement de la fiche si le user existe déjà (même mail) on obtient une page blanche à la validation de la fiche
Comportement attendu :
- un message alerte le user "identifiant" utilise déjà cette adresse mail
- possibilité de retourner à l'édition de la fiche pour changer le mail ou annuler la création de la fiche 
- ou possibilité d'enregistrer la fiche sans créer de nouveau user et donc attribuer cette fiche au user existant

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki doryphore 2021-02-15-10

**Comment by J9rem** [comment]
@MelanieMichel je clos cette issue car résolu (toutefois, on peut la réouvrir si tu perçoit des attentes non remplies par le correctif)
