### ISSUE TITLE
meilleure gestion des exceptions

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#673]
bug et nouvelle fonctionnalité

**Description**
Le correctif suivant https://github.com/YesWiki/yeswiki/commit/511ab0419cd353bd0c9223556a1225d82113674d n'est pas idéal.
@acheype propose une meilleure gestion des exceptions
- [x] récupérer les exceptions au niveau du Performer 
- [x] affiche un message d'erreur générique avec l'exception plus bas
- [ ]  rajouter des contrôles similaires mais à l'écriture d'une fiche dans form et entry manager

Perso je trouve que ce sont de bonnes propositions

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore 2021/02/17

**Comment by acheype** [comment]
je peux faire 1 et 2 si vous pensez que c'est utile @J9rem et @mrflos

pour 3 (que j'assimile également au getOne), je me suis aperçu en faisait le fix que c'est une chaîne de caractère qui est donné en argument, donc on ne peut spécifier int en argument de fonction. On peut faire par contre faire un contrôle semblable à celui qui est fait et renvoyer une exception plutôt que null.
Ou on peut simplement laisser sans aucun contrôle (je préfère cette solution au null renvoyé actuellement).
Que préférez-vous ?

**Comment by mrflos** [comment]
oui, ca serait super utile, il faut éviter les pages blanches, c'est primordial! :)
Et en effet les 2 premier soucis sont prioritaires, pour le troisième, a priori si on arrive en mode édition c'est que la partie visualisation marchait, j'imagine que dans 90% on affiche la fiche avant d'aller la modifier.

**Comment by J9rem** [comment]
Petite proposition :
est-ce qu'un comportement dépendant de  `if ($this->GetConfigValue('debug')=='yes') {` ne serait pas souhaitable ?
Avec, 
- si debug = no, on retourne "null" et on ne génère pas d'exception : le site fonctionne toujours (à la rigueur on génère un message dans le stream error qui sera stocké dans les log du serveur php
- si debug = yes alors on génère un exception qui remonte toute la pile, est attrapée par le Performer qui affiche un message jolie mais inquiétant à destination des développeurs.

Je serai embêté de savoir qu'en cas d'erreur, sur un de mes sites, l'utilisateur voit un message inquiétant alors que ça n'est qu'à destination des développeurs. Je préférerais qu'il voit une page blanche (plus neutre côté alerte) ou un tout petit message en petit en bas de page du genre "oups, il y a eu un souci sur cette page" 

Qu'en dites-vous ?

**Comment by J9rem** [comment]
Sinon je suis d'accord, c'est super utile.

**Comment by mrflos** [comment]
Pour cacher l'erreur, faudrait vraiment le penser globalement (loggue t'on l'erreur quelque part? est ce debug qui signale l'erreur ou un mode env = prod qui cache? etc...), ça me parait ambitieux.  

Après, si le message est intelligible genre "Une erreur s'est produite, veuillez contacter le webmaster en lui signalant le code erreur suivant : <nom de l'exception>".  

Je pense que les usagers préfèrent savoir qu'un truc ne marche pas, que de se retrouver sur une page blanche.

**Comment by acheype** [comment]
ok je vais faire quelques tests ce soir.

pour 3) & co : le code de jérem servait finalement que pour le cas de la chaîne vide car avec une chaîne de caractère qui n'est pas un entier, cela rendait déjà null. J'ai vu qu'en spécifiant les ' autour du chiffre dans la requête SQL on n'avait plus ce soucis. 
Je pense que je vais essayer de mettre ces guillemets systématiquement puis certainement rajouter quelques types d'argument pour contrôler les types des méthodes Manager. Ca a l'avantage de rien rajouter niveau code et d'avoir suffisamment de retour si les fonctions sont mal utilisées.

Et puis s'il y a une erreur de type qui survient, cela ne plantera pas la page grâce à 1) et 2).

Ce que je propose, c'est retenir l'idée de Jéremie pour avoir un comportement dépendant de `$this->GetConfigValue('debug')=='yes'` (bonne idée !), mais de l'utiliser pour l'affichage de l'erreur.
Ainsi sans le mode débug, on peut écrire juste un message général de type "Une erreur inattendue s'est produite. Veuillez contacter l'administrateur du site et lui communiquer l'erreur affichée en mode « debug »." On peut ainsi mettre un lien sur "mode « debug »" ou si vous préférez un bouton à côté "mode débug".
Et bien entendu en mode débug (même lien avec &debug), on aura directement l'erreur PHP.

Est-ce que cela vous irait ?

**Comment by mrflos** [comment]
J'insiste, je ne voies pas de raison de cacher des erreurs aux usagers : quand un navigateur n'arrive pas à a accéder a un site, il affiche aux utilisateurs lambdas "erreur réseau" ou "problème d'encodage" (et l'utilisateur s'en accomode tres bien). On peut afficher des erreurs quand un truc se passe mal, pas la peine de coder une logique compliquée, et mettre une url pour accéder au mode debug, juste catcher l'erreur et donner une piste, c'est utile, y compris pour un usager lambda qui peut faire un retour par copier/coller sans faire de manip. Je pense que c'est le meilleur comportement, le mode debug c'est pour les trace des requetes sql et les erreurs warning et notice, selon moi (et si l'utilisateur les voies, là il va s'inquieter).

**Comment by acheype** [comment]
Mouais... les deux façons de voir les choses s'entendent. En tout cas, y'a aucune logique compliquée : si "mode debug", afficher message de l'exception, sinon afficher message général.

Je trouvais que c'était un bon compromis puisque les gens qui ne veulent pas en savoir plus auraient juste un message général et c'est plus doux pour eux :bear:. Mais à la fois, ça me va aussi d'avoir un unique message avec l'erreur en dessous.

**Comment by J9rem** [comment]
Je dirais faisons au plus simple.
ET donc finalement, à vous lire, je trouve ma proposition complexe donc pas idéale.
En plus, c'est une bonne idée d'avoir un message d'erreur effectivement.

**Comment by acheype** [comment]
yep, je suis parti du coup là-dessus ! et ça marche bien d'ailleurs :)

**Comment by acheype** [comment]
suite de la discussion directement dans la PR

**Comment by J9rem** [comment]
a priori @acheype #678 permet de faire tout ce que nous avons évoqué non ?
pouvons-nous clore cette issue ?

**Comment by J9rem** [comment]
Bon @acheype je clos cette issue, elle me semble traitée par #678

**Comment by acheype** [comment]
Oui, la troisième tâche n'est pas nécessaire.

Le seul truc qui manque c'est de pouvoir continuer à afficher l'erreur dans la console. Je n'ai pas trouvé comment écrire directement dans la console sur yeswiki. Souvent on a des gestionnaires de log dans les projets qui permet assez facilement d'écrire une erreur, un warning, une info...
