### ISSUE TITLE
Améliorer la gestion des valeurs par defaut dans le form-builder

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#674]
**Amélioration**

Lors de la définition des options par défaut dans [form-edit-template.js](https://github.com/YesWiki/yeswiki/blob/doryphore/tools/bazar/presentation/javascripts/form-edit-template.js), il semblerait que

1. lors de la création d'un formulaire, la valeur par défaut des listes de type `<select>` est `""`. Il semblerait que si elle n'est pas trouvée, les valeurs associées sont classées par ordre alphabétique des clés, puis la clé retenue à l'enregistrement est la première clée classée **par ordre alphabétique**. un `""` sera remplacé par `*** ***`
2. lors de la modification d'un formulaire, la valeur vide est `" "` car extraite de `*** ***`. Il y a recherche de la clé associée, si elle n'est pas trouvé. Nous avons le comportement du 1.

Ainsi, pour avoir un comportement par défaut de ce type `{"":"oui","0":"non"}` alors oui sera choisi par défaut et à chaque modification il sera à nouveau choisi car il est le premier dans la liste.
Pour avoir un non par défaut, il faut mettre `{"":"non","1":"oui"}`, sauf que ça fonctionne à la création du formulaire mais pas à la modification. En effet, le `non` est associé à `""` alors qu'il recherche `" "`.

En gros, pour que ça fonctionne, il faut mettre le code non élégant : `{"0":"non","1":"oui","":"non"}`

**Serait-il possible d'améliorer ce comportement ?**

**Propositions**
- [ ] définir qu'une valeur vide est `""` et non `" "`
- [ ] choisir par défaut la première valeur de la liste et non la première valeur par ordre alphabétique

**Comment by mrflos** [comment]
c'est bizarre, les valeurs du template formulaire étaient cleanées avec la fonction trim() auparavant.
Et le comportement était si le champ est obligatoire prend la premiere valeur de la liste, et sinon le choix était ""=>"Choisir..." , qui enregistrait un champ vide.  
Et il ne devrait pas etre possible d'avoir des valeurs vides comme clés, genre ""=>"non"

**Comment by J9rem** [comment]
@mrflos est-ce que je peux pousser `{"0":"non","1":"oui","":"non"}` temporairement pour pouvoir désactiver l'envoi par défaut des e-mails ?
je sais ça n'est pas élégant

**Comment by J9rem** [comment]
En fait : `{"0":"non","1":"oui"}` fonctionne mieux.

**Comment by mrflos** [comment]
ok!

**Comment by J9rem** [comment]
@mrflos je m'apprête à pousser un commit qui change dans la base sql par défaut la valeur 1 à 0 pour l'envoi des e-mails.
https://github.com/YesWiki/yeswiki/blob/doryphore/setup/sql/default-content.sql#L4
OK pour toi ?

**Comment by mrflos** [comment]
oui!
