### ISSUE TITLE
simplification fond page de configuration yeswiki

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#68]
Configuration de la base de données ajouter (informations fournies par votre hébergeur)

dans pour en savoir plus, changer
Préfixe des tables : Permet d'utiliser plusieurs YesWiki sur une même base de donnnées par chaque nouveau wiki installé devra avoir un préfixe des tables différent.
en tous cas, données ne prend que 2 n

Nom de votre site : Ceci est généralement un NomWiki et EstSousCetteForme se débrouiller pour que l'on puisse écrire comme on veut, même avec des accents

**Comment by mrflos** [comment]
+1

**Comment by mrflos** [comment]
corrigé https://github.com/mrflos/yeswiki/commit/7c6c551599b0658be28ca5678bb16f91882a3a9d
