### ISSUE TITLE
Problème d'import de fiches bazar

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#682]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lorsque l'on importe des fiches bazar, les boutons n'apparaissent pas avec le thème margot : 
![image](https://user-images.githubusercontent.com/12220999/109484139-5f683700-7a80-11eb-855e-a3afc21018ed.png)
Et lorsque je change de thème, des cases à cocher apparaissent, mais pas de bouton pour valider l'import.
![image](https://user-images.githubusercontent.com/12220999/109484207-727b0700-7a80-11eb-852d-0b151195f77a.png)

ça a bien fonctionné juste avant avec des formulaires comportant respectivement 5 et 1 fiche. 

**Additionnal informations / Informations complémentaires**
- même version de yeswiki sur les wikis d'import et d'export la dernière version doryhore proposée par le bouton de màj automatique le 1er mars

**Comment by J9rem** [comment]
A priori ce serait lié à la présence de l'extension LMS ping @acheype pour que  nous gardions un oeil dessus.

**Comment by RomainLalande** [comment]
En fait ici c'est le bug qui persiste une fois que j'ai désinstallé l'extension LMS, avec le LMS installé, ça me bloquait carrément l'import via un message du type /home/TRUCMACHIN/www/a/DMN11/tools/lms/templates/bazar/fiche-1203.tpl.html on line 32"

**Comment by J9rem** [comment]
Merci pour la précision @RomainLalande :+1:

**Comment by J9rem** [comment]
Question @RomainLalande as-tu mis à jour le thème Margot ?

**Comment by acheype** [comment]
J'ai testé, le bouton s'affiche bien chez moi.
+1 avec ce que dit Jérémy, essaie de voir si tu es à jour au niveau de Margot

**Comment by RomainLalande** [comment]
Hello, 
Alors oui a priori mon Margot était à jour. Mais là depuis il a dû y avoir un truc qui a réglé le soucis car quand je reteste d'importer... les boutons s'affichent bien et j'ai pu faire un import avec l'extension LMS installée. 
J'imagine qu'entre temps quelqu'un a dû mettre à jour mon wiki, en tous cas ça me semble résolu sans que je comprenne pourquoi :/
Après je ne peux plus vraiment tester dans les mêmes conditions car depuis j'avais rappatrié les formulaires /fiches à la main. Normalement dans trois semaine je dois renouveller exactement la même opération sur un futur wiki. 
Je testerai donc à nouveau en situation réelle pour valider mais ça me semble ok.

Désoler pour le délais, git ne m'envoie plus de mail et je ne suis pas repassé ici depuis... Merci pour vos aides en tous cas !

**Comment by acheype** [comment]
@RomainLalande Ce qui s'est peut-être passé, c'est que le thème margot sur ton wiki était à jour mais que ton navigateur avait encore en cache l'ancienne version. En général, il faut faire attention à bien supprimer le cache de ton navigateur. Perso je laisse appuyé la touche Shift puis clique sur Recharger, ça force la réactualisation de tous les fichiers... en tout cas sur Firefox et Chrome.
