### ISSUE TITLE
Traduire en Anglais les fichiers .lang

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#683]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
- [ ] Traduire en Anglais tous les fichiers 'lang' dans le coeur et dans les extensions de base
- [ ] Vérifier que les menus et textes sont tous gérés par un fichier 'lang', à défaut, faire la mise à jour
- [x] Mettre à niveau l'action builder (bouton composant) pour qu'il puisse gérer le multilingue.

**Additionnal informations / Informations complémentaires**
- point évoqué en AG du 2 mars 2021
- peut être implémenté sous Doryphore

**Comment by sylvainboyer** [comment]
*Avec Sarah Rutter…*
Le wiki sur lequel nous travaillons est là : http://rutter.fr/englishyeswiki/
Et notre page gare centrale pour ce projet est celle-ci : http://rutter.fr/englishyeswiki/?YesWikitoEnglish

#### Ce que nous avons fait
- ajouté une icône sur page d'accueil qui permet de se rendre sur YesWikitoEnglish ;
- commencé à rédiger, dans YesWikitoEnglish, comment transformer son yeswiki en un wiki anglophone ;
- commencé la traduction de certaines des pages de gestion.

#### Ce qu'il reste à faire
- Finir de rédiger YesWikitoEnglish (comment transformer son yeswiki en un wiki anglophone).
- Finir la traduction des pages de gestion.
- Reprendre les actions suivantes pour :
  - remplacer les textes en dur par des *tokens*,
  - s'assurer que tous les *tokens* existent bien en français et en anglais,
  - et cela pour les actions suivantes : `{{admintag}}`, `{{mailperiod}}`, `{{Listusers}}`, `{{recentchanges}}`, `{{OrphanedPages}}`, `{{bazarrecordsindex}}`, `{{pageonlyindex}}`, `{{gererthemes}}`, `{{setwikidefaulttheme}}`, `{{gererdroits}}`, `{{editgroups}}`, `{{userstable}}`, `{{update}}`.
- Faire le même travail pour les différents constructeurs graphiques (au fait, je suis preneur d'une liste de ceux-ci :stuck_out_tongue_winking_eye: .

**Comment by J9rem** [comment]
Super ! @sylvainboyer 
Pour info, j'ai crée une page tutoriel en Français pour le moment https://yeswiki.net/?AiderATraduire pour donner les instructions aux noms développeurs pour nous aider à traduire les fichiers de langue.

**Comment by gatienbataille** [comment]
Hello @sylvainboyer l'assoc yeswiki a décidé de filer un peu de temps à @J9rem pour poursuivre le travail de nettoyage du code yeswiki avec les mots en français codés en dur. Si ça vous branche de re rentrer dans la boule avec Sarah, welcome ;-)

**Comment by J9rem** [comment]
Côté développeur on a avancé sur des specs pour passer les fichiers javascripts avec des varaibles #808

**Comment by seballot** [comment]
il n'y a plus de fichier `.lang`, donc je ferme

**Comment by J9rem** [comment]
Je dirai plutôt que cette issue est remplacée par https://priorites.yeswiki.net/posts/25/possibilite-de-traduire-le-wiki-de-base
