### ISSUE TITLE
Créer un wiki de base tout en Anglais

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#684]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
En lien avec #683, pouvoir choisir à l'installation d'un wiki de charger un wiki de base en Anglais plutôt qu'en Français.
- [ ] créer une seconde base sql par défaut tout en Anglais
- [x] ajouter un menu de choix de langue dans l'interface d'installation
- [x] détecter automatiquement la langue du navigateur lors de l'installation pour choisir par défaut la bonne version

**Additionnal informations / Informations complémentaires**
- évoqué lors de l'AG du 2 mars 2021
- peut être fait avec Doryphore

**Comment by mrflos** [comment]
ya aussi remplacer les textes en francais hardcodés, par des fonctions `_t('MA_CLE_DE_TRADUCTION')` et traduire les clés de traduction présentes uniquement sur la version française en anglais.
edit: c'est prévu dans #683

**Comment by sylvainboyer** [comment]
Faudrait en discuter, mais mes première remarques  :
- Sur le 3e point, je pense que ce n'est pas une bonne idée. Je connais au moins deux personnes qui installent régulièremetn des wikis dans une langue autre que celle de leur navigateur.
- Sur le 2e point, il y a déjà un mchoix de langue à l'installation (qui s'appuie d'ailleurs sur la langue du navigateur et qu'il ne faut surtout pas toucher lors de l'installation si on veut que tout se passe bien) => ce truc modifie la langue notée dans le `wakka.config.php` mais je ne sais pas quels autres effetes cela a.
- Sur le 1er point, je pense que dans un premier temps, on peut parfaitement fonctionner avec un wiki de base qui embarque les deux arborescences. C'est une solution au rabais mais plus aisée à mettre en place.

**Comment by J9rem** [comment]
Ah oui bien vu @sylvainboyer et donc il suffirait juste d'embarquer la version anglais dans la base sql de base ;-)

**Comment by mrflos** [comment]
moi je ne suis pas très chaud pour un sql de base contenant toutes les langues, j'imagine que la traduction en anglais est un pas vers l'internationalisation, et que si pour les 6 langues déja dispo, on rajoute tout dans le sql ca va faire trop de pages inutiles.

**Comment by J9rem** [comment]
C'est vrai que ça va demander d'avoir des pages plus compliquée pour les débutants.
(il y aura des parties en Français et en Anglais dans la même page séparée par `{{lang ...}}`)

**Comment by sylvainboyer** [comment]
> moi je ne suis pas très chaud pour un sql de base contenant toutes les langues, j'imagine que la traduction en anglais est un pas vers l'internationalisation, et que si pour les 6 langues déja dispo, on rajoute tout dans le sql ca va faire trop de pages inutiles.

Il s'agit juste de le faire pour l'anglais en attendant une belle solution comme celle de cette issue

**Comment by sylvainboyer** [comment]
> C'est vrai que ça va demander d'avoir des pages plus compliquée pour les débutants.
> (il y aura des parties en Français et en Anglais dans la même page séparée par `{{lang ...}}`)

Non j'y ai un peu réfléchi l'idée c'est vraiment de faire au plus simple dans un premier temps.
Ça n'empêche pas de faire un reuc plus soigné pour la suite.

**Comment by mrflos** [comment]
je pense qu'on n'a pas d'urgence sur cette tache et qu'il vaut mieux la penser bien et la faire bien, car de mon expérience le multi-linguisme, si c'est mal fait à la base, cela entraine de la dette pire que la dette technique.

**Comment by sylvainboyer** [comment]
> je pense qu'on n'a pas d'urgence sur cette tache et qu'il vaut mieux la penser bien et la faire bien, car de mon expérience le multi-linguisme, si c'est mal fait à la base, cela entraine de la dette pire que la dette technique.

Nous sommes donc complètement d'accord. Un truc soft et non implicant d'abord (l'autre issue) puis un truc bien pensé (cette issue)

**Comment by fbredow** [comment]
Bonjour, j'arrive un peu après la bataille, j'avais développé ça : https://github.com/supagroflorac/yeswiki-extension-multilang pour un site en 5 langues. Ça fonctionne plutôt bien. Pour le voir en fonctionnement : https://erasmus-anicare.eu Si ça peut aider ou donner des idées. Cela mérite un peu d'affinage (ça ne prend pas en compte les langues qui se lisent de droite à gauche par exemple).

Pour résumer ça utilise la page de la langue par défaut comme un hub, en ajoutant l'action {{translate}} dans cette page. Imaginons que la PagePrincipale contienne cette action et que la langue par défaut est l'anglais ;
 - Si un navigateur configuré en anglais le contenu de la page est affiché et {{translate}} n'a pas plus d'effet.
 - Si un navigateur configuré en français arrive sur cette page, il sera redirigé vers la page PagePrincipaleFr si elle existe. 
 - Si l'utilisateur a les droit d’édition et que la page n'existe pas il lui sera proposé d'en faire une traduction.
 - 
Il y a d'autres possibilités comme 
 - l'affichage de drapeaux permettant de changé la langue a la volée
 - la traduction d'une partie de texte à partir d'un tableau PHP présente dans le dossier du thème (je m'en sers dans les templates).
 - ...

N'hésitez pas à me contacter si besoin de plus d'explications.

**Comment by J9rem** [comment]
@daiko entre dev. nous avons avancé sur des spécifications pour mettre en place les fichiers de traductions pour le javascript et le php #808 .
Ça viendra compléter l'extension que tu as développée, qui permet de gérer le contenu.

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/25/possibilite-de-traduire-le-wiki-de-base

**Comment by johentsch** [comment]
Coucou tout le monde. Je viens de découvrir YesWiki et je l'ADORE! Je viens d'en ouvrir un pour un groupe d'allemand.e.s qui ne parlent pas français ou pas beaucoup. Du coup, je vais leur traduire le bac à sable et tout ça (je suis allemand aussi), peut-être meme renommer les pages, etc. Evidemment je voulais voir si personne n'avait déjà fait ça -- il semble que non. C'est pas très évident non plus de voir où se trouvent les fichier de défault -- j'ai enfin trouvé le mot `bacasable` dans un fichier SQL.

Je serais bien intéressé de contribuer une traduction anglaise et allemande et, si vous voulez garder ce méchanisme, je peux aussi le faire en SQL. Me faudrait juste un peu les instructions comment exactement et j'imagine qu'il faudrait aussi un petit boulot de votre part afin de pouvoir configurer ça avant/pendant l'installation?

**Comment by mrflos** [comment]
Hallo @johentsch !
Merci de ta proposition! On peut traduire en allemand les différentes parties de yeswiki a partir de https://hosted.weblate.org/projects/yeswiki/ et ce sera ajouté un coeur de yeswiki.

Il manque en effet encore le sql dans cette interface mais c'est prévu de le rajouter bientot.

Si tu est motivé pour traduire officiellement en allemand, il te faut créer un compte sur hosted.weblate.org et je rajouterai la langue allemande dans les différents module il ne te restera qu'a traduire les milliers de mots qui composent YesWiki... 😓 

Je te laisse me dire si ce travail colossal t'intéresserait.

Mitr freundliche Gruesse

**Comment by johentsch** [comment]
Super, que de bonne nouvelles, merci! Du coup, en anglais c'est déjà fait? Parce que c'est en fait par là que j'allais commencer.

Juste pour être claire: On parle de traduire le contenu des pages initaux, et non pas l'interface, n'est-ce pas?

**Comment by mrflos** [comment]
non la il s'agit de l'interface, les contenus initiaux c'est avec le sql actuellement..
La traduction anglaise et presque complete, l'allemande inexistante.

**Comment by johentsch** [comment]
> non la il s'agit de l'interface

D'accord. Ça n'a pas tellement d'importance pour nous, les boutons en anglais, c'est la normalité sur le web. Par contre, je me vois bien contribuer de temps en temps. Mais ce ticket, et ma proposition, est vraiment sur le contenu des pages dans le SQL. Ce n'est pas un projet de traduire les templates?
