### ISSUE TITLE
PageTitre de Doryphore

### ISSUE THREAD

**Issue by Hoppicker** [YesWiki/yeswiki#686]
Dans la PageTitre de Doryphore, le ¶ du h1 ne fonctionne pas
![Capture d’écran du 2021-03-04 17-14-11](https://user-images.githubusercontent.com/61345755/109994461-a159dd00-7d0d-11eb-986a-7108c3a85d7e.png)

**Comment by mrflos** [comment]
Il faudrait plutot rentrer ce code dans la partie PageHeader, la PageTitre est plutot destinée à n'accueillir qu'un image logo ou un titre court qui resterait dans la barre de menu sur une ligne

**Comment by furax37** [comment]
Si, elle fonctionne mais juste pour y mettre un petit texte, pas un background image ;-)

**Comment by Hoppicker** [comment]
Merci pour vos retours, bien compris, c'est rectifié
