### ISSUE TITLE
carto

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#69]
harmoniser les actions map avec celles de carto
ou encore mieux, de débrouiller pour qu'il n'y ai qu'une action bazarcarto mais avec un paramètre qui permette de choisir sa carte (google / osm / ...)

**Comment by mrflos** [comment]
Corrigé par @daviddelon ici  https://github.com/mrflos/yeswiki/commit/f9ed85e2d11a326ed0f3e54f2be331dd912d2678
