### ISSUE TITLE
Bug sur envoi fichier (attach)

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#691]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Dans éditeur Yeswiki, le bouton "Fichier" ne permet pas de télécharger une image messge "Echoué"
cependant l'action {{attach file=""}} est bien insérée dans le code . 
En ajoutant le nom du fichier dans le paramètre file de l'action {{attach file="mon_fichier.jpg}} le reste de la manip roule et le fichier est bien inséré.
Bug constaté sur hébergement OVH  et apparemment pas sur d'autres hebergements ...

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki doryphore 2021-03-09-3
- url to see the problem or an example / url pour voir le probleme ou un exemple https://pratic-coop.fr/doryphore/
- screenshot / capture d’écran
- logs

**Comment by J9rem** [comment]
effectivement, je ne reproduis pas l'erreur mais je l'ai déjà eue.
Est-il toujours présent avec la dernière release (Margot à jour) ?

**Comment by J9rem** [comment]
Bon, j'ai vraiment dû mal à résoudre le souci.
Ma seule piste, (mais ça n'est qu'une hypothèse):
 - le fichier [tools/attach/libs/fileuploader.js](https://github.com/YesWiki/yeswiki/blob/doryphore/tools/attach/libs/fileuploader.js) utilise une propriété [`.upload.onprogress`](https://github.com/YesWiki/yeswiki/blob/eb17f311524fd677a68c45b1ee00773de2c58a6a/tools/attach/libs/fileuploader.js#L1193) non standard de XMLHttpRequest
_Source : https://xhr.spec.whatwg.org/#the-upload-attribute_

**Comment by J9rem** [comment]
Juste que ce sera compliqué à remplacer par `$.ajax` car l'objet `jqXHR` n'implémente pas la propriété `upload`.
_Source: https://api.jquery.com/Jquery.ajax/#jqXHR_

**Comment by MelanieMichel** [comment]
Le problème est constaté sur un hébergement OVH lorsque le firewall est activé
Résolu en désactivant le firewall : éditer le fichier .ovhconfig et remplacer 
http.firewall=security par http.firewall=none
