### ISSUE TITLE
Paramètre user dans action bazarliste ne semble pas fonctionner

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#696]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité
Bug / Bogue

**Description**
L'utilisation du paramètre user dans bazarliste renvoie les fiches de l'utilisateur connecté, quelque soit le nom du user spécifié
exemple {{bazarliste id="2" user="TataYoyo" }} fournit les fiches de WikiAdmin si WikiAdmin est connecté
 En revanche le paramètre  filteruserasowner="true"  fonctionne parfaitement

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki doryphore 2021-03-11-6
- url to see the problem or an example / url pour voir le probleme ou un exemple https://pratic-coop.fr/doryphore/?BacASable
- screenshot / capture d’écran
- logs

**Comment by J9rem** [comment]
Corrigé avec le dernier commit, ce sera corrigé à la prochaine release
