### ISSUE TITLE
pb d'incompatibilité des facettes avec le pager

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#699]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
pb d'incompatibilité des facettes avec le pager

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore 2021-03-11-6
en mode liste_accordeon avvoir 20 fiches par pages, et facette ne trie que dans les 20 fiches visibles alors qu'il en existe 300 par exemple) et aussi dans le même style incompatibilité entre facettes et l'option cluster de la carto

**Comment by mrflos** [comment]
Possible duplicate #190

**Comment by J9rem** [comment]
Ah oui, effectivement, je ne l'avais pas retrouvée, je clos donc la présente issue pour éviter le doublon.
Merci pour ton attention
