### ISSUE TITLE
Rendre fonctionnel BazarListeexterne

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#701]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité
Bug / Bogue

(les deux mon capitaine !)

**Description**
Rendre fonctionnel BazarListeexterne

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki (Ce serait très utile sur Doryphore)
- (et pas si compliqué à faire mais peut-être u peu long pour le faire en bénévolat uniquement)

**Comment by J9rem** [comment]
Je vous propose @mrflos et @acheype d'échanger ici sur la spécification des modifications à mener pour faire fonctionner BazarListeexterne.

En utilisant la branche https://github.com/YesWiki/yeswiki/tree/fix-bazarlisteeterne, ça fonctionne si le wiki local possède le même template de formulaire pour le même formId que le wiki distant.

(Il reste à gérer quand id est une liste).

Toutefois, je proposerai bien:
- réserver les identifiant de formulaires 1300 à 1500 pour pouvoir avoir des formulaires temporaires pour ExternalBazarService
- ExternalBazarService importe le json du formulaire, régénère le formulaire en local
- créer une méthode FormManager->putFormInCache($formId,$form)
  permettant à ExternalBazarService de sauvegarder le formulaire généré dans le cache
 - lors de l'import des entries,:
   - remplacement dans le json de l'identifiant d'origine par le nouveau identifiant temporaire
   - ajout d'une valeur $entry['externalBaseUrl'] qui permettrait de facilement détecter que cette $entry est externe et donner directement l'url de base (uniquement dans le json pas dans la bdd)
   - ajout d'une valeur $entry['original_id_typeannonce'] pour faciliter les traductions qui seraient potentiellement nécessaire
 
L'idée :
- pouvoir pointer plusieurs yeswiki dont les adresses seront dans url="url1|url2|url3" vide = wiki courant
- les ids correspondant sont sous la forme id="id1,id2|id3,id5|id8"
- ne pas avoir besoin de rappatrier le manuellement le formulaire distant
- ajouter un temps de cache des url de 1h pour les formulaires
- allonger le temps de cache des url de 5 min pour les entries

Qu'en dites-vous ?

**Comment by J9rem** [comment]
De @mrflos :
>surtout ne pas importer les formulaires

mais ouvrir les routes ?api/forms/<id>

et si prepared ne le fait pas

faire un param genre ?api/forms/<id>&showenums=1

et pour les éléments de type liste, checkbox, listefiche, etc, avoir avec le champs dans le formulaire la liste de leurs id => labels

quand tu appeles bazar listeexterne, avec 2 requetes json, une sur les listes, une sur les entries il récupère tout ce qu'il faut, tu peux eventuellement faire un cache json local pour garder les valeurs 10min par exemple
11:15 AM

tu voies l'idée? les services api servent a ce que le wiki externe appelé s'occupe de fournir les bonnes données, de reproduire localement des formulaires et fiches serait trop ambitieux amha

**Comment by J9rem** [comment]
Pour le moment, on utilise le handler json car c'est le handler officiel et maintenu pour suivre les formulaires (mais aucun souci pour passer sur l'api quand il aura disparu).

Je trouverai cohérent d'importer en mémoire les formulaires distants (dans le cache de FormManager) afin d'éviter les soucis quand les formulaires distants sont légèrement différents du formulaire local (voire quand le formulaire local n'existe même pas)

**Comment by acheype** [comment]
J'ai hâte de voir cette action fonctionner ! depuis que j'ai rejoins le projet, elle est en vrac...

C'était une demande du commanditaire que l'action puisse aussi récupérer les formulaires ?
Je pense également que ça serait plus clair si l'action s'occupait uniquement de récupérer les fiches et listes associées. Ca me paraît normal de laisser à l'utilisateur faire en sorte que le formulaire qu'il a en local corresponde à l'orginal. Je vois aussi le cas où il pourrait avoir besoin de ne pas afficher certains champs du formulaire d'origine et ça peut être intéressant qu'il soit légèrement différent.

Ce qui n'empêche pas que l'importation mériterait d'être amélioré, et ce que tu proposes avec par exemple l'import automatique des listes associées serait un vrai plus. Mais je serais partisan pour que ce soit fait uniquement à un seul endroit (au niveau du code surtout mais pour au niveau UX ça me paraît plus clair aussi).

Je n'ai pas compris les formulaires réservés de 1300 à 1500 que tu proposais mais c'est certainement lié à l'import des formulaires que tu voulais automatiser ?

**Comment by J9rem** [comment]
Bon, je me dis que c'est plus facile à expliquer avec des diagrammes : 
https://pad.lescommuns.org/nIpt8etiSTqcuSVDFyj0Tg?view

**Comment by J9rem** [comment]
@acheype tu proposes qu'il n'y ait pas d'importation du formulaire distant en local mais que ce soit à l'utilisateur ou utilisatrice d'importer à la main le formulaire distant.
En termes d'UX, je trouve ceci trop complexe.

En plus, avec @mrflos + les discussions canal dev. nous nous sommes mis d'accord sur le cas par défaut suivant:
 - syntaxe `{{bazarliste id="1,http://monurl.com/|3,http://monurl.com/|4,5"}}`
 - importation des formulaires en local avec copie TEMPORAIRE dans le cache de FormManager SANS modification de la base sql
 - mise en cache des requêtes api ou json dans des fichiers texte dans le dossier cache

Ce que tu proposes est intéressant et pourrait être une option qui me plait en utilisant la syntaxe suivante:
`{{bazarliste id="1,http://monurl.com/|3->7,http://monurl2.com/|4,5"}}`

ce qui signifie:
 - prendre les fiches du formulaire 1 local
 - prendre les fiches du formulaire 3 de `http://monurl.com/` mais les afficher en utilisant le formulaire 7 local (**nouvelle option proposée**)
 - prendre les fiches du formulaire 4 de `http://monurl2.com/` en important ce formulaire dans le cache de FormManager sans modif sql
 - prendre les fiches du formulaire 5 local

Qu'en dites-vous ? @mrflos @acheype Est-ce que cette syntaxe et ce principe vous irait ? 
Si OK pour vous, je propose la syntaxe à la validation sur le canal dev.

**Comment by mrflos** [comment]
L'intéret du `->7` c'est pour quel usage? Utiliser un rendu fiche custom genre fiche7.tpl.html?

**Comment by J9rem** [comment]
> L'intéret du `->7` c'est pour quel usage? Utiliser un rendu fiche custom genre fiche7.tpl.html?

Je n'avais pas pensé à cet usage.
L'intérêt est plutôt comme le propose @acheype de pouvoir choisir ce qu'on affiche ou pas localement à partir des données externes (sachant que le formulaire externe affiche peut-être trop de données)

**Comment by mrflos** [comment]
mmhh ok.  
J'ai rien contre cette feature, mais elle ne me parait pas essentielle, j'imagine que ce qui est important c'est de voir si tu peux le faire dans le temps imparti !

**Comment by J9rem** [comment]
C'est pas trop compliqué à mettre en place en même temps, ... juste un petit test et hop pas de cache.

**Comment by J9rem** [comment]
Bon ça commence à bien prendre forme : https://github.com/YesWiki/yeswiki/tree/fix-bazarlisteeterne

**Comment by acheype** [comment]
Merci pour ces précisions. Je comprends l'envie de vouloir que l'utilisateur n'ait pas à importer le formulaire et l'alternative que tu proposes répond bien au cas que je mentionnais (même si pas prioritaire du tout).
Au niveau de la gestion des fiches externes, il pourrait y avoir des améliorations. De ce que je vois, tu as dû modifier les templates existants pour prendre en compte les fiches externes, et il me semble que celui qui écrit un template de liste ou de fiche ne devrait pas avoir à se préocupper de si la fiche vient d'un site externe ou non.
Mais je vous laisse voir si ça vous va comme ça.

**Comment by J9rem** [comment]
Super ton commentaire @acheype .
Je trouve ton point de vue pertinent.
je propose de faire une fusion dans l'état (enfin après le prochain commit à venir) pour permettre de remettre en fonctionnement cette action.
PUIS
si on trouve du budget pour l'améliorer, mettre en place un truc plus sympa pour tenir compte de ce que tu pointes comme prise de risque pertinente

**Comment by J9rem** [comment]
Je clos l'issue car résolue par #755
