### ISSUE TITLE
bug visuel de facette

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#705]
BUG

**Description**
bug visuel de facette

Bug relevé par @acheype 

Lorsque c'est le premier élément qui est filtré, on n'a plus la barre du dessous de margot : 
![2021-03-20 07-05 - Capture d'écran](https://user-images.githubusercontent.com/8435038/111881172-a24a6a00-89af-11eb-981e-5fc4309bb11c.png)

et quand on filtre sur un élément qui n'est pas en première position, on a une barre en trop au dessus et pas de barre en dessous : 
![2021-03-20 07-05 - Capture d'écran_1](https://user-images.githubusercontent.com/8435038/111881213-c1e19280-89af-11eb-8212-813fefa2d5f4.png)

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore 2021-03-18

**Comment by seballot** [comment]
pour moi avec bazar lite dynamic je n'ai pas ce problème, peut etre ca a été réglé entre temps
