### ISSUE TITLE
Doryphore: Sur Bazar, impossible d'accéder aux vues autre que"formulaire"

### ISSUE THREAD

**Issue by seballot** [YesWiki/yeswiki#707]
Yop, sur cette page : https://gogowiki.teritorio.xyz/?BazaR?vue=formulaire

![image](https://user-images.githubusercontent.com/17404254/111974048-6b836980-8aff-11eb-8dcb-8376898ce32c.png)

Si je clique sur les onglets, ou alors sur une ligne du formulaire sur les icons "loupe" ou "+", l'url change et la page est rechargée (https://gogowiki.teritorio.xyz/?BazaR?vue=saisir) mais c'est toujours la vue formulaire qui s'affiche

![image](https://user-images.githubusercontent.com/17404254/111974633-e51b5780-8aff-11eb-8123-14ee5a7c042e.png)

Je suis sur la dernière version de doryphore

![image](https://user-images.githubusercontent.com/17404254/111974418-ac7b7e00-8aff-11eb-86fa-3ffcf7b97dd8.png)

Note: dans un autre page je peux quand meme afficher la vue saisir avec `{{bazar voirmenu="0" vue="saisir" id="1"}}`

**Comment by seballot** [comment]
Ah oui ben je viens de trouver, ça vient de l'url, y'a un `?` après BazaR au lieu d'un `&`

https://gogowiki.teritorio.xyz/?BazaR?vue=formulaire
au lieu de
ttps://gogowiki.teritorio.xyz/?BazaR&vue=formulaire

**Comment by seballot** [comment]
En local ça fonctionne sur la branche doryphore, ça a déjà été fixé alors?

**Comment by acheype** [comment]
Ca me dit quelque chose ce bug mais oui c'est fixé.
