### ISSUE TITLE
Ne pas écraser le thème yeswikicerco lors de la mise à jour vers doryphore

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#711]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Explain the bug or the feature / expliquer le bogue ou la fonctionnalité demandée
Lors de la mise à jour d'un wiki cerco vers doryphore, le thème Yeswiki utilisé est "écrasé" et devient indisponible, ce qui fait apparaître sur les pages du wiki mis à jour le bandeau rouge qui dit, j'ai plus le thème demandé donc je prends le tème par défaut (à savoir margot quand on passe à doryphore)

or ce n'est pas nécessairement la demande de la personne qui fait la mise à jour.

Ne pourrait-on pas garder le thème yeswikicerco présent afin que ce souci d'affichage ne se produise plus 
et laisser à l'user l'appréciation de rester sur cerco ou de passer sur doryphore

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : doryphore 2021-03-25-19
- url to see the problem or an example / url pour voir le probleme ou un exemple
- screenshot / capture d’écran
- logs

**Comment by J9rem** [comment]
C'est normalement fonctionnel avec la dernière version de Doryphore.
@gatienbataille Peux-tu vérifier ? si OK, je te laisse clore cette issue.
Attention, il n'y a pas encore la sécurité pour le php 7.3

**Comment by gatienbataille** [comment]
dernier test à faire et je clos si tout est ok

**Comment by J9rem** [comment]
Je clos cette issue car normalement elle est corrigée.
