### ISSUE TITLE
Gérer thème, j'voudrais bien mais j'peux point

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#712]
**Impossible de choisir le thème par défaut s'il n'y a que margot installé**

Bug / Bogue

**Description**
sous doryphore, quand on souhaite sékectionner un thème par défaut et qu'il n'y a que margot d'installé, impossible d'accéder aux squelettes et style. Pour que cale fonctionne, il faut installer un autre thème, le sélectionner puis revenir sur le thème margot... un peu laborieux
**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
Doryphore
- url to see the problem or an example / url pour voir le problème ou un exemple
- screenshot / capture d’écran
![Screenshot_2021-03-30 Boite à outils](https://user-images.githubusercontent.com/1269848/113011533-2ce25480-917a-11eb-9356-194902f68c70.png)

- logs

**Comment by J9rem** [comment]
C'est sûrement lié à #362 et #473

**Comment by J9rem** [comment]
Normalement c'est corrigé dans la dernière release de Doryphore.
Confirmez-vous @furax37  ?
si c'est OK je vous laisse clore cette issue.

**Comment by furax37** [comment]
Bravo et merci ;-)
