### ISSUE TITLE
[Doryphore] Lors de la création d'une nouvelle page le thème n'est pas conservé.

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#713]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
J'ai un menu sur ma page principale, ses différentes entrées n'existe pas encore. Lorsque je clique sur l'une d'elle et que l'on me propose de créer la page, le thème de la page principale n'est pas conservé et reviens au thème par défaut.

Petite précision, le menu est géré dans le template,  pas dans une page.

**Additionnal informations / Informations complémentaires**
- dernière version de Doryphore via la mise a jour depuis le dépot. (doryphore 2021-03-25-19)

**Comment by J9rem** [comment]
Bon, c'est normal car la conservation du thème n'est possible que pour les liens créés par YesWiki (actions button ou [[MaPage Nom du lien]].

En définissant les liens dans le template, ça contourne ce mécanisme.

L'idéal serait de ne pas définir ces liens dans le template MAIS de conserver les pages PageMenuHaut, etc, ...

Ensuite, en modifiant la page en question, il faudrait changer les paramètres de thème avancés pour utiliser une nouvelle PageMenuHautNew qu'il faudra avoir créer avant.

Ensuite le thème se propagera naturellement.

**Comment by fbredow** [comment]
Je m'en doutais un peu... possible de remplacer bug par feature ? ;) Je clos. Merci pour la réponse.

**Comment by J9rem** [comment]
Sinon, si dans ton template tu remplaces:
`<a href="https://www.example.com/?AccueiL">Mon lien</a>`
par
`{{button link="AccueiL" text="Mon lien" nobtn="1"}}`

Normalement, ça marche.
Je te laisse tester.
En effet, les actions sont accessibles depuis les squelettes et donc tu peux profiter de l'action button qui te permettra de créer ç la chaîne les pages en conservant les liens.

**Comment by fbredow** [comment]
Merci c'est une solution intéressante, je n'y avais pas pensé :)
