### ISSUE TITLE
Sauver sa configuration graphique dans pageCSS

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#714]
**Actuellement, dans https://ferme.yeswiki.net/WikiDeBase/?LookWiki on peut se faire un look aux petits oignons mais on ne peut pas le sauver**
New feature / Nouvelle fonctionnalité

**Description**
Idée de rajouter une action qui permet de sauver la configuration graphique générée avec le wysiwyg

**Additionnal informations / Informations complémentaires**
- doryphore
![Screenshot_2021-03-31 Tester les thèmes YesWiki](https://user-images.githubusercontent.com/1269848/113164240-37b3ec80-9241-11eb-8b24-e38118f50458.png)

**Comment by mrflos** [comment]
pour préciser, j'imaginais avoir une section dans PageCss, ou un triple de presets

**Comment by J9rem** [comment]
_Suite aux échanges avec @mrflos_:

- les paramètres seront sauvegardés en fichier .css dans le dossier `/custom/css-presets`. (c'est pas stable de le faire dans pageCSS)
- l'interface proposera un champ à l'utilisateur pour choisir le nom du fichier (si c'est le même que celui d'avant il y a écrasement)
- le presets.css sera utilisé pour tous les thèmes qui utilisent des variables permettant à l'utilisateur de conserver ses réglages de couleurs en cas de changement de thème

@furax37 est-ce que ce changement de lieu de sauvegarde te semble cohérent ?

**Pré-requis**, sur lesquels Florian va avancer:
- charger pageCSS en dernier
- harmoniser themeselector pour charger les fichiers css-presets et les proposer dans la fenêtre de choix thememanager
- passer les presets json en css

**Comment by J9rem** [comment]
@furax37 tu l'as demandé, tu vas pouvoir le tester : https://github.com/YesWiki/yeswiki/pull/756
Je déploie une nouvelle release de doryphore dans la foulée pour que tu puisses faire les tests.

@mrflos a prévu d'apporter quelques améliorations

**Comment by gatienbataille** [comment]
Hello, j'ai pu tester aujourd'hui avec des gens en formation
super !! 
je m'interroge sur leur présence dans la partie "thème" en bas de chaque page car ça me semble "trop chargé" sous cette forme... en tout cas ça invisibilise le bouton "paramètre avancé" (qui permet de jouer sur la langue ou le squelette de la page)
![Capture d’écran 2021-05-18 à 21 25 20](https://user-images.githubusercontent.com/7147716/118711183-951af180-b81f-11eb-8e78-f606b27f9ead.png)

proposition :
 - on rend visible les presets dans cette partie mais via un encadré qui s'ouvre/se ferme (fermé par défaut)
 - on laisse (pas ma préférence) et on rend bcp plus visible le bouton "paramètres avancés"

**Comment by J9rem** [comment]
@gatienbataille sur quelle page as-tu vu ceci car ça n'est pas normal ?

As-tu bien pensé à rafraîchir le cache de ton navigateur après la mise à jour ?

**Comment by gatienbataille** [comment]
clique sur le bouton thème en bas
https://ferme.cooptic.be/activitespcsleuze/?PagePrincipale/edit

**Comment by mrflos** [comment]
je vais faire des modifications pour bien séparer la partie configuration des presets et la partie sélection du thème et presets.
J'ai une idée claire de ce qu'il faudrait faire, je tente une itération vendredi prochain!

**Comment by J9rem** [comment]
En fait, il suffit juste de ne pas afficher la partie themeselector en mode edit (car les .js et .css ne sont plus chargés au passage)

**Comment by J9rem** [comment]
Je viens de faire un commit https://github.com/YesWiki/yeswiki/commit/75b37f27d7dfe84f181d32a51dd8eaa827c4d7b7 je le teste en fin de matinée avant de faire une release

**Comment by J9rem** [comment]
C'est corrigé avec la version doryphore 2021-05-19-1

**Comment by J9rem** [comment]
Je clos cette issue car elle semble normalement diffusée dans le coeur
