### ISSUE TITLE
{{tocjs}} ne suit pas vraiment

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#718]
**Quand on insère un tocjs dans une page, il ne suit pas quand on descend**
Bug / Bogue

**Description**
Normalement, quand on insère tocjs dans une page et que l'on clique sur un des paragraphe proposé, le menu généré est censé suivre lors de la descente. Ce n'est visiblement plus le cas

**Additionnal informations / Informations complémentaires**
- Doryphore
- https://yeswiki.net/?ChangeLog

**Comment by seballot** [comment]
ça a l'air d'avoir été résolu, ça marche bien pour moi. Réouvre si pour toi ça ne fonctionne toujours pas !
