### ISSUE TITLE
[Cercopitheque][aceditor] L'ajout de lien / nouvelle page n'a pas d'effet.

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#721]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lorsque j'édite une page et que je clique sur "Lien / Nouvelle Page" la formulaire apparaît bien mais le remplir et le valider n'a pas d'effet.

**Additionnal informations / Informations complémentaires**
- version of YesWiki : cercopitheque2021-02-18-2

**Comment by J9rem** [comment]
Merci pour avoir remonté ce bug, sauf que je n'arrive pas à le reproduire.
Survient-il juste après avoir fait la mise à jour ? ou après avoir redémarré le navigateur internet (et/ou taper CTRL+MAJ+R) ?

**Comment by fbredow** [comment]
Bonjour, je n'arrive plus a reproduire le problème. Pourtant il m'avait été remonté par un utilisateur et j'avais confirmé le problème sur plusieurs wikis en vidant le cache (Firefox). Désolé pour le mauvais signalement.
