### ISSUE TITLE
Affichage d'un double bandeau lorsque l'on arrive sur une page qui nécessite une connexion

### ISSUE THREAD

**Issue by LudovicParenty** [YesWiki/yeswiki#722]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**

Bug / Bogue

**Description**
Affichage d'un double bandeau lorsque l'on arrive sur une page qui nécessite une connexion

**Additionnal informations / Informations complémentaires**
Exemple : https://www.basededonnees-habitatparticipatif-oasis.fr/?BazaR

**Comment by J9rem** [comment]
J'ai corrigé ceci dans la dernière release de Doryphore donc je clos cette issue (sauf si @LudovicParenty tu constates toujours le souci après mise à jour doryhore)
