### ISSUE TITLE
Module LDAP ne charge pas le template modal

### ISSUE THREAD

**Issue by AisukoHakumei** [YesWiki/yeswiki#726]
Bug / Bogue

**Description**
Lorsque que le module LDAP est installé et configuré, le site retourne une erreur 500. Le debug montre que le module LDAP n'arrive pas à charger le fichier modal.tpl.html

**Additionnal informations / Informations complémentaires**
- Version 2021-02-18-2 cercopitheque
- logs :
`
Fatal error: Uncaught Exception: Template non trouvé : tools/loginldap/presentation/templates/modal.tpl.html in /var/www/yeswiki/includes/squelettephp.class.php:64 Stack trace: #0 /var/www/yeswiki/tools/loginldap/actions/login.php(195): SquelettePhp->__construct() #1 /var/www/yeswiki/includes/YesWiki.php(1437): include('/var/www/yeswik...') #2 /var/www/yeswiki/includes/YesWiki.php(1251): YesWiki\Wiki->IncludeBuffered() #3 /var/www/yeswiki/formatters/wakka.php(338): YesWiki\Wiki->Action() #4 [internal function]: WikiniFormatter->callback() #5 /var/www/yeswiki/formatters/wakka.php(81): preg_replace_callback() #6 /var/www/yeswiki/formatters/wakka.php(494): WikiniFormatter->format() #7 /var/www/yeswiki/includes/YesWiki.php(1437): include('/var/www/yeswik...') #8 /var/www/yeswiki/includes/YesWiki.php(1373): YesWiki\Wiki->IncludeBuffered() #9 /var/www/yeswiki/actions/include.php(85): YesWiki\Wiki->Format() #10 /var/www/yeswiki/includes/YesWiki.php(1437): include('/var/www/yeswik...') #11 /var/www/yeswiki/includes/YesWiki.php(1 in /var/www/yeswiki/includes/squelettephp.class.php on line 64`

**Comment by mrflos** [comment]
Bonjour @AisukoWasTaken ,
tu peux vérifier que le fichier `tools/loginldap/presentation/templates/modal.tpl.html` existe et a les bons droits d'acces en lecture sur ton serveur ?
A priori le fichier existe bien sur le dépot de code https://github.com/YesWiki/yeswiki-extension-loginldap/blob/master/presentation/templates/modal.tpl.html et dans le zip de téléchargement depuis le repo YesWiki https://repository.yeswiki.net/cercopitheque/extension-loginldap-2021-01-26-4.zip

Éventuellement, par l'interface de gestion des mises à jour, désinstaller l'extension puis la remettre, si la copie a planté.
