### ISSUE TITLE
Libellés absents dans le cas où 'default_language' => 'en'

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki#736]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Dans le cas où un visiteur navigue sur un YesWiki en Doryphore (2021-04-26-1)
- avec un navigateur (Firefox 87.0) paramétré en Français
- et que le Wiki est paramétré en anglais (`'default_language' => 'en'` dans le `wakka-config.php`)
les libellés ne sont pas résolus (par exemple `LOGIN_LOGIN` au lieu de `Se connecter`)

**Comment by J9rem** [comment]
Merci @sylvainboyer pour l'identification de cette erreur.
Aurais-tu un lien vers le site qui ne fonctionne pas ?
Car je n'arrive pas à reproduire le bug en local.

**Comment by sylvainboyer** [comment]
Merci @J9rem 
Tu peux voir ça, là : https://osons.cc/p/FormateursO10c/?GererMisesAJour
Dis-moi :
- si tu veux que je te passe un compte en admin,
- quand tu as fini. parce que là, ils vont râler (je viens de repasser le `wakka-config.php` en `'default_language' => 'en' ` pour toi :wink: )

**Comment by J9rem** [comment]
Pas besoin de compte admin.
Je perçois le souci mais je ne vois pas pourquoi il est présent.
Tu peux remettre l'option à sa valeur par défaut `'default_language' => 'fr',`
pourrais-tu remplacer `'base_url' => 'http://osons.cc/p/FormateursO10c/?',` par `'base_url' => 'https://osons.cc/p/FormateursO10c/?',` avec `https` ? C'est pour voir si ça résout une partie du souci

**Comment by sylvainboyer** [comment]
Bien vu pour le `https`, je cherchais depuis quelques temps pourquoi j'avais des alertes de sécurité. J'ai ma réponse.
Pour revenir à notre sujet. Je viens de recharger le `wakka.config.php` avec le `https` et toujours en `'default_language' => 'en'`. Et cela ne fonctionne pas. Je te le laisse en l'état le temps que tu constates par toi-même :wink:

**Comment by J9rem** [comment]
C'est bizarre en faisant `https://osons.cc/p/FormateursO10c/?BazaR&lang=en` ça fonctionne et 
`https://osons.cc/p/FormateursO10c/?BazaR&lang=fr` non...

**Comment by sylvainboyer** [comment]
Exactement. Le comportement est différent selon la langue. et c'est 'fr' qui pose problème. 
Je ne m'en suis apperçu que parceque mon navigateur est en anglais et qua je rencontre le problème de la #746 depuis longtemps et que je le contourne en laissant 'en' comme langue par défaut (et parfois j'oublie de changer en 'fr' et les utilisateurs râlent).
Je repasse en 'fr'.

**Comment by J9rem** [comment]
J'ai trouvé le correctif, ... je pousse les corrections sur le dépôt. Ce sera corrigé dans la prochaine release.

**Comment by J9rem** [comment]
Normalement résolu avec la dernière release.. je te laisse clore cette issue si tout est ok

**Comment by J9rem** [comment]
@sylvainboyer confirmes-tu que c'est corrigé ?

**Comment by sylvainboyer** [comment]
Oui, super. Merci.
