### ISSUE TITLE
[Doryphore] Le handler 'json' retourne une page vide.

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#741]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Si j'ajoute le handler /json a la fin d'une URL (page ou fiche bazar) j'obtiens une page vide.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : doryphore 2021-04-27-3

**Comment by J9rem** [comment]
Je clos cette issue car ça n'est pas un bogue.
En effet, le handler `json` est utilisé comme api GET est n'est pas dédié à être utilisé seul sans paramètre.
A termes, il sera remplacé par des routes `api`
