### ISSUE TITLE
[Doryphore][Bazar] Export en json donne une page vide

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#742]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Exporter les fiches d'un formulaire au format json (bouton sur la page d'administration de bazar) donne une page vide. Peut être un rapport avec : #741. Testé en étant connecté en tant que WikiAdmin et non connecté.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki :  doryphore 2021-04-27-3

**Comment by J9rem** [comment]
Je clos cette issue car elle est redondante avec #708.
J'ai déjà codé la solution #727 qui attend validation.
