### ISSUE TITLE
[bazar] Conserver les dates de création / modification lors de l'export/import.

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#743]
Nouvelle fonctionnalité

**Description**
J'ai importé le formulaire et les fiches correspondantes dans un nouveau wiki (via CSV). Malheureusement les dates de création et modification de chaque fiche correspondent à la date/heure de l'importation.
Comme il s'agit d'une liste d'actualités, et que la date de création/modification permet de les ordonner, cela perd un peu de son sens. ;)

Peut être une option à ajouter ?

**Comment by seballot** [comment]
salut

tu pourrais créer de nouveau champs date autre que création/modification pour gérer cela
Car pour la plupart des cas je pense que c'est le comportement attendu que le created_at soit la date de l'import
