### ISSUE TITLE
Incorrect page name when switching from French to English on installation page

### ISSUE THREAD

**Issue by samy** [YesWiki/yeswiki#746]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
- Extract YesWiki in a folder
- Go to the URL corresponding to the Wiki
- Display the installation page using a French-spoken browser
- Switch the "Langue par défaut" to English
- The "Incorrect page name" is displayed

**Additionnal informations / Informations complémentaires**
- Version : cercopitheque
- The problem is not present if you go to /index.php?installAction=default&lang=en (with the .php page name)

**Comment by sylvainboyer** [comment]
@samy , seen the same problem the other way around:
- Extract YesWiki in a folder
- Go to the URL corresponding to the Wiki
- Display the installation page using a **English**-spoken browser
- Switch the **"Default language" to French**
- The "Incorrect page name" is displayed

My temporary work around (obviously does not correct the bug) is to: 
- let the default language as is
- run the installation with that language
- afterwards, modify default language int the `wakka.config.php` file.

**Comment by samy** [comment]
In fact, I succeeded using index.php?installAction=default&lang=en.php in the URL (instead of ?installAction=default&lang=en.php), but it is to fix the bug for other people :)

**Comment by sylvainboyer** [comment]
agreed :)

**Comment by J9rem** [comment]
It would be interesting to test if the bug is ever present in the next revision Doryphore when it will be officially diffused.

**Comment by sylvainboyer** [comment]
My use case is corrected. Thanks @J9rem .
@samy did you have any opportunities to test yours?

**Comment by J9rem** [comment]
I close this issue because corrected.
