### ISSUE TITLE
Perte de données (image surtout) lors de la mise à jour dory vers dory

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#749]
Bug / Bogue

**Description**
Lors d'une mise à jour du wiki (de dory vers dory  : pas de passage de version), une partie des données semble avoir été perdue ;-( c'est principalement le cas des images présentes dans les fiches bazar et le plus embâtant c'est que les fichiers ont disparus du dossier files... aie aie aie
aussi une partie des fiches a perdu les données d'un champ checkbox

bon quelques pistes : 

- il semble que les plus vieilles fiches aient gardé leurs images (nommée NomPage_image_bf_imageimage_image....)
- il semble que les plus vieiiles fiches aient gardé leur checkbox

j'ai malheureusement pas en tête de quelle version dory vers dory a fait sauter le truc

le wiki tourna actuellement en doryphore 2021-05-03-6
https://www.pnth-terreenaction.org/?LesProjets

Il faut sans doute voir si d'autres ont eu aussi (il semble bien que oui mais à des degrés divers (par ex sans perte des images dans le dossier files) 

enn tout cas, les fichiers perdus c'est dur dur à rattraper chez le "client" ;-(

**Comment by gatienbataille** [comment]
je vois que les fiches qui ont perdu leur image ont été modifiées lors de la maj 
NathaliePreillon (Citoyen en action) créée le 01.08.2019 à 14:28, mise à jour le 03.03.2021 à 17:44 
ChristianQuintin (Citoyen en action) créée le 01.08.2019 à 14:21, mise à jour le 03.03.2021 à 17:43 

il se pourrait donc que le souci se soit passé lors de la maj vers
yeswiki-doryphore-2021-02-26-2 ou yeswiki-doryphore-2021-03-03-1

**Comment by J9rem** [comment]
Bon avec la version d'hier, normalement c'est plus compliqué de supprimer les images d'une fiche.

toutefois, ça peut venir d'une extension.
Quelles est la liste des extensions présentes sur ce YesWiki ?

**Comment by J9rem** [comment]
Mais d'autres ont eu le souci.
Est-ce que la mise à jour est de 17:43 ?
Car je serai plutôt partisan d'un script robot qui balaye le site et qui avant pouvait supprimer les images (maintenant c'est corrigé).

**Comment by gatienbataille** [comment]
rhhaaa en fait je suis en train de me rendre compte que le robot il est passé sur plusieurs sites ;-( et que des images j'en ai perdues un peu partout... bon je fais vite les maj là où c'est pas fait...

**Comment by J9rem** [comment]
Le plus important est que tu me confirmes qu'il n'y aura plus de suppression intempestive par la suite.

**Comment by J9rem** [comment]
Pour moi, le souci est résolu car la mise à jour des fiches a eu lieu en mars `03.03.2021 à 17:44` avec une version YesWiki qui permettait à l'époque la suppression des images sans être connecté.
La dernière version devrait normalement empêcher ceci donc je serai partisan de clore cette issue qui correspond à des vieilles versions de doryphore.

**Comment by gatienbataille** [comment]
ok
