### ISSUE TITLE
facette cassée (checkbox)

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#750]
Bug / Bogue

sur un wiki sous doryphore 2021-05-03-6
des fiches contenant des données dans un checkbox nommé checkboxListeThemeaction (récupéré via le /raw) ne s'affichent pas dans la facette (ex avec la fiche GatienBataille qui a pourtant "checkboxListeThemeaction":"1,5")

https://www.pnth-terreenaction.org/?CarteProjet

info : Les fiches du formulaire appelé contiennent un listefiches***1*** *** *** ***actu.tpl.html***checkbox***
mais bon ça fonctionnait avant maj

**Comment by J9rem** [comment]
Bon, je ne comprends pas ton bug car mes test en local (en copiant les données de ton sites) et les tests sur le lien que tu m'as donné montrent que tout fonctionne, tout s'affiche dans les facettes etc.
As-tu des précisions encore plus précises sur le souci pour que je sache je corrigé ?

**Comment by gatienbataille** [comment]
Ou de fait, ,sorry pour réponse tardive.
en fait j'ai du repasser sur chaque fiche pour resélectionner les checkboxs qui avaient disparus (visiblement lors d'une mise à jour d'une version précédente de doru, celle qui permettait de virer les images du /files

bref en repassant sur les fiches, c'est opérationnel
je clos
