### ISSUE TITLE
ID du Champ bazar fichier renommé lors de l'édition d'un formulaire

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#754]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lors d'une migration de cerco vers doryphore les champs de type fichier qui avait était definis avec des majuscules dedans genre "fichierPublicationTelechargee" passent en lowecase  et donc renommés en "fichierpublicationtelechargee" au moment où on édite le formulaire 

Et par conséquent sur les fiches anciennes on a l'impression de ne plus voir les fichiers 

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : doryphore 2021-05-05-2
- url to see the problem or an example / url pour voir le probleme ou un exemple http://pratic-coop.fr/cercopitheque/?BazaR&vue=consulter&action=recherche&id=8

**Comment by MelanieMichel** [comment]
@J9rem a identifié à quel endroit bazar passe les noms en lower case : 
 /tools/bazar/presentation/javascripts/form-edit-template.js
et  /tools/bazar/presentation/javascripts/form-builder.min.js 

Mais ne trouve pas opportun de modifier ces bibliothèques. Une autre piste ?

**Comment by J9rem** [comment]
Oui, profiter du /update pour mettre à jour les fiches et les formulaires par requête sql

**Comment by J9rem** [comment]
J'y repense @mrflos et @seballot si vous êtes OK, nous pouvons modifier les deux fichiers cités pour permettre de répondre au besoin de retrocompatibilité mais ça fera que des noms de champs pourront avec des majuscules en attendant une mise à jour par /update

**Comment by J9rem** [comment]
Je réouvre car le commit https://github.com/YesWiki/yeswiki/commit/3f2dbfac7beb716fb2078eab55024ac3ab6c8da7 n'a finalement pas été accepté par la communauté.

**Comment by seballot** [comment]
@MelanieMichel est ce que c'est toujours d'actualité? y'en encore des wiki sur cercopitheque? c'est pas un peu trop tard pour résoudre ça?

**Comment by MelanieMichel** [comment]
Oui le plus gros des migrations de cercopitheque vers doryphore a été fait en 2021. On a géré les soucis de nom de champ file contenant des majuscules au cas par cas. On peut clore le sujet.
