### ISSUE TITLE
Quelques propsitions d'amélioration de l'expérience user 

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#757]
Propositions en sortie d'une journée de formation à Yeswik avec des "débutants" (dernière version de dory du 18 mai)

- [x] ajouter la possibilité d'activer la class "full-widht" quand on est dans le composant section
- [x] ajouter la possibilité d'activer la class "clearfix" quand on ajoute une image pour forcer le passage à la ligne sous cette image (sinon faut jouer avec des enter...)
- [x] ajouter un contrôle strict sur le champ carto des formulaires pour empêcher la validation de la fiche si l'user n'a pas cliqué pour se mettre sur la carte (souvent il remplit son adresse mais oublie d'appuyer pour se géolocaliser)
- [x] dans le composant bouton, avoir une autocomplétion du champ "adresse du lien"  avec les pages existantes du wiki (comme dans le composant liens)
- [x] rendre plus visible le bouton d'aide (?) qui est présent lors du mode édition / moi je serai pour le rapprocher des autres boutons de la barre d'édition et de le nommer "Aide" ou ... mais un mot plutôt qu'un ? 
- [x] j'ai vu que attach était +/- un composant (pas dans la liste des composants) mais modifiable comme  un composant une fois que l'image est arrivée... possible d'avoir {{attach}} uniquement comme composant ? bonne idée ? 
- [x] ajouter dans le composant vidéo la possibilité de mettre un % dans la largeur et pas uniquement un nbr de pixels

Ceci fait liste au père noël mais c'est juste une proposition à débattre ;-)

**Comment by J9rem** [comment]
>dans le composant bouton, avoir une autocomplétion du champ "adresse du lien" avec les pages existantes du wiki (comme dans le composant liens)

Possible mais il faut pouvoir gérer aussi les liens de types url externes, .... ça demande à créer un nouveau objet interne pour les composants (genre gestion des liens externes + auto-complétion des pages internes, ...), je note..

**Comment by J9rem** [comment]
>j'ai vu que attach était +/- un composant (pas dans la liste des composants) mais modifiable comme un composant une fois que l'image est arrivée... possible d'avoir {{attach}} uniquement comme composant ? bonne idée ?

Le chargement des fichiers n'est pas géré par composants et donc il n'est pas possible en l'état de mettre attach uniquement dans composants.

>  ajouter dans le composant vidéo la possibilité de mettre un % dans la largeur et pas uniquement un nbr de pixels

C'est possible, mais pas trop urgent pour le moment.

**Comment by seballot** [comment]
salut @gatienbataille !

est ce que tu peux relire cette liste, voir si y'a des trucs toujours d'actualité, et créer posts dédié sur priorites.yeswiki.net si besoin? Merci !

**Comment by gatienbataille** [comment]
j'ai coché tout ce qui est déjà opérationnel, je crée une demande d'intérêt autour de la largeur des vidéos en % 
merci et à bientôt !
