### ISSUE TITLE
[Attach/bazar] Déplacer les aperçus/vignettes dans le dossier "cache" ?

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#758]
New feature / Nouvelle fonctionnalité

**Description**
En regardant des wikis qui on quelques années, je retrouve des aperçus (vignettes) d'images qui ne sont plus utilisées dans le wiki. La suppression de ceux ci ne pose pas de problème puisqu'ils sont régénéré au besoin. Leur place ne serait elle pas plutôt dans le cache du wiki ? Par exemple le dossier `cache/thumbs/`.

**Comment by J9rem** [comment]
En fait, si je comprends bien, les fichiers sont déjà dans cache ?

**Comment by J9rem** [comment]
@daiko , je clos cette issue, car les aperçus/vignettes sont déjà dans la cache.
Certes, il n'y a pas de gestion de l'effaçage des anciennes vignettes non utilisées, mais c'est déjà en prévision avec https://github.com/YesWiki/yeswiki/issues/373
