### ISSUE TITLE
Plante si le dossier 'cache' n'est pas accessible en écriture.

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#761]
Nouvelle fonctionnalité ou Bogue : Mon coeur balance... je vous laisser choisir ;)

**Description**
Si le dossier `/cache` n'est pas accessible en écriture le site ne s'affiche pas : 

```Grosse erreur sale
Fatal error: Uncaught RuntimeException: Unable to write in the cache directory (cache/templates/97). in /var/www/html/vendor/twig/twig/src/Cache/FilesystemCache.php:57 Stack trace: #0 /var/www/html/vendor/twig/twig/src/Environment.php(349): Twig\Cache\FilesystemCache->write('cache/templates...', '<?php\n\nuse Twig...') #1 /var/www/html/vendor/twig/twig/src/Environment.php(309): Twig\Environment->loadTemplate('__TwigTemplate_...', '@templates/aler...') #2 /var/www/html/vendor/twig/twig/src/Environment.php(277): Twig\Environment->load('@templates/aler...') #3 /var/www/html/includes/services/TemplateEngine.php(123): Twig\Environment->render('@templates/aler...', Array) #4 /var/www/html/includes/services/TemplateEngine.php(114): YesWiki\Core\Service\TemplateEngine->renderTwig('@templates/aler...', Array) #5 /var/www/html/includes/services/Performer.php(196): YesWiki\Core\Service\TemplateEngine->render('@templates/aler...', Array) #6 /var/www/html/includes/YesWiki.php(738): YesWiki\Core\Service\Performer->run('header', 'action in /var/www/html/vendor/twig/twig/src/Cache/FilesystemCache.php on line 57
```

Le comportement attendu serait plutôt un message d'alerte et pourquoi pas un fonctionnement sans cache.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki ; doryphore 2021-05-24-7

**Comment by sylvainboyer** [comment]
Je pense que ça va plus loin que *doryphore*
Je suis tombé, chez un client, sur un wiki en dernière version de *cercopitheque*  dont je ne pouvais pas mettre la page `GererMisesAJour` à jour (pas possible d'enregistrer après avoir ajouté `version="doryphore"` dans l'action `{{update}}`). En farfouillant dans le forum, j'ai vu une mention à un problème de droits sur `/files` et `/cache`. Or, si les droits étaient corrects, il n'y avait pas de dossier `/cache`. J'en ai ajouté un, vide. Et hop, ça fonctionne.
Je dois ajouter que ce n'était pas mon navigateur qui posait le problème car celui-ci m'avait été remonté par quelqu'un sur une autre machine et que j'ai tout purgé sur le mien.
Je sais que c'est con de passer du temps sur *cercopitheque* mais là, on risque d'avoir pas mal de problèmes avec des gens qui ont besoin d'éditer cette page.

**Comment by J9rem** [comment]
Bon, j'ai ajouté une sécurité en fin de mise à jour pour être sûr de la présence des dossiers `files` et `cache` mais pour que la mise à jour se fasse, il y a forcément existence du dossier `cache`donc normalement, ça n'est pas nécessaire.

Donc, finalement, si le YesWiki est installé depuis le `.zip` avec uniquement des mises à jour par le bouton `GereMisesAJour` alors normalement, il n'y a pas de soucis.

Pour les autres mises à jour faites par ftp, si la personne ne copie pas le dossier `cache` ou ne met par les bons droits d'accès, ça ne peut être la responsabilité de `YesWiki` et je ne suis pas partisan de forcer la changement des droits d'écriture de façon automatique.

A priori, il ne devrait pas y avoir de soucis si le tutoriel suivant est bien suivi : https://yeswiki.net/?DocumentationMiseAJour et https://yeswiki.net/?DocumentationInstallation

Je clos l'issue. J'espère que c'est bon pour toi @daiko
