### ISSUE TITLE
[Bazar] Accepter les URL interne dans les champs textes cours de type URL (+autres protocoles)

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#763]
Nouvelle fonctionnalité

Actuellement une URL doit absolument commencer par http ou https. Ce serait pratique de pouvoir mettre des URL internes (tag de page, PagePrincipale par exemple). Mon cas d'usage est d'utiliser bazar pour indexer certaines pages d'un wiki. Je peux mettre les URL complète, mais si le site change d'URL ça va demander de tout modifier (sans parler des URL différentes entre la version de test et celle de prod).

En bonus accepter d'autre type d'URL comme par exemple 'mailto:', 'tel:', 'ftp://', 'gopĥer://', ou encore 'gemini://'. Même si les deux derniers sont plutôt réservé à des initiés ;)

**Comment by J9rem** [comment]
En fait, @daiko il nous faudrait un champ lien_internet qui puisse se comporter comme texte à savoir permettre l'usage de pattern personnalisé

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/37/bazar-accepter-les-url-interne-dans-les-champs-textes-cours-de-type-url-autres-protocoles
