### ISSUE TITLE
Curseur décalé lors de l'édition d'une page.

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#764]
Bug / Bogue

**Description**
Lorsque j'édite une page le curseur est décalé d'un caractère. Par exemple si je fais effacer en arrière alors que mon curseur est entre le 'p' et le 'l'  de 'exemple' ça efface le 'm' au lieu d'effacer le 'p'.
Cela ne se produit pas a chaque fois, mais cela semble plus fréquent lorsque j'ai l'action bazar dans la page.

Exemple de page ou cela se produit : 
```
======Les ressources pour comprendre======

{{bazar vue="consulter" id="2" voirmenu="0" template="eco_resources.tpl.html" champ="date_creation_fiche" ordre="desc" query="checkboxListeRessourcestype=10"}}
```

- version of YesWiki : doryphore 2021-05-25-2 (mais j'ai déjà repéré le problème sur des versions antérieurs)
La page en question : https://reseau-ecoresponsables.educagri.fr/?LesRessources (je peux donner temporairement un accès en écriture si besoin de faire des tests, contactez moi directement : [florestan.bredow@supagro.fr](mailto:florestan.bredow@supagro.fr) )

**Comment by mrflos** [comment]
Je pense que c'est plutôt une histoire de police fixe a mettre pour l'éditeur Aceditor : il ne marche qu'avec des polices à taille fixe, sinon il décale le curseur.

**Comment by mrflos** [comment]
Je pense que c'est plutôt une histoire de police fixe a mettre pour l'éditeur Aceditor : il ne marche qu'avec des polices à taille fixe, sinon il décale le curseur.

**Comment by seballot** [comment]
bug non reproductible... si tu as une page ouverte avec ce bug je veux bien un lien pour tester !
