### ISSUE TITLE
Nombres et Sliders

### ISSUE THREAD

**Issue by PiR-o** [YesWiki/yeswiki#771]
Hello ! @J9rem 
First issue pour moi donc j'espère que ça va marcher !

Lorsqu'on souhaite créer un formulaire avec un texte qui contient seulement des **caractères numériques** (nombre), on peut encore écrire des lettres (ex : "nombre d'heures effectuées : 8h"" au lieu de "8", ce qui empêche par la suite d'imaginer des tableaux qui traiteront les données comme des nombres...

+

**Slider** ( je ne sais pas trop de quoi il en retourne mais il y a un bogue aussi de ce côté apparemment.

Version : Doryphore
Apparemment problème connu...

Amicalement,
PiR-o

**Comment by acheype** [comment]
Salut,
Pour info, j'ai un fix en cours de finalisation qui permet de résoudre ce
soucis de sliders et par la même occasion l'autre soucis des caractères
numérique.
J'ai encore un peu de style CSS à terminer pour qu'en plus du slider, il y
ait une bulle qui mette en avant la valeur sélectionnée.
J'essaye de vous commiter cela la semaine prochaine à mon retour de
vacances.

**Comment by J9rem** [comment]
OK @acheype on attend avec impatience ta contribution :wink:

**Comment by J9rem** [comment]
@acheype des nouvelles sur le commit concernant le slider et l'affichage du numéro en temps réel ?

**Comment by J9rem** [comment]
cf. https://github.com/YesWiki/yeswiki/compare/textfield-range-output pour les travaux en cours

**Comment by acheype** [comment]
J'avoue ne pas avoir eu le temps de terminer, ni de m'y remette mais
j'avais pas oublié.
Mais vu que j'ai des trucs qui fonctionnent déjà... Peut-être que je peux
juste poster cela dans une PR...

Le ven. 17 déc. 2021 à 13:46, Jérémy Dufraisse ***@***.***> a
écrit :

**Comment by J9rem** [comment]
@mrflos travaille dessus aujourd'hui

**Comment by mrflos** [comment]
j'ai fini sur la branche `textfield-range-input` , on va fusionner et si t'as le gout d'améliorer @acheype , n'hésites pas!
