### ISSUE TITLE
Page d'accueil vide et aucun texte visible après installation

### ISSUE THREAD

**Issue by thom4parisot** [YesWiki/yeswiki#775]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**

Bug / Bogue

**Description**

Lors de l'installation, j'ai précisé un nom de page alternative (`Accueil`).

![image](https://user-images.githubusercontent.com/138627/126280434-3e354958-fd45-4b9e-8975-e2c9639dcdcd.png)

Je ne sais pas quoi dire d'autre, j'ai pas eu le temps de faire grand chose 😓 

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : celle proposée sur la page d'accueil en date du 20 juillet.
- url to see the problem or an example / url pour voir le probleme ou un exemple : https://labo.usinevivante.org

**Comment by mrflos** [comment]
Hello, 
Je regarde vendredi en priorité ce bug, mais j'ai un doute qu'il soit lié au changement de page d'accueil, mais plutot a une requête d'insertion des pages foireuse.  
Je m'assigne la tache, merci de la remontée!

**Comment by gatienbataille** [comment]
Tests réalisés ce jour en installant sans  problème 
- un wiki avec page principale AccueiL https://cooptic.be/florian
- un autre avec page principale Accueil https://cooptic.be/florian-bis
la présence de 2 majuscules ou d'une seule ne pose pas de souci

**Comment by mrflos** [comment]
Merci @gatienbataille pour les tests!  
J'en conclus que c'est une histoire d'environnement SQL, le serveur cooptic.be étant avec mariadb de debian, @oncletom pour l'usine vivante, est ce que par hasard ce ne serait pas du mysql server ? tu saurais la version?

**Comment by gatienbataille** [comment]
je supprime les wikis de tests pour pas encombrer le serveur

**Comment by thom4parisot** [comment]
C’est chez O2Switch, j’ai pas la version sous le coude:

**Comment by thom4parisot** [comment]
C'est du MariaDB 10.2.39-MariaDB-cll-lve

![image](https://user-images.githubusercontent.com/138627/126874437-3f12d527-df2d-4596-a474-650dee120dc7.png)

**Comment by thom4parisot** [comment]
Bon, j'ai retenté après avoir supprimé le `wakka.config.php` et… ça a fonctionné.

Pas sûr d'avoir remis les mêmes paramètres.
Je réouvrirai si je retrouve le problème.

**Comment by mrflos** [comment]
ok bizarre, je l'ai déja vu passer ce soucis, jamais réussi à le reproduire, donc je pensais que c'était lié à l'environnement...  
T'autant plus bizarre car cette version de MariaDB est tres standard et on l'utilise aussi...

**Comment by J9rem** [comment]
Hello,
une question, il n'y a pas de vérification de la bonne syntaxe de 'root_page' lors de l'intallation, donc si on entre `Accueil `entouré par des espaces, ça peut créer des erreurs, ......

Je préconise, l'introduction d'un `trim`avant de sauvegarder la configuration et avant de modifier la base sql.
On pourrait aussi ajouter une règle de saisie sur le champ texte concerné (Uniquement des lettres `/[A-Za-z0-9]+/`.
Qu'en dites-vous ?

**Comment by mrflos** [comment]
oups, oui a vérifier avec au minimum un `trim` , et idéalement, ya la regex des chars possible pour une page wiki [WN_CAMEL_CASE_EVOLVED](https://github.com/YesWiki/yeswiki/blob/doryphore/includes/constants.php#L26)

**Comment by J9rem** [comment]
Fait, je viens de faire un commit pour améliorer la sécurité pour le nom de la page d'accueil.
