### ISSUE TITLE
Bogue des tags dans le bazar

### ISSUE THREAD

**Issue by AxelMonti** [YesWiki/yeswiki#777]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Bonjour,
C'est la première fois que je rapporte un problème via git hub, n'hésitées pas à me signaler mes erreurs.

Mon problème est survenu depuis la mise à jour de mon wiki à la version  _doryphore 2021-07-20-1_. Après cette mise à jour, je ne peux plus ajoutez des mots clés avec un formulaire Bazar. 

Cependant l'ajout de mots clés sur une page fonctionne. Et les mots clés précédemment renseignés dans les formulaires sont toujours présent. 

La commande utiliser dans le formulaire est la suivante : 
tags***tags_1624368421657***listes des moyens de fabrication*** *** *** *** *** ***0*** ***validez un tags en pressant sur la touche "entrée"*** * *** * *** *** *** ***

Mon Wiki est hébergé sur la ferme à yeswiki.

**Additionnal informations / Informations complémentaires**
- version de YesWiki : doryphore 2021-07-20-1

**Comment by J9rem** [comment]
Bonjour @ibram-gaunt ,

parfait pour l'issue GitHub.
Je viens de trouver le correctif.
Il va être déployer ce soir.

**Comment by J9rem** [comment]
@ibram-gaunt si tu as les droits, je te laisse vérifier si ça fonctionne avec la release de ce soir et clore cette issue si tout est bon.

**Comment by AxelMonti** [comment]
Bonjour Jérémy,

Après la mise à jour à la version doryphore doryphore 2021-07-27-7 le
problème persiste. Quand j'ajoute un tag avec un formulaire baz

**Comment by AxelMonti** [comment]
Bonjour Jérémy,

Après la mise à jour à la version doryphore doryphore 2021-07-27-7 le
problème persiste. Quand j'ajoute un tag avec un formulaire bazar, il n'est
pas pris en compte.

Bonne journée
Ibram gaunt


Le mer. 28 juil. 2021 à 11:10, Axel Monti ***@***.***> a
écrit :

**Comment by J9rem** [comment]
Bonjour @ibram-gaunt ,

je suis embêté car ça fonctionne à nouveau chez moi.
pourrais-tu vérifier si ça fonctionne en ajoutant dans un formulaire de test un nouveau champ tags tout neuf ?

Sinon, ça me sera plus pratique d'avoir l'adresse d'un site internet qui ne fonctionne pas pour que je puisse identifier les potentielles causes.
Si tu as une préférence pour partager le lien en message privé plutôt qu'ici, tu peux utiliser mon adresse e-mail visible que mon profil https://github.com/J9rem (en mode connecté)

**Comment by J9rem** [comment]
Cette fois-ci @ibram-gaunt ça devrait être bon.
J'ai corrigé un souci que j'avais introduit juste avant.
Lors de la sélection d'un mot existant dans le menu déroulant, il y avait automatiquement une remise à zéro de la valeur (alors qu'en fait il fallait juste remettre à zéro la zone de saisie au lieu de la valeur).

Est-ce que ça fonctionne maintenant ?

Merci pour tes tests et ta patience.
Je te laisse clore l'issue (si tu en as les droits) si tout est bon.

**Comment by AxelMonti** [comment]
Salut j9rem,

La je ne peux pas vérifier que cela fonctionne. Je regarderais ça se soir.

En tout cas merci pour ton implication.

Cordialement
Ibram gaunt

**Comment by AxelMonti** [comment]
salut J9rem,

J'ai pu faire la mise à jour et un test et tout semble fonctionner
correctement.
Merci encore pour ton aide et ta réactivité.
Je clos l'issu de ce pas.

Cordialement,
Ibram Gaunt

Le ven. 30 juil. 2021 à 09:20, Axel Monti ***@***.***> a
écrit :
