### ISSUE TITLE
Export csv  - ajouter le champ id_fiche dans le fichier export

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#779]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Serait-il possible d'ajouter une colonne id_fiche dans le fichier d'export csv ?
Un cas d'usage possible serait :
un formulaire 1 est créé pour recueillir des contributions à un évènement
un formulaire 2 est créé pour établir le programme
Pour établir le programme, le groupe d'organisation travaille à partir d'un export csv et attribue des créneaux horaires et des lieux
Le fichier csv finalisé sera importé dans le formulaire 2 ( programme ).
Si l'export du formulaire 1 contient la colonne id_fiche, on pourrait facilement lier les 2 formulaires pour avoir accès aux infos détaillées présente dans le formulaire de contribution.

Je vous laisse maitre de voir si le cas est trop spécifique ?

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
- url to see the problem or an example / url pour voir le probleme ou un exemple
- screenshot / capture d’écran
- logs

**Comment by J9rem** [comment]
L'idée est bonne.
Aurais-tu une idée pour résoudre le cas suivant ?
_Dans le tableau_, présence d'un `id_fiche` déjà présent sur le wiki où on importe les données.
1. on renomme le nouveau `id_fiche`, ce qui est le cas actuellement mais ça casse le liens
2. on écrase la fiche déjà existante sur le wiki

On peut aussi ajouter une mise à jour automatique des liens lors de l'import (mais ça prend un peu de temps de dev, ..)

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/36/export-csv-ajouter-le-champ-id_fiche-dans-le-fichier-export
