### ISSUE TITLE
Ajout d'une fiche impossible dans une modal box

### ISSUE THREAD

**Issue by EdmondAgate** [YesWiki/yeswiki#780]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lorsqu'un formulaire de saisie d'une fiche est affichée sous format modalbox (depuis un bouton par exemple), il est impossible d'ajouter une fiche. Les controles de validité ne semblent pas effectués sur le formulaire et si le bouton valider ferme la modal box, celle-ci n'est pas enregistrée.

Le même formulaire sans modal box fonctionne parfaitement.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki
- url to see the problem or an example / url pour voir le probleme ou un exemple
- screenshot / capture d’écran
- logs

**Comment by J9rem** [comment]
Cette fonctionnalité ne sera pas disponible facilement et vu l'environnement de la `modalbox` je conseille de ne pas l'utiliser pour l'ajout de fiche, ... il vaut mieux utiliser un ceci `class="modalbox" data-iframe="1"`

**Comment by EdmondAgate** [comment]
Merci @J9rem pour le retour. Et bien noté que ce n'est aps une bonne pratique.  je ne suis pas sur de comprendre par contre le "class="modalbox" data-iframe="1", a quel endroit conseille tu d'utiliser ceci si modalbox n'est pas conseillé ?

**Comment by J9rem** [comment]
dans le template

**Comment by J9rem** [comment]
@EdmondAgate je clos cette issue car il me semble que nous avons l'usage de passer par la modal iframe pour la création des fiches
