### ISSUE TITLE
Facette - tri par formulaire non fonctionnel

### ISSUE THREAD

**Issue by EdmondAgate** [YesWiki/yeswiki#781]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Il me semble que la possibilité de trier par facette plusieurs formulaire appelé ne fonctionne plus. Autrement dit groups="id_typeannonce" n'a plus l'air de fonctionner 

**Additionnal informations / Informations complémentaires**
exemple : https://reseaujeunesse73.fr/?PageActeurs

**Comment by J9rem** [comment]
résolu avec `4.3.1`
