### ISSUE TITLE
les fichiers du dossier files ne sont pas mis à jour

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#783]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug

**Description**
Certains fichiers ne sont pas mis à jour dans le dossier files lors des mises à jour.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki Doryphore 2021-08-17-3

Lors d'une mise à jour, le contenu du dossier files [est ignoré](https://github.com/YesWiki/yeswiki/blob/e4418074042460cb673d36950c89e152e010aa0d/tools/autoupdate/app/PackageCore.php#L7).

Ainsi, si une nouvelle version de doryphore modifie les fichiers nécessaires stockés dans le dossier files (cf. [.gitignore](https://github.com/YesWiki/yeswiki/blob/e4418074042460cb673d36950c89e152e010aa0d/.gitignore#L15)), ils ne sont pas ajoutés...

Le souci est que l'extension ferme copie le wiki de tête pour créer les nouveaux wiki (comportement de base) et que ce wiki ne sera pas à jour pour le contenu de `files` ce qui crée un manque pour le bandeau de tête par exemple.

**Comment by mrflos** [comment]
Bien vu, je vais voir pour faire une config avec des fichiers à ajouter à `files`, en mettant les deux de l'install par défaut

**Comment by J9rem** [comment]
je clos cette PR car résolue
