### ISSUE TITLE
barre d'outils flottante (édition texte)

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#79]
peut-on imaginer que la barre de menu (aceditor) de yeswiki, quand on est en mode édition soit flottante afin qu'il soit plus facile de l'utiliser ?

**Comment by daviddelon** [comment]
Il risque d'y avoir des effets de bord.

**Comment by furax37** [comment]
ajouter le bouton annuler en haut

**Comment by Cyrille37** [comment]
Par flottante, veux-tu dire que la barre d'outils reste toujours à l'écran quand le haut du bloque d'édition n'est plus visible  ?

Sinon, pour faire rupture avec les traditions, il y a ce mode d'édition: [ContentTools](http://getcontenttools.com/) :-P

**Comment by mrflos** [comment]
Oui, flottant = toujours dispo en position fixe tout en haut, quand on scrolle vers le bas de page
Pour l'editeur je serais plutot pour https://simplemde.com/

**Comment by Cyrille37** [comment]
Il est chouette ce SimpleMde.

J'essayai d'amener un wysiwyg total !     :-p
(_ContentTools doit pouvoir gérer du Markedown avec un plugin_)

**Comment by mrflos** [comment]
2 infos:
J’ai un début de plugin pour markdown et simplemde, mais WIP (peut être il faut mettre active="1" dans desc.xml)
https://github.com/YesWiki/yeswiki-extensions-deprecated/tree/master/markdown https://github.com/YesWiki/yeswiki-extensions-deprecated/tree/master/markdown

Bazar contient aussi un éditeur WYSIWYG pour les champs textelong
http://summernote.org/ http://summernote.org/

J’aime vraiment bien le design de ContentTools mais je crains qu’il est le meme défaut que tous les éditeurs wysiwyg : on se retrouve forcement avec une salade de <p></p><p></p><p></p><span></span><span></span><span></span><span></span><span></span> et autres attributs vides après quelques manipulations ou des copier coller!

**Comment by Cyrille37** [comment]
Oui, tu as bien raison.

**Comment by mrflos** [comment]
je clos car c'est le comportement par defaut de l'editeur dans doryphore
