### ISSUE TITLE
soucis d'envoi de mail quand ssl:// non spécifié dans host et blocage du yeswiki

### ISSUE THREAD

**Issue by acheype** [YesWiki/yeswiki#806]
Je me permets de remonter ce bug car j'ai mis du temps à comprendre d'où venait le problème et ce dernier rendait mon serveur complètement instable.

J'ai l'habitude de configurer avec sendinblue l'envoi de mail et je viens ainsi de découvrir [ici](https://yeswiki.net/?ReparerLesWikisQuiNEnvoientPasLesMails&lang=fr) que la configuration n'est pas la même qu'habituellement. Normalement, il faut spécifié ssl:// devant l'adresse du port, tandis qu'avec sendinblue il ne faut pas mettre cette information.

Ainsi en voulant configurer l'envoi de mail avec le service de mail d'ovh, j'ai omis le ssl:// devant. Ainsi quand un utilisateur essayait d'envoyer un mail, il n'avait aucun message d'erreur, ni de confirmation (contrairement dans le cas inverse où avec sendinblue on spécifie ssl:// devant le nom du serveur -> on a alors bien un message qui montre un soucis d'authentification).

Mais là où le bât blesse, c'est qu'à chaque clic cela rend complètement inactif apache sur cette application... je ne savais même pas que c'était possible qu'un thread puisse empêcher toutes les autres connections de s'établir.
En fait si on attend un moment, le message finit par arriver (dans mon cas environ 1min10). Le voici :
![2021-09-11 11-56 - Capture d'écran](https://user-images.githubusercontent.com/8435038/132944177-0708d595-636f-45cb-9e7a-3ca0f900dec8.png)

Une fois, un utilisateur testeur a dû s'exciter sur le bouton car le yeswiki a été rendu inactif pendant 2h !

**Comment by mrflos** [comment]
Et comment as tu résolu le problème?
En utilisant ssl:// sur ovh?  
Faudrait voir si c'est pas un soucis isolé, car en l'état je ne voies pas comment résoudre cela, à part documenter plus?

**Comment by acheype** [comment]
Oui j'ai mis ssl:// devant.

Pas évident en effet, je comprends pas déja comment ça peut bloque toute
l'application pour l'ensemble des clients...

Je viens de faire quelques tests. En fait sur sending blue, ça fonctionne
bien et ça utilise l'encodage quand on met tls:// devant.
Et si on ne met rien, ça marche aussi et j'ai vu au niveau de PhPMailer que
ça n'utilisait aucun encodage.
Dans la doc, ça serait donc mieux de précauniser de mette tls:// devant
pour SendInBlue.

Si d'autres pouvaient vérifier que le bug se produit avec leur hébergeur,
ça nous permettrait de voir si c'est un cas isolé ou non.
Je me demande si le soucis se produit qu'avec OVH, car dans l'autre sens
quand pour SendInBlue je mets  ssl:// devant, j'ai direct un message
d'erreur.

**Comment by J9rem** [comment]
@acheype en gros, si on vérifiait l'intégrité du paramètre `'contact_smtp_host'` pour s'assurer que s'il contient `sendinblue` alors il ne faut pas que ça commence par `ssl:\` sinon ne pas prendre en compte ce paramètre, est-ce que ça suffirait ?
@mrflos est-ce que ça t'irait comme correctif ?

**Comment by acheype** [comment]
oui il peut y avoir un test très spécifique comme tu décris, mais ça me semblerait utile de confirmer d'abord si d'autres personnes rencontrent le même soucis qui freeze le serveur avec OVH.

mais plus généralement je me demande s'il ne faudrait pas diviser le host en deux : le protocole + le domaine du serveur. Il me semble que si le champ de config 'protocol' est obligatoire et est contraint aux valeurs 'TLS' ou 'SSL' (comme c'est le cas dans la config de nombreux outils), l'utilisateur se posera la question et le renseignera avec le protocol utilisé par l'hébergeur... Là il peut juste renseigner le domaine du serveur, et de ces expérience je constate que PhPMailer met par défaut le mode TLS.
