### ISSUE TITLE
I18n and config in javascript

### ISSUE THREAD

**Issue by seballot** [YesWiki/yeswiki#808]
Yop !

**Concernant l'internationalisation** pour le javascript, pour moi y'a deux options assez simple :

1. avoir un fichier de traduction côté JS, au format JSON, et donc découplé des actuels fichiers php. sur les outils comme weblate ce n'est pas un soucis on peut envoyer plusieurs fichiers à traduire, à des formats différents. Et comme de toute façon les fichiers actuels ne respectent aucune convention de format de traduction, là on pourra partir sur un truc standard. Vu le peu de traduction côté JS, je serai pour avoir un seul fichier dans /lang plutot que un fichier par tools (sauf pour les extensions)
2. Utiliser le même genre de fichier php qu'actuellement, mais avec un `$GLOBALS['translations_js']`, et envoyer de tableau au javascript.

Dans les deux cas, on pourra facilement avoir une petite fonction de traduction, qu'on peut aussi appeler `_t()` et qui sera dispo dans tous les JS, et dans les composants vue avec un petit plugin qui va bien

**Concernant la config** (par example `tools/bazar/config.yml`, il me semble qu'une bonne partie de cette config est maintenant faite dans la doc de l'action-builder (le choix des valeurs par défaut notamment), pour le reste ça à l'air plus lié au backend. Si on en a vraiment besoin côté js, on peut toujours passer au cas par cas certaines config au javascript. je ne suis donc pas sûr que ça vaille la peine de faire une passerelle généralisée entre le js et ces fichiers de conf

Qu'en pensez vous?

**Comment by seballot** [comment]
@mrflos @J9rem un avis?

**Comment by J9rem** [comment]
Salut,

merci pour ce début de concertation

>Vu le peu de traduction côté JS, je serai pour avoir un seul fichier dans /lang plutot que un fichier par tools (sauf pour les extensions)

et bien je suis de l'avis contraire et de laisser séparer comme c'est . J'aime bien ne pas tout changer tout en même temps. ET c'est bien de savoir où est le périmètre de chaque tools

>$GLOBALS['translations_js'], et envoyer de tableau au javascript.

bonne idée.

Quelques choses de plus meta, le sujet que tu amènes n'est pas le premier sur la roadmap, nous souhaiterions sortir les nouveaux thèmes margot juste avant.
Du coup, il est possible que nous nous concentrions sur ta question qu'un peu plus tard.
J'espère que tu comprendras.

**Comment by mrflos** [comment]
Pour moi aussi, j'aime bien l'idée que chaque extension et chaque tools du cœur de yeswiki ait son dossier `lang` avec ses propres traductions dedans, sachant qu'au moment de travailler sur la prochaine version majeure, sans doute (dans mon idée en tout cas) les tools comme templates et bazar entrerons dans le cœur et toutes les extensions non vitales seraient en dehors du cœur et ce serait donc centralisé a ce moment la.

Pour le choix des 2 options pour les traductions js, la première est plus propre et plus standard, mais je me dis que la logique de laisser php gérer et avoir la variable globale `translations_js` est plus dans la continuité de l'existant et a l'avantage de permettre de hacker le contenu des fichiers de langues dans des extensions custom (il suffirait de changer une entrée du tableau global pour modifier une trad), même si j'imagine que la même chose est faisable en js, je suis moins a l'aise pour le faire, ca fait plus statique, le json.

Aussi, a terme, pour les traductions, j'envisageais [d'utiliser xgettext](https://www.tutorialspoint.com/unix_commands/xgettext.htm) pour parser les fichiers du code et générer un .po comme c'est fait dans le [Makefile du lufi](https://framagit.org/fiat-tux/hat-softwares/lufi/-/blob/master/Makefile) qui permettrait d’accéder a plein d'outils standard pour gérer les traductions. D'ou l'importance de mettre des _t() de partout pour qu'il retrouve tout!

Enfin pour les configs, ok pour ta proposition de ne pas faire du global et de passer au cas par cas ou par l'action builder si pertinent.

**Comment by J9rem** [comment]
@seballot que penses-tu de cette première solution pour la traduction ?
https://github.com/YesWiki/yeswiki/compare/i18n?expand=1

ça a le mérite d'être immédiatement mis en place (hormis le temps de traduction)

**Comment by J9rem** [comment]
ou sinon @seballot tu as plutôt dans la tête que dans le dossier `tools/bazar/lang/` on ait `fr-FR.json` `en-US.json`

chaque fichier contient:
 ```json
{
  BAZ_EDIT_FORM_YES: 'Oui',
  BAZ_EDIT_FORM_NO: 'Non',
}
```
et on crée une fonction `_t('BAZ_EDIT_FORM_NO')` qui s'occupe d'appeler l'objet `wiki.lang['BAZ_EDIT_FORM_NO']`

Il y a bien sûr une phase d’initialisation dans `YesWiki->LoadExtensions` pour donner la liste des dossiers d'extensions à balayer et ceci pourrait être utiliser par la fonction `_t()` en js pour peupler wiki.lang la première fois.

**Comment by seballot** [comment]
salut !

Moi je voyais plutôt une nouvelle variable php `translations_js`, dont le contenu est fournit sur toutes les pages via la variable globale wiki
Là, le fait de devoir déclarer dans chaque Controller quels sont les clés de traductions dont tu as besoin je trouve ça trop compliqué (quand tu fais du js, faut que tu comprennes quel Controller est appelé, puis initialiser la variable, la passer à la vue etc...), et l'optimisation apportée n'est pas assez importante pour demander un tel supplément de travail aux devs. Si à terme on veut gagner en perf, on peut mettre en cache la version json de `translation_js` de manière à ce que le browser puisse le cacher, comme ça tu le charge une seule fois

aussi, je pense qu'il vaut mieux créer une fonction globale javascript appelée `_t`, comme ça c'est comme dans php, n'importe ou tu fais `_t('MY_KEY')`, non? plus c'est court mieux c'est je trouve, sachant que les clés sont souvent déjà assez longue
L'autre avantage de la fonction, c'est que on pourra inclure de l'interpolation i.e
```
MY_KEY = "salut {name}"
_t('MY_KEY', {name: 'Seby'})
```
Qui est une pratique assez indispensable dans la gestion de l'internationalisation !

Faudra aussi mettre cette fonction accessible dans Vue, je m'en chargerai si tu veux, faut faire un petit plugin

Et sinon, petit détail à la marge sur ton commit, je pense qu'il vaudrait mieux appeler ta clé `YES` plutôt que `BAZ_FORM_EDIT_YES`. Pour les trucs assez communs mieux vaut ne pas mettre de contexte pour que ça soit facilement réutilisable

Merci d'avoir avancé la dessus !

**Comment by J9rem** [comment]
@seballot super ton idée, mais je n'ai pas tout compris.

Actuellement nous avons `wiki.lang` qui permet de sauvegarder les données de traduction.
Tu proposes donc de créer une nouvelle variable `wiki.translation_js`, est-ce bien ceci ?

Ensuite, pour le peuplement de cette variable, comment vois-tu la chose ?
Le PHP peuple la variable `wiki.translation_js` à partir de fichiers `/lang/fr-FR.json` ou `tools/bazar/lang/fr-FR.json`. Est-ce bien ce que tu vois ?

**Comment by seballot** [comment]
désolé j'ai pas expliqué jusqu'au bout, le `translation_js` c'est côté php
```php
<?php
$GLOBALS['translations'] = array_merge($GLOBALS['translations'], array(
    'USED_IN_PHP' => "boom"
);
$GLOBALS['translations_js'] = array_merge($GLOBALS['translations_js'], array(
    'USED_IN_JAVASCRIPT' => "coucou"
);
```

soit on met ces deux déclaration dans le même fichier lang, genre `aceditor_en.php`, soit on en créé un nouveau spécial pour javascript avec la déclaration de `translation_js`, par exemple `aceditor_js_en.inc.php`

ou soit, comme je le proposais au début, mais peut être ça avait été mal compris, on créé un seul fichier de lang pour tout le javascript : `lang/javascript_en.php`, et on met toutes les traductions utilisées en javascript ici, peu importe l'extension (l'idée étant qu'il va y avoir assez peu de traductions côté js, donc ça peut peut être être plus simple de toutes les réunir. Mais garder des fichiers lang javascript par extension me va aussi)

**Comment by J9rem** [comment]
@seballot je comprends mieux.
Donc je fais une proposition en me basant sur ce que tu as énoncé mais avec d'autres apports. Qu'en dis-tu ?

 - **côté js**:
   - les traductions sont stockées dans la variable `wiki.lang` dans la langue courante de la page
   - une fonction `function _t('MY_KEY', {name: 'Seby'})` assure la traduction de `MY_KEY` à partir de `wiki.lang` en remplaçant les occurrences de `{name}` par `Seby`
   - une fonction javascript dans `yeswiki-base.js` est exécuté une seule fois à l'initialisation pour charger les fichiers de traduction dans `wiki.lang` en utilisant la variable `wiki.locale` pour choisir les bons noms de fichiers
 - **côté fichiers**:
   - les données traductions javascripts sont stockées dans des fichiers ou variables distinctes de ceux pour le php de façon à n'envoyer à l'environnement `js` que les données de traduction nécessaire (et pas toutes les traductions nécessaires à PHP)
   - pour faciliter les traductions dans les autres langues, nous pourrions introduire le stockage dans des fichiers `json` du genre `myextensioname-lang.json` comme `bazar-fr.json` ou `bazar-en.json`
   - les fichiers sont rangés dans les dossiers suivants `lang`, `tools/bazar/lang`, `tools/aceditor/lang`, `tools/extensionname/lang`, `custom/lang`
 - **côté php** :
   - il n'y a pas de chargement des données depuis les `json`
   - afin de profiter du cache sur le navigateur du client, il plus utile de charger les fichiers de traduction depuis le javascript
   - `YesWiki->LoadExtensions` s'occupe déjà de définir la liste des dossiers de chaque extension. Nous pourrions alors profiter de ce balayage des extensions pour vérifier l'existence du dossier `lang` dans chaque extension et d'ajouter le chemin relatif de ce dossier à la variable _php_ `YesWiki->langFolders`
   - cette variable `YesWiki->langFolders` est alors recopiée dans le html `<script>var wiki.langFolders = {{ wiki.langFolders|json_encode() }};</script>`
   - n'importe quelle actions, handler, controller peut alors ajouter chemin spécifique vers un dossier contenant des json qui ne seront chargés que si cette action est utilisée (comme par exemple `tools/bazar/lang/form-edit/`)

**Comment by seballot** [comment]
Yo !

donc si je comprends bien, tu veux mettre les traductions dans des fichiers `json`, et les charger de manière asynchrone grâce à `wiki.langFolders` qui les listera? si c'est ça, ça ne va pas fonctionner, car au même moment les autres fichiers js vont s'exécuter, et vont appeler `_t(...)` avant que les fichiers de traductions soient chargés, non?

Je pense qu'il faut pas se compliquer, mettre les traduction dans des fichiers php, et juste initialiser wiki.lang avec la totalité des traductions js définies dans ces fichiers php. Le jour où on aura tellement de traduction JS qu'on voudra optmiser un peu, on verra comment implémenter un cache efficace, mais là vu le nombre minime de ces traductions faut pas trop batailler je crois !

**Comment by J9rem** [comment]
super @seballot , ça me va aussi. Je suis d'accord avec toi et je n'avais pas perçu le problème avant que tu l'évoques.
Est-ce qu'on peut par contre garder les fichiers json et faire en sorte que leur chargement peuple correctement la variable `translation_js` en convertissant le json en tableau php grâce à `json_decode()` ? Ceci permettrait d'avoir tout de suite les fichiers dans un format plus standardisé pour les traductions automatiques si j'ai bien compris.

**Comment by seballot** [comment]
ah ah ça devient un peu tordu cette affaire mais pourquoi pas !!

J'ai vu aussi qu'on peut charger en synchrone les fichiers json, suffit de mettre `async: false` : https://stackoverflow.com/questions/4116992/how-to-include-json-data-in-javascript-synchronously-without-parsing#4117026

Donc trois options
1. on déclare les traductions js dans des fichiers php, on initialize la variable javascript wiki.lang avec
2. on déclare les traductions js dans des fichiers json, on les lit côté php, et on initialize la variable javascript wiki.lang avec
3. on déclare les traductions js dans des fichiers json, et on les charge depuis le javascript en synchrone

Moi j'irai plutot pour l'option 1, qui semble la plus simple à implémenter. Je préfère ausis avoir tous les fichiers de traduction dans le même format
Ca fera pas des fichiers traduction standard, mais homogène avec les traductions php actuels. Donc quand on convertira les fichier traduction php en fichier traduction standard, ça fera tout en même temps
D'ailleurs, j'ai regardé à la fois [Weblate](https://docs.weblate.org/fr/latest/formats.html#laravel-php-strings ) et à la fois le [module de traduction Symfony](https://symfony.com/doc/current/translation.html#translation-resource-file-names-and-locations)  supportent des fichiers php pour des traductions, qui doivent juste retourner un tableau
donc faudrait juste changer
```
<?php
$GLOBALS['translations'] = array_merge($GLOBALS['translations'], array(
    'AB_bazar_label' => "Display form's data"
)
```
en
```
<?php
return array(
    'AB_bazar_label' => "Display form's data"
)
```
Et voilà !
Ca me semble une bonne piste !

@mrflos un avis?

**Comment by J9rem** [comment]
@seballot j'aime bien cette option de rester sur des fichiers php par souci d'harmonisation et oui c'est possible selon moi de passer à des fichiers avec `return Array...` (tout en assurant la rétrocompatibilité avec les anciens fichiers de langues pour les extensions custom).

Merci pour cette proposition synthétique

**Comment by mrflos** [comment]
je suis pour l'option 1

**Comment by J9rem** [comment]
@seballot est-ce que ce commit sur la branche de travail i18n commence à se rapprocher de ta vision ?
https://github.com/YesWiki/yeswiki/commit/ed5b3a6e77a770ac6f176385305a9f03eb6ee838

**Comment by seballot** [comment]
Top ! bien joué @J9rem ! J'ai juste mis un petit commentaire sur un fallback sur l'anglais

**Comment by J9rem** [comment]
Du coup avec le dernier commit sur la branche i81n , je vais pouvoir passer à une PR.
@mrflos on te semble sur la bonne voie aussi ?

**Comment by J9rem** [comment]
a priori, on nous pouvons fermer cette issue vu que tout est en application.
Je laisse une semaine pour les réactions éventuelles avant de la clore.
