### ISSUE TITLE
Remove template gogocarto

### ISSUE THREAD

**Issue by seballot** [YesWiki/yeswiki#809]
Yop ! je crois qu'il est buggé, et avec le nouveau bazar-list dynamique je pense qu'on en a plus besoin

On peut faire une redirection vers le template map pour les éventuels wiki qui l'utiliserait

ça vous va?

**Comment by mrflos** [comment]
ok, si un jour on arrive a le reparer, on pourait le mettre dans l'extension contrib

**Comment by J9rem** [comment]
@seballot vu qu'il fonctionne à nouveau ce template, est-ce que la présente issue est toujours d'actualité ?

**Comment by seballot** [comment]
Nop, bien vu :)
