### ISSUE TITLE
[Attach] Suppression des fichiers attachés lors de la suppression d'un page.

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#813]
Nouvelle fonctionnalité

**Description**
J'ai parcouru le code et fait un test avec la dernière version de YesWiki doryphore disponible à ce jour. Le fichiers attachés a une page ne sont pas supprimé lors de la suppression de celle-ci.

Ce serait bien que ce soit le cas :)

Une solution pour détecter les fichiers orphelins serait aussi fort pratique (ou les vieilles versions) et les supprimer. Pourquoi pas un bouton ccleaner dans la page GérerSite. ;)

**Comment by J9rem** [comment]
@daiko c'est difficile de décider de supprimer automatiquement les fichiers liés à une page ou une fiche car il peut exister des liens externes vers ces fichiers.
Toutefois, c'est une très bonne idée de rajouter au futur Gestionnaire de fichier la possibilité de faire le tri.

cf. #373, https://github.com/YesWiki/yeswiki/tree/filescleanning

toutefois, nous avons prévu dans notre road map actuelle de nous occuper de ce gestionnaire de fichier après la traduction, les nouveaux thèmes et un bazarliste dynamique ...

**Comment by fbredow** [comment]
@j9rem J'aimerai donner un coup de main, mais pas moyen de débloquer du temps.

Automatiquement c'est effectivement dangereux. Peux être un bouton après la suppression comme pour les pages admin lors de la mises à jour (très bonne idée en passant).

**Comment by J9rem** [comment]
Je te propose @daiko de voir quand la roadmap aura avancer : a priori à partir de décembre ce sera possible de tous nous intéresser au gestionnaire de fichiers mais il est prévu plus pour la version ectoplasme. 

Je devine ton impatience..;

**Comment by J9rem** [comment]
L'extension https://github.com/YesWiki/yeswiki-extension-multideletepages/ permet l'usage du handler [`filescleaning`](https://github.com/YesWiki/yeswiki-extension-multideletepages/blob/master/handlers/FilesCleaningHandler.php).

Avec ce handler, il est possible de supprimer en masse les fichiers inutilisés.

Je clos donc la présente issue.

**Comment by J9rem** [comment]
Au passage, par sécurité, les fichiers associés à une fiche ne sont pas supprimés lors de la suppression de la fiche pour éviter les soucis d'erreur de suppression. Il est assez facile de retrouver une version récente de la base de données `SQL` pour y retrouver la fiche à réimporter. Il est en général plus complexe de retrouver la sauvegarde des fichiers.

C'est pour ceci que j'ai plutôt proposé un nettoyage a posteriori fait par un administrateur qui saura plus facilement si des suppressions involontaires (ou par des robots malveillants) font que certains fichiers doivent être maintenu même s'ils sont orphelins.
