### ISSUE TITLE
Rediriger vers la fiche créé quand une fiche est créée

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#820]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Lors de création d'une fiche, la redirection vers la page de création pose problème avec les éventuels formulaires inclus dans les text area de la dite fiche.

fiche avec bf_description correspondant à un textelong en mode wiki

```
{...
"bf_description":"{{bazar vue="saisie" voirmenu="0" id="3"}}"
...}
```
(attention ça n'est pas exactement le code json d'une dite fiche, je l'ai rendu ici lisible en enlevant des `\`)

**Proposition**:
rediriger vers la fiche en question EN MAINTENANT la présence du message de tête.
ceci pourrait se faire avec la librairie `flash()` que la PR #810 va ajouter.

@acheype Elle va remplacer l'issue 19 de LMS https://github.com/YesWiki/yeswiki-extension-lms/issues/19 qui en fait n'est pas spécifique à LMS

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki doryphore

**Comment by acheype** [comment]
Merci @J9rem pour cette amélioration. 
Elle corrige bien le message en double qu'on peut avoir quand on créé une fiche depuis une page d'Activité LMS :
![2021-11-05 11-22 - Capture d'écran](https://user-images.githubusercontent.com/8435038/140496007-cfedb60e-f17b-4877-9f8f-38d24bdef709.png)

Mais l'issue 19 de LMS YesWiki/yeswiki-extension-lms#19 ne traitait pas de cela. Il ne se produit pas à la création d'une fiche d'un formulaire intégré à une activité LMS mais à la création de l'activité LMS elle-même. Cf cet exemple où on voit le soucis d'imbrication que cela continuer de générer suite à ta correction :

![2021-11-05 12-39 - Capture d'écran](https://user-images.githubusercontent.com/8435038/140497225-7163a126-62e1-4920-a35e-bed539a7ac46.png)

**Comment by J9rem** [comment]
@acheype si tu regardes bien, l'imbrication n'est plus infinie mais elle est limité à 3 niveaux pour le moment grâce à cette ligne https://github.com/YesWiki/yeswiki/blob/5d6df554a1e551b9ad30a2290f3d92cac4efab2e/tools/bazar/controllers/EntryController.php#L85

On pourrait limiter à 1 niveau mais ça peut être perturbant pour l'utilisateur qui ne s'attendait pas à ne rien voir.

Donc j'ai mis 3 niveaux pour déjà éviter le souci de la boucle infinie et ne plus faire planter le php.

pour le reste, effectivement, ça n'est pas résolu, je poursuis dans la PR https://github.com/YesWiki/yeswiki-extension-lms/issues/19

**Comment by acheype** [comment]
J'avais en effet pas fait gaffe que c'était limité à 3 niveau maintenant vu que le code provient d'un autre commit. Merci de l'avoir précisé.
