### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [YesWiki/yeswiki#821]
Hey there!

I belong to an open source security research community, and a member (@hitisec) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by mrflos** [comment]
Thanks for get in touch!  
We created https://github.com/YesWiki/yeswiki/blob/doryphore/SECURITY.md as advised by you!

**Comment by J9rem** [comment]
@zidingz 
Hello,

thanks for all your messages.
Now, I think that with the file created by @mrflos you will have all data to contact us. 
Do you think we can close this current issue ?
