### ISSUE TITLE
[theme][margot] sémantique action "toc"

### ISSUE THREAD

**Issue by Cyrille37** [YesWiki/yeswiki#823]
Bonjour,

Je n'ai pas trouvé où faire un ticket pour un thème, du coup je le pose ici :-)

Sur un YesWiki cercopitheque (*je crois*) utilisant le thème Margot il manque le tag &lt;ul&gt; pour l'action **{{toc}}**:

![image](https://user-images.githubusercontent.com/368965/136195683-16cbc5da-681f-4edd-a8a1-369cc4838ed4.png)

On peut le voir là : https://aiguillage.artefacts.coop/?LaFaq

Bonne route :-)

**Comment by J9rem** [comment]
Salut @Cyrille37 ,

est-ce que le souci est présent avec un site en version Doryphore ?
Car en effet, nous n'assurons plus que les mises à jour de sécurité pour cercopitheque.
Il existe l'action `{{tocjs}}` peut-être plus stable non ?
