### ISSUE TITLE
Sécurisation de la création de comptes

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#825]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Nouvelle fonctionnalité

**Description**
Pour sécuriser la création et gestion des comptes : 
 - ajouter une focntionnalité à l'action UserTable afin de permettre aux administrateurs de créer des comptes pour de nouveaux utilisateur.ices, avec si possible génération d 'un mot de passe via un clic sur un lien reçu par mail
 - ajout d'un captcha ou tout autre système limitant la possibilité de création de comptes par un robot

**Comment by J9rem** [comment]
Cette issue est en lien avec #125

**Comment by VeveQNV** [comment]
Bonjour, je suis en train d'implémenter pour mes besoins la validation de l'inscription par l'envoi d'un mail avec un lien d'activation. J'utilise la table triples pour stocker les informations liées à ce processus (clefs et booleen sur l'activation du compte). Si le code vous intéresse je vous le proposerais.

**Comment by J9rem** [comment]
@VeveQNV il y a déjà des travaux en cours avec #935 qui va bientôt être fusionnée.
Nous pourrons alors repartir de la nouvelle version de YesWiki pour voir comment mettre en place les besoins de validation (je serai alors curieux de voir comment tu proposes de faire à partir de la future nouvell eversion)

**Comment by VeveQNV** [comment]
Oui j'ai vu cela. A la fois, je n'ai aucune visibilité sur la sortie de 
tout ceci. Néanmoins je pense que la restructuration du code est un 
détail en 1 sens. L'algorithme a proprement parlé peut s'intégrer 
facilement ici ou là, A peu de choses près, c'est le nom des fonctions 
qui changent.

Niveau du fonctionnement : je rajoute un triple qui indique si le compte 
est activé ou non. A la fin de la création de la fiche j'envoie un mail 
avec un lien contenant une clef que j'ai stocké également dans la table 
triples. Puis je redirige vers une page qui dit qu'il faut valider le 
compte en cliquant sur le lien. Je rajoute une action qui est appelé à 
partir de la page du lien. Elle valide le compte utilisateur si la clef 
est bonne. Au login on teste si le compte est activé.

Le 08/07/2022 à 22:59, Jérémy Dufraisse a écrit :

**Comment by J9rem** [comment]
fixed by #935
