### ISSUE TITLE
Permettre d'avoir plusieurs champs 'map' dans une même formulaire

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#828]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Permettre d'avoir plusieurs champs 'map' dans une même formulaire

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/35/permettre-davoir-plusieurs-champs-map-dans-une-meme-formulaire
