### ISSUE TITLE
recherche adresse bazar

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#83]
je ne pense pas que cela vienne de bazar, mais je signale quand même, quand je cherche mon adresse, pour la positionner sur la carte quand je saisi une fiche, celle ci ne me trouve plus et me met à Paris. 
2 place de l'ancienne mairei
34270 Claret

**Comment by daviddelon** [comment]
Je viens de tester : pas de problème. C'est sur quel Wiki ?
