### ISSUE TITLE
Wiki cassé quand mise à jour sur Yunohost

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#830]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Quand notre yeswiki est installé via yunohost, la mise à jour casse tout le wiki ("cette page ne fonctionne pas") et on a plus comme choix que de le réinstaller via yunohost ce qui fait qu'on perd tout :-) 

Je sais pas si c'est lié à yeswiki ou à la version proposée sur yunohost :/

**Comment by J9rem** [comment]
@RomainLalande peux-tu être plus précis au sujet de 'mettre à jour' ?
via yunohost ou via le bouton de mise à jour de YesWiki ?

**Comment by J9rem** [comment]
ceci est normalement lié à #782

**Comment by RomainLalande** [comment]
Aouch désoler je n'ai pas eu de retour de Didier à qui c'est arrivé, mais depuis, Quentin en Auvergne a eu le même soucis. Je lui met le lien vers cette issue qu'il puisse te faire un retour (il est plus au fait que moi).
Et a priori c'est via le bouton mise à jour yeswiki et Effectivement ça semble bien lié à un problème de droits :s

**Comment by J9rem** [comment]
et donc c'est vraiment la #782 qui est concernée, je la passerai sur le dépôt de Yunohost pour qu'elle puisse être prise en compte

**Comment by J9rem** [comment]
Je clos cette issue car la demande est un peu vieille est ne semble plus correspondre aux versions `doryphore` en production (soit directement en installation ftp soit via `yunohost`).

Si le souci réapparait, une nouvelle issue avec le numéro de version `doryphore` pourra être recréée
