### ISSUE TITLE
EntryManager.php ligne 740 : Invalid argument supplied for foreach()...

### ISSUE THREAD

**Issue by ericfavr3** [YesWiki/yeswiki#839]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug

**Description**
Explain the bug or the feature / expliquer le bogue ou la fonctionnalité demandée
J'ai le message suivant lors de l'affichage des fiches baazar - c'est juste un warning et la fiche s'affiche correctement.
Warning: Invalid argument supplied for foreach() in /home/clients/eee5f31115f9c44c5941e258e59953a8/web/yeswiki/wikis/testFerme/tools/bazar/services/EntryManager.php on line 740

**Additionnal informations / Informations complémentaires**
- version de YesWiki : doryphore 2021-11-11-1
- [url to see the problem or an example / url pour voir le probleme ou un exemple](https://yeswiki.paquerette.eu/wikis/testFerme/?FramasofT)

**Comment by J9rem** [comment]
@ericfavr3 est-ce que tu peux vérifier que le souci a bien disparu avec la toute dernière version de yeswiki ?

**Comment by J9rem** [comment]
apparemment c'est corrigé.
