### ISSUE TITLE
Sauvegarder auto le code dans les formulaires

### ISSUE THREAD

**Issue by HugoARDEAR** [YesWiki/yeswiki#844]
** Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Dans la création de formulaire aucun message d'avertissement ne s'affiche si l'on passe du "code" au "constructeur graphique". 
Peut être afficher un message comme celui qui s'affiche lors de la non sauvegarde d'une page wiki ou alors sauvegarder automatiquement le code si l'on passe dans le "constructeur graphique"

**Comment by J9rem** [comment]
Bienvenue @HugoARDEAR et bonne idée que tu proposes.

Auparavant, il y avait une utilisation du "code" avant de passer au "constructeur graphique", un peu une sorte de ne pas perdre les modifications MAIS si le code ne correspondait pas à ce que comprendre le "constructeur graphique", il pouvait y avoir des pertes, ....

Je vais laisser murir les idées quelques temps pour trouver la solution adéquate qui fonctionnerait

**Comment by J9rem** [comment]
@HugoARDEAR ce commit https://github.com/YesWiki/yeswiki/commit/eab87bfb0334175f3e6d1a6fd99f9f3a95bd0df0 résout une partie du problème en indiquant un message de confirmation avant de retourner au constructeur graphique
Je me permets donc de clore cette issue.
