### ISSUE TITLE
New Feature - amélioration champs titre dans les formulaires

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#849]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Concernant le bf_titre , les utilisateurs novice le suppriment souvent par inadvertance. Serait-il possible : 
-  Soit d'empêcher la validation du formulaire lorsqu'il n'y a pas de bf_titre 
- Soit de faire une pop-up "Attention vous venez de supprimer le champs titre qui est obligatoire" quand on le supprime
- Soit d'ajouter lors de la validation d'un formulaire ne contenant pas de champs titre "attention le formulaire ne comporte pas de champs titre, votre fiche n'a pas été enregistrée
(soit un mix de ces pistes de solution)

Concernant le champs "titre automatique", quand on l'utilise mal et qu'on y met du texte brut, mais qu'ensuite on remplit une fiche en saisie du formulaire elle ne se valide pas et met une grosse erreur terrifiante du type "Erreur code machin à la ligne truc". 
Est-ce qu'il serait possible 
 - Soit de remplacer ce message par un message du type "attention, votre fiche n'a pas été enregistré, il y a un champs titre automatique mal renseigné dans votre formulaire".
 - Soit d'intégrer un message d'erreur lorsque l'on remplit mal le paramètre "titre automatique" dans l'interface de création de formulaire
(soit un mix des deux solutions)

**Comment by J9rem** [comment]
@RomainLalande J'ai l'impression que c'est plus une amélioration de l'interface qu'un bug.
Car si le concepteur de YesWiki suit correctement la documentation, il n'y a pas de bugs, ...

Il semblerait que pour répondre au besoin que tu as évoqué, il faudrait ajouter un vérificateur de formulaire avant de le valider.
Cette fonctionnalité n'existe pas actuellement.
Ce serait une nouveauté à prévoir dans les futurs chantiers YesWiki

**Comment by RomainLalande** [comment]
Top, du coup j'ai modifié le titre en conséquence. Je le garde en tête pour voir au sprint si c'est un vrai besoin commun ou un petit caprice perso :p

**Comment by seballot** [comment]
il me semble que cela a déjà été amélioré dans un précédent sprint, je ferme donc, mais si ce n'est pas le cas n'hésite pas à faire une demande sur https://priorites.yeswiki.net/ @RomainLalande
