### ISSUE TITLE
Gérer nativement h5p

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#851]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Gérer nativement h5p

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki doryphore
- https://h5p.org/
- outil lié h5p : https://ladigitale.dev/logiquiz/#h5p
- exemples : https://h5p.org/content-types-and-applications

**Comment by mrflos** [comment]
C'est plutôt une issue pour le lms, non?

**Comment by J9rem** [comment]
Et bien vu le commentaire sur le canal centre-ville c'est plus un besoin pour le cœur YesWiki pas uniquement l'extension LMS.
Après si tu penses que c'est plus pertinent de le mettre que dans LMS alors je déménage la PR (même si pour le moment, il apparaissait que le besoin était général)

**Comment by mrflos** [comment]
non, je vais clarifier sur le canal, mais je ne pense pas que ce soit un besoin général, et le système d'extension est suffisamment clé en main pour que l'on ajoute cette extension si le besoin de support h5p se fait sentir.  
Il faut etre vigilant·e à ne pas gonfler le coeur de fonctionnalités non essentielles à wiki.

**Comment by J9rem** [comment]
Je suis tout à fait d'accord avec toi que ça n'est pas utile de gonfler le cœur, on déménage alors la PR ça me va aussi.
Effectivement, on peut inviter celles et ceux qui ont besoin du h5p à installer lms.
Ok pour toi @mrflos
