### ISSUE TITLE
Mettre à jour les fiches bazar qui utilisent encore "carte_google"

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#852]
New feature / Nouvelle fonctionnalité

**Description**
Explain the bug or the feature / expliquer le bogue ou la fonctionnalité demandée
Dans bazar le champ carto historique "carte_google": "45.5716566|5.6943937", a été remplacé par    
geolocation { "bf_latitude": "45.539060482134495",
    "bf_longitude": "5.707546487318736"
  }
La retro compatibilité est assurée pour l'affichage map classique mais pour l'affichage map dynamic ca ne passe pas.

Pourrait-on envisager un script pour mettre à jour les fiches qui contiennent encore carte_google afin de  permettre l'utilisation de nouvelle fonctionnalité map dynamic sur des wikis créés avant juin 2021 ?

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki doryphore 2021-11-11-1
- url to see the problem or an example / url pour voir le probleme ou un exemple
- screenshot / capture d’écran
- logs

**Comment by J9rem** [comment]
corrigé par https://github.com/YesWiki/yeswiki/commit/e1366c2516c7be726146007ad2098db7f3d08c4c
(sera bientôt déployé dans `doryphore`)

**Comment by J9rem** [comment]
fixed by https://github.com/YesWiki/yeswiki/commit/e1366c2516c7be726146007ad2098db7f3d08c4c
