### ISSUE TITLE
{{newtextsearch}} encore vraiment fonctionnel ?

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#853]
Je me demande si la fonction de recherche présente sur le wiki (loupe à côté de roue crantée) est encore parfaitement fonctionnelle

J'ai constaté à plusieurs reprises sur des wikis à jour  (doryphore 2021-12-02-7) que des mots "très clairement présents" dans des pages ou des fiches du wiki ne sont pas trouvées via le moteur de recherche

il me semble que sur yeswiki.net ça fonctionne (sous doryphore 2021-11-29-2)

**Comment by J9rem** [comment]
fixed by https://github.com/YesWiki/yeswiki/commit/1ed2d63fdeb19e919c78961a086797d65425aaec
