### ISSUE TITLE
Suivre les modifications d'une ou de plusieurs pages 

### ISSUE THREAD

**Issue by Hoppicker** [YesWiki/yeswiki#856]
**Type of issue  / Type de demande**
New feature / Nouvelle fonctionnalité

**Description**
Permettre à un utilisateur enregistré de suivre une page donnée et d'être informé par mail quand la page est modifiée.

**Additionnal informations / Informations complémentaires**
- version of YesWiki : Doryphore
- Utile, par exemple, pour une page donnant les dates des prochains événements.
- url to see an example / url pour voir un exemple https://www.dokuwiki.org/fr:subscription
- une image : https://www.dokuwiki.org/_detail/subcriptionmanagement.png?id=fr%3Asubscription

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/34/suivre-les-modifications-dune-ou-de-plusieurs-pages
