### ISSUE TITLE
L'environnement de tests automatiques ne fonctionne pas sur un fork github

### ISSUE THREAD

**Issue by VeveQNV** [YesWiki/yeswiki#857]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**

Bug / Bogue

**Description**

"Run composer test" retourne une erreur lors d'un "Run Test Suite"

**Additionnal informations / Informations complémentaires**

Run composer test
> phpunit tests 
PHPUnit 9.5.9 by Sebastian Bergmann and contributors.
PHP Warning: file_put_contents(/home/runner/work/yeswiki/yeswiki/vendor/phpunit/phpunit/.phpunit.result.cache): failed to open stream: Permission denied in /home/runner/work/yeswiki/yeswiki/vendor/phpunit/phpunit/src/Runner/DefaultTestResultCache.php on line 154
EESSSESSSESSS 13 / 13 (100%)
Time: 00:00.016, Memory: 6.00 MB
There were 4 errors:
1) YesWiki\Test\Core\YesWikiTest::testInitWiki
Cannot modify header information - headers already sent by (output started at /home/runner/work/yeswiki/yeswiki/vendor/phpunit/phpunit/src/Util/Printer.php:104)
/home/runner/work/yeswiki/yeswiki/includes/YesWikiInit.php:192
/home/runner/work/yeswiki/yeswiki/includes/YesWikiInit.php:85
/home/runner/work/yeswiki/yeswiki/includes/YesWiki.php:95
/home/runner/work/yeswiki/yeswiki/includes/YesWikiLoader.php:49
/home/runner/work/yeswiki/yeswiki/tests/YesWikiTestCase.php:14
/home/runner/work/yeswiki/yeswiki/tests/includes/YesWikiTest.php:17
2) YesWiki\Test\Core\Service\AclServiceTest::testACLServiceExisting
Cannot modify header information - headers already sent by (output started at /home/runner/work/yeswiki/yeswiki/vendor/phpunit/phpunit/src/Util/Printer.php:104)
/home/runner/work/yeswiki/yeswiki/includes/YesWikiInit.php:192
/home/runner/work/yeswiki/yeswiki/includes/YesWikiInit.php:85
/home/runner/work/yeswiki/yeswiki/includes/YesWiki.php:95
/home/runner/work/yeswiki/yeswiki/includes/YesWikiLoader.php:49
/home/runner/work/yeswiki/yeswiki/tests/YesWikiTestCase.php:14
/home/runner/work/yeswiki/yeswiki/tests/includes/services/AclServiceTest.php:17
3) YesWiki\Test\Core\Service\PerformerTest::testPerformerExisting
Cannot modify header information - headers already sent by (output started at /home/runner/work/yeswiki/yeswiki/vendor/phpunit/phpunit/src/Util/Printer.php:104)
/home/runner/work/yeswiki/yeswiki/includes/YesWikiInit.php:192
/home/runner/work/yeswiki/yeswiki/includes/YesWikiInit.php:85
/home/runner/work/yeswiki/yeswiki/includes/YesWiki.php:95
/home/runner/work/yeswiki/yeswiki/includes/YesWikiLoader.php:49
/home/runner/work/yeswiki/yeswiki/tests/YesWikiTestCase.php:14
/home/runner/work/yeswiki/yeswiki/tests/includes/services/PerformerTest.php:18
4) YesWiki\Test\Core\Service\UserManagerTest::testUserManagerExisting
Cannot modify header information - headers already sent by (output started at /home/runner/work/yeswiki/yeswiki/vendor/phpunit/phpunit/src/Util/Printer.php:104)
/home/runner/work/yeswiki/yeswiki/includes/YesWikiInit.php:192
/home/runner/work/yeswiki/yeswiki/includes/YesWikiInit.php:85
/home/runner/work/yeswiki/yeswiki/includes/YesWiki.php:95
/home/runner/work/yeswiki/yeswiki/includes/YesWikiLoader.php:49
/home/runner/work/yeswiki/yeswiki/tests/YesWikiTestCase.php:14
/home/runner/work/yeswiki/yeswiki/tests/includes/services/UserManagerTest.php:18
ERRORS!
Tests: 13, Assertions: 0, Errors: 4, Skipped: 9.
Script phpunit tests handling the test event returned with error code 2
Error: Process completed with exit code 2.

**Comment by J9rem** [comment]
A priori @VeveQNV c'est résolu.
Je te laisse vérifier

**Comment by J9rem** [comment]
résolu par https://github.com/YesWiki/yeswiki/commit/311140efec8b61746bd9d8265a0d17bf16dddac2
