### ISSUE TITLE
Pouvoir définir la période de validité d'une fiche bazar

### ISSUE THREAD

**Issue by idopisebas** [YesWiki/yeswiki#858]
**Type of issue / Type de demande**
New feature / Nouvelle fonctionnalité

**Description**
To be able to define the period of validity of a bazar file  /  Lors d'une saisie de fiche, je trouve qu'il serait intéressant que l'utilisateur puisse paramétrer "la durée de vie" de la fiche bazar qu'il est en train de rédiger. .. De manière à ce qu'elle s'autodétruise à une date donnée...Une sorte de période de validité en somme...

**Comment by idopisebas** [comment]
Est-ce techniquement possible ?

**Comment by mrflos** [comment]
A mon avis ca doit presque être possible déjà actuellement en mode bidouille, car nous n'avons pas de notion de date de publication dans les fiches bazar.
Mais on peut rajouter un champ date `bf_date_fin_publication` au formulaire des fiches et dire de n'afficher que les fiches ayant une date inférieure a la date de la fiche avec une syntaxe comme `
{{bazarliste correspondance="bf_date_debut_evenement=bf_date_fin_publication" datefilter="past" }}`

**Comment by seballot** [comment]
le workaround proposé par Flo à l'air de faire l'affaire, alors je ferme :)
