### ISSUE TITLE
New Feature - Bouton "créer un lien"

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#859]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Pour faciliter l'usage, proposition d'évolution de l'interface de création de lien, je proposerais bien : 

- Quand on selectionne l'option "ouvrir dans l'onglet courant" , générer quand même une synthaxe {{button parma=""}} plutôt que d'utiliser la synthaxe ancienne [[mapage mon texte de lien]] qui ne permet pas de l'éditer avec le petit crayon dans la marge une fois inséré dans la page

Voilà voilà

**Comment by J9rem** [comment]
@RomainLalande je ne suis pas d'accord, car l'ancienne syntaxe est plus simple à lire.

**Comment by RomainLalande** [comment]
Je pense que c'est une question peut-être plus large alors d'orientation de l'ergonomie, si on imagine quelu'un qui découvre YW aujourd'hui ça me semble plus simple au contraire de se référer à une seule modalité de compréhension des actions/codes wikis : cliquer dans la marge sur le crayon modifier pour agir sur le code via une interface visuelle. 
Mais vu la difficulté d'en débattre longtemps ici et  vu que c'est loin d'être urgent, je propose de laisser en suspend et d'avoir le temps de tirer tous les fils de ce débats à quelques un.e.s pendant un sprint :-)

**Comment by J9rem** [comment]
résolu par https://github.com/YesWiki/yeswiki/commit/2260a9d9f65c0e83894cf9d5ca81bdd7943d1053
