### ISSUE TITLE
Nouveau parametres de l'action bazarcarto

### ISSUE THREAD

**Issue by daviddelon** [YesWiki/yeswiki#86]
Suite à la re-ecriture de bazarcarto : revoir la doc associée.

**Comment by furax37** [comment]
c'est à dire c quoi les nouveautés ?

**Comment by mrflos** [comment]
tout a été revu et documenté pour la sortie de cerco 
Work in progress : http://yeswiki.net/cercopitheque/wakka.php?wiki=ActionBazarliste
