### ISSUE TITLE
bazar . bug nav par onglet

### ISSUE THREAD

**Issue by idopisebas** [YesWiki/yeswiki#863]
**Description** 
via constructeur graphique et via code wiki :
navigation par onglet ; le paramétrage `Déplacer le bouton 'Valider'` ne semble pas fonctionner...
`tabs***Descriptions,Contact,Géolocalisation*** *** *** ***ICI***nav-tabs***btn-primary***0*** *** *** *** *** *** *** ***`
-version doryphore 2021-12-22-8 
;)

**Comment by J9rem** [comment]
Bonjour @idopisebas ,

est-ce que je peux avoir les autres bouts de code `labelhtml` du formulaire en question car en laissant les anciennes syntaxes, il peut y avoir un conflit

**Comment by idopisebas** [comment]
Bonjour @J9rem :)
... je n'ai pas de `labelhtml` justement ... 
Mais ohoh... je viens de voir que ce que je prenais pour un bug était en fait un oubli de ma part ! !

```
tabs***TAB1,TAB2,TAB3*** *** *** *** ***nav-tabs***btn-primary***0*** *** *** *** *** *** *** ***
texte***bf_titre***titre*** *** ***0*** ***number***1*** *** *** * *** * *** *** *** ***
textelong***bf_description***Zone de texte*** *** *** *** ***wiki***0*** *** *** * *** * *** *** *** ***
image***bf_image***Image***140***140***600***600***right***0*** *** *** * *** * *** *** *** ***
tabchange***formChange*** *** *** *** *** *** ***0*** *** *** *** *** *** *** ***
lien_internet***bf_url***Url*** *** *** *** *** ***0*** *** *** * *** * *** *** *** ***
champs_mail***bf_mail***Email*** *** *** *** *** ***0***0*** *** * *** * *** *** *** ***
tabchange***formChange*** *** *** *** *** *** ***0*** *** *** *** *** *** *** ***
texte***bf_adresse***Adresse du point sur la carte*** *** *** *** ***text***1*** *** *** * *** * *** *** *** ***
map***bf_latitude***bf_longitude*** *** *** *** *** ***0***
```
**J'avais oublié de mettre une dernière ligne :**
```
tabchange***formChange*** *** *** *** *** *** ***0*** *** *** *** *** *** *** ***
```
cela n'étais pas un bug ;) `tabs` et `tabchange` sont les nouvelles syntaxes je suppose... 
la doc est donc à mettre à jour https://yeswiki.net/?ChampsPossibles

**Comment by idopisebas** [comment]
dslé pour ce temps perdu...

**Comment by J9rem** [comment]
pas de souci, je clos l'issue
