### ISSUE TITLE
Formulaire : manque une alerte fichier trop gros pour le champ Upload de fichier

### ISSUE THREAD

**Issue by paysages** [YesWiki/yeswiki#884]
Nouvelle fonctionnalité pour éviter un bug

**Description**
Dans le champ "upload de fichier" d'un formulaire, si on joint un fichier trop gros, on n'a pas d'alerte, et le formulaire crée malgré tout un lien pour accéder au fichier, alors que le fichier n'a pas pu être uploadé. Donc par la suite on clique sur le lien pensant visualiser le fichier or on obtient une erreur 404.

**Additionnal informations / Informations complémentaires**
- version : doryphore 2021-10-21-11
- url to see the problem or an example / url pour voir le probleme ou un exemple : https://wikirueauxenfants.netemedia.fr/files/MerignaC_bf_file_merignac.pdf
ou encore : https://wikirueauxenfants.netemedia.fr/files/VersUneRencontreRegionaleRueAuxEnfantsR_bf_file_merignac.pdf
(même fichier, mais dans 2 fiches créées à des dates différentes (fichier joint le même jour, ce 25/01/22)

**Comment by J9rem** [comment]
_note pour les dev : tester si le bugs existe aussi en doryphore_

**Comment by mrflos** [comment]
plan pour ce problème :
 - unifier le comportement entre le champ image et le champs fichier :
   - avoir un paramètre global dans le fichier de conf
   - avoir un paramètre max size au niveau du champ
   - si la paramètre du champ n'est pas défini, prendre le paramètre global
   - afficher une erreur en cas de non respect de la taille max lors de la saisie d'une fiche

**Comment by mrflos** [comment]
completed in #1150
