### ISSUE TITLE
les couleurs du mode edit disparaissent

### ISSUE THREAD

**Issue by FrederiqueDum** [YesWiki/yeswiki#886]
Bogue

les couleurs du mode edit disparaissent après une ligne avec une puce...

version de YesWiki : Doryphore

capture d’écran
![image](https://user-images.githubusercontent.com/98479363/151209615-0945f49a-cd13-422c-ae7e-874d6c4245bb.png)

**Comment by furax37** [comment]
c'est un pb d'affichage quand tu utilises les listes à puces, dans ce cas, les titre perdent leur coloration syntaxique

**Comment by J9rem** [comment]
Nous avions déjà évoqué ce souci https://github.com/YesWiki/yeswiki/issues/634 et nous avions conclu qu'il n'était pas important de nous en occuper.
@furax37 est-ce que nous gardons la présente issue ouverte pour nous dire d'y retravailler plus tard ou faisons-nous comme l'autre en la clôturant car le travail sur markdown prévu pour ectoplasme pourrait tout changer ?

**Comment by mrflos** [comment]
en fait c'est pas un bug mais une fonctionnalité :  on doit aller a la ligne après une liste a puce, en allant a la ligne, la coloration revient.

**Comment by furax37** [comment]
Pour moi pas grave du tout, ça peut attendre très très longtemps ;-)

**Comment by FrederiqueDum** [comment]
en effet, avec une ligne après la liste à puce, la coloration revient... 
je n'y avait pas pensé, pardon ! Je vais l'écrire quelque part dans la 
doc pour que ça ne vous revienne pas une autre fois !

Merci les amis ! :-)

Solidairement,

Frédérique Dumont
06.84.96.43.60
***@***.***

Le 27/01/2022 à 18:21, Florian a écrit :
