### ISSUE TITLE
insertion d'image effets graphiques ne semblent pas fonctionner

### ISSUE THREAD

**Issue by FrederiqueDum** [YesWiki/yeswiki#887]
Bogue

pour une insertion d'image / paramètres avancés, les effets graphiques ne semblent pas fonctionner, ils n'apparaissent pas dans la ligne ajoutée

version de YesWiki : Doryphore
captures d’écran :
![image](https://user-images.githubusercontent.com/98479363/151210473-c8027749-f958-496d-8eb1-568e4156f12f.png)
donne
![image](https://user-images.githubusercontent.com/98479363/151210715-07d76c31-3e63-488b-9042-b3223da2c04a.png)

**Comment by furax37** [comment]
l'action attach n'est pas une action comme les autres, quand tu l'utilise pour la première fois tu as des éléments basics, par contre quand tu recliques sur le crayon tu auras accès à plus de fonctionnalités. cela sera redéveloppé dans ectoplasme, la prochaine version de YW

**Comment by J9rem** [comment]
@FrederiqueDum merci de m'avoir signalé ce souci dû aux changements brutaux du css il y a une semaine.
Je vais regarder pour adapter ceci

**Comment by J9rem** [comment]
En dehors du défaut visuel le reste de l'action fonctionne, juste que les paramètres par défaut ne sont pas insérés pour éviter de surcharger le wikicode

**Comment by J9rem** [comment]
Il faudra jsute attendre la prochaine version en ligne pour voir les correctifs
