### ISSUE TITLE
Action {{attach }} paramètre Width : permettre des valeurs en pourcentage

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki#896]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Dans l'action attach, il serait utile, particulièrement pour les images, de pouvoir indiquer une valeur en % dans le paramètre lié à la largeur. Pour l'instant ce n'est possible qu'en pixel.

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/30/action-attach-parametre-width-permettre-des-valeurs-en-pourcentage
