### ISSUE TITLE
mauvais mot de passe

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#90]
quand je tape un mauvais mot de passe, j'arrive sur une page blanche, c'est quand je fais retour qu'on me dit que mon mot de passe n'est pas bon.

**Comment by gekette** [comment]
+1

**Comment by mrflos** [comment]
besoin d'avoir une url exemple pour reproduire le bug

**Comment by gekette** [comment]
Alors pour l'URL c'est ici :
http://les.couches.lavables.free.fr/wakka.php?wiki=parametresutilisateur
Le seul membre  de ce wiki est WikiAdmin, et tu verras qu'avec mauvais mot
de passe on n'a pas de message d'erreur (j'ai pas vérifié avec mauvais
utilisateur)
Si tu veux le bon mdp je te le donnerai en MP
