### ISSUE TITLE
nouvelle action {{tabs}} ?

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#908]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Créer une nouvelle action `{{tabs}}` accessible lors de l'édition des pages ou dans les champs `textelong` en mode `wikicode` pour permettre de faire comme l'action actuelle `{{nav}}` ais en mettant tout dans une seule page au lieu de devoir le découper sur plusieurs pages.

**A spécifier (cocher = validé; barré = annulé)**
 - [ ] ne pas utiliser l'action `{{section}}` mais plutôt créer une nouvelle action
 - [ ] nom des actions 
```
{{tabs class="<classe pour le rendu des titres" <paramètres-pour-l'affichage-des-boutons>}}
{{tab title="Titre 1"}}
Coontenu 1
{{end elem="tab}}
{{tab title="Titre 2"}}
Coontenu 2
{{end elem="tab}}
{{end elem="tabs"}}
```
 - [ ] création d'un service du cœur `TabsService`
 - [ ] l'action `{{tabs}}` initialise les variables internes de `TabsService`
 - [ ] l'action `{{tab}}` stocke les informations de l'onglet dans `TabsService` et démarre (via `TabsService`) un système similaire à `ob_start` pour enregistrer le flux de sortie
   - [ ] l'action `{{tab}}` peut avoir le paramètre facultatif `{{tab anchor="MonOnglet3"}}` qui permet de forcer le nom de l'ancre pour cet onglet (sinon c'est un identifiant unique basé sur le titre permettant d'avoir plusieurs fois des groupes d'onglets sur une même page)
   - [ ] l'action `{{tab}}` peut avoir le paramètre facultatif `{{tab default="1"}}` pour indiquer que c'est l'onglet par défaut
 - [ ] l'action `{{end elem="tab"}}` arrête l'enregistrement du flux de sortie (`ob_get_contents` `ob_end_clean`)`+ récupère éventuellement ce qui est dans `$output` (via `TabsService`) et le stocke dans `TabsService`
 - [ ] l'action `{{end elem="tabs"}}` :
   - [ ] : vérifie que les `ob_start` sont bien fermés
   - [ ] : fait le rendu de la barre de navigation (avec une identification unique des identifiants des onglets) (le premier onglet est considéré comme celui par défaut, sinon c'est le premier onglet ayant l'option `default="1"`
   - [ ] : fait le rendu de chaque onglet (à partir des informations précédemment stockées)
   - [ ] : nettoie les stockages internes de `TabsService` pour permettre u autre appel plus bas.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki doryphore

@mrflos @acheype c'est en lien avec notre discussion lms du 2 mars 2022.
@gatienbataille @furax37 est-ce que ce nom de nouvelle action vous convient ?

**Comment by acheype** [comment]
Ok ! Il me semble juste manquer l'attribut d'action `anchor=MonOnglet3` qui permet de définir la valeur de l'ancre qui servira à accéder à l'onglet ouvert. Par exemple, pour l'attribut ci-dessus, l'onglet généré aura ce lien : `https://monwiki.fr/?MaPage#MonOnglet3`. Et par défaut, j'imagine que ce sera le premier onglet qui sera ouvert, mais est-ce qu'on va plus loin et qu'on permet d'ouvrir par défaut l'onglet qui a l'attribut d'action `default` quand il est défini dans un des onglets ?

**Comment by J9rem** [comment]
Très bonnes idées @acheype on garde dans la spec. donc

**Comment by acheype** [comment]
Je reviens sur ce que j'ai dis et l'adapte car :

- je pensais que bootstrap gérait directement les ancres qu'il mets dans les liens mais il faut faire un hack en javascript pour qu'il les prenne en compte
- une ancre dans l'url ne permettrait pas de ne sélectionner qu'un onglet parmi une série d'onglet (et il peut y avoir plusieurs séries d'onglets si l'action est utilisée plusieurs fois)

ainsi je propose plutôt d'avoir : 

- l'argument `urlparam` pour l'action tabs : `{{tabs urlparam="tab1" ...}}`
- l'argument `urlselected` pour l'action tab : `{{tab urlselected="titre1"}}`

Un exemple d'url pour sélectionner plusieurs onglets de différents groupes à la fois serait : `https://monwiki.fr/?MaPage?tab1=titre1&monautretab=monautretitre`

Sinon pour `urlselected` on pourrait s'en passer et se baser sur `title` en le transformant en slug avec la librairie ajoutée par @mrflos.

**Comment by J9rem** [comment]
@acheype je te laisse rajouter ou barrer les lignes en question dans le commentaire de tête (ne pas supprimer de lignes pour assurer le suivi)
Ca me sera plus facile pour  assurer le suivi.
Il faut juste nous assurer que si la case est cochée, c'est que nous sommes d'accord pour ne pas prendre en compte la ligne barrée ou pour valider la ligne non barrée correspondante
