### ISSUE TITLE
Souci avec le rendu bloc-card

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#913]
Bug / Bogue

**Description**
Sur un wiki doryphore 4.1.4 avec margot 1.0.1 je rencontre pas mal de problème avec le rendu bloc
 - pas de mise à jour du code à placer dans le page lorsque  j'effectue des choix via l'interface
 - voire parfois un retour à zéro (colonnes perdues, height map... 
 - aussi sur le rendu carte mode dynamic, la version en popup bloque le retour à la carte, y a un voile blanc qui se place sur la page lors de l'affichage du popup mais qui bloque toute action ensuite

visions possibles ici https://cooptic.be/plateformegal/?ActeurS (attention c'est un wiki qui vit ;-) 

merci !

**Comment by gatienbataille** [comment]
je complète avec le souci du template "qui tourne" (quand c'est en dynamic)
voir ici https://cooptic.be/pratiques-transition/?PratiqueS (doryphore 4.1.4)
ça semble lié à une facette qui "veut" pas (car si je l'enlève, ça tourne plus)

**Comment by seballot** [comment]
Salut Gatien !

J'ai testé tes liens et chez moi tout marche correctement

Est ce que tu pourrais faire des vidéos stp? tu utilises quel navigateur?

**Comment by J9rem** [comment]
@gatienbataille est-ce que les soucis sont présents en version 4.2.0 ?

**Comment by gatienbataille** [comment]
@J9rem c'est ok ça fonctionne / merci !
