### ISSUE TITLE
soupçon d'erreur page blanche lors de maj vers la dernière version cerco

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki#914]
Bug / Bogue
**Description**
en mettant à jour des vieux wiki sous cerco vers la dernière version AVANT de tenter une migration vers doryphore
je suis tombé deux fois sur un écran blanc et l'impossibilité de travailler sur mon wiki (et donc de tenter la suite vers doryphore)
j'ai du passer par une install ftp classique (pas toujours concluante...) 

du coup j'ai plus de wiki test à fournir
je cherche à recréer le cas pour le mettre ici (le wiki page blanche)

**Comment by J9rem** [comment]
@gatienbataille je clos cette issue car elle ne permet pas de reproduire le bug (il manque des informations sur la version de l'ancienne version cercopitheque).

Il est connu qu'il y ait des écrans blancs lors des mises à jour depuis pratiquement toutes les versions cercopitheques avant mars 2021 et pratiquement toutes les versions doryphore avant mars 2021 (et ce quelque soit la version visée à l'arrivée).
En effet, le bug de l'écran blanc lors des mises à jour n'est pas dû à ce qu'il y a dans les nouvelles versions mais dans ce qui est déjà installé avec des vieilles versions (donc impossible à corriger avant de faire la mise à jour).

Pour les versions cercopitheque et doryphore après mars 2021, il ne devrait pas y avoir beaucoup d'écrans blancs (sauf quelques cas particuliers corrigés depuis)
