### ISSUE TITLE
Adaptation à la langue Persane

### ISSUE THREAD

**Issue by magalied** [YesWiki/yeswiki#915]
J'ai réalisé une page de test pour la rédaction en persan pour mieux visualiser : https://tuilage.org/?Pagetest1
1/ il manque la fonctionnalité pour écrire de droite à gauche
2/ certains éléments de ponctuation réagissent différemment : 
- le point d'interrogation et le point-virgule réagissent correctement
- le point, le point d'exclamation, la virgule et les 2 points réagissent de 2 manières différentes
* soit le paragraphe se poursuit. Dans ce cas, l'élément de ponctuation se place à droite quand on le saisit (alors qu'il devrait être à gauche) et dès que l'on poursuit la rédaction, l'élément se positionne automatiquement à la bonne place (c'est-à-dire à gauche).
* soit le paragraphe s'arrête et il y a un retour à la ligne. Dès que l'on saisit l'élément de ponctuation il se place à droite (comme dans la situation précédente) mais le fait du retour à la ligne, cela ancre l'élément de ponctuation à droite.
3/ la mise en forme est affectée avec la même logique, mais ne se constate qu'en mode édition (cf exemple surla page test) : en mode consultation, ça apparait correctement

**Comment by mrflos** [comment]
Bonjour,
Je pense que ca se regle avec du css, je me suis permis de rajouter du code dans la page https://tuilage.org/?Pagetest1

```css
html {
  direction: rtl;
}
```
