### ISSUE TITLE
Intitulé pour "afficher un formulaire de création de fiche"

### ISSUE THREAD

**Issue by magalied** [YesWiki/yeswiki#916]
Contexte : 
Dans le composant "Afficher un formulaire de création de fiche", dans les paramètres avancées, il est possible de renvoyer l'utilisateur vers une page du wiki après la création d'une fiche.

Proposition d'amélioration : 
En complément de "Nom de la page de ce wiki à afficher après création d'une fiche", ajouter "précédé du ?" ou indiquer l'url de la page wiki.

**Comment by mrflos** [comment]
Hello, merci pour ce retour, je pense qu'on devrait plutot faire en sorte que les NomWiki soient reconnus, sans mettre de ? devant

**Comment by seballot** [comment]
Ca a été corrigé, et il y maintenant de l'autocompletion pour choisir la page
