### ISSUE TITLE
petit pb affichage formulaire bazar

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#92]
Lorsque je fais des formulaire dans bazar, quand je retourne sur l'interface de gestion des formulaire, l'icone "feuille" se cache derrière le texte. pas très grave.

**Comment by furax37** [comment]
![pbaffichagelisteformulaire](https://f.cloud.github.com/assets/1269848/2124559/7f3312a0-9241-11e3-8df1-3b4c1ac05115.png)

**Comment by mrflos** [comment]
corrigé

**Comment by gekette** [comment]
J'ai la même chose si j'oublie de renseigner la catégorie du formulaire. Il y avait un vrai bug, ou c'est la même chose ? (Lila alias gekette)
