### ISSUE TITLE
Ajout extension pour statistiques avec Matomo

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [YesWiki/yeswiki#922]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Bonjour,
Récemment la CNIL a émis un avis de non-confirmité RGPD à Google analytics.
Est-ce qu'il serait possible de développer une extension permettant d'avoir des statistiques avec Matomo par exemple ?
https://fr.matomo.org/

**Additionnal informations / Informations complémentaires**
- Dans la ferme

**Comment by seballot** [comment]
Salut @Jacques-Olivier-Farcy !

Il n'y a pas besoin d'extension, tu peux déjà utiliser Matomo dans un YesWiki, il te suffit de copier le code fournit par Matomo et l'inscruster dans une page telle que PageMenuHaut (qui est chargé sur toutes les pages)
