### ISSUE TITLE
Problème d'affichage de variable de champs d'un formulaire du Bazar

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [YesWiki/yeswiki#923]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Bonjour,

Dans Bazar lorsque j'ajoute un champs dynamique pour l'affichage de la fiche d'un membre, par exemple {{bf_code_postal}} de la fiche d'un membre.
Si j'enlève ce champs dans mon formulaire, puis que j'enlève également ce champs dans la partie Titre automatique, il s'affiche {{bf_code_postal}} sur la fiche.

Je me retrouve du coup dans le trombinoscope avec des fiches de membre affichant la variable (voir capture)
J'utilise un Yes Wiki dans la ferme.

**Additionnal informations / Informations complémentaires**
![image](https://user-images.githubusercontent.com/19731340/161384007-1bb11ca2-8bf5-4100-8963-299541fcaafd.png)

**Comment by J9rem** [comment]
Bonjour @Jacques-Olivier-Farcy ,

est-ce que le souci apparait pour les fiches qui ont été modifiée après que tu es changé le formulaire ?
est-ce que le souci apparait pour les fiches qui ont été modifiées avant les changements dans le formulaire ?

En effet, il me semble que le souci ne devrait apparaître que pour les fiches qui auraient été modifiées pendant que tu modifiez le formulaire (entre l'étape 1 et l'étape 2).
Si c'est le cas, c'est un comportement qui correspond à ce qui est attendu en fait.
(Il faudrait limiter les changements de formulaires avec des modifications des fiches pendant les changements du formulaire sur `bf_titre`)

**Comment by Jacques-Olivier-Farcy** [comment]
Bonjour Jérémy,

Oui cela est apparu après des changements dans le formulaire.
Je comprends mieux le fonctionnement du coup.
Je vais procéder autrement pour la gestion des rôles en créant un autre formulaire
