### ISSUE TITLE
Suppression des données personnelles RGPD ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [YesWiki/yeswiki#926]
**Nouvelle fonctionnalité**

**Description**
Ajouter la possibilité pour une personne authentifiée de supprimer toutes ces données personnelles la concernant dans Yes Wiki afin d'avoir une compatibilité RGPD (Une personne devrait être je crois en mesure de pouvoir le faire par un traitement automatisé).

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/28/permettre-a-un-utilisateur-de-supprimer-toutes-ses-donnees-rgpd
