### ISSUE TITLE
Bug sur le champ datefilter="futur"

### ISSUE THREAD

**Issue by FleurianeH** [YesWiki/yeswiki#931]
Bug sur le champ datefilter="futur dans l'affichage d'un formulaire Bazar

**Description**
En utilisant un template carto, le champ date=future ne fonctionne pas, des fiches avec des dates passées s'affichent quand même. Le formulaire a été testé avec d'autres templates installés de base dans wiki et des templates custom, le problème persiste.

**Additionnal informations / Informations complémentaires**
 version de YesWiki 4.1.5
 url pour voir le probleme ou un exemple : https://colibris-groupeslocaux.org/?AgenDaCarte

**Comment by J9rem** [comment]
@FleurianeH merci pour cette mise en évidence.
Il semblerait que les évènements en question n'aient pas de date de fin.

Le comportement du code est de considérer que ces évènements ne s'arrêtent pas (donc ils sont dans le futur).
Ceci ne correspond pas à l'affichage de type `calendar` qui suppose dans ce cas que l'évènement s'arrête par défaut à minuit du jour de début de l'évènement.

Je serais partisan alors de retirer dans les résultats 'futur', les évènements qui commencent dans le passé et n'ont pas de date de fin.
@FleurianeH confirmes-tu que ce que propose correspond à ce que tu verrais comme correction du bug ?

**Comment by FleurianeH** [comment]
Oui, tout à fait, ça me va très bien ! Merci :)
