### ISSUE TITLE
Pas de controle des droits sur les champs lors de l'envoi d'une fiche par mail

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#938]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue
Version Doryphore 4.1.5.

**Description**
Lorsqu'une fiche est envoyée par mail (à l'adresse indiquée dans la fiche) tout le contenu de la fiche est présent dans le mail y compris les champs dont la lecture est réservée à un groupe admin.

**Comment by J9rem** [comment]
Salut @MelanieMichel ,

pour comprendre le souci, j'ai besoin d'un peu plus de détails sur la façon d'envoyé la fiche :
 - est-ce en modifiant la fiche en étant le propriétaire de la fiche non admin ?
 - est-ce en modifiant la fiche en étant un administrateur ?
 - est-ce en faisant le handler `/mail` sans paramètre à la fin de l'adresse d'une fiche en étant ni propriétaire, ni admin ?
 - est-ce en faisant le handler `/mail` sans paramètre à la fin de l'adresse d'une fiche en étant propriétaire, non admin ?
 - est-ce en faisant le handler `/mail` sans paramètre à la fin de l'adresse d'une fiche en admin ?

Est-ce qu'en testant les différentes configurations concernées, le contenu reçu par e-mail est différent ?

Est-ce que les champs concernées ont bien droits de lecture `@admins` ?

**Comment by MelanieMichel** [comment]
Salut @J9rem . 
En effet le contexte c'est une modification de fiche en étant admin. 
La fiche a été envoyée au mail renseigné dans bf_mail
Les champs concernés ont des droits de lecture @groupeX
mais la personne contact dont le mail est renseigné ne fait pas partie du groupeX

**Comment by J9rem** [comment]
OK merci pour le retour.
Je vais regarder.
(Normalement, j'avais résolu ce souci, mais bon, il y a eu des trous dans la raquette.)

**Comment by J9rem** [comment]
@MelanieMichel est-ce que tu pourrais m'envoyer en message privé un lien vers le site qui plante ?
Je pourrai ainsi reproduire la configuration du site sur mes sites de tests pour réussir à la corriger.
