### ISSUE TITLE
filtercolsize limité à 10

### ISSUE THREAD

**Issue by MelanieMichel** [YesWiki/yeswiki#940]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Dans affichage bazar liste, la largeur des facettes n'est pas correctement prise en compte si filtercolsize=12
Cela permettait d'afficher les filtres en pleine largeur au dessus du formulaire

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki 4.2.1.
- url to see the problem or an example / url pour voir le probleme ou un exemple  https://pratic-coop.fr/doryphore/?Test421
- screenshot / capture d’écran
- logs

**Comment by J9rem** [comment]
fixed by https://github.com/YesWiki/yeswiki/commit/a351aa5c0d7a1550b84eaa0973acc6cb652d836e
