### ISSUE TITLE
"Légende" quand un champ pour la couleur et/ou une icone est utilisé sur un rendu bazar

### ISSUE THREAD

**Issue by EdmondAgate** [YesWiki/yeswiki#942]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
 Nouvelle fonctionnalité

**Description**
La possibilité d'avoir des couleurs ou des icones en fonction des réponses dans un champ dans un rendu liste,carte, tableau est super. Pour que ça soit au top de la pop il ne manquerait que la légende, qui pourrait par exemple figurer dans les facettes ?

**Comment by seballot** [comment]
salut @EdmondAgate 

Désolé je ne comprends pas très bien, tu pourrais faire une capture d'écran ou un petit dessin pour expliquer? et faire cette proposition sur https://priorites.yeswiki.net?

Merci !

**Comment by EdmondAgate** [comment]
ca bien été traduit ici https://priorites.yeswiki.net/posts/40/facette-visualiser-la-couleur-icone-dans-la-facette-elle-meme-comme-une-legende donc pas de souci
