### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by pierreozoux** [YesWiki/yeswiki#945]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Hi!

Do you plan to support Postgres?

Thanks!

**Comment by mrflos** [comment]
Hi,
The long term plan for yeswiki is to make it a [12factor app](https://12factor.net/), and for the next major release (ectoplasme, sem. version 5.0 ), we will move our database layer to PDO and support Postgresql (and SQLite).  

So it's planned, but i think nothing will be ready before 2023, we are a small dev community for now.

FYI it tooks us 7 year to move from yeswiki cercopitheque version (3.0) to doryphore (4.0), we espect to be faster from now on but we have no release date schedule planified for now.

**Comment by seballot** [comment]
Closing, cause this goal is far away :)
