### ISSUE TITLE
S3 support

### ISSUE THREAD

**Issue by pierreozoux** [YesWiki/yeswiki#946]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
 Hi!

Do you plan to support S3?

Thanks!

**Comment by mrflos** [comment]
as indicated in #945 , the long term plan for yeswiki is to make it a [12factor app](https://12factor.net/), so it's on the list, but not as sure than postgresql support.

We haven't discussed the technical options in php for this now (i'm just aware of https://flysystem.thephpleague.com/docs/ ), but in theory, the amount of folders in yeswiki that containts specific data is quite small and identified, so it should be doable, the question is when, and probably after the next major release.

**Comment by pierreozoux** [comment]
Yes, the library you mentionned seems like the way to go,

Thanks a lot for the answers :)

The project is just beginning, so that's why I'm asking questions, I'm not even sure we'll host it.
But I'll also ask if they have a bit of budget to fund this kind of features.
And then, if they do, I'll come back to ask if I could fund such dev? If yes, what would be the conditions, but then we can also move this out of GH.
