### ISSUE TITLE
Warning: Input variables exceeded 1000

### ISSUE THREAD

**Issue by mbrasebin** [YesWiki/yeswiki#947]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
En voulant modifier un formulaire composé de 97 champs pointant vers des listes + quelques conditionnalité, j'ai eu l'erreur PHP - sur XAMPP : 

Warning: Input variables exceeded 1000

Cela bloque la sauvegarde du formulaire, en modifiant la variable max_input_vars, j'arrive à contourner le bug, mais je ne suis pas sûr de pouvoir configurer cela comme il faut sur mon serveur en ligne. Est-ce un bug connu ? Est-ce qu'il y a une solution de contournement ?

Merci d'avance

**Additionnal informations / Informations complémentaires**
-  version de YesWiki : doryphore 4.1.5

**Comment by J9rem** [comment]
Salut @mbrasebin ,

j'ai l'impression que la solution de `max_input_vars` dans `php.ini` est la bonne.

Personnellement, je ne dirais pas que c'est un bug YesWiki car ça concerne la configuration `php.ini` sur le serveur concerné.

Est-ce une bonne idée d'avoir un si long formulaire en termes d'interface utilisateur ? les deux points de vue (oui/non) se valent mais dans le cadre de YesWiki fonctionnant en `doryphore` en mode soumission du formulaire en une seule fois, les formulaires trop long peuvent outrepasser les contraintes de configuration des serveurs.

Pour avoir quelque chose de plus robuste pour ces contraintes et de plus agréable pour les utilisateurs, il faudrait avoir un système de soumission de formulaire an AJAX permettant de faire plusieurs parties, etc, ... ça n'est pas la solution actuelle dans YesWiki. 
Il peut être possible de proposer cette idée de nouveauté pour les prochaines grandes versions de YesWiki (ectoplasme ou flibustier). Je te laisse @mbrasebin porter cette proposition si elle correspond à ton besoin (a priori, je ne suis pas pour cette nouveauté, mais si personne ne l'a met dans les nouvelles idées, nous ne risquons pas de l'étudier et d'argumenter autour de son intérêt ou non, .... ;-))

**Comment by mbrasebin** [comment]
Salut @J9rem 

oui, je me questionnais plus sur la quantité de variables qui semblait beaucoup plus importantes que celles qui devaient remonter.

Non, je ne suis pas sûr que ça intéresse beaucoup de monde comme fonctionnalité, mais au moins cet échange laissera une trace si d'autres utilisateurs ont cette limitation :). La solution de changer le paramètre dans le php.ini est complètement convenable. J'avais juste peur qu'il faille repousser d'avantage la valeur si je venais ajouter un champ ou 2 (mais ça n'a pas l'air d'être le cas).

Le ticket peut être clos, à bientôt

**Comment by J9rem** [comment]
>oui, je me questionnais plus sur la quantité de variables qui semblait beaucoup plus importantes que celles qui devaient remonter.

le point est important en effet, dans le cadre de l'usage de nombreuses listes, si toutes les cases sont cochées à chaque fois, alors il y a une valeur de type 'input' pour chaque case coché, il est alors possible de dépasser 1000 rapidement.

Toutefois, l'usage de la saisie par `tags` pour les checkbox permet d'éviter ceci mais il n'y a alors plus possibilité de faire 'sélectionner tout', je ne sais pas si ça répond à ta demande.
(et en effet, si la saisie de formulaire était en ajax, il n'y aurait alors pas autant d'`input` à envoyer pour enregistrer le formulaire)

A bientôt pour d'autres échanges (n'hésite pas @mbrasebin à réouvrir le ticket si la quantité de variables n'est pas due à un 'sélectionner tout' dans une liste à plus de 1000 éléments)
