### ISSUE TITLE
style par défaut

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#95]
quand on assigne un style par défaut dans wakka.config.php, ça fonctionne bien sauf dans les fiches bazar créées... dommage

**Comment by mrflos** [comment]
J'ai pas compris, tu veux dire que le look des fiches bazar ne correspond pas au thème choisi?
Aurais tu une url?
Ou souhaiterais tu personaliser l'apparence des fiches bazar?

**Comment by furax37** [comment]
J'ai pas compris, tu veux dire que le look des fiches bazar ne correspond pas au thème choisi?
oui

**Comment by gekette** [comment]
même problème mais pas seulement pour les fiches bazar, pour toute nouvelle page. http://les.couches.lavables.free.fr/wakka.php?wiki=Galerie4
le wakka config définit bien les styles par défauts, j'ai vérifié que le thème est bien à sa place et pourtant il ne les trouve pas. ( et impossible d'utiliser hide action template pour cacher le pb parce que besoin de plusieurs templates)

**Comment by mrflos** [comment]
Corrigé depuis un moment
