### ISSUE TITLE
start with local docker-compose out of the box

### ISSUE THREAD

**Issue by simonLouvet** [YesWiki/yeswiki#950]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
make up and docker-compose are not ready for out of the box start

**Description**
- php and javascript vendor have to build out of docker needing composer and npm to be installed in the host.
- installer can't create wakka.config.js in mounted volume because www-data user don't have permission.
- installation don't use environnent variable in install screen providing confusion. wakka.config.js contains data base connetion information and environnent variables are not used.

**Comment by simonLouvet** [comment]
@J9rem @srosset81 @mrflos  j'ai une PR à proposé pour résoudre cette issue. Pouvez vous me mettre contributeurs svp.

**Comment by mrflos** [comment]
Hi @simonLouvet Je t'ai invité à rejoindre la team YesWiki, welcome aboard et content de te voir contribuer à YesWiki, ca fait très plaisir!

**Comment by seballot** [comment]
Coucou !

Perso je n'aime pas trop lancer des commandes dans le dockerfile ou le docker-compose (ici make install), car si elles plantent, le conteneur ne se lance pas, et du coup faut utiliser un entrypoint spécifique pour lancer le conteneur sans ses commandes pour pouvoir s'y connecter et résoudre le problème

mais bon je m'oppose pas à ce changement !

par contre pourquoi lancer un chmod à chaque lancement du container?
et le apache2-foreground il sert à quoi? apache est déjà automatiquement lancé non?

**Comment by simonLouvet** [comment]
@seballot 

"Perso je n'aime pas trop lancer des commandes dans le dockerfile ou le docker-compose (ici make install), car si elles plantent, le conteneur ne se lance pas, et du coup faut utiliser un entrypoint spécifique pour lancer le conteneur sans ses commandes pour pouvoir s'y connecter et résoudre le problème"

Une commande est toujours lancée qu'elle soit fourni par le dockerfile ou le docker-compose. Je ne comprends donc pas bien ton commentaire. Pour debugger un lancement de container on peut logger ```docker-compose logs -f <container>``` ou rentrer dans le container pour aller plus loin ```docker-compose exec <container> sh``` (ou bash). 

"par contre pourquoi lancer un chmod à chaque lancement du container?"

L’installer (première connexion à localhost) de yeswikki à besoin de créer wakka.config.php sur ```/var/www/html``` qui est un volume branché sur la racine du projet ```.:/var/www/html```. le montage de volume fait que le user propriétaire de ```/var/www/html```  est ```root``` alors que apache utilise ```www-data```. Sans changer les droits après le montage du volume (donc obligatoirement dans le docker-compose) l'installer plante.

"et le apache2-foreground il sert à quoi? "

Une commande dans le docker-compose remplace la commande du dockerfile.  Il n'y a pas de commande dans le dockerfile de yeswiki donc c'est le dockerfile sur lequel il est basé ```lavoweb/php-7.3:composer``` qui fait foi. ```lavoweb/php-7.3:composer``` contient la commande  ```CMD ["apache2-foreground"]``` à la ligne 31. la commande dans le docker-compose remplace cette commande en rajoutent les étape nécessaire à un lancement out of the box. Il reste necessaire de lancer apache à la fin des commande préliminaire.

**Comment by J9rem** [comment]
Tout est bon pou moi à la lecture du code (je n'ai pas testé).
Merci @simonLouvet pour ce debug.

Est-ce que ça fonctionne bien ensuite la configuration du site ?
_Je pense que nous pouvons clore la présente issue_

**Comment by srosset81** [comment]
> Une commande est toujours lancée qu'elle soit fourni par le dockerfile ou le docker-compose. Je ne comprends donc pas bien ton commentaire. Pour debugger un lancement de container on peut logger `docker-compose logs -f <container>` ou rentrer dans le container pour aller plus loin `docker-compose exec <container> sh` (ou bash).

Si la commande a échoué au lancement, le container Docker ne sera pas lancé et `docker-compose exec` ne marchera pas.
