### ISSUE TITLE
Pas d'affichage TOC ou TOCJS en Markdown 

### ISSUE THREAD

**Issue by McFlyPartages** [YesWiki/yeswiki#958]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Quand nous utilisons la syntaxe Markdown, les titres entre les balises Markdown ne s'affiche pas dans les TOC/TOCJS

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki 
V4.2.1
- url to see the problem or an example / url pour voir le problème ou un exemple
https://wiki.hacf.fr/?PremiereConfiguration

**Comment by seballot** [comment]
Salut @McFlyPartages, le lien ne fonctionne plus, est ce que tu en as un nouveau? ou des captures d'écrans?

**Comment by McFlyPartages** [comment]
Bonjour,

Non le lien ne fonctionne pljs carnous sommes passé sur un autre CMS. Désolé
