### ISSUE TITLE
Proposition : validation des emails pour création de compte

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#961]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Suite à des échanges avec @VeveQNV (cf. https://github.com/YesWiki/yeswiki/pull/935#issuecomment-1179499554), il apparaît que la création de comptes utilisateurs peut être améliorée avec une validation de l'e-mail.

La PR #935 a été fusionnée au préalable afin de ne pas modifier en même des fichiers en cours de suppression.

J'ouvre cette issue pour recueillir les échanges écrits autour de cette nouvelle fonctionnalité, en attendant la concertation orale ou en présence autour de celle-ci.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki future `doryphore 4.3.0`

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/33/validation-par-email-pour-creation-de-compte
