### ISSUE TITLE
Changer le format des cookies d'authentification

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#962]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
La sauvegarde des données d'authentification des utilisateurs dans les cookies utilise un système un peu ancien (comme nous l'a fait remarqué @VeveQNV).
J'ouvre cette issue pour garder une trace qu'il nous faudrait l'améliorer e commençant par spécifier le format du nouveau cookie.

Nous pouvons recueillir ici les écrits concernant cette concertation en attendant le temps de concertation orale / en présence.

Le temps de spécification a dû attendre la fusion de #935 car cette PR a fait un gros refactor de ce qui touche à l'authentification.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki pour après `doryphore 4.5.0`

**Comment by VeveQNV** [comment]
Bonsoir à tous, de retour, je vais reprendre mes développements perso et je pense également utile que nous communiquions rapidement afin de faciliter des intégrations possibles de mes développements dans le nouveau framework. 

A priori concernant le cookie il me semble que c'est l'identifiant de session que nous devons sauvegarder dans le cookie : session_id. C'est lui qui permet de restaurer la session. Cet identifiant doit être mémorisé dans la bdd.

On en reparle bientot.

A bientot 

Yves

**Comment by VeveQNV** [comment]
https://www.php.net/manual/fr/function.session-id.php

**Comment by J9rem** [comment]
@VeveQNV 
> je pense également utile que nous communiquions rapidement

je t'ai envoyé un message via framateam pour convenir d'un RDV. L'as-tu reçu ?

**Comment by J9rem** [comment]
Après notre échange de jeudi, effectivement la proposition de @VeveQNV d'utiliser les données de `$_SESSION` peut être une solution temporaire mais un peu mieux que de stocker le mot de passe chiffré dans les cookies.
Pour y arriver:
 - il faudra s'assurer de réécrire le cookie de session en mode permanent pour qu'il ne soit pas effacé après la fin de la session chez l'usager MAIS ceci ne peut plus se faire via [`session_cache_expire`](https://www.php.net/manual/en/function.session-cache-expire.php) une fois que la session est démarrée et il faudra sûrement faire 
```php
session_start();
// ...
$sessionParams = session_get_cookie_params();
$newParams= array_filter($sessionParams,function ($v,$k){
  return in_array($k,['path','domain','secure','httponly','samesite']);
});
$newParams['expires']= time()+60*60*($remember ? 24*365 : 1);
setcookie(session_name(),session_id(),$sessionParams);
```

MAIS il faudra un jour changer cette façon de faire car la documentation de php sur session est explicite:
 - nous serons dépendant du paramètre de `php.ini` `session.gc_maxlifetime` qui peut être réécrit par la plus petite valeur sur les serveurs partagés : https://www.php.net/manual/fr/session.configuration.php#ini.session.gc-maxlifetime
 - >Les développeurs **ne doivent pas utiliser d'identifiants de session avec une grande durée de vie pour l'auto-identification**, car cela accroit le risque d'utiliser des sessions volées. Une fonctionnalité d'auto-identification doit être implémenté par le développeur.
    
   (source : https://www.php.net/manual/fr/features.session.security.management.php#features.session.security.management.session-and-autologin)

Donc je pense que oui dans un premier temps, on peut se baser sur le cookie de session pour que ce soit moins sale mais qu'à termes il faudra passer par un truc plus solide comme https://github.com/symfony/security/blob/4.4/Core/Authentication/AuthenticationProviderManager.php par exemple

Qu'en penses-tu @mrflos ?
