### ISSUE TITLE
Séparateur des milliers

### ISSUE THREAD

**Issue by EdmondAgate** [YesWiki/yeswiki#965]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Nouvelle fonctionnalité : avoir la possibilité d'un séparateur de millier pour les champs numériques (dans les fiches, affichage tableau etc.)

**Description**
Pour une meilleure lisibilité (notamment des montants financiers) la possibilité (ou systématisation) d'un séparateur des milliers serait utile

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/27/ameliorer-laffichage-des-nombres
