### ISSUE TITLE
 barre de défilement horizontal pour les tableaux en flottant

### ISSUE THREAD

**Issue by EdmondAgate** [YesWiki/yeswiki#966]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité : avoir un barre de défilement horizontal pour les tableaux en flottant

**Description**
Explain the bug or the feature / expliquer le bogue ou la fonctionnalité demandée
Le template tableau est très pratique, cependant quand le tableau est large (nombreuses colonnes) et long (nombreuses lignes) cela demande de beaucoup scroller pour atteindre la barre de défilement horizontale. Une barre flotante serait très pratique !

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/26/template-teableau-barre-de-defilement-horizontal-flottante
