### ISSUE TITLE
estomper les fonds sous les textes

### ISSUE THREAD

**Issue by furax37** [YesWiki/yeswiki#97]
En fonction des images de fond utilisés, les textes deviennent illisibles. Il y avait un effet de transparence dans le temps qui permettait d'estomper le fond, afin de permettre une meilleure lisibilité.
sur bootstrap, je n'ai pas vu sur yeswiki

**Comment by mrflos** [comment]
Je propose de clôturer ce bug vieux de 5 ans, et si besoin de prendre 15 min pour documenter quelque part comment faire une estompe en css
