### ISSUE TITLE
Bad parameter used for userMustBeAddedToGroup call in userfield.php

### ISSUE THREAD

**Issue by VeveQNV** [YesWiki/yeswiki#970]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**

The call userMustBeAddedToGroup line 333 of userfield.php is invalid : bad parameter

if ($this->userMustBeAddedToGroup($wikiName, $groupName, $forceGroupCreation, $wiki, $existingsGroups)) 

The $wiki parameter should be replaced by $userManager

- version of YesWiki / version de YesWiki : doryphore-dev

**Comment by J9rem** [comment]
@VeveQNV je pense que tu n'as pas étudié le fonctionnement de UserField et donc tu aurais compris que cette méthode est une méthode interne à UserField.

Toutefois, il pourrait manquer des commentaires pour en expliquer son fonctionnement.
Aurais-tu des propositions à faire pour l'amélioration des annotations de cette méthode ?

**Comment by VeveQNV** [comment]
@J9rem la fonction s'attend à recevoir un usermanager et elle recoit un 
wiki. C'est une erreur : tu as correctement fait l'appel quelques lignes 
plus haut. Ca plante tout betement parce que le parametre attendu n'est 
pas le bon. Il faut changer l'appel. Je ne comprend pas le lien avec mon 
étude sur le fonctionnement de UserField. Qu'est ce que tu entends par la ?

Le 24/07/2022 à 09:29, Jérémy Dufraisse a écrit :

**Comment by J9rem** [comment]
Effectivement, tu as pointé un bug, MERCI je le corrigerai par un commit en début de semaine.

Je suis désolé ce matin, j'avais mal compris l'issue (et surtout je l'avais mal lue). Je pense qu'il faut que j'arrête les messages le dimanche matin :wink:

_J'avais supprimé mon précédent message qui ne correspondait pas à l'issue mais je n'ai pas eu la possibilité d'apporter un message correctif que celui ci avant ce soir_

**Comment by VeveQNV** [comment]
Pas de soucis, ca arrive. Merci de ta réponse. Bonne fin de dimanche.

Le 24/07/2022 à 20:34, Jérémy Dufraisse a écrit :
