### ISSUE TITLE
Chargement long des pages avec base distante

### ISSUE THREAD

**Issue by mbrasebin** [YesWiki/yeswiki#975]
Bonjour

New feature / Nouvelle fonctionnalité

Nous essayons de mettre en place un environnement de développement collaboratif pour les projets nécessitant du développement de templates, de styles, etc histoire d'éviter les copier/coller via FTP sur un serveur (avec le risque d'écraser les fichiers des collègues).

Pour faire cela, nous avons opté pour la mise en place d'une base de données sur un serveur (afin de partager les modifications que l'on ferait dans les pages du wiki) et d'installer les fichiers web du wiki en local pour développer dessus (avec partage du code via un git). 

Sur le principe, cela fonctionne, mais j'ai noté que le temps de chargement des pages était multiplié par 4 avec ce mode de fonctionnement alors que si l'on rapatrie les fichiers web sur le serveur hébergeant la base, les performances sont bonnes.

En faisant un profilage sur les performance, il passe un très long temps à charger la page en elle-même
Requête https://nom_domaine/nom_wiki/?nom_page

Est-ce que c'est un comportement que vous avez observé ? Est-ce qu'il y a une configuration (côté php ou wiki ?) qui permet d'accélérer le chargement des pages dans ce mode de fonctionnement ? 

Merci pour vos retours

Mickaël Brasebin

**Comment by seballot** [comment]
Salut

>  Est-ce qu'il y a une configuration (côté php ou wiki ?) qui permet d'accélérer le chargement des pages dans ce mode de fonctionnement ?

Non je ne pense pas

C'est bizarre qu'il y ait une telle dégradation, mais je ne pense pas que ce soit lié à yeswiki. Je ferme donc l'issue

**Comment by mbrasebin** [comment]
Bonjour, 

je me permets de réouvrir le ticket que j'avais un peu oublié, mais le sujet est revenu sur la table cette semaine :) 

Le problème de lenteur peut s'illustrer avec ce site là : https://www.observatoiredesfriches73.fr/?PagePrincipale&debug 

Si on regarde les logs, on peut voir sur la page d'accueil : 

- en ligne sur la page d'accueil on retrouve : 

![image](https://github.com/YesWiki/yeswiki/assets/10995312/f1095977-bfaf-4507-a0d6-b50872b514db)

- en local sur cette même page : 

![image](https://github.com/YesWiki/yeswiki/assets/10995312/5bd47c12-a8b5-4aac-8fb7-7d801fa188c9)
Les 2 sites attaquent la même base et on le même cache

Sur une application Lychee qu'on développe sur le même principe, on ne note pas les mêmes écarts de chargement, mais cela doit être du au nombre de requêtes qui est très élevés pour YesWiki.

Peut être y  a t il des paramétrages PHP plus performants ? Ou alors, c'est juste le temps de latence normal pour la création de la connexion + exécution de plus de 150 requêtes SQL. 

Je me demandais si d'autres personnes avaient le même problème, en tout cas pour nos développements, c'est plus pratique de passer par du dev local avant de pousser le site en ligne que de tester page après page sur le site en ligne.

Merci d'avance si vous avez un retour d'XP

**Comment by mrflos** [comment]
Je pense que c'est "normal", on n'a pas du bien optimiser entre les requêtes SQL, je me demande s'il ne refais pas une connexion entre chaque requête, donc forcement, dans un contexte ou la base est distante, ca pique...

On doit aussi réduire le nombre de requêtes sql par chargement de page, pour sur... 150 c'est bien trop...

Ok pour garder l'issue ouverte et faire des tests approfondis a l'occasion.

Après pour du dev local, ca peut être bien d'avoir la bdd locale aussi, non, juste histoire de ne pas casser la base de prod distante?

**Comment by mbrasebin** [comment]
Super, merci :) 

On a une base de données dev et une prod sur le même serveur distant :), on a besoin de la base distante car on peut être plusieurs à modifier le code

**Comment by seballot** [comment]
J'ai crée une issue dédiée, plus explicite sur ce qu'il faut faire #1126 

Après c'est un vaste sujet cette optimization !
