### ISSUE TITLE
Facing issue with docker installation

### ISSUE THREAD

**Issue by AkshayraviC09YC47** [YesWiki/yeswiki#977]
Hello maintainer, im not able to install yeswiki via docker , its showing db error
<img width="1440" alt="Screenshot 2022-07-29 at 10 17 01 PM" src="https://user-images.githubusercontent.com/58636452/181806633-4e05e2b9-0eb6-45cd-9e14-949549cc33d5.png">
<img width="1440" alt="Screenshot 2022-07-29 at 10 16 46 PM" src="https://user-images.githubusercontent.com/58636452/181806640-65811eff-f606-4709-bd4a-f297760a3187.png">

How to solve this?? , thanks

**Comment by AkshayraviC09YC47** [comment]
Database:

<img width="917" alt="Screenshot 2022-07-29 at 10 45 47 PM" src="https://user-images.githubusercontent.com/58636452/181810735-3444528b-6720-425f-bab8-0d1af94678ae.png">

**Comment by mrflos** [comment]
Ping @seballot @srosset81 , who are using docker, any idea ?
I would recommand to use mariadb instead of old mysql server but it should work as it is..

**Comment by seballot** [comment]
Hi,

as described in the Install doc, you need to configure the host to "db" and not to "localhost" ;)

**Comment by J9rem** [comment]
fixed by https://github.com/YesWiki/yeswiki/commit/18474436b362af9fda7c05e1da2f06495587c8c7

**Comment by AkshayraviC09YC47** [comment]
🥴🥴🥴🥴🥴
<img width="1440" alt="Screenshot 2022-08-05 at 9 11 40 PM" src="https://user-images.githubusercontent.com/58636452/183112647-f964d9a7-b793-402a-9bb2-79e1f7843653.png">

**Comment by AkshayraviC09YC47** [comment]
I have added host as 'db', & password: "P@ssw0rd123".....still the issue is there, unable to install
@seballot @J9rem @nervo 

https://user-images.githubusercontent.com/58636452/183113764-bff4718d-8685-4f5c-84f3-62a958a48b06.mov

**Comment by AkshayraviC09YC47** [comment]
This error also...

<img width="1440" alt="Screenshot 2022-08-05 at 9 39 49 PM" src="https://user-images.githubusercontent.com/58636452/183117763-b8eb95d6-5263-4633-88d0-5e3028361d82.png">

**Comment by J9rem** [comment]
OK, @AkshayraviC09YC47 the trouble seems to be ever existing.
I reopen this issue and leave @seballot or other dev. who used to use docker to find a way to solve it.

Thanks @AkshayraviC09YC47 for your attention about this trouble

**Comment by mose** [comment]
I have a running dev local docker environment working, after a couple of PR. In the installer while using docker you need to put `root` as db username and `root` as db password.

**Comment by mose** [comment]
Note that if you want to custom the db user, you will need to tune up the `docker-compose.yml` file accordingly.

**Comment by nervo** [comment]
Please @AkshayraviC09YC47 don't spam my name without reasons.
