### ISSUE TITLE
Les liens "Ouvrir dans une nouvelle fenetre" ne marchent pas avec le WYSIWYG editor

### ISSUE THREAD

**Issue by VeveQNV** [YesWiki/yeswiki#980]
Bug / Bogue

Lors de la création avec le wysiwyg editor d'un lien devant s'ouvrir dans une autre fenetre, l'attribut target="_blank" est bien créé.

Cependant il est supprimé par HTMLPurifier dans HtmlPurifierService.php

Pour corriger ceci, il faut que le purifier soit configuré avec les options :

config->set ( 'HTML.Allowed',  'a[href|target]')
config-set ('Attr.AllowedFrameTargets', array('_blank') ])

**Comment by mrflos** [comment]
merci du retour @VeveQNV , je vais mettre un bugfix dans la branche 4.2.3-dev pour cela, je dois regarder pour les fichier xml aussi (ping @J9rem pour info).
