### ISSUE TITLE
Des facettes dynamiques 

### ISSUE THREAD

**Issue by SilvainD** [YesWiki/yeswiki#982]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Lors de l'affichage des données d'un formulaire, les facettes permettent de trier et d'afficher le nombre de fiches pour chaque critère. Il serait intéressant que lorsque l'utilisateur coche un critère dans une facette, alors les nombres de fiches dans les autres facettes se mettent à jour et si égal à 0 que les critères disparaissent. 

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki  : doryphore 4.2.3
- url to see the problem or an example / url pour voir le probleme ou un exemple : https://en-communs.incitu.org/?TrombiAnnuaire

**Comment by J9rem** [comment]
Déjà en cours de discussions ici : https://github.com/YesWiki/yeswiki/pull/976

**Comment by J9rem** [comment]
je clos cette issue, car la discussion de #976 a conduit à ne pas intégrer de suite la fonctionnalité dans le YesWiki.
Elle reste toutefois disponible avec une extension non officielle : https://github.com/J9rem/yeswiki-extension-twolevels
