### ISSUE TITLE
Un filtrage à plusieurs niveaux

### ISSUE THREAD

**Issue by SilvainD** [YesWiki/yeswiki#983]
**New feature / Nouvelle fonctionnalité**

**Description**
Pour augmenter les possibilités de trie : une facette dans une facette 
- je pose une première facette 
- chaque critère extrait du champ connecté peut être développé en sous-critères : besoin de champs liés dans le formulaire
- ainsi en cochant un critère et un ou plusieurs sous critères on peut mieux cibler la donnée

**Additionnal informations / Informations complémentaires**

**Comment by J9rem** [comment]
déjà en cours de discussions ici : https://github.com/YesWiki/yeswiki/pull/976

**Comment by J9rem** [comment]
je clos cette issue car il a été décidé dans #976 de ne pas l'intégrer dans le coeur de YesWiki pour le moment.
une extension non officielle existe : https://github.com/J9rem/yeswiki-extension-twolevels

Me contacter en message privé pour convenir des solutions d'installation de cette extension
