### ISSUE TITLE
Configurer l'image par défaut des formulaires

### ISSUE THREAD

**Issue by SilvainD** [YesWiki/yeswiki#984]
**New feature / Nouvelle fonctionnalité**

**Description**
Personnaliser l'image affichée lorsqu'il n'y a pas d'image fourni par l'utilisateur. 
Soit en sélectionnant une image pour le YesWiki Soit par une option dans le Formulaire.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki

**Comment by EdmondAgate** [comment]
Egalement intéressé (notamment pour les formulaires affichés en mode card)

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/20/une-image-par-defaut-dans-les-formulaires-bazar
