### ISSUE TITLE
If Sanitizer not activated, the upload of svg files creates empty files

### ISSUE THREAD

**Issue by mrflos** [YesWiki/yeswiki#985]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
If Sanitizer not activated, the upload of svg files creates empty files
This will be corrected in version 4.3, meanwhile you can activate the sanitizer or apply https://github.com/YesWiki/yeswiki/commit/3e8c7c5f03c726addbf96ee9529f370cff495856#diff-e049e2d4d0e070d0371841c8eba4d7101e0dcc7e273202107d8fd5e7fcc74426L75

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki 4.2.4

**Comment by J9rem** [comment]
je clos cette issue vue qu'elle ne concernait que `4.2.4` et que c'est corrigé avec `4.3.x`
