### ISSUE TITLE
Bug sur le champ {{attach class="new-window" 

### ISSUE THREAD

**Issue by FleurianeH** [YesWiki/yeswiki#987]
Bug 

**Description**
{{attach class="new-window" file="monimage.jpg" desc="mon image" link="https://monlien.ext/"}} ne fonctionne plus, le lien s'ouvre dans l'onglet courant au lieu de s'ouvrir dans un nouvel onglet.

**Informations complémentaires**
- version de YesWiki 4.2.4
- url pour voir le problème ou un exemple : https://colibris-wiki.org/benevoles/?PageprincipalE

**Comment by mose** [comment]
Pour me faire la main j'ai fouiné un peu et je me suis rendu compte qu'il manquait un truc, j'ai soumis une poule ricouèste qui corrige le problème.

**Comment by J9rem** [comment]
Salut @FleurianeH ,

je dirais plutôt que la prise en compte de la classe `new-window` n'a jamais vraiment fonctionné pour `attach`.

**Comment by J9rem** [comment]
je clos cette issue car corrigée par https://github.com/YesWiki/yeswiki/commit/030c7f6ac65d0575a3bd568297c0c21d7cebd2d2
