### ISSUE TITLE
Amélioration template liste dynamique

### ISSUE THREAD

**Issue by EdmondAgate** [YesWiki/yeswiki#989]
Amélioration de liste dynamique

Description
En mode petit iframe (rendu type smartphone) un rendu liste dynamique :
- affiche la pagination sous les facettes si ceux-ci sont mis à droite =>difficulté à comprendre que les résultats sont plus nombreux que ceux affichés (car la pagination est sous les facettes)
Nb :  la solution altrenative est bien de mettre les facettes à gauche pour avoir une pagination cohérente (mais en cas de nombreuses facettes cela masque les résultats - scrolling important)

exemple de rendu sur https://www.puy-de-dome.fr/territoires/numerique/mediation-numerique.html
depuis https://carto.hinaura.fr/?AnnuaireMedNum63Liste/

**Comment by mrflos** [comment]
La demande c'est que la pagination soit en dessous des résultats et que les facettes apparaissent apres les résultats et la pagination, c'est cela?

**Comment by EdmondAgate** [comment]
j'avoue la demande est pas hyper claire parce que je ne suis pas certain de ce qui est le plus cohérent coté utilisateur, mais oui je me dis que la pagination sous les résultats dans tous les cas serait plus adapté non ?

**Comment by mrflos** [comment]
Oui je pense aussi je c'est plus logique, on va demander à nos product owners de valider ce choix, ping @furax37 et @gatienbataille

**Comment by J9rem** [comment]
En attendant la validation par @furax37 et @gatienbataille, nous pourrions déjà déplacer la zone de pagination au dessus des filtres pour les petits écrans, qu'en dis-tu @mrflos ?

**Comment by mrflos** [comment]
Je pense que c'est plus simple de le mettre dans le bon ordre au niveau des templates plutot que de maintenir un code css spécifique aux petits écrans (a part si t'as une astuce très élégante, mais généralement le css c'est un peu du hack). Je vais relancer @furax37 et @gatienbataille sur mattermost.

**Comment by J9rem** [comment]
@mrflos je propose cette PR #1003 pour que ce soit plus élégant

**Comment by mrflos** [comment]
oui donc bien déplacer dans le template! ;) j'ai pingué les product owners, j'espère qu'ils vont se bouger le cul :P

**Comment by gatienbataille** [comment]
hop, j'en ai discuté entre deux posts avec @furax37 et si on a bien compris la demande initiale, il nous semblait plus judicieux que sur petit écran, les facettes apparaissent au-dessus des résultats (car si on a bcq de fiches sans pagination, on peut ne jamais voir les facettes) et pour pagination, on peut imaginer le faire apparaître dessus et dessous ou dessous tout le temps et dessus uniquement si le nbr de fiches demandées pour la pagination dépasse (par ex) 20 (car ça voudrait dire que la pagination risquerait elle aussi de ne pas être vue car trop en bas de l'écran... c'est compréhensible ? est ce que ça répond à la question ou on n'a pas compris la question ?

**Comment by mrflos** [comment]
Ben c'est un autre probleme que vous abordez là.
Nous on ne parlait que de mettre la pagination sur les fiches avant les facettes

**Comment by J9rem** [comment]
>Nous on ne parlait que de mettre la pagination sur les fiches avant les facettes

résolu par #1003

**Comment by mrflos** [comment]
Pour la gestion des facettes sur mobile, en effet ya rien d'idéal.
Pour colibris on partirait sur 
![image](https://user-images.githubusercontent.com/124845/187475460-33e780e4-8b2c-4f94-b2b0-dead3bfc149d.png)
que je pourrais éventuellement proposer au coeur plus tard

**Comment by gatienbataille** [comment]
ah yes pas trop mal le truc colibri / ok pour pagination

**Comment by seballot** [comment]
Il y a eu un fix cette année, par Mélanie je crois, pour qu les facettes s'affichent toujours au dessus sur mobile. Je pense que c'est déjà pas mal non? si vous voulez allez plus loin avec un truc plus responsive (genre comme suggéré par Flo un bouton "filtre" à coté de la barre de recherche qui affiche les facettes), je vous laisse créer un ticket sur https://priorites.yeswiki.net ;)
