### ISSUE TITLE
It would be nice to have default content consistent with install language choice

### ISSUE THREAD

**Issue by mose** [YesWiki/yeswiki#996]
**Type of issue**
New feature

**Description**
It would be nice to have a default content installed according to chosen language. At the moment we only have french content in `setup/sql/default-content.sql` I wonder if we could get those useful pages translated at some point and served according to the choice made during the install process,

**Comment by J9rem** [comment]
duplicate of #684 for English

**Comment by seballot** [comment]
https://priorites.yeswiki.net/posts/25/possibilite-de-traduire-le-wiki-de-base

**Comment by johentsch** [comment]
Seems like the issue is not resolved, only moved to a ticket tracker that's unavailable to the public?

**Comment by mrflos** [comment]
It's not resolved.. ..for now but there are plans for next release 4.6 to support better i18n
